[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:LOCALAPPDATA\Lacksan\EXP-049-state.json",
 [string]$LogPath="$env:LOCALAPPDATA\Lacksan\EXP-049.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-049';$provider='classic-teams-demand-launch'
$runPath='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run';$valueName='com.squirrel.Teams.Teams'
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|msrdc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|recovery|accessibility|narrator|magnify|intune|sccm|configmgr|mdm|ms-teams\.exe'
function Write-Log([string]$Event,[string]$Result,[object]$Data){$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=3;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-Hash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=$en;OmadmAccounts=$om;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);RunPolicy=(Test-Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')};[pscustomobject]@{Managed=($x.DomainJoined-or$en-gt0-or$om-gt0-or$x.PolicyManager-or$x.ConfigMgr-or$x.RunPolicy);Signals=$x}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$e=Test-Elevated;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and$e-and!$m.Managed);OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=$e;Managed=$m.Managed;ManagementSignals=$m.Signals;EvidenceStatus='needs-evidence'}}
function Get-ProtectedSnapshot{$services=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$x=Get-CimInstance Win32_Service -Filter "Name='$n'" -ErrorAction SilentlyContinue;if($x){[ordered]@{Name=$x.Name;State=$x.State;StartMode=$x.StartMode;PathName=$x.PathName}}};$newTeams=@(Get-AppxPackage -Name MSTeams -ErrorAction SilentlyContinue|Sort-Object PackageFullName|Select-Object Name,PackageFullName,Version,Status);$j=[ordered]@{Services=@($services);NewTeamsPackages=$newTeams}|ConvertTo-Json -Compress -Depth 12;[pscustomobject]@{Hash=Get-Hash $j;Snapshot=$j}}
function Resolve-ClassicTeamsCommand([string]$Command){$e=[Environment]::ExpandEnvironmentVariables($Command).Trim();if($e-match$protected){return $null};$pattern='^\s*"(?<update>[^"]+\\Update\.exe)"\s+--processStart\s+"?Teams\.exe"?\s+--process-start-args\s+"?--system-initiated"?\s*$';if($e-notmatch$pattern){return $null};try{$u=[IO.Path]::GetFullPath($matches.update)}catch{return $null};if($u-notmatch'(?i)\\Microsoft\\Teams\\Update\.exe$'){return $null};$t=Join-Path (Split-Path -Parent $u) 'current\Teams.exe';[pscustomobject]@{ExpandedCommand=$e;UpdatePath=$u;TeamsPath=$t}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$i=Get-Item -LiteralPath $Path;$s=Get-AuthenticodeSignature -LiteralPath $Path;$p=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$i.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$i.VersionInfo.FileVersion;ProductName=$i.VersionInfo.ProductName;CompanyName=$i.VersionInfo.CompanyName;SignatureStatus=$s.Status.ToString();Publisher=$p;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidMicrosoftPublisher=($s.Status-eq'Valid'-and$p-match'(?i)Microsoft Corporation')}}
function Get-Candidates{if(!(Test-Path -LiteralPath $runPath)){return @()};$k=Get-Item -LiteralPath $runPath;if(!($k.GetValueNames()-contains$valueName)){return @()};$d=[string]$k.GetValue($valueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$r=Resolve-ClassicTeamsCommand $d;if(!$r){return @()};$u=Get-FileIdentity $r.UpdatePath;$t=Get-FileIdentity $r.TeamsPath;if(!$u-or!$t-or!$u.ValidMicrosoftPublisher-or!$t.ValidMicrosoftPublisher){return @()};$a=Get-Acl -LiteralPath $runPath;@([pscustomobject]@{Path=$runPath;Name=$valueName;Kind=$k.GetValueKind($valueName).ToString();Data=$d;ExpandedCommand=$r.ExpandedCommand;Update=$u;Teams=$t;KeyOwner=$a.Owner;KeySddl=$a.Sddl})}
function Assert-Eligible($Support,[object[]]$Candidates){if(!$Support.Supported){if(!$Support.Elevated){throw'Elevation required.'};if($Support.Managed){throw'Enterprise-management ownership detected.'};throw'HP Windows 11 is required.'};if($Candidates.Count-ne1){throw"Exactly one eligible classic Teams Squirrel Run registration is required; found $($Candidates.Count)."}}
function Save-State($Support,[object[]]$Candidates){Assert-Eligible $Support $Candidates;if(Test-Path -LiteralPath $StatePath){throw'State overwrite refused.'};$p=Get-ProtectedSnapshot;$s=[ordered]@{schemaVersion=3;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedScopeHash=$p.Hash;entry=$Candidates[0];evidenceStatus='needs-evidence'};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$s|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if(!(Test-Path -LiteralPath $StatePath)){throw'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne3-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw'State identity validation failed.'};$s}
function Test-Removed($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $true};!((Get-Item -LiteralPath $State.entry.Path).GetValueNames()-contains[string]$State.entry.Name)}
function Test-Restored($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $false};$k=Get-Item -LiteralPath $State.entry.Path;if(!($k.GetValueNames()-contains[string]$State.entry.Name)){return $false};$d=[string]$k.GetValue($State.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$d-eq[string]$State.entry.Data-and$k.GetValueKind($State.entry.Name).ToString()-eq[string]$State.entry.Kind}
function Assert-BinaryIdentity($State){foreach($n in 'Update','Teams'){$e=$State.entry.$n;$c=Get-FileIdentity([string]$e.Path);if(!$c-or!$c.ValidMicrosoftPublisher-or$c.Sha256-ne[string]$e.Sha256-or$c.Thumbprint-ne[string]$e.Thumbprint-or$c.FileVersion-ne[string]$e.FileVersion){throw"Classic Teams $n binary identity drift detected."}}}
function Assert-Protected($State){if((Get-ProtectedSnapshot).Hash-ne[string]$State.protectedScopeHash){throw'Protected security update remote-access or new Teams state drift detected.'}}
function Assert-RunKey($State){if(!(Test-Path -LiteralPath $State.entry.Path)){throw'Run-key drift detected; exact rollback safety cannot be established.'};$acl=Get-Acl -LiteralPath $State.entry.Path;if($acl.Owner-ne[string]$State.entry.KeyOwner-or$acl.Sddl-ne[string]$State.entry.KeySddl){throw'Run-key ACL drift detected.'}}
function Assert-Guards($State){if(!(Test-Elevated)){throw'Elevation required.'};if((Get-ManagementState).Managed){throw'Management ownership appeared.'};Assert-RunKey $State;Assert-BinaryIdentity $State;Assert-Protected $State}
function Assert-Baseline($State){Assert-Guards $State;if(!(Test-Restored $State)){throw'Captured classic Teams Run registration drift detected.'}}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{$c=Get-Candidates;Write-Log 'candidate-inventory' 'pass' @{count=$c.Count;names=@($c.Name)};[pscustomobject]@{Support=$support;Candidates=$c;Profile='ClassicTeamsDemandLaunch';EvidenceStatus='needs-evidence'}}
'Capture'{$s=Save-State $support (Get-Candidates);Write-Log 'capture' 'pass' @{path=$s.entry.Path;name=$s.entry.Name;kind=$s.entry.Kind;keyOwner=$s.entry.KeyOwner};$s}
'DryRun'{$c=Get-Candidates;Assert-Eligible $support $c;$r=[pscustomobject]@{Profile='ClassicTeamsDemandLaunch';WouldChange=$true;MutationCount=1;Path=$c[0].Path;Name=$c[0].Name;PreserveClassicTeamsInstallation=$true;PreserveNewTeamsPackage=$true;PreserveServices=$true;PreserveScheduledTasks=$true;PreserveRunKeyAcl=$true;RebootPersistenceCheckRequired=$true;Rollback='Restore exact captured path, value name, kind, and unexpanded data after management, ACL, binary, and protected-state drift checks.';EvidenceStatus='needs-evidence'};Write-Log 'dry-run' 'pass' $r;$r}
'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support (Get-Candidates)};if(Test-Removed $s){Assert-Guards $s;Write-Log 'apply' 'idempotent' @{mutationCount=0};return[pscustomobject]@{Applied=$true;MutationCount=0}};Assert-Baseline $s;if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Remove exact classic Teams Squirrel Run registration')){Remove-ItemProperty -LiteralPath $s.entry.Path -Name $s.entry.Name}else{return};if(!(Test-Removed $s)){throw'Apply verification failed.'};Assert-Guards $s;Write-Log 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$s=Read-State;if(!(Test-Removed $s)){throw'Immediate verification failed.'};Assert-Guards $s;Write-Log 'verify' 'pass' @{removed=$true};$true}
'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw'A later boot is required.'};if(!(Test-Removed $s)){throw'Reboot persistence failed.'};Assert-Guards $s;Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');evidenceStatus='needs-evidence'};$true}
'Rollback'{$s=Read-State;if(!(Test-Removed $s)){if(Test-Restored $s){Assert-Guards $s;Write-Log 'rollback' 'idempotent' @{mutationCount=0};return[pscustomobject]@{RolledBack=$true;MutationCount=0}};throw'Rollback overwrite refused.'};Assert-Guards $s;if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Restore exact classic Teams Squirrel Run registration')){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.entry.Kind,$true);(Get-Item -LiteralPath $s.entry.Path).SetValue([string]$s.entry.Name,[string]$s.entry.Data,$kind)}else{return};if(!(Test-Restored $s)){throw'Exact rollback verification failed.'};Assert-Guards $s;Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'};throw}
