[CmdletBinding()]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')]
    [string]$Action='Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$runPath='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$protected=@('omnissa','vmware horizon','windows app','remote desktop','mstsc','tailscale','windows security','securityhealth','defender','credential','bitlocker','firewall')
function Write-ProviderLog([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$record=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-049';provider='classic-teams-run';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($record|ConvertTo-Json -Compress -Depth 10) -Encoding UTF8}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$computer=Get-CimInstance Win32_ComputerSystem;[pscustomobject]@{Supported=([version]$os.Version).Major-ge 10-and$os.Caption-match'Windows 11'-and$computer.Manufacturer-match'HP|Hewlett-Packard';OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$computer.Manufacturer;Model=$computer.Model}}
function Test-Identity([string]$Name,[string]$Command){$identity=($Name+' '+$Command).ToLowerInvariant();foreach($token in $protected){if($identity.Contains($token)){return $false}};if($Name-cne'com.squirrel.Teams.Teams'){return $false};$updateExe=$Command-match'(?i)(^|[\\/" ])Update\.exe(?:[" ]|$)';$processStart=$Command-match'(?i)--processStart\s+"?Teams\.exe"?';$systemInitiated=$Command-match'(?i)--process-start-args\s+"?--system-initiated"?';$refused=$Command-match'(?i)ms-teams\.exe|MSTeams_[^\\ ]+|WindowsApps|--update|/update';return($updateExe-and$processStart-and$systemInitiated-and-not$refused)}
function Get-Candidates{if(-not(Test-Path $runPath)){return @()};$key=Get-Item -LiteralPath $runPath;$items=foreach($name in $key.GetValueNames()){$value=[string]$key.GetValue($name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);if(Test-Identity $name $value){[pscustomobject]@{Path=$runPath;Name=$name;Data=$value;Kind=$key.GetValueKind($name).ToString()}}};@($items)}
function Save-State([object[]]$Candidates){if($Candidates.Count-gt 1){throw'More than one eligible classic Teams registration was found.'};$state=[ordered]@{schemaVersion=1;experiment='EXP-049';provider='classic-teams-run';capturedUtc=(Get-Date).ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=([System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value);entries=@($Candidates)};$state|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $StatePath -Encoding UTF8;$state}
function Read-State{if(-not(Test-Path $StatePath)){throw"State file missing: $StatePath"};$state=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($state.schemaVersion-ne 1-or$state.experiment-ne'EXP-049'-or$state.provider-ne'classic-teams-run'-or$state.machine-ne$env:COMPUTERNAME-or$state.userSid-ne$sid){throw'State identity validation failed.'};$state}
function Test-Removed($State){foreach($entry in @($State.entries)){if(Get-ItemProperty -LiteralPath $entry.Path -Name $entry.Name -ErrorAction SilentlyContinue){return $false}};$true}
function Test-Restored($State){foreach($entry in @($State.entries)){$key=Get-Item -LiteralPath $entry.Path -ErrorAction SilentlyContinue;if(-not$key){return $false};$value=[string]$key.GetValue($entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);if($value-ne[string]$entry.Data-or$key.GetValueKind($entry.Name).ToString()-ne[string]$entry.Kind){return $false}};$true}
try{$support=Get-SupportState;Write-ProviderLog 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;if(-not$support.Supported){throw'Provider supports HP systems running Windows 11 only.'};switch($Action){'Check'{$c=Get-Candidates;Write-ProviderLog 'candidate-inventory' 'pass' @{count=$c.Count;names=@($c.Name)};$c}'Capture'{$c=Get-Candidates;$s=Save-State $c;Write-ProviderLog 'capture' 'pass' @{count=$c.Count;statePath=$StatePath};$s}'DryRun'{$c=Get-Candidates;if($c.Count-gt 1){throw'Dry run found multiple eligible registrations.'};Write-ProviderLog 'dry-run' 'pass' @{count=$c.Count;names=@($c.Name)};[pscustomobject]@{Provider='classic-teams-run';WouldChange=@($c);RebootRequired=$false}}'Apply'{$s=Read-State;$current=Get-Candidates;foreach($entry in $current){if(@($s.entries|Where-Object{$_.Name-eq$entry.Name-and$_.Data-eq$entry.Data-and$_.Kind-eq$entry.Kind}).Count-ne 1){throw"Current candidate differs from captured state: $($entry.Name)"};Remove-ItemProperty -LiteralPath $entry.Path -Name $entry.Name};if(-not(Test-Removed $s)){throw'Apply verification failed.'};Write-ProviderLog 'apply' 'pass' @{removed=$current.Count};[pscustomobject]@{Provider='classic-teams-run';Applied=$true;MutationCount=$current.Count;RebootRequired=$false}}'Verify'{$s=Read-State;$ok=Test-Removed $s;Write-ProviderLog 'verify' $(if($ok){'pass'}else{'fail'}) @{};if(-not$ok){throw'Removal verification failed.'};$true}'VerifyReboot'{$s=Read-State;$ok=Test-Removed $s;Write-ProviderLog 'verify-reboot' $(if($ok){'pass'}else{'fail'}) @{bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime};if(-not$ok){throw'Reboot persistence verification failed.'};$true}'Rollback'{$s=Read-State;foreach($entry in @($s.entries)){if(-not(Test-Identity $entry.Name $entry.Data)){throw"Rollback identity rejected: $($entry.Name)"};if(Get-ItemProperty -LiteralPath $entry.Path -Name $entry.Name -ErrorAction SilentlyContinue){throw"Rollback refused because the registration already exists: $($entry.Name)"};if(-not(Test-Path $entry.Path)){New-Item -Path $entry.Path -Force|Out-Null};(Get-Item -LiteralPath $entry.Path).SetValue($entry.Name,[string]$entry.Data,[Microsoft.Win32.RegistryValueKind]::$($entry.Kind))};if(-not(Test-Restored $s)){throw'Rollback verification failed.'};Write-ProviderLog 'rollback' 'pass' @{restored=@($s.entries).Count};[pscustomobject]@{Provider='classic-teams-run';RolledBack=$true;MutationCount=@($s.entries).Count}}}}catch{Write-ProviderLog 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
