[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',[string]$StatePath,[string]$LogPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-071';$provider='edge-background-mode-off';$profile='EdgeBackgroundModeOff';$policyPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended';$mandatoryPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge';$valueName='BackgroundModeEnabled';$related=@('StartupBoostEnabled')
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-RegistryState([string]$Path,[string]$Name){if(!(Test-Path -LiteralPath $Path)){return [pscustomobject]@{KeyExists=$false;ValueExists=$false;Kind=$null;Data=$null}};$k=Get-Item -LiteralPath $Path;$exists=$k.GetValueNames()-contains$Name;if(!$exists){return [pscustomobject]@{KeyExists=$true;ValueExists=$false;Kind=$null;Data=$null}};[pscustomobject]@{KeyExists=$true;ValueExists=$true;Kind=$k.GetValueKind($Name).ToString();Data=$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)};[pscustomobject]@{Managed=($x.DomainJoined-or$x.MdmEnrollments-gt0-or$x.PolicyManager-or$x.ConfigMgr);Signals=$x}}
function Get-EdgeIdentity{$roots=@([Environment]::GetEnvironmentVariable('ProgramFiles(x86)'),[Environment]::GetEnvironmentVariable('ProgramFiles'))|Where-Object{$_}|Select-Object -Unique;$paths=@($roots|ForEach-Object{Join-Path $_ 'Microsoft\Edge\Application\msedge.exe'}|Where-Object{Test-Path -LiteralPath $_});$items=@($paths|ForEach-Object{$i=Get-Item -LiteralPath $_;$sig=Get-AuthenticodeSignature -LiteralPath $_;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$i.FullName;Version=$i.VersionInfo.FileVersion;Major=[int]($i.VersionInfo.FileVersion.Split('.')[0]);Sha256=(Get-FileHash -LiteralPath $_ -Algorithm SHA256).Hash;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidPublisher=($sig.Status-eq'Valid'-and$pub-match'(?i)Microsoft Corporation')}});if($items.Count-ne1){return $null};$items[0]}
function Get-StartupFolderState{$folders=@([Environment]::GetFolderPath('Startup'),[Environment]::GetFolderPath('CommonStartup'))|Where-Object{$_}|Select-Object -Unique;$shell=New-Object -ComObject WScript.Shell;$entries=@();foreach($f in $folders){if(!(Test-Path -LiteralPath $f)){continue};foreach($item in Get-ChildItem -LiteralPath $f -File -ErrorAction SilentlyContinue){$target=$null;if($item.Extension-eq'.lnk'){try{$target=$shell.CreateShortcut($item.FullName).TargetPath}catch{}};$entries+=[pscustomobject]@{Folder=$f;Name=$item.Name;FullName=$item.FullName;Target=$target;Edge=([bool]($item.Name-match'(?i)edge|msedge' -or $target-match'(?i)\\msedge\.exe$'))}}};[pscustomobject]@{Entries=@($entries);EdgeEntries=@($entries|Where-Object{$_.Edge});EdgeEntryCount=@($entries|Where-Object{$_.Edge}).Count}}
function Get-ProtectedSnapshot{$svc=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale'){$x=Get-CimInstance Win32_Service -Filter "Name='$n'" -ErrorAction SilentlyContinue;if($x){[ordered]@{Name=$x.Name;State=$x.State;StartMode=$x.StartMode;PathName=$x.PathName}}};$proc=@(Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.ProcessName-match'(?i)omnissa|horizon|msrdc|mstsc|tailscale'}|Select-Object -ExpandProperty ProcessName|Sort-Object -Unique);([ordered]@{Services=@($svc);Processes=$proc}|ConvertTo-Json -Compress -Depth 8)}
function Get-PolicyBundle{$x=[ordered]@{MandatoryMain=Get-RegistryState $mandatoryPath $valueName;RecommendedMain=Get-RegistryState $policyPath $valueName;MandatoryRelated=[ordered]@{};RecommendedRelated=[ordered]@{}};foreach($n in $related){$x.MandatoryRelated[$n]=Get-RegistryState $mandatoryPath $n;$x.RecommendedRelated[$n]=Get-RegistryState $policyPath $n};[pscustomobject]$x}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$e=Get-EdgeIdentity;$pol=Get-PolicyBundle;$startup=Get-StartupFolderState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and(Test-Elevated)-and$e-and$e.Major-ge77-and$e.ValidPublisher-and!$m.Managed-and!$pol.MandatoryMain.ValueExists-and!$pol.RecommendedMain.ValueExists-and$startup.EdgeEntryCount-eq0);OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=Test-Elevated;Managed=$m.Managed;ManagementSignals=$m.Signals;Edge=$e;Policies=$pol;StartupFolders=$startup}}
function Assert-Supported($s){if(!$s.Supported){throw 'Unsupported, managed, unsigned, ambiguous, policy-owned, or Startup-folder Edge state.'}}
function Save-State($s){Assert-Supported $s;if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$state=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;policyPath=$policyPath;valueName=$valueName;original=$s.Policies.RecommendedMain;policies=$s.Policies;edge=$s.Edge;management=$s.ManagementSignals;startupFolders=$s.StartupFolders;protectedScope=Get-ProtectedSnapshot};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$state|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;$state}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw 'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Compare-State([object]$A,[object]$B){(($A|ConvertTo-Json -Compress -Depth 20)-eq($B|ConvertTo-Json -Compress -Depth 20))}
function Assert-DriftFree($s){$e=Get-EdgeIdentity;if(!$e-or$e.Sha256-ne[string]$s.edge.Sha256-or$e.Thumbprint-ne[string]$s.edge.Thumbprint-or$e.Version-ne[string]$s.edge.Version){throw 'Edge identity drift detected.'};$m=Get-ManagementState;if($m.Managed){throw 'Management ownership appeared.'};$pol=Get-PolicyBundle;if(!(Compare-State $pol.MandatoryRelated $s.policies.MandatoryRelated)-or!(Compare-State $pol.RecommendedRelated $s.policies.RecommendedRelated)-or!(Compare-State $pol.MandatoryMain $s.policies.MandatoryMain)){throw 'Related Edge policy drift detected.'};$startup=Get-StartupFolderState;if($startup.EdgeEntryCount-ne0-or!(Compare-State $startup $s.startupFolders)){throw 'Edge Startup-folder drift detected.'};if((Get-ProtectedSnapshot)-ne[string]$s.protectedScope){throw 'Protected-scope drift detected.'};$e}
function Test-Applied{$x=Get-RegistryState $policyPath $valueName;$x.ValueExists-and$x.Kind-eq'DWord'-and[int]$x.Data-eq0}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{[pscustomobject]@{Support=$support;Profile=$profile}}
'Capture'{$s=Save-State $support;Write-Log 'capture' 'pass' @{path=$policyPath;name=$valueName;edge=$s.edge.Version;startupEdgeEntries=$s.startupFolders.EdgeEntryCount;related=$s.policies};$s}
'DryRun'{Assert-Supported $support;$r=[pscustomobject]@{Profile=$profile;WouldChange=$true;MutationCount=1;Path=$policyPath;Name=$valueName;Type='DWord';Value=0;BrowserRestartRequired=$false;RebootPersistenceCheckRequired=$true;Rollback='Restore exact captured registry state or remove only the experiment-created value and empty key.'};Write-Log 'dry-run' 'pass' $r;$r}
'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support};Assert-DriftFree $s|Out-Null;if(Test-Applied){Write-Log 'apply' 'idempotent' @{mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};Assert-Supported $support;if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$policyPath::$valueName",'Disable recommended Microsoft Edge background mode for demand-launch comparison')){if(!(Test-Path -LiteralPath $policyPath)){New-Item -Path $policyPath -Force|Out-Null};New-ItemProperty -LiteralPath $policyPath -Name $valueName -PropertyType DWord -Value 0 -Force|Out-Null};if(!(Test-Applied)){throw 'Apply verification failed.'};Write-Log 'apply' 'pass' @{mutationCount=1;dynamicPolicyRefresh=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$s=Read-State;Assert-DriftFree $s|Out-Null;if(!(Test-Applied)){throw 'Immediate verification failed.'};Write-Log 'verify' 'pass' @{value=0;dynamicPolicyRefresh=$true;startupFolderEdgeEntries=0};$true}
'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};Assert-DriftFree $s|Out-Null;if(!(Test-Applied)){throw 'Reboot persistence failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');value=0;startupFolderEdgeEntries=0};$true}
'Rollback'{$s=Read-State;Assert-DriftFree $s|Out-Null;$current=Get-RegistryState $policyPath $valueName;if(!$current.ValueExists){Write-Log 'rollback' 'idempotent' @{mutationCount=0};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($current.Kind-ne'DWord'-or[int]$current.Data-ne0){throw 'Policy drift detected; rollback refused.'};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$policyPath::$valueName",'Restore exact captured Edge background-mode policy state')){if($s.original.ValueExists){New-ItemProperty -LiteralPath $policyPath -Name $valueName -PropertyType $s.original.Kind -Value $s.original.Data -Force|Out-Null}else{Remove-ItemProperty -LiteralPath $policyPath -Name $valueName;if(!$s.original.KeyExists-and(Test-Path -LiteralPath $policyPath)){if(@((Get-Item -LiteralPath $policyPath).GetValueNames()).Count-eq0-and@(Get-ChildItem -LiteralPath $policyPath).Count-eq0){Remove-Item -LiteralPath $policyPath}}}};$after=Get-RegistryState $policyPath $valueName;if(!(Compare-State $after $s.original)){throw 'Exact rollback verification failed.'};Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message};throw}
