[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-079-edge-startup-boost-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-079-edge-startup-boost-events.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-079';$Provider='edge-startup-boost-enabled-policy'
$Recommended='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended';$Mandatory='HKLM:\SOFTWARE\Policies\Microsoft\Edge';$ValueName='StartupBoostEnabled';$TargetValue=1
$ProtectedServices=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','edgeupdate','edgeupdatem')
function Hash([string]$Text){$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','')}finally{$h.Dispose()}}
function Same($A,$B){($A|ConvertTo-Json -Compress -Depth 30)-eq($B|ConvertTo-Json -Compress -Depth 30)}
function Log([string]$Event,[string]$Result,$Before=$null,$After=$null,[string]$Reason=$null,[string]$Failure=$null){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;action=$Action;event=$Event;result=$Result;before=$Before;after=$After;refusalReason=$Reason;failureDetail=$Failure;evidenceStatus='needs-evidence'}|ConvertTo-Json -Compress -Depth 30|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;ConfigMgr=$ccm;EnrollmentCount=$en;OmadmCount=$om}}
function Reg([string]$Path){if(!(Test-Path $Path)){return [pscustomobject]@{KeyExists=$false;ValueExists=$false;Kind=$null;Data=$null}};$k=Get-Item $Path;if($k.GetValueNames()-notcontains$ValueName){return [pscustomobject]@{KeyExists=$true;ValueExists=$false;Kind=$null;Data=$null}};[pscustomobject]@{KeyExists=$true;ValueExists=$true;Kind=$k.GetValueKind($ValueName).ToString();Data=$k.GetValue($ValueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function Edge{$paths=@($env:ProgramFiles,${env:ProgramFiles(x86)})|Where-Object{$_}|ForEach-Object{Join-Path $_ 'Microsoft\Edge\Application\msedge.exe'}|Where-Object{Test-Path -LiteralPath $_}|Select-Object -Unique;$rows=@($paths|ForEach-Object{$f=Get-Item -LiteralPath $_;$s=Get-AuthenticodeSignature -LiteralPath $_;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};$v=[version]$f.VersionInfo.FileVersion;[pscustomobject]@{Path=$f.FullName;Version=$v.ToString();Major=$v.Major;Sha256=(Get-FileHash -LiteralPath $_ -Algorithm SHA256).Hash;SignatureStatus=$s.Status.ToString();Publisher=$pub;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};Valid=($s.Status-eq'Valid'-and$pub-match'(?i)Microsoft Corporation')}});if($rows.Count-ne1){return $null};$rows[0]}
function Startup{$shell=New-Object -ComObject WScript.Shell;$rows=@();foreach($folder in @([Environment]::GetFolderPath('Startup'),[Environment]::GetFolderPath('CommonStartup'))|Where-Object{$_}|Select-Object -Unique){if(Test-Path $folder){foreach($i in Get-ChildItem $folder -File -ErrorAction SilentlyContinue){$target=$null;if($i.Extension-eq'.lnk'){try{$target=$shell.CreateShortcut($i.FullName).TargetPath}catch{}};$rows+=[pscustomobject]@{Path=$i.FullName;Target=$target;Edge=[bool]($i.Name-match'(?i)edge|msedge'-or$target-match'(?i)\\msedge\.exe$')}}}};[pscustomobject]@{EdgeEntryCount=@($rows|Where-Object Edge).Count;Entries=$rows}}
function Protected{@($ProtectedServices|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,StartMode,PathName)}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$e=Edge;$m=Management;$r=Reg $Recommended;$d=Reg $Mandatory;$st=Startup;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required.'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required.'};if(!(Elevated)){$reasons+='Elevation required.'};if(!$e-or!$e.Valid-or$e.Major-lt88){$reasons+='Exactly one Microsoft-signed Edge 88+ installation required.'};if($m.Managed){$reasons+='Enterprise management ownership detected.'};if($r.ValueExists-or$d.ValueExists){$reasons+='Existing mandatory or recommended StartupBoostEnabled policy refused.'};if($st.EdgeEntryCount-ne0){$reasons+='Edge Startup-folder entry refused.'};[pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=(Elevated);Edge=$e;Management=$m;Recommended=$r;Mandatory=$d;Startup=$st;EvidenceStatus='needs-evidence'}}
function Save($s){if(!$s.Supported){throw($s.Reasons-join' ')};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$o=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootUtc=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;original=$s.Recommended;mandatory=$s.Mandatory;edge=$s.Edge;management=$s.Management;startup=$s.Startup;protectedHash=Hash((Protected|ConvertTo-Json -Compress -Depth 20));evidenceStatus='needs-evidence'};$o|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $StatePath -Encoding UTF8;[pscustomobject]$o}
function Read{if(!(Test-Path -LiteralPath $StatePath)){throw 'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Drift($s){$e=Edge;if(!$e-or!$e.Valid-or$e.Sha256-ne[string]$s.edge.Sha256-or$e.Version-ne[string]$s.edge.Version-or$e.Thumbprint-ne[string]$s.edge.Thumbprint){throw 'Edge executable identity drift detected.'};if((Management).Managed){throw 'Management ownership drift detected.'};if(!(Same (Reg $Mandatory) $s.mandatory)){throw 'Mandatory policy drift detected.'};if((Startup).EdgeEntryCount-ne0){throw 'Edge Startup-folder drift detected.'};if((Hash((Protected|ConvertTo-Json -Compress -Depth 20)))-ne[string]$s.protectedHash){throw 'Protected configuration drift detected.'}}
function Applied{$r=Reg $Recommended;$r.ValueExists-and$r.Kind-eq'DWord'-and[int]$r.Data-eq$TargetValue}
try{$sup=Support;Log 'support-detection' $(if($sup.Supported){'pass'}else{'refused'}) $null $sup ($(if($sup.Supported){$null}else{$sup.Reasons-join' '}));switch($Action){
 'Check'{$sup}
 'Capture'{$s=Save $sup;Log 'capture' 'pass' $null $s;$s}
 'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join' ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Path=$Recommended;Name=$ValueName;Type='DWord';Value=$TargetValue;BrowserRestartRequired=$true;RebootPersistenceRequired=$true;KeepEdgeOutOfStartupFolder=$true;Rollback='Restore exact captured registry value/type/key semantics after Edge, management, Startup-folder, mandatory-policy, and protected-scope drift checks.';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $sup.Recommended $r;$r}
 'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read}else{Save $sup};Drift $s;if(Applied){Log 'apply' 'idempotent' (Reg $Recommended) (Reg $Recommended);return [pscustomobject]@{Applied=$true;MutationCount=0}};$now=Reg $Recommended;if($now.ValueExists){throw 'Recommended policy collision detected.'};if($WhatIfPreference){Log 'apply' 'whatif' $now $now;return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$Recommended::$ValueName",'Set recommended Edge StartupBoostEnabled to 1')){if(!(Test-Path $Recommended)){New-Item $Recommended -Force|Out-Null};New-ItemProperty $Recommended -Name $ValueName -PropertyType DWord -Value $TargetValue -Force|Out-Null};if(!(Applied)){throw 'Application verification failed.'};Log 'apply' 'pass' $now (Reg $Recommended);[pscustomobject]@{Applied=$true;MutationCount=1}}
 'Verify'{$s=Read;Drift $s;if(!(Applied)){throw 'Treatment verification failed.'};$r=[pscustomobject]@{Verified=$true;BrowserRestart='needs-evidence';WarmLaunchClassification='needs-evidence';ProtectedApplicationReadiness='needs-evidence'};Log 'verify' 'pass' (Reg $Recommended) $r;$r}
 'VerifyReboot'{$s=Read;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootUtc){throw 'A later boot is required.'};Drift $s;if(!(Applied)){throw 'Reboot persistence failed.'};$r=[pscustomobject]@{VerifiedReboot=$true;BootUtc=$boot.ToString('o');WarmLaunchClassification='needs-evidence';ProtectedApplicationReadiness='needs-evidence'};Log 'verify-reboot' 'pass' (Reg $Recommended) $r;$r}
 'Rollback'{$s=Read;Drift $s;$now=Reg $Recommended;if(Same $now $s.original){Log 'rollback' 'idempotent' $now $now;return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if(!$now.ValueExists-or!$now.Kind-eq'DWord'-or[int]$now.Data-ne$TargetValue){throw 'Rollback collision detected.'};if($WhatIfPreference){Log 'rollback' 'whatif' $now $now;return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$Recommended::$ValueName",'Restore exact captured Edge Startup Boost policy state')){if($s.original.ValueExists){$k=Get-Item $Recommended;$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.original.Kind,$true);$k.SetValue($ValueName,$s.original.Data,$kind)}else{Remove-ItemProperty $Recommended -Name $ValueName;if(!$s.original.KeyExists-and(Test-Path $Recommended)-and@((Get-Item $Recommended).GetValueNames()).Count-eq0-and@((Get-ChildItem $Recommended -ErrorAction SilentlyContinue)).Count-eq0){Remove-Item $Recommended}}};$after=Reg $Recommended;if(!(Same $after $s.original)){throw 'Exact rollback verification failed.'};Log 'rollback' 'pass' $now $after;[pscustomobject]@{RolledBack=$true;MutationCount=1;RestoredExactOriginal=$true}}
}}catch{Log 'failure' 'failure' $null $null $null $_.Exception.Message;throw}
