[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-141-edge-performance-detector-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-141-edge-performance-detector-events.jsonl",
 [string]$ProfileFixturePath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-141';$Provider='edge-disable-performance-detector'
$Recommended='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended';$Mandatory='HKLM:\SOFTWARE\Policies\Microsoft\Edge';$ValueName='PerformanceDetectorEnabled'
$Held=@('ExtensionsPerformanceDetectorEnabled','StartupBoostEnabled','BackgroundModeEnabled','SleepingTabsEnabled','EfficiencyModeEnabled','HardwareAccelerationModeEnabled','NetworkPredictionOptions','CopilotNewTabPageEnabled','NewTabPagePrerenderEnabled')
$Protected=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','edgeupdate','edgeupdatem')
function Log([string]$Event,[string]$Result,$Data=$null){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data;evidenceStatus='needs-evidence'}|ConvertTo-Json -Compress -Depth 30|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Reg([string]$Path,[string]$Name){if(!(Test-Path $Path)){return [pscustomobject]@{KeyExists=$false;ValueExists=$false;Kind=$null;Data=$null}};$k=Get-Item $Path;if($k.GetValueNames()-notcontains$Name){return [pscustomobject]@{KeyExists=$true;ValueExists=$false;Kind=$null;Data=$null}};[pscustomobject]@{KeyExists=$true;ValueExists=$true;Kind=$k.GetValueKind($Name).ToString();Data=$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 30)-eq($b|ConvertTo-Json -Compress -Depth 30)}
function Edge{ $paths=@($env:ProgramFiles,${env:ProgramFiles(x86)})|Where-Object{$_}|ForEach-Object{Join-Path $_ 'Microsoft\Edge\Application\msedge.exe'}|Where-Object{Test-Path $_}|Select-Object -Unique;$rows=@($paths|ForEach-Object{$i=Get-Item $_;$s=Get-AuthenticodeSignature $_;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$i.FullName;Version=$i.VersionInfo.FileVersion;Major=[int]$i.VersionInfo.FileVersion.Split('.')[0];Sha256=(Get-FileHash $_ -Algorithm SHA256).Hash;Signature=$s.Status.ToString();Publisher=$pub;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};Valid=($s.Status-eq'Valid'-and$pub-match'Microsoft Corporation')}});if($rows.Count-ne1){return $null};$rows[0] }
function Management{$c=Get-CimInstance Win32_ComputerSystem;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;ConfigMgr=$ccm;EnrollmentCount=$en;OmadmCount=$om}}
function Fixture{if([string]::IsNullOrWhiteSpace($ProfileFixturePath)){return $null};$m=Join-Path $ProfileFixturePath '.lacksan-edge-performance-detector.json';if(!(Test-Path $m)){return $null};$x=Get-Content $m -Raw|ConvertFrom-Json;if($x.experiment-ne'EXP-141'-or$x.controlledProfile-ne$true-or$x.microsoftAccountSignedIn-ne$false-or$x.detectorEligible-ne$true){return $null};[pscustomobject]@{Path=(Resolve-Path $ProfileFixturePath).Path;Marker=$m;MarkerSha256=(Get-FileHash $m -Algorithm SHA256).Hash;ProfileId=[string]$x.profileId;MicrosoftAccountSignedIn=[bool]$x.microsoftAccountSignedIn;DetectorEligible=[bool]$x.detectorEligible}}
function Startup{$shell=New-Object -ComObject WScript.Shell;$rows=@();foreach($f in @([Environment]::GetFolderPath('Startup'),[Environment]::GetFolderPath('CommonStartup'))|Where-Object{$_}|Select-Object -Unique){if(Test-Path $f){foreach($i in Get-ChildItem $f -File -ErrorAction SilentlyContinue){$t=$null;if($i.Extension-eq'.lnk'){try{$t=$shell.CreateShortcut($i.FullName).TargetPath}catch{}};$rows+=[pscustomobject]@{Path=$i.FullName;Target=$t;Edge=[bool]($i.Name-match'(?i)edge|msedge'-or$t-match'(?i)\\msedge\.exe$')}}}};[pscustomobject]@{EdgeEntryCount=@($rows|Where-Object Edge).Count;Entries=$rows}}
function Policies{$x=[ordered]@{Recommended=Reg $Recommended $ValueName;Mandatory=Reg $Mandatory $ValueName;Held=[ordered]@{}};foreach($n in $Held){$x.Held[$n]=[ordered]@{Recommended=Reg $Recommended $n;Mandatory=Reg $Mandatory $n}};[pscustomobject]$x}
function ProtectedState{@($Protected|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,StartMode,PathName)}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$e=Edge;$m=Management;$f=Fixture;$p=Policies;$st=Startup;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required.'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required.'};if(!(Elevated)){$reasons+='Elevation required.'};if(!$e-or!$e.Valid-or$e.Major-lt107){$reasons+='Exactly one Microsoft-signed Edge 107+ installation required.'};if($m.Managed){$reasons+='Enterprise management ownership detected.'};if(!$f){$reasons+='Controlled non-MSA profile fixture with detector eligibility required.'};if($p.Recommended.ValueExists-or$p.Mandatory.ValueExists){$reasons+='Existing PerformanceDetectorEnabled policy refused.'};if($st.EdgeEntryCount-ne0){$reasons+='Edge Startup-folder entry refused.'};[pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=(Elevated);Edge=$e;Management=$m;Fixture=$f;Policies=$p;Startup=$st;EvidenceStatus='needs-evidence'}}
function Save($s){if(!$s.Supported){throw($s.Reasons-join' ')};if(Test-Path $StatePath){throw 'State overwrite refused.'};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory $p -Force|Out-Null};$o=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootUtc=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;original=$s.Policies.Recommended;mandatory=$s.Policies.Mandatory;held=$s.Policies.Held;edge=$s.Edge;fixture=$s.Fixture;management=$s.Management;startup=$s.Startup;protected=ProtectedState;evidenceStatus='needs-evidence'};$o|ConvertTo-Json -Depth 30|Set-Content $StatePath -Encoding UTF8;[pscustomobject]$o}
function Read{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Drift($s){$e=Edge;if(!$e-or$e.Sha256-ne$s.edge.Sha256-or$e.Version-ne$s.edge.Version-or$e.Thumbprint-ne$s.edge.Thumbprint){throw 'Edge identity drift detected.'};if((Management).Managed){throw 'Management ownership drift detected.'};$f=Fixture;if(!$f-or$f.MarkerSha256-ne$s.fixture.MarkerSha256-or$f.ProfileId-ne$s.fixture.ProfileId-or$f.MicrosoftAccountSignedIn-or!$f.DetectorEligible){throw 'Controlled profile drift detected.'};$p=Policies;if(!(Same $p.Mandatory $s.mandatory)-or!(Same $p.Held $s.held)){throw 'Related Edge policy drift detected.'};if((Startup).EdgeEntryCount-ne0){throw 'Edge Startup-folder drift detected.'};if(!(Same (ProtectedState) $s.protected)){throw 'Protected service configuration drift detected.'}}
function Applied{$r=Reg $Recommended $ValueName;$r.ValueExists-and$r.Kind-eq'DWord'-and[int]$r.Data-eq0}
try{$sup=Support;Log 'support-detection' $(if($sup.Supported){'pass'}else{'refused'}) $sup;switch($Action){'Check'{$sup};'Capture'{$s=Save $sup;Log 'capture' 'pass' $s;$s};'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join' ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Path=$Recommended;Name=$ValueName;Type='DWord';Value=0;RebootPersistenceRequired=$true;Rollback='Restore exact captured registry value/type/key semantics.';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $r;$r};'Apply'{$s=if(Test-Path $StatePath){Read}else{Save $sup};Drift $s;if(Applied){Log 'apply' 'idempotent' @{MutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};if($WhatIfPreference){Log 'apply' 'whatif' @{MutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$Recommended::$ValueName",'Set recommended Edge PerformanceDetectorEnabled to 0')){if(!(Test-Path $Recommended)){New-Item $Recommended -Force|Out-Null};New-ItemProperty $Recommended -Name $ValueName -PropertyType DWord -Value 0 -Force|Out-Null};if(!(Applied)){throw 'Apply verification failed.'};Log 'apply' 'pass' @{MutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}};'Verify'{$s=Read;Drift $s;if(!(Applied)){throw 'Policy verification failed.'};$r=[pscustomobject]@{Verified=$true};Log 'verify' 'pass' $r;$r};'VerifyReboot'{$s=Read;Drift $s;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootUtc){throw 'A later boot is required.'};if(!(Applied)){throw 'Reboot persistence failed.'};$r=[pscustomobject]@{VerifiedReboot=$true;BootUtc=$b.ToString('o')};Log 'verify-reboot' 'pass' $r;$r};'Rollback'{$s=Read;Drift $s;$now=Reg $Recommended $ValueName;if(!$s.original.ValueExists-and!$now.ValueExists){Log 'rollback' 'idempotent' @{MutationCount=0};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($s.original.ValueExists){if($now.ValueExists-and!(Applied)){throw 'Rollback collision detected.'};$k=Get-Item $Recommended;$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.original.Kind,$true);$k.SetValue($ValueName,$s.original.Data,$kind)}else{if($now.ValueExists-and!(Applied)){throw 'Rollback collision detected.'};if($now.ValueExists){Remove-ItemProperty $Recommended -Name $ValueName};if(!$s.original.KeyExists-and(Test-Path $Recommended)-and@((Get-Item $Recommended).GetValueNames()).Count-eq0-and@((Get-ChildItem $Recommended -ErrorAction SilentlyContinue)).Count-eq0){Remove-Item $Recommended}};$after=Reg $Recommended $ValueName;if(!(Same $after $s.original)){throw 'Exact rollback verification failed.'};Log 'rollback' 'pass' @{RestoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;RestoredExactOriginal=$true}}}}catch{Log 'failure' 'failure' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
