[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')]
    [string]$Action='Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$recommendedPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended'
$mandatoryPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge'
$valueName='StartupBoostEnabled'
function Write-ProviderLog([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$record=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-054';provider='edge-startup-boost-policy';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($record|ConvertTo-Json -Compress -Depth 10) -Encoding UTF8}
function Get-EdgePath{$paths=@("$env:ProgramFiles(x86)\Microsoft\Edge\Application\msedge.exe","$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe");@($paths|Where-Object{$_-and(Test-Path -LiteralPath $_)})|Select-Object -First 1}
function Get-ManagementState{$managed=$false;$signals=@();try{$text=(& dsregcmd.exe /status 2>$null)-join "`n";foreach($name in @('AzureAdJoined','DomainJoined','WorkplaceJoined')){if($text-match"(?im)^\s*$name\s*:\s*YES\s*$"){$managed=$true;$signals+=$name}}}catch{};[pscustomobject]@{Managed=$managed;Signals=$signals}}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$computer=Get-CimInstance Win32_ComputerSystem;$edge=Get-EdgePath;$version=$null;if($edge){$raw=(Get-Item -LiteralPath $edge).VersionInfo.ProductVersion;if($raw){$version=[version]$raw}};$management=Get-ManagementState;$admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$computer.Manufacturer-match'HP|Hewlett-Packard'-and$edge-and$version-and$version.Major-ge 88);OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$computer.Manufacturer;Model=$computer.Model;EdgePath=$edge;EdgeVersion=$(if($version){$version.ToString()}else{$null});Managed=$management.Managed;ManagementSignals=$management.Signals;Elevated=$admin}}
function Get-ValueState([string]$Path){$keyExists=Test-Path -LiteralPath $Path;$valueExists=$false;$data=$null;$kind=$null;if($keyExists){$key=Get-Item -LiteralPath $Path;$valueExists=$key.GetValueNames()-contains$valueName;if($valueExists){$data=$key.GetValue($valueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$kind=$key.GetValueKind($valueName).ToString()}};[pscustomobject]@{Path=$Path;KeyExists=$keyExists;ValueExists=$valueExists;Data=$data;Kind=$kind}}
function Assert-Safe($Support,$Recommended,$Mandatory){if(-not$Support.Elevated){throw'Elevation is required.'};if($Support.Managed){throw('Enterprise management detected: '+($Support.ManagementSignals-join', '))};if($Mandatory.ValueExists-or$Recommended.ValueExists){throw'Existing mandatory or recommended Edge policy detected; refusing to override.'}}
function Save-State($Support,$Recommended,$Mandatory){$state=[ordered]@{schemaVersion=1;experiment='EXP-054';provider='edge-startup-boost-policy';capturedUtc=(Get-Date).ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;recommendedPath=$recommendedPath;mandatoryPath=$mandatoryPath;valueName=$valueName;edgePath=$Support.EdgePath;edgeVersion=$Support.EdgeVersion;recommended=$Recommended;mandatory=$Mandatory};$state|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $StatePath -Encoding UTF8;$state}
function Read-State{if(-not(Test-Path -LiteralPath $StatePath)){throw"State file missing: $StatePath"};$state=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;if($state.schemaVersion-ne 1-or$state.experiment-ne'EXP-054'-or$state.provider-ne'edge-startup-boost-policy'-or$state.machine-ne$env:COMPUTERNAME-or$state.valueName-ne$valueName){throw'State identity validation failed.'};$state}
function Test-Applied{$current=Get-ValueState $recommendedPath;$current.ValueExists-and$current.Kind-eq'DWord'-and[int]$current.Data-eq 0}
function Restore-State($State){if($State.recommended.ValueExists){throw'Captured state was ineligible for application.'};$current=Get-ValueState $recommendedPath;if($current.ValueExists-and-not($current.Kind-eq'DWord'-and[int]$current.Data-eq 0)){throw'Rollback refused because the policy changed after application.'};if($current.ValueExists-and$PSCmdlet.ShouldProcess("$recommendedPath::$valueName",'Remove experiment policy')){Remove-ItemProperty -LiteralPath $recommendedPath -Name $valueName};if(-not$State.recommended.KeyExists-and(Test-Path -LiteralPath $recommendedPath)){if((Get-Item -LiteralPath $recommendedPath).ValueCount-eq 0-and@(Get-ChildItem -LiteralPath $recommendedPath -ErrorAction SilentlyContinue).Count-eq 0){if($PSCmdlet.ShouldProcess($recommendedPath,'Remove empty experiment-created key')){Remove-Item -LiteralPath $recommendedPath -Force}}}}
try{$support=Get-SupportState;Write-ProviderLog 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;if(-not$support.Supported){throw'Provider supports HP Windows 11 systems with Edge 88 or later only.'};$recommended=Get-ValueState $recommendedPath;$mandatory=Get-ValueState $mandatoryPath;switch($Action){'Check'{[pscustomobject]@{Support=$support;Recommended=$recommended;Mandatory=$mandatory}}'Capture'{Assert-Safe $support $recommended $mandatory;$state=Save-State $support $recommended $mandatory;Write-ProviderLog 'capture' 'pass' @{statePath=$StatePath};$state}'DryRun'{if((Test-Path -LiteralPath $StatePath)-and(Test-Applied)){[void](Read-State);$result=[pscustomobject]@{Provider='edge-startup-boost-policy';WouldChange=$false;AlreadyApplied=$true;BrowserRestartRequired=$true;RebootPersistenceCheckRequired=$true}}else{Assert-Safe $support $recommended $mandatory;$result=[pscustomobject]@{Provider='edge-startup-boost-policy';WouldChange=$true;Path=$recommendedPath;Name=$valueName;Kind='DWord';Data=0;BrowserRestartRequired=$true;RebootPersistenceCheckRequired=$true}};Write-ProviderLog 'dry-run' 'pass' $result;$result}'Apply'{if(Test-Path -LiteralPath $StatePath){$state=Read-State;if(Test-Applied){Write-ProviderLog 'apply' 'pass' @{changed=$false};[pscustomobject]@{Provider='edge-startup-boost-policy';Applied=$true;MutationCount=0;BrowserRestartRequired=$true;RebootRequired=$false};break}}else{Assert-Safe $support $recommended $mandatory;$state=Save-State $support $recommended $mandatory};if($PSCmdlet.ShouldProcess("$recommendedPath::$valueName",'Set REG_DWORD 0')){if(-not(Test-Path -LiteralPath $recommendedPath)){New-Item -Path $recommendedPath -Force|Out-Null};New-ItemProperty -LiteralPath $recommendedPath -Name $valueName -PropertyType DWord -Value 0 -Force|Out-Null};if(-not(Test-Applied)){throw'Apply verification failed.'};Write-ProviderLog 'apply' 'pass' @{changed=$true;browserRestartRequired=$true};[pscustomobject]@{Provider='edge-startup-boost-policy';Applied=$true;MutationCount=1;BrowserRestartRequired=$true;RebootRequired=$false}}'Verify'{$ok=Test-Applied;Write-ProviderLog 'verify' $(if($ok){'pass'}else{'fail'}) @{browserRestartRequired=$true};if(-not$ok){throw'Policy verification failed.'};$true}'VerifyReboot'{$ok=Test-Applied;Write-ProviderLog 'verify-reboot' $(if($ok){'pass'}else{'fail'}) @{bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime};if(-not$ok){throw'Reboot persistence verification failed.'};$true}'Rollback'{$state=Read-State;Restore-State $state;$current=Get-ValueState $recommendedPath;$ok=-not$current.ValueExists;Write-ProviderLog 'rollback' $(if($ok){'pass'}else{'fail'}) @{restoredExactOriginal=$ok};if(-not$ok){throw'Rollback verification failed.'};[pscustomobject]@{Provider='edge-startup-boost-policy';RolledBack=$true;MutationCount=1}}}}catch{Write-ProviderLog 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
