[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',[string]$StatePath,[string]$LogPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$recommendedPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended'
$mandatoryPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge'
$valueName='SleepingTabsEnabled'
function Write-Log([string]$Event,[string]$Result,[object]$Data){if($LogPath){$p=Split-Path -Parent $LogPath;if($p){New-Item -ItemType Directory -Path $p -Force|Out-Null};$r=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-072';provider='edge-sleeping-tabs-policy';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($r|ConvertTo-Json -Compress -Depth 10) -Encoding UTF8}}
function Get-EdgePath{@("$env:ProgramFiles(x86)\Microsoft\Edge\Application\msedge.exe","$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")|Where-Object{$_-and(Test-Path -LiteralPath $_)}|Select-Object -First 1}
function Get-Management{$signals=@();try{$t=(& dsregcmd.exe /status 2>$null)-join"`n";foreach($n in @('AzureAdJoined','DomainJoined','WorkplaceJoined')){if($t-match"(?im)^\s*$n\s*:\s*YES\s*$"){$signals+=$n}}}catch{};[pscustomobject]@{Managed=($signals.Count-gt0);Signals=$signals}}
function Get-Support{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$edge=Get-EdgePath;$v=if($edge){[version](Get-Item $edge).VersionInfo.ProductVersion}else{$null};$m=Get-Management;$admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and$edge-and$v.Major-ge88);Elevated=$admin;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;EdgePath=$edge;EdgeVersion=$(if($v){$v.ToString()}else{$null});Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Get-Value([string]$Path){$k=Test-Path $Path;$e=$false;$d=$null;$kind=$null;if($k){$key=Get-Item $Path;$e=$key.GetValueNames()-contains$valueName;if($e){$d=$key.GetValue($valueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$kind=$key.GetValueKind($valueName).ToString()}};[pscustomobject]@{Path=$Path;KeyExists=$k;ValueExists=$e;Data=$d;Kind=$kind}}
function Assert-Safe($s,$r,$m){if(-not$s.Elevated){throw'Elevation is required.'};if(-not$s.Supported){throw'HP Windows 11 with supported Microsoft Edge is required.'};if($s.Managed){throw('Enterprise management detected: '+($s.ManagementSignals-join', '))};if($m.ValueExists-or$r.ValueExists){throw'Existing mandatory or recommended Edge sleeping-tabs policy detected; refusing to override.'}}
function Save-State($s,$r,$m){if(-not$StatePath){throw'StatePath is required.'};$state=[ordered]@{schemaVersion=1;experiment='EXP-072';provider='edge-sleeping-tabs-policy';machine=$env:COMPUTERNAME;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');edgePath=$s.EdgePath;edgeVersion=$s.EdgeVersion;recommended=$r;mandatory=$m};$p=Split-Path -Parent $StatePath;if($p){New-Item -ItemType Directory -Path $p -Force|Out-Null};$state|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8;$state}
function Read-State{if(-not(Test-Path $StatePath)){throw"State file missing: $StatePath"};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne'EXP-072'-or$s.provider-ne'edge-sleeping-tabs-policy'-or$s.machine-ne$env:COMPUTERNAME){throw'State identity validation failed.'};$s}
function Test-Applied{$c=Get-Value $recommendedPath;$c.ValueExists-and$c.Kind-eq'DWord'-and[int]$c.Data-eq1}
try{$s=Get-Support;Write-Log 'support-detection' $(if($s.Supported){'pass'}else{'unsupported'}) $s;$r=Get-Value $recommendedPath;$m=Get-Value $mandatoryPath;switch($Action){
'Check'{[pscustomobject]@{Support=$s;Recommended=$r;Mandatory=$m}}
'Capture'{Assert-Safe $s $r $m;$x=Save-State $s $r $m;Write-Log 'capture' 'pass' $x;$x}
'DryRun'{if((Test-Path $StatePath)-and(Test-Applied)){[void](Read-State);$x=[pscustomobject]@{WouldChange=$false;AlreadyApplied=$true}}else{Assert-Safe $s $r $m;$x=[pscustomobject]@{WouldChange=$true;Path=$recommendedPath;Name=$valueName;Kind='DWord';Data=1;BrowserRestartRequired=$true}};Write-Log 'dry-run' 'pass' $x;$x}
'Apply'{if(Test-Path $StatePath){[void](Read-State);if(Test-Applied){Write-Log 'apply' 'pass' @{changed=$false};return [pscustomobject]@{Applied=$true;MutationCount=0}}}else{Assert-Safe $s $r $m;[void](Save-State $s $r $m)};if($PSCmdlet.ShouldProcess("$recommendedPath::$valueName",'Set REG_DWORD 1')){if(-not(Test-Path $recommendedPath)){New-Item $recommendedPath -Force|Out-Null};New-ItemProperty $recommendedPath -Name $valueName -PropertyType DWord -Value 1 -Force|Out-Null};if(-not(Test-Applied)){throw'Apply verification failed.'};Write-Log 'apply' 'pass' @{changed=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$ok=Test-Applied;Write-Log 'verify' $(if($ok){'pass'}else{'fail'}) @{browserRestartRequired=$true};if(-not$ok){throw'Verification failed.'};$true}
'VerifyReboot'{$ok=Test-Applied;Write-Log 'verify-reboot' $(if($ok){'pass'}else{'fail'}) @{bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime};if(-not$ok){throw'Reboot persistence verification failed.'};$true}
'Rollback'{$state=Read-State;if($state.recommended.ValueExists){throw'Captured state was ineligible.'};$c=Get-Value $recommendedPath;if($c.ValueExists-and-not($c.Kind-eq'DWord'-and[int]$c.Data-eq1)){throw'Rollback refused because policy drifted.'};if($c.ValueExists-and$PSCmdlet.ShouldProcess("$recommendedPath::$valueName",'Remove experiment policy')){Remove-ItemProperty $recommendedPath -Name $valueName};$ok=-not(Get-Value $recommendedPath).ValueExists;Write-Log 'rollback' $(if($ok){'pass'}else{'fail'}) @{restoredExactOriginal=$ok};if(-not$ok){throw'Rollback verification failed.'};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
