[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',[string]$StatePath,[string]$LogPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$recommendedPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended'
$mandatoryPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge'
$valueName='StartupBoostEnabled'
$targetValue=1
function Write-Log([string]$Event,[string]$Result,[object]$Data){if($LogPath){$parent=Split-Path -Parent $LogPath;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$record=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-079';provider='edge-startup-boost-enabled-policy';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($record|ConvertTo-Json -Compress -Depth 10) -Encoding UTF8}}
function Get-EdgePath{$paths=@("$env:ProgramFiles(x86)\Microsoft\Edge\Application\msedge.exe","$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")|Where-Object{$_-and(Test-Path -LiteralPath $_)};if(@($paths).Count-ne1){return $null};$paths|Select-Object -First 1}
function Get-Management{$signals=@();try{$text=(& dsregcmd.exe /status 2>$null)-join"`n";foreach($name in @('AzureAdJoined','DomainJoined','WorkplaceJoined')){if($text-match"(?im)^\s*$name\s*:\s*YES\s*$"){$signals+=$name}}}catch{};[pscustomobject]@{Managed=($signals.Count-gt0);Signals=$signals}}
function Get-Support{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$edge=Get-EdgePath;$version=if($edge){[version](Get-Item -LiteralPath $edge).VersionInfo.ProductVersion}else{$null};$management=Get-Management;$admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and$edge-and$version.Major-ge88);Elevated=$admin;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;EdgePath=$edge;EdgeVersion=$(if($version){$version.ToString()}else{$null});Managed=$management.Managed;ManagementSignals=$management.Signals}}
function Get-Value([string]$Path){$keyExists=Test-Path -LiteralPath $Path;$valueExists=$false;$data=$null;$kind=$null;if($keyExists){$key=Get-Item -LiteralPath $Path;$valueExists=$key.GetValueNames()-contains$valueName;if($valueExists){$data=$key.GetValue($valueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$kind=$key.GetValueKind($valueName).ToString()}};[pscustomobject]@{Path=$Path;KeyExists=$keyExists;ValueExists=$valueExists;Data=$data;Kind=$kind}}
function Assert-Safe($support,$recommended,$mandatory){if(-not$support.Elevated){throw'Elevation is required.'};if(-not$support.Supported){throw'HP Windows 11 with exactly one Microsoft Edge 88 or later installation is required.'};if($support.Managed){throw('Enterprise management detected: '+($support.ManagementSignals-join', '))};if($mandatory.ValueExists-or$recommended.ValueExists){throw'Existing mandatory or recommended Startup Boost policy detected; refusing to override.'}}
function Save-State($support,$recommended,$mandatory){if(-not$StatePath){throw'StatePath is required.'};$state=[ordered]@{schemaVersion=1;experiment='EXP-079';provider='edge-startup-boost-enabled-policy';machine=$env:COMPUTERNAME;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');edgePath=$support.EdgePath;edgeVersion=$support.EdgeVersion;targetValue=$targetValue;recommended=$recommended;mandatory=$mandatory};$parent=Split-Path -Parent $StatePath;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$state|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $StatePath -Encoding UTF8;$state}
function Read-State{if(-not(Test-Path -LiteralPath $StatePath)){throw"State file missing: $StatePath"};$state=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;if($state.schemaVersion-ne1-or$state.experiment-ne'EXP-079'-or$state.provider-ne'edge-startup-boost-enabled-policy'-or$state.machine-ne$env:COMPUTERNAME-or[int]$state.targetValue-ne$targetValue){throw'State identity validation failed.'};$state}
function Test-Applied{$current=Get-Value $recommendedPath;$current.ValueExists-and$current.Kind-eq'DWord'-and[int]$current.Data-eq$targetValue}
try{$support=Get-Support;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;$recommended=Get-Value $recommendedPath;$mandatory=Get-Value $mandatoryPath;switch($Action){
'Check'{[pscustomobject]@{Support=$support;Recommended=$recommended;Mandatory=$mandatory;TargetValue=$targetValue;BrowserRestartRequired=$true}}
'Capture'{Assert-Safe $support $recommended $mandatory;$state=Save-State $support $recommended $mandatory;Write-Log 'capture' 'pass' $state;$state}
'DryRun'{if((Test-Path -LiteralPath $StatePath)-and(Test-Applied)){[void](Read-State);$result=[pscustomobject]@{WouldChange=$false;AlreadyApplied=$true}}else{Assert-Safe $support $recommended $mandatory;$result=[pscustomobject]@{WouldChange=$true;Path=$recommendedPath;Name=$valueName;Kind='DWord';Data=$targetValue;BrowserRestartRequired=$true;RebootPersistenceCheckRequired=$true}};Write-Log 'dry-run' 'pass' $result;$result}
'Apply'{if(Test-Path -LiteralPath $StatePath){[void](Read-State);if(Test-Applied){Write-Log 'apply' 'pass' @{changed=$false};return [pscustomobject]@{Applied=$true;MutationCount=0}}}else{Assert-Safe $support $recommended $mandatory;[void](Save-State $support $recommended $mandatory)};if($PSCmdlet.ShouldProcess("$recommendedPath::$valueName","Set REG_DWORD $targetValue")){if(-not(Test-Path -LiteralPath $recommendedPath)){New-Item -Path $recommendedPath -Force|Out-Null};New-ItemProperty -LiteralPath $recommendedPath -Name $valueName -PropertyType DWord -Value $targetValue -Force|Out-Null};if(-not(Test-Applied)){throw'Apply verification failed.'};Write-Log 'apply' 'pass' @{changed=$true;targetValue=$targetValue;browserRestartRequired=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$ok=Test-Applied;Write-Log 'verify' $(if($ok){'pass'}else{'fail'}) @{browserRestartRequired=$true;targetValue=$targetValue};if(-not$ok){throw'Verification failed.'};$true}
'VerifyReboot'{$ok=Test-Applied;Write-Log 'verify-reboot' $(if($ok){'pass'}else{'fail'}) @{bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime;targetValue=$targetValue};if(-not$ok){throw'Reboot persistence verification failed.'};$true}
'Rollback'{$state=Read-State;if($state.recommended.ValueExists){throw'Captured state was ineligible.'};$current=Get-Value $recommendedPath;if($current.ValueExists-and-not($current.Kind-eq'DWord'-and[int]$current.Data-eq$targetValue)){throw'Rollback refused because policy drifted.'};if($current.ValueExists-and$PSCmdlet.ShouldProcess("$recommendedPath::$valueName",'Remove experiment policy')){Remove-ItemProperty -LiteralPath $recommendedPath -Name $valueName};$ok=-not(Get-Value $recommendedPath).ValueExists;Write-Log 'rollback' $(if($ok){'pass'}else{'fail'}) @{restoredExactOriginal=$ok};if(-not$ok){throw'Rollback verification failed.'};[pscustomobject]@{RolledBack=$true;MutationCount=$(if($current.ValueExists){1}else{0})}}
}}catch{Write-Log 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
