[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',[string]$StatePath,[string]$LogPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$policyPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge'
$valueName='HardwareAccelerationModeEnabled'
$targetValue=1
function Write-Log([string]$Event,[string]$Result,[object]$Data){if($LogPath){$p=Split-Path -Parent $LogPath;if($p){New-Item -ItemType Directory -Path $p -Force|Out-Null};$r=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-078';provider='edge-hardware-acceleration-policy';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($r|ConvertTo-Json -Compress -Depth 10) -Encoding UTF8}}
function Get-EdgePath{$paths=@("$env:ProgramFiles(x86)\Microsoft\Edge\Application\msedge.exe","$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")|Where-Object{$_-and(Test-Path -LiteralPath $_)};if(@($paths).Count-ne1){return $null};$paths|Select-Object -First 1}
function Get-Management{$signals=@();try{$t=(& dsregcmd.exe /status 2>$null)-join"`n";foreach($n in @('AzureAdJoined','DomainJoined','WorkplaceJoined')){if($t-match"(?im)^\s*$n\s*:\s*YES\s*$"){$signals+=$n}}}catch{};[pscustomobject]@{Managed=($signals.Count-gt0);Signals=$signals}}
function Get-Support{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$edge=Get-EdgePath;$v=if($edge){[version](Get-Item $edge).VersionInfo.ProductVersion}else{$null};$gpu=@(Get-CimInstance Win32_VideoController|Select-Object Name,DriverVersion,PNPDeviceID);$m=Get-Management;$admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and$edge-and$v.Major-ge77-and$gpu.Count-gt0);Elevated=$admin;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;EdgePath=$edge;EdgeVersion=$(if($v){$v.ToString()}else{$null});Graphics=$gpu;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Get-Value{$k=Test-Path $policyPath;$e=$false;$d=$null;$kind=$null;if($k){$key=Get-Item $policyPath;$e=$key.GetValueNames()-contains$valueName;if($e){$d=$key.GetValue($valueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$kind=$key.GetValueKind($valueName).ToString()}};[pscustomobject]@{Path=$policyPath;KeyExists=$k;ValueExists=$e;Data=$d;Kind=$kind}}
function Assert-Safe($s,$v){if(-not$s.Elevated){throw'Elevation is required.'};if(-not$s.Supported){throw'HP Windows 11 with one supported Microsoft Edge 77 or later installation and a detected graphics adapter is required.'};if($s.Managed){throw('Enterprise management detected: '+($s.ManagementSignals-join', '))};if($v.ValueExists){throw'Existing mandatory Edge graphics acceleration policy detected; refusing to override.'}}
function Save-State($s,$v){if(-not$StatePath){throw'StatePath is required.'};$state=[ordered]@{schemaVersion=1;experiment='EXP-078';provider='edge-hardware-acceleration-policy';machine=$env:COMPUTERNAME;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');edgePath=$s.EdgePath;edgeVersion=$s.EdgeVersion;graphics=$s.Graphics;targetValue=$targetValue;policy=$v};$p=Split-Path -Parent $StatePath;if($p){New-Item -ItemType Directory -Path $p -Force|Out-Null};$state|ConvertTo-Json -Depth 8|Set-Content $StatePath -Encoding UTF8;$state}
function Read-State{if(-not(Test-Path $StatePath)){throw"State file missing: $StatePath"};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne'EXP-078'-or$s.provider-ne'edge-hardware-acceleration-policy'-or$s.machine-ne$env:COMPUTERNAME-or[int]$s.targetValue-ne$targetValue){throw'State identity validation failed.'};$s}
function Test-Applied{$c=Get-Value;$c.ValueExists-and$c.Kind-eq'DWord'-and[int]$c.Data-eq$targetValue}
try{$s=Get-Support;Write-Log 'support-detection' $(if($s.Supported){'pass'}else{'unsupported'}) $s;$v=Get-Value;switch($Action){
'Check'{[pscustomobject]@{Support=$s;Policy=$v;TargetValue=$targetValue;BrowserRestartRequired=$true}}
'Capture'{Assert-Safe $s $v;$x=Save-State $s $v;Write-Log 'capture' 'pass' $x;$x}
'DryRun'{if((Test-Path $StatePath)-and(Test-Applied)){[void](Read-State);$x=[pscustomobject]@{WouldChange=$false;AlreadyApplied=$true}}else{Assert-Safe $s $v;$x=[pscustomobject]@{WouldChange=$true;Path=$policyPath;Name=$valueName;Kind='DWord';Data=$targetValue;BrowserRestartRequired=$true}};Write-Log 'dry-run' 'pass' $x;$x}
'Apply'{if(Test-Path $StatePath){[void](Read-State);if(Test-Applied){Write-Log 'apply' 'pass' @{changed=$false};return [pscustomobject]@{Applied=$true;MutationCount=0}}}else{Assert-Safe $s $v;[void](Save-State $s $v)};if($PSCmdlet.ShouldProcess("$policyPath::$valueName","Set REG_DWORD $targetValue")){if(-not(Test-Path $policyPath)){New-Item $policyPath -Force|Out-Null};New-ItemProperty $policyPath -Name $valueName -PropertyType DWord -Value $targetValue -Force|Out-Null};if(-not(Test-Applied)){throw'Apply verification failed.'};Write-Log 'apply' 'pass' @{changed=$true;targetValue=$targetValue;browserRestartRequired=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$ok=Test-Applied;Write-Log 'verify' $(if($ok){'pass'}else{'fail'}) @{browserRestartRequired=$true;targetValue=$targetValue};if(-not$ok){throw'Verification failed.'};$true}
'VerifyReboot'{$ok=Test-Applied;Write-Log 'verify-reboot' $(if($ok){'pass'}else{'fail'}) @{bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime;browserRestartRequired=$true;targetValue=$targetValue};if(-not$ok){throw'Reboot persistence verification failed.'};$true}
'Rollback'{$state=Read-State;if($state.policy.ValueExists){throw'Captured state was ineligible.'};$c=Get-Value;if($c.ValueExists-and-not($c.Kind-eq'DWord'-and[int]$c.Data-eq$targetValue)){throw'Rollback refused because policy drifted.'};if($c.ValueExists-and$PSCmdlet.ShouldProcess("$policyPath::$valueName",'Remove experiment policy')){Remove-ItemProperty $policyPath -Name $valueName};$ok=-not(Get-Value).ValueExists;Write-Log 'rollback' $(if($ok){'pass'}else{'fail'}) @{restoredExactOriginal=$ok};if(-not$ok){throw'Rollback verification failed.'};[pscustomobject]@{RolledBack=$true;MutationCount=$(if($c.ValueExists){1}else{0})}}
}}catch{Write-Log 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
