[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-096-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-096.jsonl",
 [string]$ProfileFixturePath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-096';$PolicyPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended';$MandatoryPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge';$ValueName='ClearCachedImagesAndFilesOnExit';$Treatment=0
function Log([string]$Event,[string]$Result,$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 24)-eq($b|ConvertTo-Json -Compress -Depth 24)}
function Reg([string]$Path,[string]$Name){if(!(Test-Path $Path)){return [pscustomobject]@{KeyExists=$false;ValueExists=$false;Kind=$null;Data=$null}};$k=Get-Item $Path;if($k.GetValueNames()-notcontains$Name){return [pscustomobject]@{KeyExists=$true;ValueExists=$false;Kind=$null;Data=$null}};[pscustomobject]@{KeyExists=$true;ValueExists=$true;Kind=$k.GetValueKind($Name).ToString();Data=$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function EdgeIdentity{$paths=@($env:ProgramFiles,${env:ProgramFiles(x86)})|Where-Object{$_}|ForEach-Object{Join-Path $_ 'Microsoft\Edge\Application\msedge.exe'}|Where-Object{Test-Path -LiteralPath $_}|Select-Object -Unique;$rows=@($paths|ForEach-Object{$f=Get-Item $_;$s=Get-AuthenticodeSignature $_;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Version=$f.VersionInfo.FileVersion;Major=[int]$f.VersionInfo.FileVersion.Split('.')[0];Sha256=(Get-FileHash $_ -Algorithm SHA256).Hash;Signature=$s.Status.ToString();Publisher=$pub;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidMicrosoft=($s.Status-eq'Valid'-and$pub-match'Microsoft Corporation')}});if($rows.Count-ne1){return $null};$rows[0]}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)}}
function Fixture{if(!$ProfileFixturePath-or!(Test-Path $ProfileFixturePath -PathType Container)){return $null};$m=Join-Path $ProfileFixturePath '.lacksan-edge-cache-retention.json';if(!(Test-Path $m)){return $null};$x=Get-Content $m -Raw|ConvertFrom-Json;if($x.experiment-ne$Experiment-or$x.controlledProfile-ne$true-or[string]::IsNullOrWhiteSpace([string]$x.profileId)){return $null};$cache=Join-Path $ProfileFixturePath 'Cache';if(!(Test-Path $cache)){ $cache=Join-Path $ProfileFixturePath 'Network\Cache' };$files=@(if(Test-Path $cache){Get-ChildItem $cache -File -Recurse -ErrorAction SilentlyContinue});[pscustomobject]@{Path=(Resolve-Path $ProfileFixturePath).Path;ProfileId=[string]$x.profileId;Marker=$m;MarkerSha256=(Get-FileHash $m -Algorithm SHA256).Hash;CachePath=$cache;CacheExists=(Test-Path $cache);CacheFileCount=$files.Count;CacheBytes=[int64](@($files|Measure-Object Length -Sum).Sum)}}
function EdgeCommandLines{$rows=@(Get-CimInstance Win32_Process -Filter "Name='msedge.exe'" -ErrorAction SilentlyContinue|Select-Object ProcessId,CommandLine);[pscustomobject]@{Processes=$rows;DiskCacheOverrideCount=@($rows|Where-Object{$_.CommandLine-match'(?i)(^|\s)--disk-cache-size(?:=|\s)'}).Count}}
function Startup{$shell=New-Object -ComObject WScript.Shell;$hits=@();foreach($d in @([Environment]::GetFolderPath('Startup'),[Environment]::GetFolderPath('CommonStartup'))|Where-Object{$_}|Select-Object -Unique){if(Test-Path $d){foreach($f in Get-ChildItem $d -File -ErrorAction SilentlyContinue){$target=$null;if($f.Extension-eq'.lnk'){try{$target=$shell.CreateShortcut($f.FullName).TargetPath}catch{}};if($f.Name-match'(?i)edge|msedge'-or$target-match'(?i)\\msedge\.exe$'){$hits+=[pscustomobject]@{Path=$f.FullName;Target=$target}}}}};[pscustomobject]@{EdgeEntries=$hits;Count=$hits.Count}}
function Protected{$svc=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','edgeupdate','edgeupdatem')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName;[pscustomobject]@{Services=@($svc)}}
function Policies{$related=[ordered]@{};foreach($n in 'ClearBrowsingDataOnExit','BrowsingDataLifetime','DiskCacheSize'){$related[$n]=[ordered]@{Mandatory=Reg $MandatoryPath $n;Recommended=Reg $PolicyPath $n}};[pscustomobject]@{CandidateMandatory=Reg $MandatoryPath $ValueName;CandidateRecommended=Reg $PolicyPath $ValueName;Related=[pscustomobject]$related}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$e=EdgeIdentity;$m=Management;$f=Fixture;$p=Policies;$cmd=EdgeCommandLines;$st=Startup;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required'};if(!(Elevated)){$reasons+='elevation required'};if(!$e-or!$e.ValidMicrosoft-or$e.Major-lt83){$reasons+='Microsoft-signed Edge 83+ required'};if($m.Managed){$reasons+='enterprise management ownership detected'};if(!$f){$reasons+='controlled profile identity required'};if($p.CandidateMandatory.ValueExists-or$p.CandidateRecommended.ValueExists){$reasons+='existing cache-on-close policy ownership detected'};if($p.Related.ClearBrowsingDataOnExit.Mandatory.ValueExists-or$p.Related.ClearBrowsingDataOnExit.Recommended.ValueExists){$reasons+='ClearBrowsingDataOnExit confounder detected'};if($p.Related.BrowsingDataLifetime.Mandatory.ValueExists-or$p.Related.BrowsingDataLifetime.Recommended.ValueExists){$reasons+='BrowsingDataLifetime confounder detected'};if($p.Related.DiskCacheSize.Mandatory.ValueExists-or$p.Related.DiskCacheSize.Recommended.ValueExists-or$cmd.DiskCacheOverrideCount-gt0){$reasons+='disk cache sizing confounder detected'};if($st.Count-ne0){$reasons+='Edge Startup-folder registration detected'};[pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=Elevated;Edge=$e;Management=$m;Fixture=$f;Policies=$p;CommandLines=$cmd;Startup=$st;Protected=Protected;EvidenceStatus='needs-evidence'}}
function Save($s){if(Test-Path $StatePath){throw 'State overwrite refused.'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$x=[ordered]@{schemaVersion=1;experiment=$Experiment;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$s;original=$s.Policies.CandidateRecommended;protected=$s.Protected;evidenceStatus='needs-evidence'};$x|ConvertTo-Json -Depth 24|Set-Content $StatePath -Encoding UTF8;$x}
function Load{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.experiment-ne$Experiment-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne[Security.Principal.WindowsIdentity]::GetCurrent().User.Value){throw 'State identity validation failed.'};$s}
function Drift($s){$e=EdgeIdentity;if(!$e-or$e.Sha256-ne$s.support.Edge.Sha256-or$e.Version-ne$s.support.Edge.Version-or$e.Thumbprint-ne$s.support.Edge.Thumbprint){throw 'Edge identity drift detected.'};if((Management).Managed){throw 'Management ownership drift detected.'};$f=Fixture;if(!$f-or$f.ProfileId-ne$s.support.Fixture.ProfileId-or$f.MarkerSha256-ne$s.support.Fixture.MarkerSha256){throw 'Profile identity drift detected.'};$p=Policies;if(!(Same $p.CandidateMandatory $s.support.Policies.CandidateMandatory)-or!(Same $p.Related $s.support.Policies.Related)){throw 'Related Edge policy drift detected.'};if((EdgeCommandLines).DiskCacheOverrideCount-gt0){throw 'Disk cache command-line override drift detected.'};if((Startup).Count-ne0){throw 'Edge Startup-folder drift detected.'};if(!(Same (Protected) $s.protected)){throw 'Protected security update or remote-access state drift detected.'}}
function Applied{$x=Reg $PolicyPath $ValueName;$x.ValueExists-and$x.Kind-eq'DWord'-and[int]$x.Data-eq$Treatment}
try{$support=Support;Log 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $support;switch($Action){
 'Check'{$support}
 'Capture'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$s=Save $support;Log 'capture' 'pass' $s;$s}
 'DryRun'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Path=$PolicyPath;Name=$ValueName;Type='DWord';Value=$Treatment;PreserveDiskCacheSize=$true;DeleteCacheFiles=$false;BrowserRestartRequired=$true;RebootPersistenceRequired=$true;Rollback='Restore exact captured registry value/type or remove only experiment-created value and empty key.';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $r;$r}
 'Apply'{$s=Load;Drift $s;if(Applied){Log 'apply' 'idempotent' @{mutationCount=0};return};$cur=Reg $PolicyPath $ValueName;if(!(Same $cur $s.original)){throw 'Candidate policy drift detected.'};if($WhatIfPreference){Log 'apply' 'whatif' @{mutationCount=0};return};if(Get-Process msedge -ErrorAction SilentlyContinue){throw 'Close Edge before application.'};if($PSCmdlet.ShouldProcess("$PolicyPath::$ValueName",'Set recommended cache retention policy')){if(!(Test-Path $PolicyPath)){New-Item $PolicyPath -Force|Out-Null};New-ItemProperty $PolicyPath -Name $ValueName -PropertyType DWord -Value $Treatment -Force|Out-Null};if(!(Applied)){throw 'Apply verification failed.'};Log 'apply' 'pass' @{mutationCount=1;before=$cur;after=(Reg $PolicyPath $ValueName)}}
 'Verify'{$s=Load;Drift $s;if(!(Applied)){throw 'Treatment policy absent.'};Log 'verify' 'pass' @{policy=(Reg $PolicyPath $ValueName);cacheMetadata=(Fixture)};$true}
 'VerifyReboot'{$s=Load;Drift $s;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};if(!(Applied)){throw 'Treatment failed reboot persistence.'};Log 'verify-reboot' 'pass' @{boot=$boot.ToString('o');policy=(Reg $PolicyPath $ValueName);evidenceStatus='needs-evidence'};$true}
 'Rollback'{$s=Load;Drift $s;$cur=Reg $PolicyPath $ValueName;if(!$cur.ValueExists-and!$s.original.ValueExists){Log 'rollback' 'idempotent' @{mutationCount=0};return};if($cur.ValueExists-and!(Applied)){throw 'Rollback collision or policy drift detected.'};if($WhatIfPreference){Log 'rollback' 'whatif' @{mutationCount=0};return};if(Get-Process msedge -ErrorAction SilentlyContinue){throw 'Close Edge before rollback.'};if($PSCmdlet.ShouldProcess("$PolicyPath::$ValueName",'Restore exact captured cache-on-close policy state')){if($s.original.ValueExists){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.original.Kind,$true);if(!(Test-Path $PolicyPath)){New-Item $PolicyPath -Force|Out-Null};(Get-Item $PolicyPath).SetValue($ValueName,$s.original.Data,$kind)}elseif(Test-Path $PolicyPath){Remove-ItemProperty $PolicyPath -Name $ValueName -ErrorAction SilentlyContinue;if(!$s.original.KeyExists-and@((Get-Item $PolicyPath).GetValueNames()).Count-eq0-and@((Get-ChildItem $PolicyPath -ErrorAction SilentlyContinue)).Count-eq0){Remove-Item $PolicyPath}}};$after=Reg $PolicyPath $ValueName;if(!(Same $after $s.original)){throw 'Exact rollback verification failed.'};Log 'rollback' 'pass' @{restoredExactOriginal=$true;after=$after;cacheFilesDeleted=$false};$after}
}}catch{Log 'failure' 'failure' @{stage=$Action;refusalReason=$_.Exception.Message;failureDetail=$_.Exception.ToString()};throw}
