[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath,
 [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-054'
$provider='edge-true-demand-launch'
$policyPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended'
$mandatoryPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge'
$valueName='StartupBoostEnabled'
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 16|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)};[pscustomobject]@{Managed=($x.DomainJoined-or$x.MdmEnrollments-gt0-or$x.PolicyManager-or$x.ConfigMgr);Signals=$x}}
function Get-EdgeIdentity{$paths=@("$env:ProgramFiles(x86)\Microsoft\Edge\Application\msedge.exe","$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")|Where-Object{Test-Path -LiteralPath $_};$items=@($paths|ForEach-Object{$i=Get-Item -LiteralPath $_;[pscustomobject]@{Path=$i.FullName;Version=$i.VersionInfo.FileVersion;Major=[int]($i.VersionInfo.FileVersion.Split('.')[0]);Sha256=(Get-FileHash -LiteralPath $_ -Algorithm SHA256).Hash}});if($items.Count-ne1){return $null};$items[0]}
function Get-RegistryState{param([string]$Path,[string]$Name);$keyExists=Test-Path -LiteralPath $Path;if(!$keyExists){return [pscustomobject]@{KeyExists=$false;ValueExists=$false;Kind=$null;Data=$null}};$k=Get-Item -LiteralPath $Path;$exists=$k.GetValueNames()-contains$Name;if(!$exists){return [pscustomobject]@{KeyExists=$true;ValueExists=$false;Kind=$null;Data=$null}};[pscustomobject]@{KeyExists=$true;ValueExists=$true;Kind=$k.GetValueKind($Name).ToString();Data=$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$e=Get-EdgeIdentity;$mandatory=Get-RegistryState $mandatoryPath $valueName;$recommended=Get-RegistryState $policyPath $valueName;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and(Test-Elevated)-and$e-and$e.Major-ge88-and!$m.Managed-and!$mandatory.ValueExists-and!$recommended.ValueExists);OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=Test-Elevated;Managed=$m.Managed;ManagementSignals=$m.Signals;Edge=$e;Mandatory=$mandatory;Recommended=$recommended}}
function Assert-Supported($s){if(!$s.Supported){throw 'Unsupported or policy-owned Edge Startup Boost state.'}}
function Save-State($s){Assert-Supported $s;if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$state=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;policyPath=$policyPath;valueName=$valueName;original=$s.Recommended;mandatory=$s.Mandatory;edge=$s.Edge;management=$s.ManagementSignals};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$state|ConvertTo-Json -Depth 16|Set-Content -LiteralPath $StatePath -Encoding UTF8;$state}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw 'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Test-Applied{$x=Get-RegistryState $policyPath $valueName;$x.ValueExists-and$x.Kind-eq'DWord'-and[int]$x.Data-eq0}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{[pscustomobject]@{Support=$support;Profile='EdgeTrueDemandLaunch'}}
'Capture'{$s=Save-State $support;Write-Log 'capture' 'pass' @{path=$policyPath;name=$valueName};$s}
'DryRun'{Assert-Supported $support;$r=[pscustomobject]@{Profile='EdgeTrueDemandLaunch';WouldChange=$true;MutationCount=1;Path=$policyPath;Name=$valueName;Type='DWord';Value=0;BrowserRestartRequired=$true;RebootPersistenceCheckRequired=$true;Rollback='Remove only the experiment-created value and newly created empty key.'};Write-Log 'dry-run' 'pass' $r;$r}
'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support};if(Test-Applied){Write-Log 'apply' 'idempotent' @{mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};Assert-Supported $support;if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$policyPath::$valueName",'Set recommended Edge Startup Boost policy to disabled')){if(!(Test-Path -LiteralPath $policyPath)){New-Item -Path $policyPath -Force|Out-Null};New-ItemProperty -LiteralPath $policyPath -Name $valueName -PropertyType DWord -Value 0 -Force|Out-Null};if(!(Test-Applied)){throw 'Apply verification failed.'};Write-Log 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{Read-State|Out-Null;if(!(Test-Applied)){throw 'Immediate verification failed.'};Write-Log 'verify' 'pass' @{value=0};$true}
'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};if(!(Test-Applied)){throw 'Reboot persistence failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o')};$true}
'Rollback'{$s=Read-State;$current=Get-RegistryState $policyPath $valueName;if(!$current.ValueExists){Write-Log 'rollback' 'idempotent' @{mutationCount=0};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($current.Kind-ne'DWord'-or[int]$current.Data-ne0){throw 'Policy drift detected; rollback refused.'};if((Get-ManagementState).Managed){throw 'Management ownership appeared.'};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$policyPath::$valueName",'Restore exact original Edge policy state')){Remove-ItemProperty -LiteralPath $policyPath -Name $valueName;if(!$s.original.KeyExists-and(Test-Path -LiteralPath $policyPath)){if(@((Get-Item -LiteralPath $policyPath).GetValueNames()).Count-eq0-and@(Get-ChildItem -LiteralPath $policyPath).Count-eq0){Remove-Item -LiteralPath $policyPath}}};$after=Get-RegistryState $policyPath $valueName;if($after.ValueExists){throw 'Exact rollback verification failed.'};Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message};throw}
