[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-148-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-148.jsonl",
 [string]$TargetProfilePath,
 [ValidateSet('Unknown','Local','AD','Entra','MSA')][string]$ProfileSignInType='Unknown',
 [switch]$BaselineContentActive,
 [switch]$SelfManagedNtpConfirmed,
 [switch]$CopilotNtpActive
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-148';$PolicyPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge';$RecommendedPath='HKLM:\SOFTWARE\Policies\Microsoft\Edge\Recommended';$ValueName='NewTabPageContentEnabled';$Treatment=0
function Log([string]$Event,[string]$Result,$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 32|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 32)-eq($b|ConvertTo-Json -Compress -Depth 32)}
function Reg([string]$Path,[string]$Name){$keyExists=Test-Path $Path;if(!$keyExists){return [pscustomobject]@{Path=$Path;KeyExists=$false;ValueExists=$false;Kind=$null;Data=$null;Owner=$null;Sddl=$null}};$k=Get-Item $Path;$acl=Get-Acl $Path;$exists=$k.GetValueNames()-contains$Name;[pscustomobject]@{Path=$Path;KeyExists=$true;ValueExists=$exists;Kind=$(if($exists){$k.GetValueKind($Name).ToString()}else{$null});Data=$(if($exists){$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}else{$null});Owner=$acl.Owner;Sddl=$acl.Sddl}}
function EdgeIdentity{$paths=@($env:ProgramFiles,${env:ProgramFiles(x86)})|Where-Object{$_}|ForEach-Object{Join-Path $_ 'Microsoft\Edge\Application\msedge.exe'}|Where-Object{Test-Path -LiteralPath $_}|Select-Object -Unique;$rows=@($paths|ForEach-Object{$f=Get-Item $_;$s=Get-AuthenticodeSignature $_;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Version=$f.VersionInfo.FileVersion;Major=[int]$f.VersionInfo.FileVersion.Split('.')[0];Sha256=(Get-FileHash $_ -Algorithm SHA256).Hash;Signature=$s.Status.ToString();Publisher=$pub;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidMicrosoft=($s.Status-eq'Valid'-and$pub-match'Microsoft Corporation')}});if($rows.Count-ne1){return $null};$rows[0]}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=$ccm}}
function Startup{$shell=New-Object -ComObject WScript.Shell;$hits=@();foreach($d in @([Environment]::GetFolderPath('Startup'),[Environment]::GetFolderPath('CommonStartup'))|Where-Object{$_}|Select-Object -Unique){if(Test-Path $d){foreach($f in Get-ChildItem $d -File -ErrorAction SilentlyContinue){$target=$null;if($f.Extension-eq'.lnk'){try{$target=$shell.CreateShortcut($f.FullName).TargetPath}catch{}};if($f.Name-match'(?i)edge|msedge'-or$target-match'(?i)\\msedge\.exe$'){$hits+=[pscustomobject]@{Path=$f.FullName;Target=$target}}}}};[pscustomobject]@{EdgeEntries=$hits;Count=$hits.Count}}
function Protected{$svc=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','edgeupdate','edgeupdatem')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName;[pscustomobject]@{Services=@($svc)}}
function Policies{$names=@('NewTabPageLocation','NewTabPagePrerenderEnabled','NewTabPageQuickLinksEnabled','NewTabPageAllowedBackgroundTypes','CopilotNewTabPageEnabled','RestoreOnStartup','StartupBoostEnabled','BackgroundModeEnabled','SleepingTabsEnabled','EfficiencyModeEnabled','NetworkPredictionOptions','LaunchEdgeOnWindowsStartupEnabled');$related=[ordered]@{};foreach($n in $names){$related[$n]=[ordered]@{Mandatory=Reg $PolicyPath $n;Recommended=Reg $RecommendedPath $n}};[pscustomobject]@{CandidateMandatory=Reg $PolicyPath $ValueName;CandidateRecommended=Reg $RecommendedPath $ValueName;Related=[pscustomobject]$related}}
function Profile([string]$Path,[string]$SignIn){if(!$Path){return [pscustomobject]@{Path=$null;Exists=$false;PreferencesExists=$false;SignInType=$SignIn;IdentityHash=$null}};$full=[IO.Path]::GetFullPath($Path);$pref=Join-Path $full 'Preferences';[pscustomobject]@{Path=$full;Exists=(Test-Path -LiteralPath $full -PathType Container);PreferencesExists=(Test-Path -LiteralPath $pref -PathType Leaf);SignInType=$SignIn;IdentityHash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes(($full.ToLowerInvariant()+'|'+$SignIn))))}}
function EdgeProcesses{$rows=@(Get-CimInstance Win32_Process -Filter "Name='msedge.exe'" -ErrorAction SilentlyContinue|ForEach-Object{$p=Get-Process -Id $_.ProcessId -ErrorAction SilentlyContinue;[pscustomobject]@{Pid=$_.ProcessId;CommandLine=$_.CommandLine;CpuSeconds=$(if($p){$p.CPU}else{$null});WorkingSet=$(if($p){$p.WorkingSet64}else{$null});PrivateBytes=$(if($p){$p.PrivateMemorySize64}else{$null});ReadBytes=$_.ReadTransferCount;WriteBytes=$_.WriteTransferCount}});[pscustomobject]@{Count=$rows.Count;Processes=$rows;Network='needs-evidence';Gpu='needs-evidence'}}
function Support([string]$Path,[string]$SignIn,[bool]$Baseline,[bool]$SelfManaged,[bool]$Copilot){$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$e=EdgeIdentity;$m=Management;$p=Policies;$st=Startup;$prof=Profile $Path $SignIn;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required'};if(!(Elevated)){$reasons+='elevation required'};if(!$e-or!$e.ValidMicrosoft-or$e.Major-lt91){$reasons+='Microsoft-signed Edge 91+ required'};if($m.Managed){$reasons+='enterprise management ownership detected'};if(!$SelfManaged){$reasons+='self-managed NTP ownership confirmation required'};if($p.CandidateMandatory.ValueExists-or$p.CandidateRecommended.ValueExists){$reasons+='existing NewTabPageContentEnabled policy ownership detected'};if($st.Count-ne0){$reasons+='Edge Startup-folder registration detected'};if(!$prof.Exists-or!$prof.PreferencesExists){$reasons+='exact Edge target profile path required'};if($SignIn-eq'Unknown'){$reasons+='target profile sign-in classification required'};if($SignIn-eq'MSA'){$reasons+='MSA-signed-in profiles are ineligible'};if(!$Baseline){$reasons+='baseline Microsoft NTP content proof required'};if($Copilot){$reasons+='Copilot NTP configuration requires separate applicability evidence'};[pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=Elevated;Edge=$e;Management=$m;Policies=$p;Startup=$st;Profile=$prof;BaselineContentActive=$Baseline;SelfManagedNtpConfirmed=$SelfManaged;CopilotNtpActive=$Copilot;Protected=Protected;Prelaunch=EdgeProcesses;EvidenceStatus='needs-evidence'}}
function Save($s){if(Test-Path $StatePath){throw 'State overwrite refused.'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');$x=[ordered]@{schemaVersion=1;experiment=$Experiment;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=$boot;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$s;original=$s.Policies.CandidateMandatory;protected=$s.Protected;evidenceStatus='needs-evidence'};$x|ConvertTo-Json -Depth 32|Set-Content $StatePath -Encoding UTF8;$x}
function Load{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne[Security.Principal.WindowsIdentity]::GetCurrent().User.Value){throw 'State identity validation failed.'};$s}
function Drift($s){$e=EdgeIdentity;if(!$e-or$e.Sha256-ne$s.support.Edge.Sha256-or$e.Version-ne$s.support.Edge.Version-or$e.Thumbprint-ne$s.support.Edge.Thumbprint){throw 'Edge identity drift detected.'};if((Management).Managed){throw 'Management ownership drift detected.'};$p=Policies;if(!(Same $p.CandidateRecommended $s.support.Policies.CandidateRecommended)-or!(Same $p.Related $s.support.Policies.Related)){throw 'Related Edge policy drift detected.'};if((Startup).Count-ne0){throw 'Edge Startup-folder drift detected.'};$prof=Profile $s.support.Profile.Path $s.support.Profile.SignInType;if(!$prof.Exists-or!$prof.PreferencesExists-or$prof.IdentityHash-ne$s.support.Profile.IdentityHash){throw 'Target Edge profile identity drift detected.'};if(!(Same (Protected) $s.protected)){throw 'Protected security update or remote-access state drift detected.'}}
function Applied{$x=Reg $PolicyPath $ValueName;$x.ValueExists-and$x.Kind-eq'DWord'-and[int]$x.Data-eq$Treatment}
try{$support=Support $TargetProfilePath $ProfileSignInType $BaselineContentActive.IsPresent $SelfManagedNtpConfirmed.IsPresent $CopilotNtpActive.IsPresent;Log 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $support;switch($Action){
 'Check'{$support}
 'Capture'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$s=Save $support;Log 'capture' 'pass' $s;$s}
 'DryRun'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Path=$PolicyPath;Name=$ValueName;Type='DWord';Value=$Treatment;DynamicPolicyRefresh=$true;BrowserRestartForBenchmark=$true;RebootPersistenceRequired=$true;TargetProfile=$support.Profile;Rollback='Restore exact captured registry value/type or remove only experiment-created value and empty key.';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $r;$r}
 'Apply'{$s=Load;Drift $s;if(Applied){Log 'apply' 'idempotent' @{mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};$cur=Reg $PolicyPath $ValueName;if(!(Same $cur $s.original)){throw 'Candidate policy drift detected.'};if($WhatIfPreference){Log 'apply' 'whatif' @{mutationCount=0};return [pscustomobject]@{Applied=$false;MutationCount=0;WhatIf=$true}};if(Get-Process msedge -ErrorAction SilentlyContinue){throw 'Close Edge before application for controlled cold-launch testing.'};if($PSCmdlet.ShouldProcess("$PolicyPath::$ValueName",'Disable Microsoft content on the Edge new-tab page')){if(!(Test-Path $PolicyPath)){New-Item $PolicyPath -Force|Out-Null};New-ItemProperty $PolicyPath -Name $ValueName -PropertyType DWord -Value $Treatment -Force|Out-Null};if(!(Applied)){throw 'Apply verification failed.'};Log 'apply' 'pass' @{mutationCount=1;before=$cur;after=(Reg $PolicyPath $ValueName)};[pscustomobject]@{Applied=$true;MutationCount=1}}
 'Verify'{$s=Load;Drift $s;if(!(Applied)){throw 'Treatment policy absent.'};if(Get-Process msedge -ErrorAction SilentlyContinue){throw 'Close Edge after observing the treated NTP before final controlled verification.'};if((Startup).Count-ne0){throw 'Edge Startup-folder registration present.'};Log 'verify' 'pass' @{policy=(Reg $PolicyPath $ValueName);startup=(Startup);targetProfile=$s.support.Profile;normalNtpShellAndContentAbsence='needs-evidence';controlledNavigation='needs-evidence'};$true}
 'VerifyReboot'{$s=Load;Drift $s;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};if(!(Applied)){throw 'Treatment failed reboot persistence.'};if((Startup).Count-ne0){throw 'Edge Startup-folder registration present after reboot.'};Log 'verify-reboot' 'pass' @{boot=$boot.ToString('o');policy=(Reg $PolicyPath $ValueName);startup=(Startup);targetProfile=$s.support.Profile;evidenceStatus='needs-evidence'};$true}
 'Rollback'{$s=Load;Drift $s;$cur=Reg $PolicyPath $ValueName;if(!$cur.ValueExists-and!$s.original.ValueExists){Log 'rollback' 'idempotent' @{mutationCount=0};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($cur.ValueExists-and!(Applied)){throw 'Rollback collision or policy drift detected.'};if($WhatIfPreference){Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;MutationCount=0;WhatIf=$true}};if(Get-Process msedge -ErrorAction SilentlyContinue){throw 'Close Edge before rollback.'};if($PSCmdlet.ShouldProcess("$PolicyPath::$ValueName",'Restore exact captured Edge NTP content policy state')){if($s.original.ValueExists){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.original.Kind,$true);if(!(Test-Path $PolicyPath)){New-Item $PolicyPath -Force|Out-Null};(Get-Item $PolicyPath).SetValue($ValueName,$s.original.Data,$kind)}elseif(Test-Path $PolicyPath){Remove-ItemProperty $PolicyPath -Name $ValueName -ErrorAction SilentlyContinue;if(!$s.original.KeyExists-and@((Get-Item $PolicyPath).GetValueNames()).Count-eq0-and@((Get-ChildItem $PolicyPath -ErrorAction SilentlyContinue)).Count-eq0){Remove-Item $PolicyPath}}};$after=Reg $PolicyPath $ValueName;if(!(Same $after $s.original)){throw 'Exact rollback verification failed.'};Log 'rollback' 'pass' @{restoredExactOriginal=$true;after=$after;originalNtpContentBehavior='needs-evidence'};[pscustomobject]@{RolledBack=$true;MutationCount=$(if($cur.ValueExists){1}else{0});Restored=$after}}
}}catch{Log 'failure' 'failure' @{stage=$Action;refusalReason=$_.Exception.Message;failureDetail=$_.Exception.ToString()};throw}
