[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath,
 [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-086'
$provider='high-performance-ac'
$highPerformanceGuid='8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c'
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 12|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$s=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)};[pscustomobject]@{Managed=($s.DomainJoined-or$s.MdmEnrollments-gt0-or$s.PolicyManager-or$s.ConfigMgr);Signals=$s}}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-PowerState{$b=Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue;$ac=if(!$b){$true}else{@($b|Where-Object{$_.BatteryStatus-in 2,3,6,7,8,9,11}).Count-gt0};$raw=& powercfg.exe /list 2>&1;if($LASTEXITCODE-ne0){throw 'powercfg inventory failed.'};$schemes=@();foreach($line in $raw){if($line-match'(?i)([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\s+\((.+)\)\s*(\*)?'){$schemes+=[pscustomobject]@{Guid=$matches[1].ToLowerInvariant();Name=$matches[2].Trim();Active=($matches[3]-eq'*')}}};$active=@($schemes|Where-Object Active);$candidate=@($schemes|Where-Object{$_.Guid-eq$highPerformanceGuid});[pscustomobject]@{AcConnected=$ac;Schemes=$schemes;Active=$active;Candidate=$candidate}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$p=Get-PowerState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and(Test-Elevated)-and$p.AcConnected-and!$m.Managed-and$p.Active.Count-eq1-and$p.Candidate.Count-eq1-and!$p.Candidate[0].Active);OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=Test-Elevated;Managed=$m.Managed;ManagementSignals=$m.Signals;Power=$p}}
function Assert-Supported($s){if(!$s.Supported){throw 'Eligible unmanaged elevated HP Windows 11 on AC power with one inactive High performance scheme is required.'}}
function Save-State($s){Assert-Supported $s;if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path $StatePath){throw 'State overwrite refused.'};$state=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;original=$s.Power.Active[0];candidate=$s.Power.Candidate[0];schemeInventory=$s.Power.Schemes};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$state|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $StatePath -Encoding UTF8;$state}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path $StatePath)){throw 'State artifact is missing.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Get-ActiveGuid{(Get-PowerState).Active[0].Guid}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{[pscustomobject]@{Support=$support;Profile='HighPerformanceAc'}}
'Capture'{Save-State $support}
'DryRun'{Assert-Supported $support;$r=[pscustomobject]@{Profile='HighPerformanceAc';WouldChange=$true;From=$support.Power.Active[0].Guid;To=$highPerformanceGuid;MutationCount=1;PreservesSchemeContents=$true;Rollback='Reactivate exact captured original scheme GUID.'};Write-Log 'dry-run' 'pass' $r;$r}
'Apply'{$s=if(Test-Path $StatePath){Read-State}else{Save-State $support};$a=Get-ActiveGuid;if($a-eq$s.candidate.Guid){Write-Log 'apply' 'idempotent' @{mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};if($a-ne$s.original.Guid){throw 'Active-scheme drift detected before application.'};if(!(Get-PowerState).AcConnected){throw 'AC power is required.'};if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($s.candidate.Guid,'Activate existing High performance scheme')){& powercfg.exe /setactive $s.candidate.Guid|Out-Null;if($LASTEXITCODE-ne0){throw 'powercfg application failed.'}};if((Get-ActiveGuid)-ne$s.candidate.Guid){throw 'Apply verification failed.'};Write-Log 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$s=Read-State;if((Get-ActiveGuid)-ne$s.candidate.Guid){throw 'Immediate verification failed.'};if(!(Get-PowerState).AcConnected){throw 'AC power disconnected.'};Write-Log 'verify' 'pass' @{active=$s.candidate.Guid};$true}
'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};if((Get-ActiveGuid)-ne$s.candidate.Guid){throw 'Reboot persistence failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o')};$true}
'Rollback'{$s=Read-State;$a=Get-ActiveGuid;if($a-eq$s.original.Guid){Write-Log 'rollback' 'idempotent' @{mutationCount=0};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($a-ne$s.candidate.Guid){throw 'Rollback drift refusal: another actor changed the active scheme.'};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($s.original.Guid,'Restore exact captured active scheme')){& powercfg.exe /setactive $s.original.Guid|Out-Null;if($LASTEXITCODE-ne0){throw 'powercfg rollback failed.'}};if((Get-ActiveGuid)-ne$s.original.Guid){throw 'Exact rollback verification failed.'};Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message};throw}
