[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',[string]$StatePath="$env:ProgramData\Lacksan\EXP-086-power-state.json",[string]$LogPath="$env:ProgramData\Lacksan\EXP-086-power-events.jsonl")
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$Experiment='EXP-086';$Provider='high-performance-power-scheme';$HighPerf='8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c'
function Log($e,$r,$d){$p=Split-Path $LogPath -Parent;if($p-and!(Test-Path $p)){New-Item -ItemType Directory $p -Force|Out-Null};[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;action=$Action;event=$e;result=$r;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$d;evidenceStatus='needs-evidence'}|ConvertTo-Json -Compress -Depth 20|Add-Content $LogPath -Encoding UTF8}
function Admin{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Mgmt{$c=Get-CimInstance Win32_ComputerSystem;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or$en-gt0);DomainJoined=[bool]$c.PartOfDomain;ConfigMgr=$ccm;EnrollmentCount=$en}}
function Schemes{$raw=& powercfg /list 2>&1;if($LASTEXITCODE-ne0){throw 'powercfg /list failed'};$rows=@();foreach($l in $raw){if($l-match'([0-9a-fA-F-]{36})\s+\(([^)]+)\)(\s+\*)?'){$rows+=[pscustomobject]@{Guid=$matches[1].ToLower();Name=$matches[2].Trim();Active=[bool]$matches[3]}}};@($rows)}
function AC{$b=Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue;if(!$b){return $true};@($b|Where-Object{$_.BatteryStatus-in 2,6,7,8,9,11}).Count-gt0}
function Protected{$names='WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale';@($names|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,StartMode,PathName)|ConvertTo-Json -Compress}
function Hash([string]$s){$x=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($x.ComputeHash([Text.Encoding]::UTF8.GetBytes($s)))).Replace('-','')}finally{$x.Dispose()}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$m=Mgmt;$sc=@(Schemes);$active=@($sc|Where-Object Active);$hp=@($sc|Where-Object Guid -eq $HighPerf);$r=@();if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required.'};if($cs.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required.'};if(!(Admin)){$r+='Elevation required.'};if($m.Managed){$r+='Enterprise management ownership detected.'};if(!(AC)){$r+='AC power required.'};if($active.Count-ne1){$r+='Exactly one active power scheme required.'};if($hp.Count-ne1){$r+='Exactly one existing High performance scheme required.'};if($hp.Count-eq1-and$hp[0].Active){$r+='High performance is already active.'};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;Management=$m;ACPower=(AC);Schemes=$sc;Original=if($active.Count-eq1){$active[0]}else{$null};Candidate=if($hp.Count-eq1){$hp[0]}else{$null};EvidenceStatus='needs-evidence'}}
function Save($s){if(!$s.Supported){throw($s.Reasons-join' ')};if(Test-Path $StatePath){throw 'State overwrite refused.'};$p=Split-Path $StatePath -Parent;if($p-and!(Test-Path $p)){New-Item -ItemType Directory $p -Force|Out-Null};$o=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;capturedBootUtc=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');original=$s.Original;candidate=$s.Candidate;management=$s.Management;protectedHash=Hash (Protected);evidenceStatus='needs-evidence'};$o|ConvertTo-Json -Depth 15|Set-Content $StatePath -Encoding UTF8;[pscustomobject]$o}
function Read{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne[Security.Principal.WindowsIdentity]::GetCurrent().User.Value-or$s.experiment-ne$Experiment){throw 'State identity validation failed.'};$s}
function Drift($s){if((Mgmt).Managed){throw 'Management drift detected.'};if(!(AC)){throw 'AC power drift detected.'};if((Hash (Protected))-ne[string]$s.protectedHash){throw 'Protected configuration drift detected.'};$sc=@(Schemes);if(@($sc|Where-Object Guid -eq[string]$s.original.Guid).Count-ne1-or@($sc|Where-Object Guid -eq[string]$s.candidate.Guid).Count-ne1){throw 'Power-scheme inventory drift detected.'};$sc}
function ActiveGuid{(@(Schemes|Where-Object Active)[0]).Guid}
try{$sup=Support;Log 'support-detection' $(if($sup.Supported){'pass'}else{'refused'}) $sup;switch($Action){'Check'{$sup};'Capture'{$s=Save $sup;Log capture pass $s;$s};'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join' ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;OriginalGuid=$sup.Original.Guid;TreatmentGuid=$sup.Candidate.Guid;Rollback='Reactivate exact captured original scheme GUID';EvidenceStatus='needs-evidence'};Log dry-run pass $r;$r};'Apply'{$s=if(Test-Path $StatePath){Read}else{Save $sup};Drift $s|Out-Null;if((ActiveGuid)-eq[string]$s.candidate.Guid){Log apply idempotent @{MutationCount=0};return};if($WhatIfPreference){Log apply whatif @{MutationCount=0};return};if($PSCmdlet.ShouldProcess($s.candidate.Guid,'Activate existing High performance scheme')){& powercfg /setactive $s.candidate.Guid|Out-Null;if($LASTEXITCODE-ne0){throw 'powercfg /setactive failed'}};if((ActiveGuid)-ne[string]$s.candidate.Guid){throw 'Application verification failed.'};Log apply pass @{MutationCount=1}};'Verify'{$s=Read;Drift $s|Out-Null;if((ActiveGuid)-ne[string]$s.candidate.Guid){throw 'Treatment verification failed.'};Log verify pass @{ActiveGuid=ActiveGuid};$true};'VerifyReboot'{$s=Read;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');if($b-eq[string]$s.capturedBootUtc){throw 'Later boot required.'};Drift $s|Out-Null;if((ActiveGuid)-ne[string]$s.candidate.Guid){throw 'Reboot persistence verification failed.'};Log verify-reboot pass @{Boot=$b};$true};'Rollback'{$s=Read;Drift $s|Out-Null;if((ActiveGuid)-eq[string]$s.original.Guid){Log rollback idempotent @{MutationCount=0};return};if($WhatIfPreference){Log rollback whatif @{MutationCount=0};return};if($PSCmdlet.ShouldProcess($s.original.Guid,'Restore captured original power scheme')){& powercfg /setactive $s.original.Guid|Out-Null;if($LASTEXITCODE-ne0){throw 'powercfg rollback failed'}};if((ActiveGuid)-ne[string]$s.original.Guid){throw 'Rollback verification failed.'};Log rollback pass @{MutationCount=1;ActiveGuid=ActiveGuid}}}}catch{Log failure fail @{Message=$_.Exception.Message};throw}
