[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-131-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-131.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop';$Experiment='EXP-131'
function Log($Event,$Result,$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 16|Add-Content $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function ExeFrom($p){$x=[Environment]::ExpandEnvironmentVariables($p.Trim());if($x.StartsWith('"')){$e=$x.IndexOf('"',1);if($e-gt1){return $x.Substring(1,$e-1)}}elseif($x-match '^([^ ]+\.exe)(?:\s|$)'){return $matches[1]};$null}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|?{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|?{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om}}
function Protected{@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|%{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|?{$_}|Sort Name|Select Name,State,StartMode,PathName}
function Candidate{$rows=@(Get-CimInstance Win32_Service|?{$_.DisplayName-match'(?i)HP.*Comm.*Recover' -or $_.PathName-match'(?i)HPCommRecovery\.exe'});if($rows.Count-ne1){return $null};$w=$rows[0];$exe=ExeFrom $w.PathName;if(!$exe-or!(Test-Path $exe -PathType Leaf)){return $null};$g=Get-Service $w.Name;$sig=Get-AuthenticodeSignature $exe;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};$key="HKLM:\SYSTEM\CurrentControlSet\Services\$($w.Name)";$k=Get-Item $key;$delay=if($k.GetValueNames()-contains'DelayedAutoStart'){[pscustomobject]@{Exists=$true;Kind=$k.GetValueKind('DelayedAutoStart').ToString();Data=$k.GetValue('DelayedAutoStart')}}else{[pscustomobject]@{Exists=$false;Kind=$null;Data=$null}};[pscustomobject]@{Name=$w.Name;DisplayName=$w.DisplayName;State=$w.State;StartMode=$w.StartMode;StartName=$w.StartName;PathName=$w.PathName;ServiceType=$w.ServiceType;Dependencies=@($g.ServicesDependedOn|% Name|Sort);Dependents=@($g.DependentServices|% Name|Sort);DelayedAutoStart=$delay;Executable=[pscustomobject]@{Path=$exe;Version=(Get-Item $exe).VersionInfo.FileVersion;Sha256=(Get-FileHash $exe -Algorithm SHA256).Hash;Signature=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidHp=($sig.Status-eq'Valid'-and$pub-match'(?i)HP Inc|Hewlett-Packard')}}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Management;$s=Candidate;$r=@();if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!(Elevated)){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};if(!$s){$r+='exactly one HP Comm Recovery candidate required'}else{if([IO.Path]::GetFileName($s.Executable.Path)-ne'HPCommRecovery.exe'){$r+='executable identity mismatch'};if(!$s.Executable.ValidHp){$r+='HP publisher signature invalid'};if($s.ServiceType-match'(?i)driver'){$r+='driver-backed service refused'};if($s.Dependencies.Count-or$s.Dependents.Count){$r+='dependency-sensitive service refused'};if($s.StartMode-notin@('Auto','Automatic')){$r+='Automatic baseline required'}};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Management=$m;Service=$s;Protected=Protected;EvidenceStatus='needs-evidence'}}
function Save($x){if(Test-Path $StatePath){throw 'State overwrite refused.'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory $d -Force|Out-Null};$o=[ordered]@{schemaVersion=1;experiment=$Experiment;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');support=$x};$o|ConvertTo-Json -Depth 16|Set-Content $StatePath -Encoding UTF8;$o}
function Load{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.experiment-ne$Experiment-or$s.machine-ne$env:COMPUTERNAME){throw 'State identity mismatch.'};$s}
function Drift($state){$c=Candidate;$o=$state.support.Service;if(!$c-or$c.Name-ne$o.Name-or$c.PathName-ne$o.PathName-or$c.Executable.Sha256-ne$o.Executable.Sha256-or$c.Executable.Thumbprint-ne$o.Executable.Thumbprint){throw 'Service identity drift detected.'};if((Management).Managed){throw 'Management drift detected.'};$c}
function Delayed($s){$s.StartMode-in@('Auto','Automatic')-and$s.DelayedAutoStart.Exists-and[int]$s.DelayedAutoStart.Data-eq1}
try{$sup=Support;Log support-detection $(if($sup.Supported){'pass'}else{'refused'}) $sup;switch($Action){'Check'{$sup};'Capture'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};Save $sup};'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};$x=@{WouldChange=(-not(Delayed $sup.Service));Service=$sup.Service.Name;To='AutomaticDelayedStart';PreserveRunningState=$true;Rollback='exact captured startup, delayed flag, and running state';EvidenceStatus='needs-evidence'};Log dry-run pass $x;$x};'Apply'{$st=Load;$c=Drift $st;if(Delayed $c){Log apply idempotent @{mutationCount=0};return $c};if($c.StartMode-ne$st.support.Service.StartMode){throw 'Configuration drift detected.'};$running=$c.State;if($WhatIfPreference){Log apply whatif @{mutationCount=0};return};if($PSCmdlet.ShouldProcess($c.Name,'Set Automatic Delayed Start')){Set-Service $c.Name -StartupType Automatic;$key="HKLM:\SYSTEM\CurrentControlSet\Services\$($c.Name)";Set-ItemProperty $key DelayedAutoStart 1 -Type DWord};$a=Candidate;if(!(Delayed $a)-or$a.State-ne$running){throw 'Apply verification failed.'};Log apply pass @{before=$c;after=$a};$a};'Verify'{$st=Load;$c=Drift $st;if(!(Delayed $c)){throw 'Delayed-start treatment absent.'};Log verify pass $c;$c};'VerifyReboot'{$st=Load;$c=Drift $st;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$st.capturedBootTime){throw 'Later boot required.'};if(!(Delayed $c)){throw 'Treatment failed reboot persistence.'};Log verify-reboot pass @{boot=$boot;service=$c;evidenceStatus='needs-evidence'};$c};'Rollback'{$st=Load;$c=Drift $st;$o=$st.support.Service;if(!(Delayed $c)){if($c.StartMode-eq$o.StartMode-and$c.State-eq$o.State){Log rollback idempotent @{mutationCount=0};return $c};throw 'Rollback collision detected.'};if($WhatIfPreference){Log rollback whatif @{restore=$o};return};if($PSCmdlet.ShouldProcess($c.Name,'Restore exact captured service state')){Set-Service $c.Name -StartupType Automatic;$key="HKLM:\SYSTEM\CurrentControlSet\Services\$($c.Name)";if($o.DelayedAutoStart.Exists){$k=Get-Item $key;$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$o.DelayedAutoStart.Kind,$true);$k.SetValue('DelayedAutoStart',$o.DelayedAutoStart.Data,$kind)}else{Remove-ItemProperty $key DelayedAutoStart -ErrorAction SilentlyContinue};$g=Get-Service $c.Name;if($o.State-eq'Running'-and$g.Status-ne'Running'){Start-Service $c.Name};if($o.State-eq'Stopped'-and$g.Status-ne'Stopped'){Stop-Service $c.Name}};$a=Candidate;if($a.StartMode-ne$o.StartMode-or$a.State-ne$o.State-or(($a.DelayedAutoStart|ConvertTo-Json -Compress)-ne($o.DelayedAutoStart|ConvertTo-Json -Compress))){throw 'Exact rollback verification failed.'};Log rollback pass @{restoredExactOriginal=$true;after=$a};$a}}}catch{Log failure failure @{stage=$Action;message=$_.Exception.Message};throw}
