[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-070-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-070.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-070';$ServiceName='HPCommRecovery';$ServiceKey="HKLM:\SYSTEM\CurrentControlSet\Services\$ServiceName"
function Log([string]$Event,[string]$Result,$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 16|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 16)-eq($b|ConvertTo-Json -Compress -Depth 16)}
function Reg([string]$Name){if(!(Test-Path $ServiceKey)){return [pscustomobject]@{Exists=$false;Kind=$null;Data=$null}};$k=Get-Item $ServiceKey;if($k.GetValueNames()-notcontains$Name){return [pscustomobject]@{Exists=$false;Kind=$null;Data=$null}};[pscustomobject]@{Exists=$true;Kind=$k.GetValueKind($Name).ToString();Data=$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function ExeFrom([string]$PathName){$x=[Environment]::ExpandEnvironmentVariables($PathName.Trim());if($x.StartsWith('"')){$e=$x.IndexOf('"',1);if($e-lt2){return $null};return $x.Substring(1,$e-1)};if($x-match '^([^ ]+\.exe)(?:\s|$)'){return $matches[1]};$null}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)}}
function Protected{$svc=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName;[pscustomobject]@{Services=@($svc)}}
function ServiceState{$rows=@(Get-CimInstance Win32_Service -Filter "Name='$ServiceName'");if($rows.Count-ne1){return $null};$w=$rows[0];$g=Get-Service -Name $ServiceName -ErrorAction Stop;$exe=ExeFrom $w.PathName;if(!$exe-or!(Test-Path -LiteralPath $exe -PathType Leaf)){return $null};$f=Get-Item $exe;$sig=Get-AuthenticodeSignature $exe;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};$deps=@($g.ServicesDependedOn|Select-Object -ExpandProperty Name|Sort-Object);$dependents=@($g.DependentServices|Select-Object -ExpandProperty Name|Sort-Object);$active=@(Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.Path -and([IO.Path]::GetFullPath($_.Path)-eq[IO.Path]::GetFullPath($exe))}|Select-Object Id,ProcessName,Path);[pscustomobject]@{Name=$w.Name;DisplayName=$w.DisplayName;State=$w.State;StartMode=$w.StartMode;StartName=$w.StartName;PathName=$w.PathName;ServiceType=$w.ServiceType;Dependencies=$deps;Dependents=$dependents;ActiveRecoveryProcesses=$active;RegistryStart=Reg 'Start';DelayedAutoStart=Reg 'DelayedAutoStart';Executable=[pscustomobject]@{Path=$f.FullName;Version=$f.VersionInfo.FileVersion;Product=$f.VersionInfo.ProductName;Company=$f.VersionInfo.CompanyName;Sha256=(Get-FileHash $exe -Algorithm SHA256).Hash;Signature=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidHp=($sig.Status-eq'Valid'-and$pub-match'(?i)HP Inc|Hewlett-Packard')}}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Management;$s=ServiceState;$reason=@();if($os.Caption-notmatch'Windows 11'){$reason+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reason+='HP platform required'};if(!(Elevated)){$reason+='elevation required'};if($m.Managed){$reason+='enterprise management ownership detected'};if(!$s){$reason+='exact HPCommRecovery service identity missing'}else{if($s.DisplayName-notmatch'(?i)HP.*Connection.*Recovery'){$reason+='display identity mismatch'};if([IO.Path]::GetFileName($s.Executable.Path)-ne'HPCommRecovery.exe'){$reason+='executable identity mismatch'};if(!$s.Executable.ValidHp){$reason+='HP publisher signature invalid'};if($s.ServiceType-match'(?i)driver'){$reason+='driver-backed service refused'};if($s.Dependencies.Count-or$s.Dependents.Count){$reason+='dependency-sensitive service refused'};if($s.ActiveRecoveryProcesses.Count){$reason+='active HP Connection Recovery process detected'};if($s.StartMode-eq'Disabled'){$reason+='disabled service refused'};if($s.StartMode-notin@('Auto','Automatic')){$reason+='baseline must be Automatic or Automatic Delayed Start'}};[pscustomobject]@{Supported=($reason.Count-eq0);Reasons=$reason;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=Elevated;Management=$m;Service=$s;EvidenceStatus='needs-evidence'}}
function Save($x){if(Test-Path $StatePath){throw 'State overwrite refused.'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$state=[ordered]@{schemaVersion=1;experiment=$Experiment;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$x;protected=Protected;evidenceStatus='needs-evidence'};$state|ConvertTo-Json -Depth 16|Set-Content $StatePath -Encoding UTF8;$state}
function Load{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.experiment-ne$Experiment-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne[Security.Principal.WindowsIdentity]::GetCurrent().User.Value){throw 'State identity validation failed.'};$s}
function Drift($state){$cur=ServiceState;if(!$cur){throw 'Service identity drift detected.'};$old=$state.support.Service;if($cur.PathName-ne$old.PathName-or$cur.Executable.Sha256-ne$old.Executable.Sha256-or$cur.Executable.Thumbprint-ne$old.Executable.Thumbprint){throw 'Service executable identity drift detected.'};if(!(Same $cur.Dependencies $old.Dependencies)-or!(Same $cur.Dependents $old.Dependents)){throw 'Dependency drift detected.'};if($cur.ActiveRecoveryProcesses.Count){throw 'Active recovery activity detected.'};if((Management).Managed){throw 'Management ownership drift detected.'};if(!(Same (Protected) $state.protected)){throw 'Protected security update or remote-access state drift detected.'};$cur}
function IsManual($s){$s.StartMode-eq'Manual'}
try{$support=Support;Log 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $support;switch($Action){
 'Check'{$support}
 'Capture'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$s=Save $support;Log 'capture' 'pass' $s;$s}
 'DryRun'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Service=$ServiceName;From=$support.Service.StartMode;To='Manual';PreserveRunningState=$true;RebootPersistenceRequired=$true;Rollback='Restore exact captured startup mode, delayed-auto-start value, and original running state.';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $r;$r}
 'Apply'{$state=Load;$cur=Drift $state;if(IsManual $cur){if(!(Same $cur.DelayedAutoStart $state.support.Service.DelayedAutoStart)){throw 'Idempotent apply refused on delayed-auto-start drift.'};Log 'apply' 'idempotent' @{mutationCount=0};return $cur};if($cur.StartMode-ne$state.support.Service.StartMode-or!(Same $cur.DelayedAutoStart $state.support.Service.DelayedAutoStart)){throw 'Service configuration drift detected.'};$running=$cur.State;if($WhatIfPreference){Log 'apply' 'whatif' @{mutationCount=0;to='Manual'};return};if($PSCmdlet.ShouldProcess($ServiceName,'Set startup type to Manual while preserving running state')){Set-Service -Name $ServiceName -StartupType Manual}else{return};$after=ServiceState;if(!(IsManual $after)-or$after.State-ne$running-or!(Same $after.DelayedAutoStart $state.support.Service.DelayedAutoStart)){throw 'Apply verification failed.'};Log 'apply' 'pass' @{mutationCount=1;before=$cur;after=$after};$after}
 'Verify'{$state=Load;$cur=Drift $state;if(!(IsManual $cur)){throw 'Treatment startup mode absent.'};if(!(Same $cur.DelayedAutoStart $state.support.Service.DelayedAutoStart)){throw 'Delayed-auto-start drift detected.'};Log 'verify' 'pass' $cur;$cur}
 'VerifyReboot'{$state=Load;$cur=Drift $state;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$state.capturedBootTime){throw 'A later boot is required.'};if(!(IsManual $cur)){throw 'Treatment failed reboot persistence.'};Log 'verify-reboot' 'pass' @{boot=$boot.ToString('o');service=$cur;evidenceStatus='needs-evidence'};$cur}
 'Rollback'{$state=Load;$cur=Drift $state;$old=$state.support.Service;if($cur.StartMode-ne'Manual'){if($cur.StartMode-eq$old.StartMode-and(Same $cur.DelayedAutoStart $old.DelayedAutoStart)-and$cur.State-eq$old.State){Log 'rollback' 'idempotent' @{mutationCount=0};return $cur};throw 'Rollback collision or service configuration drift detected.'};if(!(Same $cur.DelayedAutoStart $old.DelayedAutoStart)){throw 'Rollback refused on delayed-auto-start drift.'};if($WhatIfPreference){Log 'rollback' 'whatif' @{restoreStartMode=$old.StartMode;restoreRunningState=$old.State};return};if($PSCmdlet.ShouldProcess($ServiceName,'Restore exact captured startup and running state')){Set-Service -Name $ServiceName -StartupType Automatic;if($old.DelayedAutoStart.Exists){$k=Get-Item $ServiceKey;$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$old.DelayedAutoStart.Kind,$true);$k.SetValue('DelayedAutoStart',$old.DelayedAutoStart.Data,$kind)}elseif((Reg 'DelayedAutoStart').Exists){Remove-ItemProperty $ServiceKey -Name 'DelayedAutoStart'};$now=Get-Service $ServiceName;if($old.State-eq'Running'-and$now.Status-ne'Running'){Start-Service $ServiceName};if($old.State-eq'Stopped'-and$now.Status-ne'Stopped'){Stop-Service $ServiceName}}else{return};$after=ServiceState;if($after.StartMode-ne$old.StartMode-or!(Same $after.DelayedAutoStart $old.DelayedAutoStart)-or$after.State-ne$old.State){throw 'Exact rollback verification failed.'};Log 'rollback' 'pass' @{restoredExactOriginal=$true;after=$after};$after}
}}catch{Log 'failure' 'failure' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
