[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-067-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-067.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-067'
function Log($Event,$Result,$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 20)-eq($b|ConvertTo-Json -Compress -Depth 20)}
function ExeFrom($p){$x=[Environment]::ExpandEnvironmentVariables(([string]$p).Trim());if($x.StartsWith('"')){$i=$x.IndexOf('"',1);if($i-gt1){return $x.Substring(1,$i-1)}}elseif($x-match '^([^ ]+\.exe)(?:\s|$)'){return $matches[1]};$null}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=$ccm}}
function Protected{@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName}
function Reg($name,$value){$p="HKLM:\SYSTEM\CurrentControlSet\Services\$name";if(!(Test-Path $p)){return[pscustomobject]@{Exists=$false;Kind=$null;Data=$null}};$k=Get-Item $p;if($k.GetValueNames()-notcontains$value){return[pscustomobject]@{Exists=$false;Kind=$null;Data=$null}};[pscustomobject]@{Exists=$true;Kind=$k.GetValueKind($value).ToString();Data=$k.GetValue($value,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function Candidate{$rows=@(Get-CimInstance Win32_Service -Filter "Name='HPDiagsCap'");if($rows.Count-ne1){return $null};$w=$rows[0];if($w.DisplayName-notmatch'(?i)HP Diagnostics HSA Service'){return $null};$exe=ExeFrom $w.PathName;if(!$exe-or!(Test-Path -LiteralPath $exe -PathType Leaf)-or[IO.Path]::GetFileName($exe)-ne'DiagsCap.exe'){return $null};$sig=Get-AuthenticodeSignature -FilePath $exe;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};if($sig.Status-ne'Valid'-or$pub-notmatch'(?i)HP Inc|Hewlett-Packard'){return $null};$g=Get-Service $w.Name;[pscustomobject]@{Name=$w.Name;DisplayName=$w.DisplayName;State=$w.State;StartMode=$w.StartMode;StartName=$w.StartName;PathName=$w.PathName;ServiceType=$w.ServiceType;Dependencies=@($g.ServicesDependedOn|ForEach-Object Name|Sort-Object);Dependents=@($g.DependentServices|ForEach-Object Name|Sort-Object);RegistryStart=Reg $w.Name 'Start';DelayedAutoStart=Reg $w.Name 'DelayedAutoStart';Executable=[pscustomobject]@{Path=$exe;Version=(Get-Item $exe).VersionInfo.FileVersion;Sha256=(Get-FileHash $exe -Algorithm SHA256).Hash;Publisher=$pub;Thumbprint=$sig.SignerCertificate.Thumbprint;ValidHp=$true}}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Management;$s=Candidate;$r=@();if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!(Elevated)){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};if(!$s){$r+='exact signed HPDiagsCap DiagsCap.exe identity required'}else{if($s.ServiceType-match'(?i)driver'){$r+='driver-backed service refused'};if($s.Dependencies.Count-or$s.Dependents.Count){$r+='dependency-sensitive service refused'};if($s.StartMode-notin@('Auto','Automatic')){$r+='Automatic baseline required'};if($s.State-eq'Start Pending'-or$s.State-eq'Stop Pending'){$r+='active diagnostic transition refused'}};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=Elevated;Management=$m;Service=$s;Protected=Protected;EvidenceStatus='needs-evidence'}}
function Save($x){if(Test-Path $StatePath){throw 'State overwrite refused.'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory $d -Force|Out-Null};$o=[ordered]@{schemaVersion=1;experiment=$Experiment;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');support=$x;protected=$x.Protected;evidenceStatus='needs-evidence'};$o|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;$o}
function Load{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;if($s.experiment-ne$Experiment-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne[Security.Principal.WindowsIdentity]::GetCurrent().User.Value){throw 'State identity mismatch.'};$s}
function Drift($st){$c=Candidate;$o=$st.support.Service;if(!$c-or$c.Name-ne$o.Name-or$c.DisplayName-ne$o.DisplayName-or$c.PathName-ne$o.PathName-or$c.Executable.Sha256-ne$o.Executable.Sha256-or$c.Executable.Thumbprint-ne$o.Executable.Thumbprint){throw 'Service identity drift detected.'};if((Management).Managed){throw 'Management drift detected.'};if(!(Same $c.Dependencies $o.Dependencies)-or!(Same $c.Dependents $o.Dependents)){throw 'Dependency drift detected.'};if(!(Same (Protected) $st.protected)){throw 'Protected security update or remote-access state drift detected.'};$c}
function Manual($s){$s.StartMode-eq'Manual'}
try{$sup=Support;Log 'support-detection' $(if($sup.Supported){'pass'}else{'refused'}) $sup;switch($Action){
 'Check'{$sup}
 'Capture'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};Save $sup}
 'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};$x=[pscustomobject]@{WouldChange=$true;MutationCount=1;Service=$sup.Service.Name;From=$sup.Service.StartMode;To='Manual';PreserveRunningState=$true;RebootPersistenceRequired=$true;Rollback='restore exact captured startup mode, delayed-start value, and running state';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $x;$x}
 'Apply'{$st=Load;$c=Drift $st;if(Manual $c){if(!(Same $c.DelayedAutoStart $st.support.Service.DelayedAutoStart)){throw 'Idempotent apply refused on delayed-start drift.'};Log 'apply' 'idempotent' @{mutationCount=0};return $c};if($c.StartMode-ne$st.support.Service.StartMode-or!(Same $c.DelayedAutoStart $st.support.Service.DelayedAutoStart)){throw 'Configuration drift detected.'};$running=$c.State;if($WhatIfPreference){Log 'apply' 'whatif' @{mutationCount=0;to='Manual'};return};if($PSCmdlet.ShouldProcess($c.Name,'Set HP Diagnostics HSA Service to Manual while preserving running state')){Set-Service -Name $c.Name -StartupType Manual}else{return};$a=Candidate;if(!(Manual $a)-or$a.State-ne$running-or!(Same $a.DelayedAutoStart $st.support.Service.DelayedAutoStart)){throw 'Apply verification failed.'};Log 'apply' 'pass' @{mutationCount=1;before=$c;after=$a};$a}
 'Verify'{$st=Load;$c=Drift $st;if(!(Manual $c)){throw 'Manual treatment absent.'};if(!(Same $c.DelayedAutoStart $st.support.Service.DelayedAutoStart)){throw 'Delayed-start drift detected.'};Log 'verify' 'pass' $c;$c}
 'VerifyReboot'{$st=Load;$c=Drift $st;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$st.capturedBootTime){throw 'Later boot required.'};if(!(Manual $c)){throw 'Treatment failed reboot persistence.'};Log 'verify-reboot' 'pass' @{boot=$boot.ToString('o');service=$c;evidenceStatus='needs-evidence'};$c}
 'Rollback'{$st=Load;$c=Drift $st;$o=$st.support.Service;if(!(Manual $c)){if($c.StartMode-eq$o.StartMode-and$c.State-eq$o.State-and(Same $c.DelayedAutoStart $o.DelayedAutoStart)){Log 'rollback' 'idempotent' @{mutationCount=0};return $c};throw 'Rollback collision detected.'};if(!(Same $c.DelayedAutoStart $o.DelayedAutoStart)){throw 'Rollback refused on delayed-start drift.'};if($WhatIfPreference){Log 'rollback' 'whatif' @{restoreStartMode=$o.StartMode;restoreRunningState=$o.State};return};if($PSCmdlet.ShouldProcess($c.Name,'Restore exact captured HP Diagnostics HSA service state')){Set-Service -Name $c.Name -StartupType Automatic;$key="HKLM:\SYSTEM\CurrentControlSet\Services\$($c.Name)";if($o.DelayedAutoStart.Exists){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$o.DelayedAutoStart.Kind,$true);(Get-Item $key).SetValue('DelayedAutoStart',$o.DelayedAutoStart.Data,$kind)}elseif((Reg $c.Name 'DelayedAutoStart').Exists){Remove-ItemProperty -LiteralPath $key -Name DelayedAutoStart};$g=Get-Service $c.Name;if($o.State-eq'Running'-and$g.Status-ne'Running'){Start-Service $c.Name};if($o.State-eq'Stopped'-and$g.Status-ne'Stopped'){Stop-Service $c.Name}}else{return};$a=Candidate;if($a.StartMode-ne$o.StartMode-or$a.State-ne$o.State-or!(Same $a.DelayedAutoStart $o.DelayedAutoStart)){throw 'Exact rollback verification failed.'};Log 'rollback' 'pass' @{restoredExactOriginal=$true;after=$a};$a}
}}catch{Log 'failure' 'failure' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'};throw}
