[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$serviceName='HPDiagsCap'
$serviceReg="HKLM:\SYSTEM\CurrentControlSet\Services\$serviceName"
$policyPaths=@("HKLM:\SOFTWARE\Policies\Microsoft\Windows\System\Services\$serviceName","HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device\SystemServices\$serviceName")
$protectedPattern='(?i)defender|firewall|bitlocker|credential|vbs|security|update|recovery|accessibility|omnissa|vmware|windows app|remote desktop|termservice|tailscale|driver|network|vpn'

function Write-StructuredLog([string]$Event,[string]$Result,[object]$Data){if($LogPath){$r=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-067';provider='hp-diagnostics-hsa-service';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($r|ConvertTo-Json -Compress -Depth 12) -Encoding UTF8}}
function Get-ExecutablePath([string]$CommandLine){if([string]::IsNullOrWhiteSpace($CommandLine)){return $null};if($CommandLine -match '^\s*"([^"]+)"'){return $matches[1]};(($CommandLine -split '\s+',2)[0]).Trim('"')}
function Get-ManagementSignals{$signals=@();foreach($p in $policyPaths){if(Test-Path -LiteralPath $p){$signals+=$p}};[pscustomobject]@{PolicyPaths=@($signals);Owned=(@($signals).Count -gt 0)}}
function Get-DiagnosticActivity{$processes=@(Get-Process -ErrorAction SilentlyContinue|Where-Object {$_.ProcessName -match '(?i)HP.*Diag|Diag.*HP|HPDiags|HardwareDiagnostics'}|Select-Object ProcessName,Id);[pscustomobject]@{Processes=$processes;Active=($processes.Count -gt 0)}}
function Get-Support{
    $os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem
    $admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    $services=@(Get-CimInstance Win32_Service -Filter "Name='$serviceName'" -ErrorAction SilentlyContinue);$svc=if($services.Count -eq 1){$services[0]}else{$null}
    $exe=if($svc){Get-ExecutablePath $svc.PathName}else{$null};$sig=if($exe -and(Test-Path $exe)){Get-AuthenticodeSignature $exe}else{$null}
    $deps=if($svc){@($svc.Dependencies)}else{@()};$dependents=if($svc){@(Get-Service $serviceName -ErrorAction SilentlyContinue|ForEach-Object {$_.DependentServices.Name})}else{@()}
    $management=Get-ManagementSignals;$activity=Get-DiagnosticActivity
    $identity=($svc -and $svc.DisplayName -match '(?i)HP.*Diag.*HSA|HP Diagnostics' -and $exe -match '(?i)DiagsCap\.exe$')
    $publisher=($sig -and $sig.Status -eq 'Valid' -and $sig.SignerCertificate.Subject -match '(?i)HP Inc|Hewlett-Packard')
    $dependencySafe=(@($deps+$dependents|Where-Object {$_ -match $protectedPattern}).Count -eq 0)
    [pscustomobject]@{Supported=($os.Caption -match 'Windows 11' -and $cs.Manufacturer -match '(?i)^HP$|Hewlett-Packard' -and $services.Count -eq 1 -and $identity -and $publisher -and $dependencySafe -and -not $management.Owned -and -not $activity.Active);Elevated=$admin;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;ServiceCount=$services.Count;Service=$svc;Executable=$exe;IdentityMatched=$identity;PublisherMatched=$publisher;SignatureStatus=if($sig){$sig.Status}else{$null};Signer=if($sig -and $sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};Dependencies=$deps;DependentServices=$dependents;DependencySafe=$dependencySafe;Management=$management;DiagnosticActivity=$activity}
}
function Get-State{
    $svc=Get-CimInstance Win32_Service -Filter "Name='$serviceName'" -ErrorAction Stop;$delayed=0
    if(Test-Path $serviceReg){$v=Get-ItemProperty $serviceReg -Name DelayedAutoStart -ErrorAction SilentlyContinue;if($null-ne$v){$delayed=[int]$v.DelayedAutoStart}}
    $exe=Get-ExecutablePath $svc.PathName;$sig=if($exe-and(Test-Path $exe)){Get-AuthenticodeSignature $exe}else{$null}
    [pscustomobject]@{Name=$svc.Name;DisplayName=$svc.DisplayName;PathName=$svc.PathName;ExecutablePath=$exe;StartMode=$svc.StartMode;State=$svc.State;DelayedAutoStart=$delayed;StartName=$svc.StartName;Dependencies=@($svc.Dependencies);DependentServices=@(Get-Service $serviceName|ForEach-Object {$_.DependentServices.Name});ExecutableVersion=if($exe-and(Test-Path $exe)){(Get-Item $exe).VersionInfo.FileVersion}else{$null};ExecutableHash=if($exe-and(Test-Path $exe)){(Get-FileHash $exe -Algorithm SHA256).Hash}else{$null};SignatureStatus=if($sig){$sig.Status}else{$null};Signer=if($sig-and$sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};DiagnosticActivity=Get-DiagnosticActivity}
}
function Save-State($State,$Support){if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};$saved=[ordered]@{schemaVersion=1;experiment='EXP-067';provider='hp-diagnostics-hsa-service';machine=$env:COMPUTERNAME;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');windowsBuild=$Support.Build;manufacturer=$Support.Manufacturer;model=$Support.Model;service=$State};$parent=Split-Path -Parent $StatePath;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$saved|ConvertTo-Json -Depth 12|Set-Content $StatePath -Encoding UTF8;$saved}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or-not(Test-Path $StatePath)){throw "State file missing: $StatePath"};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne'EXP-067'-or$s.provider-ne'hp-diagnostics-hsa-service'-or$s.machine-ne$env:COMPUTERNAME-or$s.service.Name-ne$serviceName){throw 'State identity validation failed.'};$s}
function Assert-Safe($Support,$State){if(-not$Support.Elevated){throw 'Elevation is required.'};if(-not$Support.Supported){throw 'Exact supported HP Windows 11 HP Diagnostics HSA identity and inactive diagnostics are required.'};if($State.StartMode-ne'Auto'){throw 'Eligible start mode must be Automatic or Automatic Delayed Start.'};if($State.Dependencies.Count-gt0-or$State.DependentServices.Count-gt0){throw 'Service dependencies require physical review.'};if($State.DiagnosticActivity.Active){throw 'Active HP diagnostics session detected.'}}
function Test-Applied{$s=Get-State;($s.StartMode-eq'Manual'-and$s.DelayedAutoStart-eq0)}
function Assert-Identity($Saved,$Current){foreach($f in @('Name','DisplayName','PathName','ExecutablePath','StartName','ExecutableVersion','ExecutableHash','SignatureStatus','Signer')){if([string]$Current.$f-ne[string]$Saved.service.$f){throw "Rollback refused because service identity drifted: $f"}};if((@($Current.Dependencies)-join'|')-ne(@($Saved.service.Dependencies)-join'|')){throw 'Rollback refused because dependencies drifted.'};if((@($Current.DependentServices)-join'|')-ne(@($Saved.service.DependentServices)-join'|')){throw 'Rollback refused because dependent services drifted.'}}
try{$support=Get-Support;Write-StructuredLog 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{[pscustomobject]@{Support=$support;State=$(if($support.Service){Get-State}else{$null})}}
'Capture'{$state=Get-State;Assert-Safe $support $state;$saved=Save-State $state $support;Write-StructuredLog 'capture' 'pass' $saved;$saved}
'DryRun'{$state=Get-State;if((Test-Path $StatePath)-and(Test-Applied)){[void](Read-State);$r=[pscustomobject]@{WouldChange=$false;AlreadyApplied=$true}}else{Assert-Safe $support $state;$r=[pscustomobject]@{WouldChange=$true;Service=$serviceName;TargetStartMode='Manual';PreserveRunningState=$true}};Write-StructuredLog 'dry-run' 'pass' $r;$r}
'Apply'{if(Test-Path $StatePath){[void](Read-State);if(Test-Applied){Write-StructuredLog 'apply' 'pass' @{changed=$false};return [pscustomobject]@{Applied=$true;MutationCount=0}}}else{$state=Get-State;Assert-Safe $support $state;[void](Save-State $state $support)};if($PSCmdlet.ShouldProcess($serviceName,'Set startup type to Manual')){$o=& sc.exe config $serviceName start= demand 2>&1;if($LASTEXITCODE-ne0){throw "sc.exe config failed: $($o-join' ')"};New-ItemProperty $serviceReg -Name DelayedAutoStart -PropertyType DWord -Value 0 -Force|Out-Null};if(-not(Test-Applied)){throw 'Apply verification failed.'};Write-StructuredLog 'apply' 'pass' @{changed=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$ok=Test-Applied;$s=Get-State;Write-StructuredLog 'verify' $(if($ok){'pass'}else{'fail'}) $s;if(-not$ok){throw 'Verification failed.'};$true}
'VerifyReboot'{$ok=Test-Applied;$d=@{state=Get-State;bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime};Write-StructuredLog 'verify-reboot' $(if($ok){'pass'}else{'fail'}) $d;if(-not$ok){throw 'Reboot persistence verification failed.'};$true}
'Rollback'{$saved=Read-State;$current=Get-State;Assert-Identity $saved $current;if(-not($current.StartMode-eq'Manual'-and$current.DelayedAutoStart-eq0)){throw 'Rollback refused because applied configuration drifted.'};if($PSCmdlet.ShouldProcess($serviceName,'Restore exact startup and running state')){$target=if($saved.service.StartMode-eq'Auto'){'auto'}else{'demand'};$o=& sc.exe config $serviceName start= $target 2>&1;if($LASTEXITCODE-ne0){throw "sc.exe rollback failed: $($o-join' ')"};New-ItemProperty $serviceReg -Name DelayedAutoStart -PropertyType DWord -Value ([int]$saved.service.DelayedAutoStart) -Force|Out-Null;$svc=Get-Service $serviceName;if($saved.service.State-eq'Running'-and$svc.Status-ne'Running'){Start-Service $serviceName};if($saved.service.State-ne'Running'-and$svc.Status-eq'Running'){Stop-Service $serviceName}};$after=Get-State;$ok=($after.StartMode-eq$saved.service.StartMode-and$after.DelayedAutoStart-eq[int]$saved.service.DelayedAutoStart-and$after.State-eq$saved.service.State);Write-StructuredLog 'rollback' $(if($ok){'pass'}else{'fail'}) @{state=$after};if(-not$ok){throw 'Rollback verification failed.'};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-StructuredLog 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
