[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-120-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-120.jsonl",
 [string]$SecurityFloorPath="$env:ProgramData\Lacksan\EXP-120-security-floor.json"
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$Experiment='EXP-120'
function Log($e,$r,$d){$p=Split-Path $LogPath -Parent;if($p-and!(Test-Path $p)){New-Item -ItemType Directory $p -Force|Out-Null};[ordered]@{schemaVersion=2;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;action=$Action;event=$e;result=$r;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$d}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 24)-eq($b|ConvertTo-Json -Compress -Depth 24)}
function ExeFrom($p){$x=[Environment]::ExpandEnvironmentVariables(([string]$p).Trim());if($x.StartsWith('"')){$i=$x.IndexOf('"',1);if($i-gt1){return$x.Substring(1,$i-1)}}elseif($x-match'^([^ ]+\.exe)(?:\s|$)'){return$matches[1]};$null}
function Reg($n,$v){$p="HKLM:\SYSTEM\CurrentControlSet\Services\$n";if(!(Test-Path$p)){return[pscustomobject]@{Exists=$false;Kind=$null;Data=$null}};$k=Get-Item$p;if($k.GetValueNames()-notcontains$v){return[pscustomobject]@{Exists=$false;Kind=$null;Data=$null}};[pscustomobject]@{Exists=$true;Kind=$k.GetValueKind($v).ToString();Data=$k.GetValue($v,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=$ccm}}
function Protected{$svc=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|ForEach-Object{Get-CimInstance Win32_Service -Filter"Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName;$dev=@(Get-PnpDevice -ErrorAction SilentlyContinue|Where-Object{$_.Class-match'(?i)keyboard|hidclass|system'-and($_.FriendlyName-match'(?i)HP|hotkey|keyboard|HID|ACPI')}|Sort-Object InstanceId|Select-Object InstanceId,Status,Class,FriendlyName);[pscustomobject]@{Services=@($svc);HotkeyDevices=$dev}}
function SecurityFloor($model){if(!(Test-Path -LiteralPath $SecurityFloorPath)){return$null};$x=Get-Content -LiteralPath $SecurityFloorPath -Raw|ConvertFrom-Json;if($x.schemaVersion-ne1-or$x.bulletin-ne'HPSBHF04102 Rev. 2'-or$x.model-ne$model-or!$x.minimumVersion-or!$x.sourceUrl){return$null};if([string]$x.sourceUrl-notmatch'^https://support\.hp\.com/.+hpsbhf04102'){return$null};$x}
function Products{@(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*' -ErrorAction SilentlyContinue|Where-Object{$_.DisplayName-match'(?i)^HP Hotkey Support$'-and$_.Publisher-match'(?i)HP Inc|Hewlett-Packard'}|Select-Object DisplayName,DisplayVersion,Publisher,InstallLocation,PSChildName)}
function Candidate{$rows=@(Get-CimInstance Win32_Service -Filter"Name='HotKeyServiceUWP'");if($rows.Count-ne1){return$null};$w=$rows[0];if($w.DisplayName-notmatch'(?i)HP Hotkey UWP Service'){return$null};$exe=ExeFrom$w.PathName;if(!$exe-or!(Test-Path -LiteralPath$exe -PathType Leaf)-or[IO.Path]::GetFileName($exe)-ne'HotKeyServiceUWP.exe'){return$null};$sig=Get-AuthenticodeSignature -LiteralPath$exe;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};if($sig.Status-ne'Valid'-or$pub-notmatch'(?i)HP Inc|Hewlett-Packard'){return$null};$g=Get-Service$w.Name;$p=@(Products);if($p.Count-ne1){return$null};[pscustomobject]@{Name=$w.Name;DisplayName=$w.DisplayName;State=$w.State;StartMode=$w.StartMode;StartName=$w.StartName;PathName=$w.PathName;ServiceType=$w.ServiceType;Dependencies=@($g.ServicesDependedOn|ForEach-Object Name|Sort-Object);Dependents=@($g.DependentServices|ForEach-Object Name|Sort-Object);RegistryStart=Reg$w.Name'Start';DelayedAutoStart=Reg$w.Name'DelayedAutoStart';RecoveryText=((&sc.exe qfailure $w.Name 2>$null)-join"`n");TriggerText=((&sc.exe qtriggerinfo $w.Name 2>$null)-join"`n");Executable=[pscustomobject]@{Path=$exe;Version=(Get-Item$exe).VersionInfo.FileVersion;Sha256=(Get-FileHash$exe -Algorithm SHA256).Hash;Publisher=$pub;Thumbprint=$sig.SignerCertificate.Thumbprint};Product=$p[0]}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Management;$s=Candidate;$f=SecurityFloor$pc.Model;$r=@();if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!(Elevated)){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};if(!$s){$r+='exact signed HotKeyServiceUWP and HP Hotkey Support identity required'}else{if($s.ServiceType-match'(?i)driver'){$r+='driver-backed service refused'};if($s.Dependencies.Count-or$s.Dependents.Count){$r+='dependency-sensitive service refused'};if($s.StartMode-notin@('Auto','Automatic')-or($s.DelayedAutoStart.Exists-and[int]$s.DelayedAutoStart.Data-ne0)){$r+='Automatic non-delayed baseline required'};if(!$f){$r+='model-bound HPSBHF04102 security floor evidence required'}else{try{if([version]$s.Product.DisplayVersion-lt[version]$f.minimumVersion){$r+='HP Hotkey Support version below model security floor'}}catch{$r+='security version comparison failed'}}};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;BIOS=(Get-CimInstance Win32_BIOS|Select-Object SMBIOSBIOSVersion,ReleaseDate);Elevated=Elevated;Management=$m;SecurityFloor=$f;Service=$s;Protected=Protected;EvidenceStatus='needs-evidence'}}
function Save($x){if(Test-Path$StatePath){throw'State overwrite refused.'};$d=Split-Path$StatePath -Parent;if($d-and!(Test-Path$d)){New-Item -ItemType Directory$d -Force|Out-Null};$o=[ordered]@{schemaVersion=2;experiment=$Experiment;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');support=$x;protected=$x.Protected;evidenceStatus='needs-evidence'};$o|ConvertTo-Json -Depth24|Set-Content -LiteralPath$StatePath -Encoding UTF8;$o}
function Load{if(!(Test-Path$StatePath)){throw'Captured state required.'};$s=Get-Content$StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne2-or$s.experiment-ne$Experiment-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne[Security.Principal.WindowsIdentity]::GetCurrent().User.Value){throw'State identity mismatch.'};$s}
function Drift($st){$c=Candidate;$o=$st.support.Service;if(!$c-or$c.Name-ne$o.Name-or$c.PathName-ne$o.PathName-or$c.Executable.Sha256-ne$o.Executable.Sha256-or$c.Executable.Thumbprint-ne$o.Executable.Thumbprint-or$c.Product.DisplayVersion-ne$o.Product.DisplayVersion){throw'Service package or executable identity drift detected.'};if((Management).Managed){throw'Management drift detected.'};if(!(Same$c.Dependencies$o.Dependencies)-or!(Same$c.Dependents$o.Dependents)-or$c.RecoveryText-ne$o.RecoveryText-or$c.TriggerText-ne$o.TriggerText){throw'Service dependency trigger or recovery drift detected.'};if(!(Same(Protected)$st.protected)){throw'Protected security update remote-access or device state drift detected.'};$f=SecurityFloor$st.support.Model;if(!$f-or$f.minimumVersion-ne$st.support.SecurityFloor.minimumVersion){throw'Security-floor evidence drift detected.'};$c}
function Delayed($s){$s.StartMode-in@('Auto','Automatic')-and$s.DelayedAutoStart.Exists-and[int]$s.DelayedAutoStart.Data-eq1}
try{$sup=Support;Log'support-detection'$(if($sup.Supported){'pass'}else{'refused'})$sup;switch($Action){
'Check'{$sup}
'Capture'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};Save$sup}
'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};$x=[pscustomobject]@{WouldChange=$true;MutationCount=1;Service=$sup.Service.Name;From='Automatic';To='Automatic (Delayed Start)';PreserveRunningState=$true;RebootPersistenceRequired=$true;Rollback='restore exact captured startup mode, DelayedAutoStart value/type/existence, and running state';EvidenceStatus='needs-evidence'};Log'dry-run''pass'$x;$x}
'Apply'{$st=Load;$c=Drift$st;if(Delayed$c){Log'apply''idempotent'@{mutationCount=0};return$c};if($c.StartMode-ne$st.support.Service.StartMode-or!(Same$c.DelayedAutoStart$st.support.Service.DelayedAutoStart)){throw'Configuration drift detected.'};$running=$c.State;if($WhatIfPreference){Log'apply''whatif'@{mutationCount=0};return};if($PSCmdlet.ShouldProcess($c.Name,'Set Automatic Delayed Start while preserving running state')){Set-Service -Name$c.Name -StartupType Automatic;$key="HKLM:\SYSTEM\CurrentControlSet\Services\$($c.Name)";New-ItemProperty -LiteralPath$key -Name DelayedAutoStart -PropertyType DWord -Value1 -Force|Out-Null}else{return};$a=Candidate;if(!(Delayed$a)-or$a.State-ne$running){throw'Apply verification failed.'};Log'apply''pass'@{mutationCount=1;before=$c;after=$a};$a}
'Verify'{$st=Load;$c=Drift$st;if(!(Delayed$c)){throw'Delayed-start treatment absent.'};Log'verify''pass'$c;$c}
'VerifyReboot'{$st=Load;$c=Drift$st;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$st.capturedBootTime){throw'Later boot required.'};if(!(Delayed$c)){throw'Treatment failed reboot persistence.'};Log'verify-reboot''pass'@{boot=$b.ToString('o');service=$c;evidenceStatus='needs-evidence'};$c}
'Rollback'{$st=Load;$c=Drift$st;$o=$st.support.Service;if(!(Delayed$c)){if($c.StartMode-eq$o.StartMode-and$c.State-eq$o.State-and(Same$c.DelayedAutoStart$o.DelayedAutoStart)){Log'rollback''idempotent'@{mutationCount=0};return$c};throw'Rollback collision detected.'};if($WhatIfPreference){Log'rollback''whatif'@{mutationCount=0};return};if($PSCmdlet.ShouldProcess($c.Name,'Restore exact captured HP Hotkey UWP service state')){Set-Service -Name$c.Name -StartupType Automatic;$key="HKLM:\SYSTEM\CurrentControlSet\Services\$($c.Name)";if($o.DelayedAutoStart.Exists){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$o.DelayedAutoStart.Kind,$true);(Get-Item$key).SetValue('DelayedAutoStart',$o.DelayedAutoStart.Data,$kind)}else{Remove-ItemProperty -LiteralPath$key -Name DelayedAutoStart -ErrorAction SilentlyContinue};$g=Get-Service$c.Name;if($o.State-eq'Running'-and$g.Status-ne'Running'){Start-Service$c.Name};if($o.State-eq'Stopped'-and$g.Status-ne'Stopped'){Stop-Service$c.Name}}else{return};$a=Candidate;if($a.StartMode-ne$o.StartMode-or$a.State-ne$o.State-or!(Same$a.DelayedAutoStart$o.DelayedAutoStart)){throw'Exact rollback verification failed.'};Log'rollback''pass'@{mutationCount=1;restoredExactOriginal=$true};$a}
}}catch{Log'failure''fail'@{stage=$Action;message=$_.Exception.Message;evidenceStatus='needs-evidence'};throw}
