[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-087-hpssf-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-087-hpssf-events.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-087'
$Provider='hp-support-solutions-framework-manual'
$ProtectedServices=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')

function Write-Event([string]$Event,[string]$Result,$Before=$null,$After=$null,[string]$Reason=$null,[string]$Failure=$null){
 if([string]::IsNullOrWhiteSpace($LogPath)){return};$parent=Split-Path -Parent $LogPath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null}
 [ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;action=$Action;event=$Event;result=$Result;before=$Before;after=$After;refusalReason=$Reason;failureDetail=$Failure;evidenceStatus='needs-evidence'}|ConvertTo-Json -Compress -Depth 30|Add-Content -LiteralPath $LogPath -Encoding UTF8
}
function Get-Hash([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','')}finally{$sha.Dispose()}}
function Test-Same($A,$B){($A|ConvertTo-Json -Compress -Depth 30)-eq($B|ConvertTo-Json -Compress -Depth 30)}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$cs=Get-CimInstance Win32_ComputerSystem;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$cs.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$cs.PartOfDomain;ConfigMgr=$ccm;EnrollmentCount=$en;OmadmCount=$om}}
function Get-Products{
 $rows=@();foreach($root in @('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*')){foreach($p in @(Get-ItemProperty $root -ErrorAction SilentlyContinue|Where-Object{$_.DisplayName-match'(?i)^HP Support Solutions Framework'})){$rows+=[pscustomobject]@{DisplayName=[string]$p.DisplayName;DisplayVersion=[string]$p.DisplayVersion;Publisher=[string]$p.Publisher;InstallLocation=[string]$p.InstallLocation;UninstallKey=[string]$p.PSPath}}};@($rows)
}
function Resolve-Exe([string]$PathName){if([string]::IsNullOrWhiteSpace($PathName)){return $null};$m=[regex]::Match([Environment]::ExpandEnvironmentVariables($PathName),'^\s*(?:"(?<p>[^"]+\.exe)"|(?<p>[^\s]+\.exe))');if(!$m.Success){return $null};try{[IO.Path]::GetFullPath($m.Groups['p'].Value)}catch{$null}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item $Path;$sig=Get-AuthenticodeSignature $Path;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductVersion=$f.VersionInfo.ProductVersion;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};HPSigned=($sig.Status-eq'Valid'-and$pub-match'(?i)HP Inc|Hewlett-Packard')}}
function Get-Delayed([string]$Name){$p="HKLM:\SYSTEM\CurrentControlSet\Services\$Name";$v=Get-ItemProperty $p -Name DelayedAutoStart -ErrorAction SilentlyContinue;[pscustomobject]@{Exists=($null-ne$v);Value=if($null-ne$v){[int]$v.DelayedAutoStart}else{$null}}}
function Get-ServiceState($Service){$svc=Get-CimInstance Win32_Service -Filter "Name='$($Service.Name)'";$reg=Get-Item "HKLM:\SYSTEM\CurrentControlSet\Services\$($Service.Name)";$deps=@((Get-Service $Service.Name).ServicesDependedOn|Select-Object -ExpandProperty Name|Sort-Object);$dependents=@((Get-Service $Service.Name).DependentServices|Select-Object -ExpandProperty Name|Sort-Object);$qfailure=(& sc.exe qfailure $Service.Name 2>&1|Out-String).Trim();$qtrigger=(& sc.exe qtriggerinfo $Service.Name 2>&1|Out-String).Trim();[pscustomobject]@{Name=$svc.Name;DisplayName=$svc.DisplayName;StartMode=$svc.StartMode;State=$svc.State;StartName=$svc.StartName;PathName=$svc.PathName;DelayedAutoStart=Get-Delayed $svc.Name;Dependencies=$deps;Dependents=$dependents;ServiceSddl=((& sc.exe sdshow $svc.Name 2>&1|Out-String).Trim());Recovery=$qfailure;Triggers=$qtrigger;RegistryOwner=(Get-Acl $reg.PSPath).Owner}}
function Get-Listeners([int]$Pid){if($Pid-le0){return @()};@(Get-NetTCPConnection -OwningProcess $Pid -State Listen -ErrorAction SilentlyContinue|Sort-Object LocalAddress,LocalPort|Select-Object LocalAddress,LocalPort,RemoteAddress,RemotePort)}
function Get-Tasks([string]$InstallPath){if([string]::IsNullOrWhiteSpace($InstallPath)){return @()};@(Get-ScheduledTask -ErrorAction SilentlyContinue|Where-Object{($_.Actions.Execute-join' ') -like "$InstallPath*"}|Sort-Object TaskPath,TaskName|Select-Object TaskPath,TaskName,State,@{n='Execute';e={$_.Actions.Execute-join';'}},@{n='Arguments';e={$_.Actions.Arguments-join';'}})}
function Get-ProtectedConfiguration{@($ProtectedServices|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,StartMode,PathName)}
function Get-Candidate{
 $products=@(Get-Products);if($products.Count-ne1){return [pscustomobject]@{Products=$products;Candidates=@()}}
 $install=$products[0].InstallLocation;$services=@();foreach($s in @(Get-CimInstance Win32_Service)){ $exe=Resolve-Exe $s.PathName;if(!$exe){continue};$id=Get-FileIdentity $exe;if(!$id-or!$id.HPSigned){continue};$owned=if($install){$exe.StartsWith($install,[StringComparison]::OrdinalIgnoreCase)}else{($s.DisplayName-match'(?i)HP Support Solutions Framework' -and $id.CompanyName-match'(?i)HP|Hewlett-Packard')};if($owned){$services+=[pscustomobject]@{Service=$s;Executable=$id}} };[pscustomobject]@{Products=$products;Candidates=$services}
}
function Get-Support{
 $os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$mgmt=Get-ManagementState;$c=Get-Candidate;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required.'};if($cs.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required.'};if(!(Test-Elevated)){$reasons+='Elevation required.'};if($mgmt.Managed){$reasons+='Enterprise management ownership detected.'};if($c.Products.Count-ne1){$reasons+='Exactly one HP Support Solutions Framework product required.'};if($c.Candidates.Count-ne1){$reasons+='Exactly one signed product-owned Windows service required.'}
 $state=$null;$listeners=@();$tasks=@();if($c.Candidates.Count-eq1){$state=Get-ServiceState $c.Candidates[0].Service;if($state.StartMode-eq'Disabled'){$reasons+='Already-disabled service refused.'};if($state.Dependents.Count-gt0){$reasons+='Dependent services make this candidate dependency-sensitive.'};$pid=[int](Get-CimInstance Win32_Service -Filter "Name='$($state.Name)'" ).ProcessId;$listeners=Get-Listeners $pid;$tasks=Get-Tasks $c.Products[0].InstallLocation}
 [pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;Elevated=(Test-Elevated);Management=$mgmt;Product=if($c.Products.Count-eq1){$c.Products[0]}else{$null};Candidate=if($c.Candidates.Count-eq1){$c.Candidates[0]}else{$null};ServiceState=$state;Listeners=$listeners;AssociatedTasks=$tasks;DemandStartProcedure='Launch the installed HP Support Solutions Framework product-detection or diagnostic workflow; if it does not request service startup, start the captured service explicitly with Start-Service for verification.';EvidenceStatus='needs-evidence'}
}
function Save-State($Support){if(!$Support.Supported){throw($Support.Reasons-join' ')};if(Test-Path $StatePath){throw 'State overwrite refused.'};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path $parent)){New-Item -ItemType Directory $parent -Force|Out-Null};$protected=Get-ProtectedConfiguration;$state=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootUtc=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;product=$Support.Product;candidate=$Support.Candidate;original=$Support.ServiceState;listeners=$Support.Listeners;associatedTasks=$Support.AssociatedTasks;management=$Support.Management;protectedHash=Get-Hash($protected|ConvertTo-Json -Compress -Depth 20);demandStartProcedure=$Support.DemandStartProcedure;evidenceStatus='needs-evidence'};$state|ConvertTo-Json -Depth 30|Set-Content $StatePath -Encoding UTF8;[pscustomobject]$state}
function Read-State{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Assert-DriftFree($State){if((Get-ManagementState).Managed){throw 'Management ownership drift detected.'};$svc=Get-CimInstance Win32_Service -Filter "Name='$($State.original.Name)'";if(!$svc){throw 'Service identity drift detected.'};$id=Get-FileIdentity (Resolve-Exe $svc.PathName);if(!$id-or!$id.HPSigned-or$id.Sha256-ne[string]$State.candidate.Executable.Sha256-or$id.Thumbprint-ne[string]$State.candidate.Executable.Thumbprint-or$id.FileVersion-ne[string]$State.candidate.Executable.FileVersion){throw 'Executable identity drift detected.'};$now=Get-ServiceState $svc;if(!(Test-Same $now.Dependencies $State.original.Dependencies)-or!(Test-Same $now.Dependents $State.original.Dependents)-or$now.PathName-ne[string]$State.original.PathName-or$now.StartName-ne[string]$State.original.StartName-or$now.Recovery-ne[string]$State.original.Recovery-or$now.Triggers-ne[string]$State.original.Triggers){throw 'Service configuration drift detected.'};if((Get-Hash((Get-ProtectedConfiguration)|ConvertTo-Json -Compress -Depth 20))-ne[string]$State.protectedHash){throw 'Protected configuration drift detected.'};$now}
function Set-Manual([string]$Name){$out=& sc.exe config $Name start= demand 2>&1;if($LASTEXITCODE-ne0){throw("sc.exe config failed: "+($out-join' '))};$p="HKLM:\SYSTEM\CurrentControlSet\Services\$Name";if((Get-ItemProperty $p -Name DelayedAutoStart -ErrorAction SilentlyContinue)){Remove-ItemProperty $p -Name DelayedAutoStart -ErrorAction Stop}}
function Restore-Startup($State){$name=[string]$State.original.Name;$start=if($State.original.StartMode-eq'Auto'){'auto'}elseif($State.original.StartMode-eq'Manual'){'demand'}else{throw 'Unsupported original startup mode for rollback.'};$out=& sc.exe config $name start= $start 2>&1;if($LASTEXITCODE-ne0){throw("startup rollback failed: "+($out-join' '))};$p="HKLM:\SYSTEM\CurrentControlSet\Services\$name";if($State.original.DelayedAutoStart.Exists){New-ItemProperty $p -Name DelayedAutoStart -PropertyType DWord -Value ([int]$State.original.DelayedAutoStart.Value) -Force|Out-Null}else{Remove-ItemProperty $p -Name DelayedAutoStart -ErrorAction SilentlyContinue};$svc=Get-Service $name;if([string]$State.original.State-eq'Running'-and$svc.Status-ne'Running'){Start-Service $name}elseif([string]$State.original.State-ne'Running'-and$svc.Status-eq'Running'){Stop-Service $name -Force:$false}}
function Test-Treatment($State){$s=Get-ServiceState (Get-CimInstance Win32_Service -Filter "Name='$($State.original.Name)'" );$s.StartMode-eq'Manual'-and!$s.DelayedAutoStart.Exists}
try{$support=Get-Support;Write-Event 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $null $support ($(if($support.Supported){$null}else{$support.Reasons-join' '}));switch($Action){
 'Check'{$support}
 'Capture'{$s=Save-State $support;Write-Event 'capture' 'pass' $null $s;$s}
 'DryRun'{if(!$support.Supported){throw($support.Reasons-join' ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;ServiceName=$support.ServiceState.Name;TargetStartMode='Manual';PreserveCurrentRunningState=$true;RebootPersistenceRequired=$true;DemandStartProcedure=$support.DemandStartProcedure;Rollback='Restore exact captured startup mode, delayed-auto-start value presence/data, and original running state after drift checks.';EvidenceStatus='needs-evidence'};Write-Event 'dry-run' 'pass' $support.ServiceState $r;$r}
 'Apply'{$s=if(Test-Path $StatePath){Read-State}else{Save-State $support};$before=Assert-DriftFree $s;if(Test-Treatment $s){Write-Event 'apply' 'idempotent' $before $before;return [pscustomobject]@{Applied=$true;MutationCount=0}};$wasRunning=([string]$before.State-eq'Running');if($WhatIfPreference){Write-Event 'apply' 'whatif' $before $before;return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($before.Name,'Change HP Support Solutions Framework startup mode to Manual while preserving running state')){Set-Manual $before.Name}else{return};$after=Get-ServiceState (Get-CimInstance Win32_Service -Filter "Name='$($before.Name)'" );if(!(Test-Treatment $s)-or$wasRunning-ne([string]$after.State-eq'Running')){throw 'Application verification failed.'};Write-Event 'apply' 'pass' $before $after;$after}
 'Verify'{$s=Read-State;$before=Assert-DriftFree $s;if(!(Test-Treatment $s)){throw 'Treatment verification failed.'};$r=[pscustomobject]@{Verified=$true;Service=$before;HPProductDetection='needs-evidence';HPDiagnostics='needs-evidence';LocalhostWorkflow='needs-evidence';ProtectedApplicationReadiness='needs-evidence'};Write-Event 'verify' 'pass' $before $r;$r}
 'VerifyReboot'{$s=Read-State;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootUtc){throw 'A later boot is required.'};$before=Assert-DriftFree $s;if(!(Test-Treatment $s)){throw 'Reboot persistence failed.'};$r=[pscustomobject]@{VerifiedReboot=$true;BootUtc=$boot.ToString('o');Service=$before;DemandStart='needs-evidence';HPWorkflow='needs-evidence';ProtectedApplicationReadiness='needs-evidence'};Write-Event 'verify-reboot' 'pass' $before $r;$r}
 'Rollback'{$s=Read-State;$before=Assert-DriftFree $s;if($before.StartMode-eq[string]$s.original.StartMode-and(Test-Same $before.DelayedAutoStart $s.original.DelayedAutoStart)-and$before.State-eq[string]$s.original.State){Write-Event 'rollback' 'idempotent' $before $before;return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if(!(Test-Treatment $s)){throw 'Rollback collision detected; treatment state changed.'};if($WhatIfPreference){Write-Event 'rollback' 'whatif' $before $before;return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($before.Name,'Restore exact EXP-087 startup and running state')){Restore-Startup $s}else{return};$after=Get-ServiceState (Get-CimInstance Win32_Service -Filter "Name='$($before.Name)'" );if($after.StartMode-ne[string]$s.original.StartMode-or!(Test-Same $after.DelayedAutoStart $s.original.DelayedAutoStart)-or$after.State-ne[string]$s.original.State){throw 'Exact rollback verification failed.'};Write-Event 'rollback' 'pass' $before $after;$after}
}}catch{Write-Event 'failure' 'failure' $null $null $null $_.Exception.Message;throw}
