[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$expectedExecutable='hptpsmarthealth.exe'
$protectedPattern='(?i)defender|firewall|bitlocker|credential|vbs|security|update|recovery|accessibility|omnissa|vmware|windows app|remote desktop|termservice|tailscale|driver|network|vpn|ndis|tcpip|dhcp|dns|intune|sccm|configmgr|mdm'

function Write-StructuredLog([string]$Event,[string]$Result,[object]$Data){if($LogPath){$parent=Split-Path -Parent $LogPath;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$r=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-075';provider='hp-techpulse-smarthealth-service';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($r|ConvertTo-Json -Compress -Depth 14) -Encoding UTF8}}
function Get-ExecutablePath([string]$CommandLine){if([string]::IsNullOrWhiteSpace($CommandLine)){return $null};if($CommandLine -match '^\s*"([^"]+)"'){return $matches[1]};(($CommandLine -split '\s+',2)[0]).Trim('"')}
function Get-ManagementSignals([string]$ServiceName){$paths=@("HKLM:\SOFTWARE\Policies\Microsoft\Windows\System\Services\$ServiceName","HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device\SystemServices\$ServiceName",'HKLM:\SOFTWARE\Microsoft\Enrollments','HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts','HKLM:\SOFTWARE\Microsoft\CCM','HKLM:\SOFTWARE\HP\HP TechPulse\Enrollment','HKLM:\SOFTWARE\HP\HP TechPulse\Tenant','HKLM:\SOFTWARE\HP\HP Insights\Enrollment','HKLM:\SOFTWARE\HP\HP Insights\Tenant','HKLM:\SOFTWARE\WOW6432Node\HP\HP TechPulse\Enrollment','HKLM:\SOFTWARE\WOW6432Node\HP\HP Insights\Enrollment');$present=@($paths|Where-Object {Test-Path -LiteralPath $_});$mgmtServices=@(Get-CimInstance Win32_Service -ErrorAction SilentlyContinue|Where-Object {$_.Name -match '(?i)Intune|CCMExec|ConfigMgr|MDM' -and $_.State -eq 'Running'}|Select-Object Name,State);[pscustomobject]@{Paths=$present;ManagementServices=$mgmtServices;Owned=($present.Count -gt 0 -or $mgmtServices.Count -gt 0)}}
function Get-HPActivity{$processes=@(Get-Process -ErrorAction SilentlyContinue|Where-Object {$_.ProcessName -match '(?i)hpinsights|touchpoint|techpulse' -and $_.ProcessName -notmatch '(?i)^hptpsmarthealth$'}|Select-Object ProcessName,Id);[pscustomobject]@{Processes=$processes;Active=($processes.Count -gt 0)}}
function Get-PowerThermal{$battery=Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue|Select-Object -First 1 BatteryStatus,EstimatedChargeRemaining;$thermal=@(Get-CimInstance -Namespace root/wmi MSAcpi_ThermalZoneTemperature -ErrorAction SilentlyContinue|Select-Object CurrentTemperature,InstanceName);[pscustomobject]@{Battery=$battery;Thermal=$thermal}}
function Get-Candidates{@(Get-CimInstance Win32_Service -ErrorAction SilentlyContinue|Where-Object {$p=Get-ExecutablePath $_.PathName;$p -and [IO.Path]::GetFileName($p) -ieq $expectedExecutable -and $p -match '(?i)\\Program Files\\HP\\HP TechPulse SmartHealth\\hptpsmarthealth\.exe$'})}
function Get-Support{
    $os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$bios=Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue
    $admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    $services=Get-Candidates;$svc=if($services.Count -eq 1){$services[0]}else{$null};$exe=if($svc){Get-ExecutablePath $svc.PathName}else{$null};$sig=if($exe-and(Test-Path -LiteralPath $exe)){Get-AuthenticodeSignature -LiteralPath $exe}else{$null}
    $deps=if($svc){@($svc.Dependencies)}else{@()};$dependents=if($svc){@(Get-Service $svc.Name -ErrorAction SilentlyContinue|ForEach-Object {$_.DependentServices.Name})}else{@()};$management=if($svc){Get-ManagementSignals $svc.Name}else{[pscustomobject]@{Paths=@();ManagementServices=@();Owned=$true}};$activity=Get-HPActivity
    $publisher=($sig-and$sig.Status-eq'Valid'-and$sig.SignerCertificate.Subject-match'(?i)HP Inc|Hewlett-Packard');$dependencySafe=(@($deps+$dependents|Where-Object {$_ -match $protectedPattern}).Count -eq 0)
    [pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and$services.Count-eq1-and$publisher-and$dependencySafe-and@($deps).Count-eq0-and@($dependents).Count-eq0-and-not$management.Owned-and-not$activity.Active);Elevated=$admin;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;BIOS=if($bios){$bios.SMBIOSBIOSVersion}else{$null};ServiceCount=$services.Count;Service=$svc;Executable=$exe;PublisherMatched=$publisher;SignatureStatus=if($sig){$sig.Status}else{$null};Signer=if($sig-and$sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};Dependencies=$deps;DependentServices=$dependents;DependencySafe=$dependencySafe;Management=$management;HPActivity=$activity;PowerThermal=Get-PowerThermal}
}
function Get-State{
    $services=Get-Candidates;if($services.Count-ne1){throw 'Exactly one HP TechPulse SmartHealth service is required.'};$svc=$services[0];$serviceReg="HKLM:\SYSTEM\CurrentControlSet\Services\$($svc.Name)";$delayed=0;if(Test-Path -LiteralPath $serviceReg){$v=Get-ItemProperty -LiteralPath $serviceReg -Name DelayedAutoStart -ErrorAction SilentlyContinue;if($null-ne$v){$delayed=[int]$v.DelayedAutoStart}}
    $exe=Get-ExecutablePath $svc.PathName;$sig=Get-AuthenticodeSignature -LiteralPath $exe
    [pscustomobject]@{Name=$svc.Name;DisplayName=$svc.DisplayName;PathName=$svc.PathName;ExecutablePath=$exe;StartMode=$svc.StartMode;State=$svc.State;DelayedAutoStart=$delayed;StartName=$svc.StartName;Dependencies=@($svc.Dependencies);DependentServices=@(Get-Service $svc.Name|ForEach-Object {$_.DependentServices.Name});ExecutableVersion=(Get-Item -LiteralPath $exe).VersionInfo.FileVersion;ExecutableHash=(Get-FileHash -LiteralPath $exe -Algorithm SHA256).Hash;SignatureStatus=$sig.Status;Signer=$sig.SignerCertificate.Subject;Management=Get-ManagementSignals $svc.Name;HPActivity=Get-HPActivity;PowerThermal=Get-PowerThermal}
}
function Save-State($State,$Support){if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};$saved=[ordered]@{schemaVersion=1;experiment='EXP-075';provider='hp-techpulse-smarthealth-service';machine=$env:COMPUTERNAME;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');windowsBuild=$Support.Build;manufacturer=$Support.Manufacturer;model=$Support.Model;bios=$Support.BIOS;service=$State};$parent=Split-Path -Parent $StatePath;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$saved|ConvertTo-Json -Depth 14|Set-Content -LiteralPath $StatePath -Encoding UTF8;$saved}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or-not(Test-Path -LiteralPath $StatePath)){throw "State file missing: $StatePath"};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne'EXP-075'-or$s.provider-ne'hp-techpulse-smarthealth-service'-or$s.machine-ne$env:COMPUTERNAME){throw 'State identity validation failed.'};$s}
function Assert-Safe($Support,$State){if(-not$Support.Elevated){throw 'Elevation is required.'};if(-not$Support.Supported){throw 'Supported unmanaged HP Windows 11 SmartHealth identity with no active HP Insights or management ownership is required.'};if($State.StartMode-ne'Auto'){throw 'Eligible start mode must be Automatic or Automatic Delayed Start.'};if($State.Dependencies.Count-gt0-or$State.DependentServices.Count-gt0){throw 'Service dependencies require physical review.'};if($State.Management.Owned){throw 'Enterprise or HP management ownership detected.'};if($State.HPActivity.Active){throw 'Active HP Workforce Experience or TechPulse activity detected.'}}
function Test-Applied{$s=Get-State;($s.StartMode-eq'Manual'-and$s.DelayedAutoStart-eq0)}
function Assert-Identity($Saved,$Current){foreach($f in @('Name','DisplayName','PathName','ExecutablePath','StartName','ExecutableVersion','ExecutableHash','SignatureStatus','Signer')){if([string]$Current.$f-ne[string]$Saved.service.$f){throw "Rollback refused because service identity drifted: $f"}};if((@($Current.Dependencies)-join'|')-ne(@($Saved.service.Dependencies)-join'|')){throw 'Rollback refused because dependencies drifted.'};if((@($Current.DependentServices)-join'|')-ne(@($Saved.service.DependentServices)-join'|')){throw 'Rollback refused because dependent services drifted.'};if($Current.Management.Owned){throw 'Rollback refused because management ownership is present.'}}
try{$support=Get-Support;Write-StructuredLog 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{[pscustomobject]@{Support=$support;State=$(if($support.Service){Get-State}else{$null})}}
'Capture'{$state=Get-State;Assert-Safe $support $state;$saved=Save-State $state $support;Write-StructuredLog 'capture' 'pass' $saved;$saved}
'DryRun'{$state=Get-State;if((Test-Path -LiteralPath $StatePath)-and(Test-Applied)){[void](Read-State);$r=[pscustomobject]@{WouldChange=$false;AlreadyApplied=$true}}else{Assert-Safe $support $state;$r=[pscustomobject]@{WouldChange=$true;Service=$state.Name;TargetStartMode='Manual';PreserveRunningState=$true;MutationScope='service-startup-only'}};Write-StructuredLog 'dry-run' 'pass' $r;$r}
'Apply'{if(Test-Path -LiteralPath $StatePath){$saved=Read-State;if(Test-Applied){Write-StructuredLog 'apply' 'pass' @{changed=$false};return [pscustomobject]@{Applied=$true;MutationCount=0}}else{$state=Get-State;Assert-Safe $support $state;$saved=Save-State $state $support};$name=$saved.service.Name;$reg="HKLM:\SYSTEM\CurrentControlSet\Services\$name";if($PSCmdlet.ShouldProcess($name,'Set startup type to Manual while preserving current running state')){$o=& sc.exe config $name start= demand 2>&1;if($LASTEXITCODE-ne0){throw "sc.exe config failed: $($o-join' ')"};New-ItemProperty -LiteralPath $reg -Name DelayedAutoStart -PropertyType DWord -Value 0 -Force|Out-Null};if(-not(Test-Applied)){throw 'Apply verification failed.'};Write-StructuredLog 'apply' 'pass' @{changed=$true;service=$name};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$ok=Test-Applied;$s=Get-State;Write-StructuredLog 'verify' $(if($ok){'pass'}else{'fail'}) $s;if(-not$ok){throw 'Verification failed.'};$true}
'VerifyReboot'{$ok=Test-Applied;$d=@{state=Get-State;bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime};Write-StructuredLog 'verify-reboot' $(if($ok){'pass'}else{'fail'}) $d;if(-not$ok){throw 'Reboot persistence verification failed.'};$true}
'Rollback'{$saved=Read-State;$current=Get-State;Assert-Identity $saved $current;if(-not($current.StartMode-eq'Manual'-and$current.DelayedAutoStart-eq0)){throw 'Rollback refused because applied configuration drifted.'};$name=$saved.service.Name;$reg="HKLM:\SYSTEM\CurrentControlSet\Services\$name";if($PSCmdlet.ShouldProcess($name,'Restore exact startup and running state')){$target=if($saved.service.StartMode-eq'Auto'){'auto'}else{'demand'};$o=& sc.exe config $name start= $target 2>&1;if($LASTEXITCODE-ne0){throw "sc.exe rollback failed: $($o-join' ')"};New-ItemProperty -LiteralPath $reg -Name DelayedAutoStart -PropertyType DWord -Value ([int]$saved.service.DelayedAutoStart) -Force|Out-Null;$svc=Get-Service $name;if($saved.service.State-eq'Running'-and$svc.Status-ne'Running'){Start-Service $name};if($saved.service.State-ne'Running'-and$svc.Status-eq'Running'){Stop-Service $name}};$after=Get-State;$ok=($after.StartMode-eq$saved.service.StartMode-and$after.DelayedAutoStart-eq[int]$saved.service.DelayedAutoStart-and$after.State-eq$saved.service.State);Write-StructuredLog 'rollback' $(if($ok){'pass'}else{'fail'}) @{state=$after};if(-not$ok){throw 'Rollback verification failed.'};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-StructuredLog 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
