[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [Parameter(Mandatory=$true)][string]$SelectionPath,
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-153-run-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-153-run-events.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-153';$Provider='inventory-bound-run-registration'
$AllowedPaths=@('Software\Microsoft\Windows\CurrentVersion\Run','Software\Microsoft\Windows\CurrentVersion\RunOnce')
$Protected='(?i)omnissa|vmware[- ]?view|horizon|windows app|remote desktop|mstsc|msrdc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|recovery|accessib|narrator|magnify|intune|sccm|configmgr|mdm|driver|firmware|bluetooth|receiver|hid|touchpad|keyboard|mouse'
$Servicing='(?i)clicktorun|office.*update|teams.*update|edgeupdate|update(r|s|service)?|installer|setup|repair|uninstall|firmware|dfu|driver|pair(ing)?|bootstrapper'
function Write-Event([string]$Event,[string]$Result,$Data){$d=Split-Path -Parent $LogPath;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 30|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Hash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','')}finally{$s.Dispose()}}
function Same($A,$B){($A|ConvertTo-Json -Compress -Depth 30)-eq($B|ConvertTo-Json -Compress -Depth 30)}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=$ccm}}
function Get-Support{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-Management;$r=@();if($o.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($c.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!(Test-Elevated)){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=Test-Elevated;Management=$m;EvidenceStatus='needs-evidence'}}
function Get-Selection{if(!(Test-Path -LiteralPath $SelectionPath -PathType Leaf)){throw'EXP-143 selection artifact required.'};$s=Get-Content -LiteralPath $SelectionPath -Raw|ConvertFrom-Json;if($s.experiment-ne'EXP-143'-or$s.classification-ne'priority-target'-or$s.surface-notin@('RegistryRun','Run','RunOnce')-or[string]::IsNullOrWhiteSpace([string]$s.inventoryHash)-or[string]::IsNullOrWhiteSpace([string]$s.hive)-or[string]::IsNullOrWhiteSpace([string]$s.path)-or[string]::IsNullOrWhiteSpace([string]$s.valueName)-or$null-eq$s.originalState){throw'Selection must bind one EXP-143 priority-target Run/RunOnce record with inventory hash and exact original state.'};if([string]$s.hive-notin@('HKCU','HKLM')){throw'Only HKCU or HKLM selection is approved.'};if([string]$s.path-notin$AllowedPaths){throw'Only approved Run or RunOnce paths are allowed.'};if([string]$s.registryView-notin@('Registry32','Registry64')){throw'Explicit Registry32 or Registry64 view is required.'};if([string]$s.originalState.kind-notin@('String','ExpandString')){throw'Only REG_SZ and REG_EXPAND_SZ startup values are supported.'};if([string]::IsNullOrWhiteSpace([string]$s.originalState.data)){throw'Original unexpanded value data is required.'};$s}
function Open-Key($Selection,[bool]$Writable){$h=if([string]$Selection.hive-eq'HKCU'){[Microsoft.Win32.RegistryHive]::CurrentUser}else{[Microsoft.Win32.RegistryHive]::LocalMachine};$v=[Microsoft.Win32.RegistryView]::$([string]$Selection.registryView);$b=[Microsoft.Win32.RegistryKey]::OpenBaseKey($h,$v);try{$k=$b.OpenSubKey([string]$Selection.path,$Writable);if(!$k){throw'Selected Run key is missing.'};$k}finally{$b.Dispose()}}
function Get-ValueState($Selection){$k=Open-Key $Selection $false;try{$names=@($k.GetValueNames());$exists=$names-contains[string]$Selection.valueName;$acl=$k.GetAccessControl();[pscustomobject]@{KeyExists=$true;ValueExists=$exists;Kind=if($exists){$k.GetValueKind([string]$Selection.valueName).ToString()}else{$null};Data=if($exists){[string]$k.GetValue([string]$Selection.valueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}else{$null};KeySddl=$acl.GetSecurityDescriptorSddlForm([Security.AccessControl.AccessControlSections]::Access);KeyOwner=$acl.GetOwner([Security.Principal.NTAccount]).Value}}finally{$k.Dispose()}}
function Resolve-Exe([string]$Command){$e=[Environment]::ExpandEnvironmentVariables($Command).Trim();$m=[regex]::Match($e,'^\s*"(?<exe>[^"]+\.exe)"|^\s*(?<exe2>[^\s]+\.exe)');$p=if($m.Groups['exe'].Success){$m.Groups['exe'].Value}else{$m.Groups['exe2'].Value};if([string]::IsNullOrWhiteSpace($p)){return$null};try{[IO.Path]::GetFullPath($p)}catch{return$null}}
function File-Identity([string]$Path){if(!$Path-or!(Test-Path -LiteralPath $Path -PathType Leaf)){return$null};$f=Get-Item -LiteralPath $Path;$sig=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($sig.SignerCertificate){[string]$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidSignature=($sig.Status-eq'Valid'-and$null-ne$sig.SignerCertificate)}}
function Get-ProtectedConfiguration{$svc=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,StartMode,PathName;[pscustomobject]@{Services=@($svc)}}
function Get-OtherRunSnapshot($Selection){$rows=@();foreach($hive in 'HKCU','HKLM'){foreach($view in 'Registry32','Registry64'){foreach($path in $AllowedPaths){$x=[pscustomobject]@{hive=$hive;registryView=$view;path=$path};try{$k=Open-Key $x $false}catch{continue};try{foreach($n in @($k.GetValueNames()|Sort-Object)){if($hive-eq[string]$Selection.hive-and$view-eq[string]$Selection.registryView-and$path-eq[string]$Selection.path-and$n-eq[string]$Selection.valueName){continue};$rows+=[pscustomobject]@{Hive=$hive;RegistryView=$view;Path=$path;Name=$n;Kind=$k.GetValueKind($n).ToString();Data=[string]$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}}finally{$k.Dispose()}}}};@($rows)}
function Get-Candidate{$s=Get-Selection;$v=Get-ValueState $s;if(!$v.ValueExists){throw'Selected startup value is missing.'};if($v.Kind-ne[string]$s.originalState.kind-or$v.Data-ne[string]$s.originalState.data){throw'Selected startup value drifted from EXP-143 original state.'};$exe=Resolve-Exe $v.Data;$id=File-Identity $exe;if(!$id-or!$id.ValidSignature){throw'A valid signed executable-backed user application startup value is required.'};$text="$($s.hive) $($s.path) $($s.valueName) $($v.Data) $($id.Path) $($id.ProductName) $($id.CompanyName) $($id.Publisher)";if($text-match$Protected){throw'Protected startup identity refused.'};if($text-match$Servicing){throw'Servicing, updater, installer, repair, firmware, driver, or pairing startup identity refused.'};[pscustomobject]@{Selection=$s;Value=$v;Executable=$id;Identity="$($s.hive)|$($s.registryView)|$($s.path)|$($s.valueName)";EvidenceStatus='needs-evidence'}}
function Eligibility{$sup=Get-Support;$r=@($sup.Reasons);$c=$null;try{$c=Get-Candidate}catch{$r+=$_.Exception.Message};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;Platform=$sup;Candidate=$c;EvidenceStatus='needs-evidence'}}
function Save-State($e){if(!$e.Supported){throw($e.Reasons-join'; ')};if(Test-Path -LiteralPath $StatePath){throw'State overwrite refused.'};$d=Split-Path -Parent $StatePath;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$other=Get-OtherRunSnapshot $e.Candidate.Selection;$prot=Get-ProtectedConfiguration;$s=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootUtc=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');selection=$e.Candidate.Selection;candidate=$e.Candidate;originalValueHash=Hash("$($e.Candidate.Value.Kind)`n$($e.Candidate.Value.Data)");otherRunHash=Hash(($other|ConvertTo-Json -Compress -Depth 12));protectedHash=Hash(($prot|ConvertTo-Json -Compress -Depth 12));evidenceStatus='needs-evidence'};$s|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if(!(Test-Path -LiteralPath $StatePath)){throw'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw'State identity validation failed.'};$s}
function Assert-Guards($s){if(!(Test-Elevated)){throw'Elevation required.'};if((Get-Management).Managed){throw'Management ownership appeared.'};$v=Get-ValueState $s.selection;if($v.KeyOwner-ne[string]$s.candidate.Value.KeyOwner-or$v.KeySddl-ne[string]$s.candidate.Value.KeySddl){throw'Run-key ACL drift detected.'};$id=File-Identity ([string]$s.candidate.Executable.Path);if(!$id-or!$id.ValidSignature-or$id.Sha256-ne[string]$s.candidate.Executable.Sha256-or$id.Thumbprint-ne[string]$s.candidate.Executable.Thumbprint-or$id.FileVersion-ne[string]$s.candidate.Executable.FileVersion){throw'Executable identity drift detected.'};if((Hash ((Get-OtherRunSnapshot $s.selection)|ConvertTo-Json -Compress -Depth 12))-ne[string]$s.otherRunHash){throw'Unrelated Run/RunOnce registration drift detected.'};if((Hash ((Get-ProtectedConfiguration)|ConvertTo-Json -Compress -Depth 12))-ne[string]$s.protectedHash){throw'Protected configuration drift detected.'};$v}
function Test-ExactOriginal($s){$v=Get-ValueState $s.selection;$v.ValueExists-and$v.Kind-eq[string]$s.candidate.Value.Kind-and$v.Data-eq[string]$s.candidate.Value.Data}
function ConvertTo-Utc([string]$Value){([DateTimeOffset]::Parse($Value,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind)).UtcDateTime}
try{$elig=Eligibility;Write-Event 'support-detection' $(if($elig.Supported){'pass'}else{'refused'}) $elig;switch($Action){
 'Check'{$elig}
 'Capture'{$s=Save-State $elig;Write-Event 'capture' 'pass' @{identity=$s.candidate.Identity;inventoryHash=$s.selection.inventoryHash;kind=$s.candidate.Value.Kind;valueHash=$s.originalValueHash;executableHash=$s.candidate.Executable.Sha256};$s}
 'DryRun'{if(!$elig.Supported){throw($elig.Reasons-join'; ')};$c=$elig.Candidate;$x=[pscustomobject]@{WouldChange=$true;MutationCount=1;Identity=$c.Identity;Hive=$c.Selection.hive;RegistryView=$c.Selection.registryView;Path=$c.Selection.path;ValueName=$c.Selection.valueName;Kind=$c.Value.Kind;PreserveApplication=$true;PreserveServices=$true;PreserveDrivers=$true;PreserveProtectedScope=$true;RebootPersistenceRequired=$true;Rollback='restore exact captured REG_SZ or REG_EXPAND_SZ raw data after management, ACL, executable, unrelated-registration, protected-configuration, and collision checks';EvidenceStatus='needs-evidence'};Write-Event 'dry-run' 'pass' $x;$x}
 'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $elig};$v=Assert-Guards $s;if(!$v.ValueExists){Write-Event 'apply' 'idempotent' @{mutationCount=0};return[pscustomobject]@{Applied=$true;MutationCount=0}};if(!(Test-ExactOriginal $s)){throw'Captured startup value drift detected before Apply.'};if($WhatIfPreference){Write-Event 'apply' 'whatif' @{mutationCount=0};return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess([string]$s.candidate.Identity,'Delete exact EXP-143-selected Run/RunOnce value')){$k=Open-Key $s.selection $true;try{$k.DeleteValue([string]$s.selection.valueName,$true)}finally{$k.Dispose()}}else{return};if((Get-ValueState $s.selection).ValueExists){throw'Apply verification failed.'};Assert-Guards $s|Out-Null;Write-Event 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
 'Verify'{$s=Read-State;$v=Assert-Guards $s;if($v.ValueExists){throw'Immediate verification failed.'};Write-Event 'verify' 'pass' @{registrationAbsent=$true;performance='needs-evidence'};$true}
 'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le(ConvertTo-Utc ([string]$s.capturedBootUtc))){throw'A later boot is required.'};$v=Assert-Guards $s;if($v.ValueExists){throw'Reboot persistence failed.'};Write-Event 'verify-reboot' 'pass' @{bootUtc=$b.ToString('o');registrationAbsent=$true;protectedReadiness='needs-evidence'};$true}
 'Rollback'{$s=Read-State;$v=Assert-Guards $s;if($v.ValueExists){if(Test-ExactOriginal $s){Write-Event 'rollback' 'idempotent' @{mutationCount=0};return[pscustomobject]@{RolledBack=$true;MutationCount=0}};Write-Event 'rollback-collision' 'needs-evidence' @{currentKind=$v.Kind;currentHash=Hash("$($v.Kind)`n$($v.Data)")};throw'Rollback overwrite refused because a conflicting value reappeared.'};if($WhatIfPreference){Write-Event 'rollback' 'whatif' @{mutationCount=0};return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess([string]$s.candidate.Identity,'Restore exact captured Run/RunOnce value')){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.candidate.Value.Kind,$true);$k=Open-Key $s.selection $true;try{$k.SetValue([string]$s.selection.valueName,[string]$s.candidate.Value.Data,$kind)}finally{$k.Dispose()}}else{return};if(!(Test-ExactOriginal $s)){throw'Exact rollback verification failed.'};Assert-Guards $s|Out-Null;Write-Event 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true;rebootRestoreVerification='needs-evidence'};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Event 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message;evidenceStatus='needs-evidence'};throw}
