[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [Parameter(Mandatory=$true)][string]$SelectionPath,
 [string]$StatePath="$env:LOCALAPPDATA\Lacksan\EXP-153-state.json",
 [string]$LogPath="$env:LOCALAPPDATA\Lacksan\EXP-153.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop';$Experiment='EXP-153'
$ApprovedKeys=@(
 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce',
 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce',
 'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\RunOnce'
)
$Protected='(?i)omnissa|vmware[- ]?view|horizon|windows app|remote desktop|mstsc|msrdc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|edgeupdate|recovery|accessib|narrator|magnify|intune|sccm|configmgr|mdm|driver|firmware|bluetooth|receiver|hid'
$Servicing='(?i)clicktorun|office.*update|edgeupdate|updat(er|e)?\b|install|setup|repair|uninstall|firmware|dfu|driver|pairing'
function Log($Event,$Result,$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function HashText([string]$Text){$h=[Security.Cryptography.SHA256]::Create();try{($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$h.Dispose()}}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 24)-eq($b|ConvertTo-Json -Compress -Depth 24)}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=$ccm}}
function ProtectedState{$svc=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName;[pscustomobject]@{Services=@($svc)}}
function Selection{if(!(Test-Path -LiteralPath $SelectionPath -PathType Leaf)){throw 'EXP-143 selection artifact required.'};$s=Get-Content -LiteralPath $SelectionPath -Raw|ConvertFrom-Json;if($s.experiment-ne'EXP-143'-or$s.classification-ne'priority-target'-or$s.surface-ne'Registry'-or[string]::IsNullOrWhiteSpace([string]$s.inventoryHash)-or[string]::IsNullOrWhiteSpace([string]$s.identity)){throw 'Selection must bind one EXP-143 priority-target Registry record and inventory hash.'};if(!$s.originalState-or[string]::IsNullOrWhiteSpace([string]$s.originalState.kind)){throw 'Selection must include exact EXP-143 originalState kind and data.'};$s}
function SplitIdentity([string]$Identity){$i=$Identity.LastIndexOf('::',[StringComparison]::Ordinal);if($i-lt1-or$i-ge($Identity.Length-2)){throw 'Registry selection identity must be path::valueName.'};[pscustomobject]@{Path=$Identity.Substring(0,$i);Name=$Identity.Substring($i+2)}}
function ValueState([string]$Path,[string]$Name){if(!(Test-Path -LiteralPath $Path)){return $null};$k=Get-Item -LiteralPath $Path;if(!($k.GetValueNames()-contains$Name)){return $null};$acl=Get-Acl -LiteralPath $Path;[pscustomobject]@{Path=$Path;Name=$Name;Kind=$k.GetValueKind($Name).ToString();Data=$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);KeyOwner=$acl.Owner;KeySddl=$acl.Sddl}}
function Snapshot{$rows=@();foreach($p in $ApprovedKeys){if(!(Test-Path -LiteralPath $p)){continue};$k=Get-Item -LiteralPath $p;foreach($n in $k.GetValueNames()){$v=ValueState $p $n;$rows+=[pscustomobject]@{Path=$p;Name=$n;Kind=$v.Kind;Data=$v.Data}}};$rows=@($rows|Sort-Object Path,Name);$j=$rows|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Rows=$rows;Hash=HashText $j}}
function ResolveExe([object]$Data){$e=[Environment]::ExpandEnvironmentVariables([string]$Data).Trim();$exe=$null;if($e-match'^\s*"(?<x>[^"]+\.exe)"'){$exe=$matches.x}elseif($e-match'^\s*(?<x>\S+\.exe)'){$exe=$matches.x};if(!$exe){return $null};try{[IO.Path]::GetFullPath($exe)}catch{return $null}}
function FileIdentity([string]$Path){if(!$Path-or!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$sig=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash;Version=$f.VersionInfo.FileVersion;Product=$f.VersionInfo.ProductName;Company=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null}}}
function Candidate{$s=Selection;$id=SplitIdentity([string]$s.identity);if($ApprovedKeys-notcontains$id.Path){throw 'Selected registry path is outside the approved Run/RunOnce allowlist.'};$v=ValueState $id.Path $id.Name;if(!$v){return $null};if($v.Kind-ne[string]$s.originalState.kind-or([string]$v.Data)-ne([string]$s.originalState.data)){throw 'Live selected value differs from EXP-143 original state.'};$text="$($id.Path) $($id.Name) $($v.Data)";if($text-match$Protected){throw 'Protected startup identity refused.'};if($text-match$Servicing){throw 'Servicing, updater, installer, repair, firmware, driver, or pairing registration refused.'};$exe=ResolveExe $v.Data;if(!$exe){throw 'Selected command must resolve directly to an executable.'};$fi=FileIdentity $exe;if(!$fi-or$fi.SignatureStatus-ne'Valid'-or$fi.Publisher-notmatch'(?i)Microsoft Corporation|Logitech|Logi'){throw 'Initial EXP-153 implementation requires a valid Microsoft or Logitech publisher.'};[pscustomobject]@{Selection=$s;Value=$v;Executable=$fi}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Management;$e=Elevated;$r=@();$c=$null;if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!$e){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};try{$c=Candidate}catch{$r+=$_.Exception.Message};if(!$c){$r+='exact selected Run/RunOnce registration required'};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=$e;Management=$m;Candidate=$c;Protected=ProtectedState;EvidenceStatus='needs-evidence'}}
function Save($sup){if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$snap=Snapshot;$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$s=[ordered]@{schemaVersion=1;experiment=$Experiment;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');selection=$sup.Candidate.Selection;candidate=$sup.Candidate;registrySnapshot=$snap;protected=$sup.Protected;evidenceStatus='needs-evidence'};$s|ConvertTo-Json -Depth 24|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Load{if(!(Test-Path -LiteralPath $StatePath)){throw 'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.experiment-ne$Experiment-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity mismatch.'};$s}
function AssertGuards($s){if(!(Elevated)){throw 'Elevation required.'};if((Management).Managed){throw 'Management ownership appeared.'};$p=[string]$s.candidate.Value.Path;if(!(Test-Path -LiteralPath $p)){throw 'Registry-key drift detected.'};$acl=Get-Acl -LiteralPath $p;if($acl.Owner-ne[string]$s.candidate.Value.KeyOwner-or$acl.Sddl-ne[string]$s.candidate.Value.KeySddl){throw 'Registry-key ACL drift detected.'};$fi=FileIdentity([string]$s.candidate.Executable.Path);if(!$fi-or$fi.Sha256-ne[string]$s.candidate.Executable.Sha256-or$fi.Thumbprint-ne[string]$s.candidate.Executable.Thumbprint-or$fi.Version-ne[string]$s.candidate.Executable.Version){throw 'Executable identity drift detected.'};if(!(Same (ProtectedState) $s.protected)){throw 'Protected security, update, or remote-access state drift detected.'}}
function Removed($s){$null-eq(ValueState([string]$s.candidate.Value.Path)([string]$s.candidate.Value.Name))}
function Restored($s){$v=ValueState([string]$s.candidate.Value.Path)([string]$s.candidate.Value.Name);$v-and$v.Kind-eq[string]$s.candidate.Value.Kind-and([string]$v.Data)-eq([string]$s.candidate.Value.Data)}
function OthersSame($s){$now=Snapshot;$ep=[string]$s.candidate.Value.Path;$en=[string]$s.candidate.Value.Name;$before=@($s.registrySnapshot.Rows|Where-Object{!($_.Path-eq$ep-and$_.Name-eq$en)});$after=@($now.Rows|Where-Object{!($_.Path-eq$ep-and$_.Name-eq$en)});Same $before $after}
try{$sup=Support;Log 'support-detection' $(if($sup.Supported){'pass'}else{'refused'}) $sup;switch($Action){
 'Check'{$sup}
 'Capture'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};$s=Save $sup;Log 'capture' 'pass' @{identity=$s.selection.identity;kind=$s.candidate.Value.Kind;inventoryHash=$s.selection.inventoryHash};$s}
 'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};$x=[pscustomobject]@{WouldChange=$true;MutationCount=1;Identity=$sup.Candidate.Selection.identity;Kind=$sup.Candidate.Value.Kind;InventoryHash=$sup.Candidate.Selection.inventoryHash;PreserveApplication=$true;PreserveServicing=$true;PreserveProtectedScope=$true;RebootPersistenceRequired=$true;Rollback='restore exact captured value type and unexpanded data after collision and drift checks';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $x;$x}
 'Apply'{$s=Load;if(Removed $s){AssertGuards $s;if(!(OthersSame $s)){throw 'Unrelated Run/RunOnce drift detected.'};Log 'apply' 'idempotent' @{mutationCount=0};return};AssertGuards $s;if(!(Restored $s)-or!(OthersSame $s)){throw 'Candidate or unrelated Run/RunOnce drift detected.'};if($WhatIfPreference){Log 'apply' 'whatif' @{mutationCount=0};return};if($PSCmdlet.ShouldProcess("$($s.candidate.Value.Path)::$($s.candidate.Value.Name)",'Remove selected EXP-143 Run/RunOnce registration')){Remove-ItemProperty -LiteralPath $s.candidate.Value.Path -Name $s.candidate.Value.Name}else{return};if(!(Removed $s)-or!(OthersSame $s)){throw 'Apply verification failed.'};AssertGuards $s;Log 'apply' 'pass' @{mutationCount=1}}
 'Verify'{$s=Load;if(!(Removed $s)){throw 'Selected Run/RunOnce registration remains present.'};AssertGuards $s;if(!(OthersSame $s)){throw 'Unrelated Run/RunOnce drift detected.'};Log 'verify' 'pass' @{removed=$true};$true}
 'VerifyReboot'{$s=Load;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'Later boot required.'};if(!(Removed $s)){throw 'Treatment failed reboot persistence.'};AssertGuards $s;if(!(OthersSame $s)){throw 'Unrelated Run/RunOnce drift detected after reboot.'};Log 'verify-reboot' 'pass' @{boot=$b.ToString('o');evidenceStatus='needs-evidence'};$true}
 'Rollback'{$s=Load;AssertGuards $s;if(!(OthersSame $s)){throw 'Rollback refused on unrelated Run/RunOnce drift.'};if(!(Removed $s)){if(Restored $s){Log 'rollback' 'idempotent' @{mutationCount=0};return};throw 'Rollback conflicting-value overwrite refused.'};if($WhatIfPreference){Log 'rollback' 'whatif' @{mutationCount=0};return};if($PSCmdlet.ShouldProcess("$($s.candidate.Value.Path)::$($s.candidate.Value.Name)",'Restore exact captured Run/RunOnce registration')){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.candidate.Value.Kind,$true);(Get-Item -LiteralPath $s.candidate.Value.Path).SetValue([string]$s.candidate.Value.Name,$s.candidate.Value.Data,$kind)}else{return};if(!(Restored $s)-or!(OthersSame $s)){throw 'Exact rollback verification failed.'};AssertGuards $s;Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};$true}
}}catch{Log 'failure' 'failure' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'};throw}
