[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [Parameter(Mandatory=$true)][string]$SelectionPath,
 [string]$StatePath="$env:LOCALAPPDATA\Lacksan\EXP-156-state.json",
 [string]$LogPath="$env:LOCALAPPDATA\Lacksan\EXP-156.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-156';$Provider='inventory-bound-signin-task'
$ProtectedPattern='(?i)omnissa|vmware[- ]?view|horizon|windows app|remote desktop|mstsc|msrdc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|edgeupdate|recovery|intune|sccm|configmgr|mdm|accessib|narrator|magnify|driver|firmware|bluetooth|receiver|hid'
$ServicingPattern='(?i)clicktorun|office.*update|teams.*update|edgeupdate|update(r|s|service)?|servic(e|ing)|installer|setup|repair|uninstall|firmware|dfu|driver|pair(ing)?|bootstrapper'
function Write-Log([string]$Event,[string]$Result,[object]$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-TextHash([string]$Text){$h=[Security.Cryptography.SHA256]::Create();try{($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$h.Dispose()}}
function Get-DefinitionHash([string]$Xml){Get-TextHash ([regex]::Replace($Xml,'(?is)<Enabled>\s*(true|false)\s*</Enabled>','<Enabled>__EXPERIMENT_STATE__</Enabled>'))}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 24)-eq($b|ConvertTo-Json -Compress -Depth 24)}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=$ccm}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$r=@();if($o.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($c.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!(Test-Elevated)){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=Test-Elevated;Management=$m}}
function Get-Selection{if(!(Test-Path -LiteralPath $SelectionPath -PathType Leaf)){throw 'EXP-143 selection artifact required.'};$s=Get-Content -LiteralPath $SelectionPath -Raw|ConvertFrom-Json;if($s.experiment-ne'EXP-143'-or$s.classification-ne'priority-target'-or$s.surface-ne'ScheduledTask'-or[string]::IsNullOrWhiteSpace([string]$s.inventoryHash)-or[string]::IsNullOrWhiteSpace([string]$s.identity)-or$null-eq$s.originalState-or[string]::IsNullOrWhiteSpace([string]$s.originalState.xml)){throw 'Selection must bind one EXP-143 priority-target ScheduledTask record, inventory hash, identity, and original XML.'};$s}
function Get-FileIdentity([string]$Path){$p=[Environment]::ExpandEnvironmentVariables($Path).Trim().Trim('"');if(!(Test-Path -LiteralPath $p -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $p;$sig=Get-AuthenticodeSignature -LiteralPath $p;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidPublisher=($sig.Status-eq'Valid'-and$pub-match'(?i)Microsoft Corporation|Logitech|Logi')}}
function Get-AllLogonTasks{$rows=@();foreach($t in Get-ScheduledTask -ErrorAction SilentlyContinue){$xml=$null;try{$xml=Export-ScheduledTask -TaskName $t.TaskName -TaskPath $t.TaskPath}catch{continue};if($xml-notmatch'(?i)<LogonTrigger>'){continue};$rows+=[pscustomobject]@{Identity="$($t.TaskPath)$($t.TaskName)";TaskPath=$t.TaskPath;TaskName=$t.TaskName;Enabled=[bool]$t.Settings.Enabled;DefinitionSha256=Get-DefinitionHash $xml;XmlSha256=Get-TextHash $xml}};@($rows|Sort-Object Identity)}
function Get-UnrelatedSnapshot([string]$Identity){$rows=@(Get-AllLogonTasks|Where-Object{$_.Identity-ne$Identity});[pscustomobject]@{Rows=$rows;Hash=Get-TextHash ($rows|ConvertTo-Json -Compress -Depth 8)}}
function Get-ProtectedSnapshot{$svc=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName;$tasks=@();foreach($t in Get-ScheduledTask -ErrorAction SilentlyContinue){$text="$($t.TaskPath)$($t.TaskName) $($t.Author) "+(($t.Actions|ForEach-Object{"$($_.Execute) $($_.Arguments)"})-join' ');if($text-match$ProtectedPattern){$x=Export-ScheduledTask -TaskName $t.TaskName -TaskPath $t.TaskPath -ErrorAction SilentlyContinue;$tasks+=[pscustomobject]@{Identity="$($t.TaskPath)$($t.TaskName)";XmlSha256=if($x){Get-TextHash $x}else{$null}}}};$j=[ordered]@{Services=@($svc);Tasks=@($tasks|Sort-Object Identity)};[pscustomobject]@{Snapshot=$j;Hash=Get-TextHash ($j|ConvertTo-Json -Compress -Depth 12)}}
function Get-Candidate{$sel=Get-Selection;$matches=@(Get-ScheduledTask -ErrorAction SilentlyContinue|Where-Object{"$($_.TaskPath)$($_.TaskName)"-eq[string]$sel.identity});if($matches.Count-ne1){throw "Exactly one selected scheduled task is required; found $($matches.Count)."};$t=$matches[0];$xml=Export-ScheduledTask -TaskName $t.TaskName -TaskPath $t.TaskPath;if($xml-notmatch'(?i)<LogonTrigger>'){throw 'Selected task lacks a logon trigger.'};if((Get-TextHash ([string]$sel.originalState.xml))-ne(Get-TextHash $xml)){throw 'Selected task drifted from EXP-143 captured XML.'};$actions=@($t.Actions);if($actions.Count-ne1-or[string]::IsNullOrWhiteSpace([string]$actions[0].Execute)){throw 'Exactly one executable task action is required.'};$exe=Get-FileIdentity ([string]$actions[0].Execute);if(!$exe-or!$exe.ValidPublisher){throw 'A valid Microsoft or Logitech signed user-application executable is required.'};$text="$($t.TaskPath)$($t.TaskName) $($t.Author) $($actions[0].Execute) $($actions[0].Arguments) $($exe.ProductName) $($exe.CompanyName)";if($text-match$ProtectedPattern){throw 'Protected scheduled-task identity refused.'};if($text-match$ServicingPattern){throw 'Servicing, updater, installer, repair, firmware, driver, or pairing task refused.'};$info=Get-ScheduledTaskInfo -TaskName $t.TaskName -TaskPath $t.TaskPath;[pscustomobject]@{Selection=$sel;Identity="$($t.TaskPath)$($t.TaskName)";TaskPath=$t.TaskPath;TaskName=$t.TaskName;Enabled=[bool]$t.Settings.Enabled;State=$t.State.ToString();Xml=$xml;XmlSha256=Get-TextHash $xml;DefinitionSha256=Get-DefinitionHash $xml;TriggersXml=([regex]::Match($xml,'(?is)<Triggers>.*?</Triggers>').Value);SettingsXml=([regex]::Match($xml,'(?is)<Settings>.*?</Settings>').Value);RegistrationInfoXml=([regex]::Match($xml,'(?is)<RegistrationInfo>.*?</RegistrationInfo>').Value);Author=$t.Author;Principal=[ordered]@{UserId=$t.Principal.UserId;LogonType=$t.Principal.LogonType.ToString();RunLevel=$t.Principal.RunLevel.ToString()};Action=[ordered]@{Execute=$actions[0].Execute;Arguments=$actions[0].Arguments;WorkingDirectory=$actions[0].WorkingDirectory;Executable=$exe};LastRunTime=$info.LastRunTime;LastTaskResult=$info.LastTaskResult;NextRunTime=$info.NextRunTime}}
function Get-Eligibility{$sup=Get-SupportState;$r=@($sup.Reasons);$c=$null;try{$c=Get-Candidate}catch{$r+=$_.Exception.Message};if($c-and!$c.Enabled){$r+='Selected baseline task must be enabled'};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;Platform=$sup;Candidate=$c;EvidenceStatus='needs-evidence'}}
function Save-State($elig){if(!$elig.Supported){throw($elig.Reasons-join'; ')};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Split-Path $StatePath -Parent;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$prot=Get-ProtectedSnapshot;$other=Get-UnrelatedSnapshot $elig.Candidate.Identity;$st=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');selection=$elig.Candidate.Selection;candidate=$elig.Candidate;protectedScope=$prot;unrelatedTasks=$other;evidenceStatus='needs-evidence'};$st|ConvertTo-Json -Depth 24|Set-Content -LiteralPath $StatePath -Encoding UTF8;$st}
function Read-State{if(!(Test-Path -LiteralPath $StatePath)){throw 'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Get-CurrentTask($st){$t=Get-ScheduledTask -TaskName ([string]$st.candidate.TaskName) -TaskPath ([string]$st.candidate.TaskPath) -ErrorAction SilentlyContinue;if(!$t){throw 'Captured task disappeared.'};$xml=Export-ScheduledTask -TaskName $t.TaskName -TaskPath $t.TaskPath;if((Get-DefinitionHash $xml)-ne[string]$st.candidate.DefinitionSha256){throw 'Task-definition drift detected.'};$id=Get-FileIdentity ([string]$st.candidate.Action.Executable.Path);if(!$id-or!$id.ValidPublisher-or$id.Sha256-ne[string]$st.candidate.Action.Executable.Sha256-or$id.Thumbprint-ne[string]$st.candidate.Action.Executable.Thumbprint-or$id.FileVersion-ne[string]$st.candidate.Action.Executable.FileVersion){throw 'Executable or product identity drift detected.'};[pscustomobject]@{Task=$t;Xml=$xml;XmlSha256=Get-TextHash $xml}}
function Assert-Guards($st){if((Get-ManagementState).Managed){throw 'Management ownership appeared.'};if((Get-ProtectedSnapshot).Hash-ne[string]$st.protectedScope.Hash){throw 'Protected-scope drift detected.'};if((Get-UnrelatedSnapshot ([string]$st.candidate.Identity)).Hash-ne[string]$st.unrelatedTasks.Hash){throw 'Unrelated sign-in task drift detected.'}}
try{$elig=Get-Eligibility;Write-Log 'support-detection' $(if($elig.Supported){'pass'}else{'refused'}) $elig;switch($Action){
 'Check'{$elig}
 'Capture'{$s=Save-State $elig;Write-Log 'capture' 'pass' @{identity=$s.candidate.Identity;xmlSha256=$s.candidate.XmlSha256;definitionSha256=$s.candidate.DefinitionSha256;inventoryHash=$s.selection.inventoryHash};$s}
 'DryRun'{if(!$elig.Supported){throw($elig.Reasons-join'; ')};$x=[pscustomobject]@{WouldChange=$true;MutationCount=1;Identity=$elig.Candidate.Identity;FromEnabled=$true;ToEnabled=$false;InventoryHash=$elig.Candidate.Selection.inventoryHash;PreserveTaskDefinition=$true;PreserveApplication=$true;PreserveServices=$true;PreservePackages=$true;PreserveServicing=$true;PreserveFirmware=$true;PreserveDrivers=$true;PreserveProtectedScope=$true;RebootPersistenceRequired=$true;Rollback='restore exact captured enabled state after XML-definition, executable, management, unrelated-task, and protected-scope drift checks';EvidenceStatus='needs-evidence'};Write-Log 'dry-run' 'pass' $x;$x}
 'Apply'{$st=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $elig};$cur=Get-CurrentTask $st;Assert-Guards $st;if(!$cur.Task.Settings.Enabled){Write-Log 'apply' 'idempotent' @{mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess([string]$st.candidate.Identity,'Disable exact EXP-143-selected sign-in scheduled task')){Disable-ScheduledTask -TaskName ([string]$st.candidate.TaskName) -TaskPath ([string]$st.candidate.TaskPath)|Out-Null}else{return};$v=Get-CurrentTask $st;if($v.Task.Settings.Enabled){throw 'Apply verification failed.'};Assert-Guards $st;Write-Log 'apply' 'pass' @{mutationCount=1;definitionPreserved=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
 'Verify'{$st=Read-State;$cur=Get-CurrentTask $st;Assert-Guards $st;if($cur.Task.Settings.Enabled){throw 'Immediate verification failed.'};Write-Log 'verify' 'pass' @{enabled=$false;definitionPreserved=$true};$true}
 'VerifyReboot'{$st=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$st.capturedBootTime){throw 'A later boot is required.'};$cur=Get-CurrentTask $st;Assert-Guards $st;if($cur.Task.Settings.Enabled){throw 'Reboot persistence failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');enabled=$false;evidenceStatus='needs-evidence'};$true}
 'Rollback'{$st=Read-State;$cur=Get-CurrentTask $st;Assert-Guards $st;if($cur.Task.Settings.Enabled){if($cur.XmlSha256-ne[string]$st.candidate.XmlSha256){throw 'Rollback exact-XML verification failed.'};Write-Log 'rollback' 'idempotent' @{mutationCount=0;restoredExactOriginal=$true};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess([string]$st.candidate.Identity,'Restore exact captured task enabled state')){Enable-ScheduledTask -TaskName ([string]$st.candidate.TaskName) -TaskPath ([string]$st.candidate.TaskPath)|Out-Null}else{return};$v=Get-CurrentTask $st;if(!$v.Task.Settings.Enabled-or$v.XmlSha256-ne[string]$st.candidate.XmlSha256){throw 'Exact rollback verification failed.'};Assert-Guards $st;Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true;xmlVerified=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'};throw}
