[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:LOCALAPPDATA\Lacksan\EXP-053-state.json",
 [string]$LogPath="$env:LOCALAPPDATA\Lacksan\EXP-053.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-053';$provider='logitech-ghub-demand-launch';$runPath='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|msrdc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|recovery|accessibility|narrator|magnify|intune|sccm|configmgr|mdm'
function Write-Log([string]$Event,[string]$Result,[object]$Data){$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=2;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-Hash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$signals=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=$en;OmadmAccounts=$om;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);RunPolicy=(Test-Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')};[pscustomobject]@{Managed=($signals.DomainJoined-or$en-gt0-or$om-gt0-or$signals.PolicyManager-or$signals.ConfigMgr-or$signals.RunPolicy);Signals=$signals}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard');OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Managed=$m.Managed;ManagementSignals=$m.Signals;EvidenceStatus='needs-evidence'}}
function Get-ProtectedSnapshot{$services=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){ $x=Get-CimInstance Win32_Service -Filter "Name='$n'" -ErrorAction SilentlyContinue;if($x){[ordered]@{Name=$x.Name;State=$x.State;StartMode=$x.StartMode;PathName=$x.PathName}}};$drivers=@(Get-CimInstance Win32_SystemDriver -ErrorAction SilentlyContinue|Where-Object{$_.Name-match'(?i)logi|logitech'-or$_.PathName-match'(?i)logi|logitech'}|Sort-Object Name|Select-Object Name,State,StartMode,PathName);$devices=@(Get-PnpDevice -ErrorAction SilentlyContinue|Where-Object{$_.FriendlyName-match'(?i)logi|logitech'-or$_.Manufacturer-match'(?i)logi|logitech'}|Sort-Object InstanceId|Select-Object InstanceId,Status,Class,FriendlyName);$j=[ordered]@{Services=@($services);LogitechDrivers=$drivers;LogitechDevices=$devices}|ConvertTo-Json -Compress -Depth 12;[pscustomobject]@{Hash=Get-Hash $j;Snapshot=$j}}
function Resolve-Command([string]$Command){$e=[Environment]::ExpandEnvironmentVariables($Command).Trim();if($e-match$protected){return $null};$exe=$null;$args='';if($e-match'^\s*"(?<exe>[^"]+)"\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}elseif($e-match'^\s*(?<exe>\S+\.exe)\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}else{return $null};try{$exe=[IO.Path]::GetFullPath($exe)}catch{return $null};if($exe-notmatch'(?i)\\LGHUB\\.*\\?(lghub|lghub_agent|lghub_system_tray)\.exe$'){return $null};if($exe-match'(?i)updat|uninstall|repair|firmware|dfu|driver'){return $null};if([string]::IsNullOrWhiteSpace($args)-or$args-notmatch'(?i)background|minimi[sz]ed|startup|tray|silent|autostart|system-initiated'){return $null};[pscustomobject]@{ExpandedCommand=$e;Executable=$exe;Arguments=$args}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$i=Get-Item -LiteralPath $Path;$s=Get-AuthenticodeSignature -LiteralPath $Path;$p=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$i.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$i.VersionInfo.FileVersion;ProductName=$i.VersionInfo.ProductName;CompanyName=$i.VersionInfo.CompanyName;SignatureStatus=$s.Status.ToString();Publisher=$p;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidLogitechPublisher=($s.Status-eq'Valid'-and$p-match'(?i)Logitech|Logi')}}
function Get-Candidates{if(!(Test-Path -LiteralPath $runPath)){return @()};$k=Get-Item -LiteralPath $runPath;$out=@();foreach($n in $k.GetValueNames()){if($n-notmatch'(?i)^logi(?:tech)?[ ._-]*(g[ ._-]*hub|ghub)$|^lghub$'){continue};$d=[string]$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$r=Resolve-Command $d;if(!$r){continue};$id=Get-FileIdentity $r.Executable;if(!$id-or!$id.ValidLogitechPublisher){continue};$a=Get-Acl -LiteralPath $runPath;$out+=[pscustomobject]@{Path=$runPath;Name=$n;Kind=$k.GetValueKind($n).ToString();Data=$d;ExpandedCommand=$r.ExpandedCommand;Arguments=$r.Arguments;Executable=$id;KeyOwner=$a.Owner;KeySddl=$a.Sddl}};@($out)}
function Assert-Eligible($Support,[object[]]$Candidates){if(!$Support.Supported){throw 'HP Windows 11 is required.'};if($Support.Managed){throw 'Enterprise-management ownership detected.'};if($Candidates.Count-ne1){throw "Exactly one eligible Logitech G Hub Run registration is required; found $($Candidates.Count)."}}
function Save-State($Support,[object[]]$Candidates){Assert-Eligible $Support $Candidates;if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Get-ProtectedSnapshot;$s=[ordered]@{schemaVersion=2;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedScopeHash=$p.Hash;entry=$Candidates[0];evidenceStatus='needs-evidence'};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$s|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if(!(Test-Path -LiteralPath $StatePath)){throw 'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne2-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Test-Removed($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $true};!((Get-Item -LiteralPath $State.entry.Path).GetValueNames()-contains[string]$State.entry.Name)}
function Assert-Executable($State){$e=Get-FileIdentity([string]$State.entry.Executable.Path);if(!$e-or!$e.ValidLogitechPublisher-or$e.Sha256-ne[string]$State.entry.Executable.Sha256-or$e.Thumbprint-ne[string]$State.entry.Executable.Thumbprint){throw 'Logitech G Hub executable identity drift detected.'}}
function Assert-Protected($State){if((Get-ProtectedSnapshot).Hash-ne[string]$State.protectedScopeHash){throw 'Protected security update remote-access driver or device state drift detected.'}}
function Test-Restored($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $false};$k=Get-Item -LiteralPath $State.entry.Path;if(!($k.GetValueNames()-contains[string]$State.entry.Name)){return $false};$d=[string]$k.GetValue($State.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$d-eq[string]$State.entry.Data-and$k.GetValueKind($State.entry.Name).ToString()-eq[string]$State.entry.Kind}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{$c=Get-Candidates;Write-Log 'candidate-inventory' 'pass' @{count=$c.Count;names=@($c.Name)};[pscustomobject]@{Support=$support;Candidates=$c;Profile='LogitechGHubDemandLaunch';EvidenceStatus='needs-evidence'}}
'Capture'{$s=Save-State $support (Get-Candidates);Write-Log 'capture' 'pass' @{path=$s.entry.Path;name=$s.entry.Name};$s}
'DryRun'{$c=Get-Candidates;Assert-Eligible $support $c;$r=[pscustomobject]@{Profile='LogitechGHubDemandLaunch';WouldChange=$true;MutationCount=1;Path=$c[0].Path;Name=$c[0].Name;Arguments=$c[0].Arguments;PreserveApplication=$true;PreserveServices=$true;PreserveScheduledTasks=$true;PreserveStartupTasks=$true;PreserveDrivers=$true;PreserveDevices=$true;RebootPersistenceCheckRequired=$true;Rollback='Restore exact captured value name, kind, and unexpanded data.';EvidenceStatus='needs-evidence'};Write-Log 'dry-run' 'pass' $r;$r}
'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support (Get-Candidates)};if(Test-Removed $s){Assert-Executable $s;Assert-Protected $s;Write-Log 'apply' 'idempotent' @{mutationCount=0};return[pscustomobject]@{Applied=$true;MutationCount=0}};Assert-Eligible $support (Get-Candidates);Assert-Executable $s;Assert-Protected $s;if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Remove exact Logitech G Hub Run registration')){Remove-ItemProperty -LiteralPath $s.entry.Path -Name $s.entry.Name}else{return};if(!(Test-Removed $s)){throw 'Apply verification failed.'};Assert-Protected $s;Write-Log 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$s=Read-State;if(!(Test-Removed $s)){throw 'Immediate verification failed.'};Assert-Executable $s;Assert-Protected $s;Write-Log 'verify' 'pass' @{removed=$true};$true}
'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};if(!(Test-Removed $s)){throw 'Reboot persistence failed.'};Assert-Executable $s;Assert-Protected $s;Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');evidenceStatus='needs-evidence'};$true}
'Rollback'{$s=Read-State;if(!(Test-Removed $s)){if(Test-Restored $s){Assert-Executable $s;Assert-Protected $s;Write-Log 'rollback' 'idempotent' @{mutationCount=0};return[pscustomobject]@{RolledBack=$true;MutationCount=0}};throw 'Rollback overwrite refused.'};if($support.Managed){throw 'Management ownership appeared.'};Assert-Executable $s;Assert-Protected $s;if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Restore exact Logitech G Hub Run registration')){if(!(Test-Path -LiteralPath $s.entry.Path)){New-Item -Path $s.entry.Path -Force|Out-Null};$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.entry.Kind,$true);(Get-Item -LiteralPath $s.entry.Path).SetValue([string]$s.entry.Name,[string]$s.entry.Data,$kind)}else{return};if(!(Test-Restored $s)){throw 'Exact rollback verification failed.'};Assert-Protected $s;Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message;evidenceStatus='needs-evidence'};throw}
