[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-080-run-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-080-run-events.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-080';$Provider='logitech-download-assistant-demand-launch'
$RunPaths=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run')
$Protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|msrdc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|recovery|accessibility|narrator|magnify|intune|sccm|configmgr|mdm'
function Write-Event([string]$Event,[string]$Result,$Data){$d=Split-Path -Parent $LogPath;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=2;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 30|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Same($A,$B){($A|ConvertTo-Json -Compress -Depth 30)-eq($B|ConvertTo-Json -Compress -Depth 30)}
function Get-Hash([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','')}finally{$sha.Dispose()}}
function ConvertTo-UtcDateTime([string]$Value){([DateTimeOffset]::Parse($Value,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind)).UtcDateTime}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=$en;OmadmAccounts=$om;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);RunPolicy=(Test-Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')};[pscustomobject]@{Managed=($x.DomainJoined-or$en-gt0-or$om-gt0-or$x.PolicyManager-or$x.ConfigMgr-or$x.RunPolicy);Signals=$x}}
function Get-FileIdentity([string]$Path){if([string]::IsNullOrWhiteSpace($Path)-or!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$s=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($s.SignerCertificate){[string]$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Name=$f.Name;Version=$f.VersionInfo.FileVersion;Product=$f.VersionInfo.ProductName;Company=$f.VersionInfo.CompanyName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;Signature=$s.Status.ToString();Publisher=$pub;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidLogitech=($s.Status-eq'Valid'-and$pub-match'(?i)Logitech|Logi')}}
function Resolve-Command([string]$Command){$expanded=[Environment]::ExpandEnvironmentVariables($Command).Trim();if([string]::IsNullOrWhiteSpace($expanded)-or$expanded-match$Protected){return $null};$direct=[regex]::Match($expanded,'^\s*"?(?<exe>[A-Za-z]:\\[^\"]+?\.exe)"?(?:\s+(?<args>.*))?$');if($direct.Success){$exe=$direct.Groups['exe'].Value;if([IO.Path]::GetFileName($exe)-notmatch'(?i)^(LogiLDA|LogitechDownloadAssistant)\.exe$'){return $null};if($exe-notmatch'(?i)\\Logi(?:tech)?\\|\\Logitech Download Assistant\\'){return $null};$id=Get-FileIdentity $exe;if(!$id-or!$id.ValidLogitech){return $null};return[pscustomobject]@{Kind='DirectExe';Expanded=$expanded;Launcher=$exe;Arguments=$direct.Groups['args'].Value;Payload=$id}}
 $rd=[regex]::Match($expanded,'^\s*"?(?<exe>[A-Za-z]:\\[^\"]*rundll32\.exe)"?\s+"?(?<dll>[A-Za-z]:\\[^,\"]*LogiLDA\.dll)"?\s*,\s*(?<export>[A-Za-z0-9_]+)\s*$');if(!$rd.Success){return $null};if($rd.Groups['export'].Value-ne'LogiFetch'){return $null};$systemRundll=[IO.Path]::GetFullPath((Join-Path $env:SystemRoot 'System32\rundll32.exe'));try{$launcher=[IO.Path]::GetFullPath($rd.Groups['exe'].Value)}catch{return $null};if($launcher-ne$systemRundll){return $null};$payload=Get-FileIdentity $rd.Groups['dll'].Value;if(!$payload-or!$payload.ValidLogitech){return $null};[pscustomobject]@{Kind='Rundll32LogiLDA';Expanded=$expanded;Launcher=$launcher;Arguments=($rd.Groups['dll'].Value+',LogiFetch');Payload=$payload}}
function Get-ProtectedSnapshot{$configServices=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$s=Get-CimInstance Win32_Service -Filter "Name='$n'" -ErrorAction SilentlyContinue;if($s){[ordered]@{Name=$s.Name;StartMode=$s.StartMode;PathName=$s.PathName}}};$runtimeServices=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$s=Get-CimInstance Win32_Service -Filter "Name='$n'" -ErrorAction SilentlyContinue;if($s){[ordered]@{Name=$s.Name;State=$s.State}}};$drivers=@(Get-CimInstance Win32_SystemDriver -ErrorAction SilentlyContinue|Where-Object{$_.Name-match'(?i)logi|logitech'-or$_.PathName-match'(?i)logi|logitech'}|Sort-Object Name|Select-Object Name,StartMode,PathName);$devices=@(Get-PnpDevice -ErrorAction SilentlyContinue|Where-Object{$_.FriendlyName-match'(?i)logi|logitech'-or$_.Manufacturer-match'(?i)logi|logitech'}|Sort-Object InstanceId|Select-Object InstanceId,Class,FriendlyName,Manufacturer);$processes=@(Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.ProcessName-match'(?i)omnissa|horizon|msrdc|mstsc|tailscale'}|Select-Object -ExpandProperty ProcessName -Unique|Sort-Object);$configuration=[ordered]@{Services=@($configServices);LogitechDrivers=$drivers;LogitechDevices=$devices}|ConvertTo-Json -Compress -Depth 15;$runtime=[ordered]@{Services=@($runtimeServices);ProtectedProcesses=$processes}|ConvertTo-Json -Compress -Depth 10;[pscustomobject]@{Hash=Get-Hash $configuration;Configuration=$configuration;Runtime=$runtime}}
function Get-Candidates{$out=@();foreach($path in $RunPaths){if(!(Test-Path -LiteralPath $path)){continue};$key=Get-Item -LiteralPath $path;$acl=Get-Acl -LiteralPath $path;foreach($name in $key.GetValueNames()){if($name-notmatch'(?i)^(Logitech Download Assistant|LogitechDownloadAssistant|LogiLDA)$'){continue};$data=[string]$key.GetValue($name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$resolved=Resolve-Command $data;if(!$resolved){continue};$out+=[pscustomobject]@{Path=$path;Name=$name;Kind=$key.GetValueKind($name).ToString();Data=$data;KeyOwner=$acl.Owner;KeySddl=$acl.Sddl;CommandKind=$resolved.Kind;ExpandedCommand=$resolved.Expanded;Launcher=$resolved.Launcher;Arguments=$resolved.Arguments;Payload=$resolved.Payload}}};@($out)}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$e=Test-Elevated;$c=@(Get-Candidates);$r=@();if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!$e){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};if($c.Count-ne1){$r+="exactly one eligible Logitech Download Assistant Run registration required; found $($c.Count)"};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=$e;Management=$m;Candidates=$c;Protected=Get-ProtectedSnapshot;EvidenceStatus='needs-evidence'}}
function Save-State($Support){if(!$Support.Supported){throw($Support.Reasons-join'; ')};if(Test-Path -LiteralPath $StatePath){throw'State overwrite refused.'};$p=Get-ProtectedSnapshot;$d=Split-Path -Parent $StatePath;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$s=[ordered]@{schemaVersion=2;experiment=$Experiment;provider=$Provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootUtc=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedConfigurationHash=$p.Hash;protectedRuntime=$p.Runtime;entry=$Support.Candidates[0];evidenceStatus='needs-evidence'};$s|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if(!(Test-Path -LiteralPath $StatePath)){throw'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne2-or$s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw'State identity mismatch.'};$s}
function Get-ValueState($State){if(!(Test-Path -LiteralPath ([string]$State.entry.Path))){return[pscustomobject]@{KeyExists=$false;ValueExists=$false;Kind=$null;Data=$null}};$k=Get-Item -LiteralPath ([string]$State.entry.Path);$exists=$k.GetValueNames()-contains[string]$State.entry.Name;[pscustomobject]@{KeyExists=$true;ValueExists=$exists;Kind=if($exists){$k.GetValueKind([string]$State.entry.Name).ToString()}else{$null};Data=if($exists){[string]$k.GetValue([string]$State.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}else{$null}}}
function Test-ExactOriginal($State){$v=Get-ValueState $State;$v.KeyExists-and$v.ValueExists-and$v.Kind-eq[string]$State.entry.Kind-and$v.Data-eq[string]$State.entry.Data}
function Assert-Guards($State){if(!(Test-Elevated)){throw'Elevation required.'};if((Get-ManagementState).Managed){throw'Management ownership appeared.'};if(!(Test-Path -LiteralPath ([string]$State.entry.Path))){throw'Run-key drift detected; exact rollback safety cannot be established.'};$acl=Get-Acl -LiteralPath ([string]$State.entry.Path);if($acl.Owner-ne[string]$State.entry.KeyOwner-or$acl.Sddl-ne[string]$State.entry.KeySddl){throw'Run-key ACL drift detected.'};$payload=Get-FileIdentity ([string]$State.entry.Payload.Path);if(!$payload-or!$payload.ValidLogitech-or$payload.Sha256-ne[string]$State.entry.Payload.Sha256-or$payload.Thumbprint-ne[string]$State.entry.Payload.Thumbprint-or$payload.Version-ne[string]$State.entry.Payload.Version){throw'Logitech Download Assistant payload identity drift detected.'};if((Get-ProtectedSnapshot).Hash-ne[string]$State.protectedConfigurationHash){throw'Protected security update remote-access driver or device configuration drift detected.'}}
function Assert-Baseline($State){Assert-Guards $State;if(!(Test-ExactOriginal $State)){throw'Captured Logitech Download Assistant Run registration drift detected.'}}
try{$support=Get-SupportState;Write-Event 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $support;switch($Action){
 'Check'{$support}
 'Capture'{$s=Save-State $support;Write-Event 'capture' 'pass' @{path=$s.entry.Path;name=$s.entry.Name;kind=$s.entry.Kind;payload=$s.entry.Payload.Path;protectedRuntime=$s.protectedRuntime};$s}
 'DryRun'{if(!$support.Supported){throw($support.Reasons-join'; ')};$c=$support.Candidates[0];$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Path=$c.Path;Name=$c.Name;Kind=$c.Kind;CommandKind=$c.CommandKind;Payload=$c.Payload.Path;Treatment='remove exact Logitech Download Assistant Run registration';PreserveExecutable=$true;PreserveServices=$true;PreserveScheduledTasks=$true;PreservePnPDevices=$true;PreserveDriverPackages=$true;PreserveFirmware=$true;PreservePairing=$true;PreserveProtectedScope=$true;RebootPersistenceRequired=$true;Rollback='restore exact captured value name, type, and unexpanded data after ACL, payload, management, and protected-configuration drift checks';EvidenceStatus='needs-evidence'};Write-Event 'dry-run' 'pass' $r;$r}
 'Apply'{$s=Read-State;$v=Get-ValueState $s;if(!$v.ValueExists){Assert-Guards $s;Write-Event 'apply' 'idempotent' @{mutationCount=0};return[pscustomobject]@{Applied=$true;MutationCount=0}};Assert-Baseline $s;if($WhatIfPreference){Write-Event 'apply' 'whatif' @{mutationCount=0};return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Remove exact Logitech Download Assistant Run registration')){Remove-ItemProperty -LiteralPath ([string]$s.entry.Path) -Name ([string]$s.entry.Name)}else{return};if((Get-ValueState $s).ValueExists){throw'Apply verification failed.'};Assert-Guards $s;Write-Event 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
 'Verify'{$s=Read-State;if((Get-ValueState $s).ValueExists){throw'Treatment registration remains present.'};Assert-Guards $s;Write-Event 'verify' 'pass' @{registrationAbsent=$true;peripheralReadiness='needs-evidence'};$true}
 'VerifyReboot'{$s=Read-State;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();$captured=ConvertTo-UtcDateTime ([string]$s.capturedBootUtc);if($boot-le$captured){throw'A later boot is required.'};if((Get-ValueState $s).ValueExists){throw'Treatment failed reboot persistence.'};Assert-Guards $s;Write-Event 'verify-reboot' 'pass' @{bootUtc=$boot.ToString('o');registrationAbsent=$true;protectedRuntime=(Get-ProtectedSnapshot).Runtime;peripheralReadiness='needs-evidence'};$true}
 'Rollback'{$s=Read-State;$v=Get-ValueState $s;if($v.ValueExists){if(Test-ExactOriginal $s){Assert-Guards $s;Write-Event 'rollback' 'idempotent' @{mutationCount=0};return[pscustomobject]@{RolledBack=$true;MutationCount=0}};throw'Rollback overwrite refused.'};Assert-Guards $s;if($WhatIfPreference){Write-Event 'rollback' 'whatif' @{mutationCount=0};return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Restore exact captured Logitech Download Assistant Run registration')){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.entry.Kind,$true);(Get-Item -LiteralPath ([string]$s.entry.Path)).SetValue([string]$s.entry.Name,[string]$s.entry.Data,$kind)}else{return};if(!(Test-ExactOriginal $s)){throw'Exact rollback verification failed.'};Assert-Guards $s;Write-Event 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Event 'failure' 'failed' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'};throw}
