[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-081'
$provider='logitech-setpoint-event-manager-run'
$runPaths=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run')
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|recovery|accessibility|driver|firmware|receiver|bluetooth|intune|sccm|configmgr|mdm'
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$d=Split-Path -Parent $LogPath;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;data=$Data}|ConvertTo-Json -Compress -Depth 12|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-ManagementState{$cs=Get-CimInstance Win32_ComputerSystem;$signals=[ordered]@{DomainJoined=[bool]$cs.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)};[pscustomobject]@{Managed=($signals.DomainJoined-or$signals.MdmEnrollments-gt0-or$signals.PolicyManager-or$signals.ConfigMgr);Signals=$signals}}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard');OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Resolve-Executable([string]$Command){$x=[Environment]::ExpandEnvironmentVariables($Command).Trim();if($x-match'^\s*"([^"]+\.exe)"'){$p=$matches[1]}elseif($x-match'^\s*([^\s]+\.exe)'){$p=$matches[1]}else{return $null};try{[IO.Path]::GetFullPath($p)}catch{$null}}
function Get-Publisher([string]$Path){if(!(Test-Path $Path -PathType Leaf)){return $null};$s=Get-AuthenticodeSignature -LiteralPath $Path;$subject=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Status=$s.Status.ToString();Subject=$subject;Valid=($s.Status-eq'Valid'-and$subject-match'(?i)Logitech|Logi')}}
function Test-Identity([string]$Name,[string]$Command,[string]$Executable){$all="$Name $Command $Executable";if($all-match$protected){return $false};$nameOk=$Name-match'(?i)^(Logitech SetPoint Event Manager|SetPoint|SetPoint Event Manager)$';$exeOk=[IO.Path]::GetFileName($Executable)-match'(?i)^SetPoint(?:II)?\.exe$';$pathOk=$Executable-match'(?i)\\Logitech\\SetPoint|\\SetPoint\\';$refused=$Command-match'(?i)update|updater|uninstall|repair|firmware|pair|driver|device';$nameOk-and$exeOk-and$pathOk-and!$refused}
function Get-Candidates{$items=@();foreach($path in $runPaths){if(!(Test-Path $path)){continue};$key=Get-Item $path;foreach($name in $key.GetValueNames()){$data=[string]$key.GetValue($name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$exe=Resolve-Executable $data;if($exe-and(Test-Identity $name $data $exe)){$pub=Get-Publisher $exe;if($pub-and$pub.Valid){$items+=[pscustomobject]@{Path=$path;Name=$name;Kind=$key.GetValueKind($name).ToString();Data=$data;Executable=$exe;ExecutableHash=(Get-FileHash $exe -Algorithm SHA256).Hash;ExecutableVersion=(Get-Item $exe).VersionInfo.FileVersion;PublisherSubject=$pub.Subject}}}}};@($items)}
function Assert-One([object[]]$Candidates){if($Candidates.Count-eq0){throw'No eligible Logitech SetPoint Event Manager registration was found.'};if($Candidates.Count-gt1){throw'Multiple eligible Logitech SetPoint Event Manager registrations were found.'}}
function Save-State([object[]]$Candidates){Assert-One $Candidates;if([string]::IsNullOrWhiteSpace($StatePath)){throw'StatePath is required.'};if(Test-Path $StatePath){throw'State file already exists; overwrite refused.'};$s=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;entry=$Candidates[0]};$d=Split-Path -Parent $StatePath;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$s|ConvertTo-Json -Depth 12|Set-Content $StatePath -Encoding UTF8;$s}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path $StatePath)){throw'State file missing.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw'State identity validation failed.'};$s}
function Test-Removed($s){if(!(Test-Path $s.entry.Path)){return $true};!((Get-Item $s.entry.Path).GetValueNames()-contains[string]$s.entry.Name)}
function Test-Restored($s){if(!(Test-Path $s.entry.Path)){return $false};$k=Get-Item $s.entry.Path;if(!($k.GetValueNames()-contains[string]$s.entry.Name)){return $false};$v=[string]$k.GetValue($s.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$v-eq[string]$s.entry.Data-and$k.GetValueKind($s.entry.Name).ToString()-eq[string]$s.entry.Kind}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;if(!$support.Supported){throw'Provider supports HP systems running Windows 11 only.'};if($support.Managed){throw'Enterprise-management signals are present; mutation is refused.'};switch($Action){
'Check'{$c=Get-Candidates;Write-Log 'candidate-inventory' 'pass' @{count=$c.Count;names=@($c.Name)};$c}
'Capture'{$s=Save-State (Get-Candidates);Write-Log 'capture' 'pass' @{path=$s.entry.Path;name=$s.entry.Name};$s}
'DryRun'{$c=Get-Candidates;Assert-One $c;Write-Log 'dry-run' 'pass' @{candidate=$c[0]};[pscustomobject]@{Provider=$provider;WouldChange=$true;WouldRemove=$c[0];RebootPersistenceCheckRequired=$true}}
'Apply'{$s=if(Test-Path $StatePath){Read-State}else{Save-State (Get-Candidates)};if(Test-Removed $s){Write-Log 'apply' 'idempotent' @{};return [pscustomobject]@{Applied=$true;MutationCount=0}};$c=Get-Candidates;Assert-One $c;foreach($f in 'Path','Name','Kind','Data','Executable','ExecutableHash','ExecutableVersion','PublisherSubject'){if([string]$c[0].$f-ne[string]$s.entry.$f){throw"Captured-state drift detected: $f"}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Remove SetPoint Event Manager startup registration')){Remove-ItemProperty -LiteralPath $s.entry.Path -Name $s.entry.Name};if(!(Test-Removed $s)){throw'Apply verification failed.'};Write-Log 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$s=Read-State;if(!(Test-Removed $s)){throw'Removal verification failed.'};Write-Log 'verify' 'pass' @{};$true}
'VerifyReboot'{$s=Read-State;if(!(Test-Removed $s)){throw'Reboot persistence verification failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime};$true}
'Rollback'{$s=Read-State;if(!(Test-Removed $s)){throw'Rollback refused because the value already exists.'};if(!(Test-Identity $s.entry.Name $s.entry.Data $s.entry.Executable)){throw'Rollback identity validation failed.'};$pub=Get-Publisher $s.entry.Executable;if(!$pub-or!$pub.Valid-or$pub.Subject-ne[string]$s.entry.PublisherSubject){throw'Rollback publisher drift detected.'};if((Get-FileHash $s.entry.Executable -Algorithm SHA256).Hash-ne[string]$s.entry.ExecutableHash){throw'Rollback executable hash drift detected.'};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Restore exact SetPoint Event Manager startup registration')){if(!(Test-Path $s.entry.Path)){New-Item -Path $s.entry.Path -Force|Out-Null};(Get-Item $s.entry.Path).SetValue([string]$s.entry.Name,[string]$s.entry.Data,[Microsoft.Win32.RegistryValueKind]::$($s.entry.Kind))};if(!(Test-Restored $s)){throw'Rollback verification failed.'};Write-Log 'rollback' 'pass' @{mutationCount=1};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
