[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')]
    [string]$Action = 'Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$experiment = 'EXP-080'
$provider = 'logitech-download-assistant-run'
$runPaths = @('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Run')
$protectedIdentity = '(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|recovery|accessibility|intune|sccm|configmgr|mdm'
$refusedCommand = '(?i)powershell(?:\.exe)?|pwsh(?:\.exe)?|cmd(?:\.exe)?|rundll32(?:\.exe)?|msiexec(?:\.exe)?|regsvr32(?:\.exe)?|schtasks(?:\.exe)?|sc(?:\.exe)?|install|uninstall|repair|firmware|pair(?:ing)?|driver|pnputil|devcon|device'
function Write-StructuredLog([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$directory=Split-Path -Parent $LogPath;if($directory-and!(Test-Path -LiteralPath $directory)){New-Item -ItemType Directory -Path $directory -Force|Out-Null};[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;data=$Data}|ConvertTo-Json -Compress -Depth 12|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Test-IsElevated{$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($identity);$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$computer=Get-CimInstance Win32_ComputerSystem;$policyPaths=@('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run','HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run');$signals=[ordered]@{DomainJoined=[bool]$computer.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);StartupPolicy=@($policyPaths|Where-Object{Test-Path $_}).Count};[pscustomobject]@{Managed=($signals.DomainJoined-or$signals.MdmEnrollments-gt0-or$signals.PolicyManager-or$signals.ConfigMgr-or$signals.StartupPolicy-gt0);Signals=$signals}}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$computer=Get-CimInstance Win32_ComputerSystem;$management=Get-ManagementState;[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$computer.Manufacturer-match'(?i)^HP$|Hewlett-Packard');Elevated=Test-IsElevated;Edition=$os.OperatingSystemSKU;Build=$os.BuildNumber;Manufacturer=$computer.Manufacturer;Model=$computer.Model;Managed=$management.Managed;ManagementSignals=$management.Signals}}
function Get-TextHash([string]$Text){$algorithm=[Security.Cryptography.SHA256]::Create();try{($algorithm.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$algorithm.Dispose()}}
function Get-ProtectedSnapshot{$services=foreach($name in @('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale')){$service=Get-Service -Name $name -ErrorAction SilentlyContinue;if($service){[ordered]@{Name=$service.Name;Status=$service.Status.ToString();StartType=$service.StartType.ToString()}}};$processes=foreach($name in @('vmware-view','wswc','msrdc','mstsc','tailscale-ipn')){[ordered]@{Name=$name;Present=[bool](Get-Process -Name $name -ErrorAction SilentlyContinue)}};$normalized=[ordered]@{Services=@($services);ProtectedProcesses=@($processes)}|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-TextHash $normalized;Snapshot=$normalized}}
function Resolve-Executable([string]$Command){$expanded=[Environment]::ExpandEnvironmentVariables($Command).Trim();if($expanded-match'^\s*"([^"]+\.exe)"'){$path=$matches[1]}elseif($expanded-match'^\s*([^\s]+\.exe)'){$path=$matches[1]}else{return $null};try{[IO.Path]::GetFullPath($path)}catch{$null}}
function Get-Publisher([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$signature=Get-AuthenticodeSignature -LiteralPath $Path;$subject=if($signature.SignerCertificate){$signature.SignerCertificate.Subject}else{$null};$thumbprint=if($signature.SignerCertificate){$signature.SignerCertificate.Thumbprint}else{$null};[pscustomobject]@{Status=$signature.Status.ToString();Subject=$subject;Thumbprint=$thumbprint;Valid=($signature.Status-eq'Valid'-and$subject-match'(?i)Logitech|Logi')}}
function Test-Identity([string]$Name,[string]$Command,[string]$Executable){$identity="$Name $Command $Executable";if($identity-match$protectedIdentity-or$Command-match$refusedCommand){return $false};$nameOk=$Name-match'(?i)^(Logitech Download Assistant|Logi Download Assistant|LogiLDA)$';$fileOk=[IO.Path]::GetFileName($Executable)-match'(?i)^(LogitechDownloadAssistant|LogiDownloadAssistant|LogiLDA|LDA)\.exe$';$pathOk=$Executable-match'(?i)\\(Logitech|Logi)(\\|\s)';$nameOk-and$fileOk-and$pathOk}
function Get-KeyAclSummary([string]$Path){try{$acl=Get-Acl -LiteralPath $Path;[pscustomobject]@{Owner=$acl.Owner;Sddl=$acl.Sddl}}catch{[pscustomobject]@{Owner=$null;Sddl=$null}}}
function Get-Candidates{$items=@();foreach($path in $runPaths){if(!(Test-Path -LiteralPath $path)){continue};$key=Get-Item -LiteralPath $path;foreach($name in $key.GetValueNames()){$data=[string]$key.GetValue($name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$executable=Resolve-Executable $data;if(!$executable-or!(Test-Identity $name $data $executable)){continue};$publisher=Get-Publisher $executable;if(!$publisher-or!$publisher.Valid){continue};$file=Get-Item -LiteralPath $executable;$acl=Get-KeyAclSummary $path;$items+=[pscustomobject]@{Path=$path;View=if($path-match'WOW6432Node'){'Registry32'}else{'Default'};Name=$name;Kind=$key.GetValueKind($name).ToString();Data=$data;Executable=$executable;ExecutableHash=(Get-FileHash -LiteralPath $executable -Algorithm SHA256).Hash;ExecutableVersion=$file.VersionInfo.FileVersion;ProductName=$file.VersionInfo.ProductName;CompanyName=$file.VersionInfo.CompanyName;PublisherStatus=$publisher.Status;PublisherSubject=$publisher.Subject;PublisherThumbprint=$publisher.Thumbprint;KeyOwner=$acl.Owner;KeySddl=$acl.Sddl}}};@($items)}
function Assert-OneCandidate([object[]]$Candidates){if($Candidates.Count-eq0){throw'No eligible Logitech Download Assistant registration was found.'};if($Candidates.Count-gt1){throw'Multiple eligible Logitech Download Assistant registrations were found.'}}
function Save-State([object[]]$Candidates,[object]$Support){Assert-OneCandidate $Candidates;if([string]::IsNullOrWhiteSpace($StatePath)){throw'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw'State file already exists; overwrite refused.'};if($Candidates[0].Path-like'HKLM:*'-and!$Support.Elevated){throw'Elevation is required for a machine-wide registration.'};$protected=Get-ProtectedSnapshot;$state=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;windows=[ordered]@{Edition=$Support.Edition;Build=$Support.Build;Manufacturer=$Support.Manufacturer;Model=$Support.Model};managementSignals=$Support.ManagementSignals;protectedScopeHash=$protected.Hash;entry=$Candidates[0]};$directory=Split-Path -Parent $StatePath;if($directory-and!(Test-Path -LiteralPath $directory)){New-Item -ItemType Directory -Path $directory -Force|Out-Null};$state|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $StatePath -Encoding UTF8;$state}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw'State file missing.'};$state=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($state.schemaVersion-ne1-or$state.experiment-ne$experiment-or$state.provider-ne$provider-or$state.machine-ne$env:COMPUTERNAME-or$state.userSid-ne$sid){throw'State identity validation failed.'};$state}
function Test-Removed($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $true};!((Get-Item -LiteralPath $State.entry.Path).GetValueNames()-contains[string]$State.entry.Name)}
function Test-Restored($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $false};$key=Get-Item -LiteralPath $State.entry.Path;if(!($key.GetValueNames()-contains[string]$State.entry.Name)){return $false};$value=[string]$key.GetValue($State.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$value-eq[string]$State.entry.Data-and$key.GetValueKind($State.entry.Name).ToString()-eq[string]$State.entry.Kind}
try{$support=Get-SupportState;Write-StructuredLog 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;if(!$support.Supported){throw'Provider supports HP systems running Windows 11 only.'};if($support.Managed){throw'Enterprise-management or enforced startup-policy signals are present; mutation is refused.'};switch($Action){
'Check'{$candidates=Get-Candidates;Write-StructuredLog 'candidate-inventory' 'pass' @{count=$candidates.Count;names=@($candidates.Name)};$candidates}
'Capture'{$state=Save-State (Get-Candidates) $support;Write-StructuredLog 'capture' 'pass' @{path=$state.entry.Path;name=$state.entry.Name};$state}
'DryRun'{$candidates=Get-Candidates;Assert-OneCandidate $candidates;if($candidates[0].Path-like'HKLM:*'-and!$support.Elevated){throw'Elevation is required for a machine-wide registration.'};Write-StructuredLog 'dry-run' 'pass' @{candidate=$candidates[0];mutationCount=1};[pscustomobject]@{Provider=$provider;WouldChange=$true;WouldRemove=$candidates[0];MutationCount=1;RebootPersistenceCheckRequired=$true;Rollback='Restore exact value name, type, and unexpanded data.'}}
'Apply'{$state=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State (Get-Candidates) $support};if($state.entry.Path-like'HKLM:*'-and!$support.Elevated){throw'Elevation is required for a machine-wide registration.'};if(Test-Removed $state){Write-StructuredLog 'apply' 'idempotent' @{mutationCount=0};return[pscustomobject]@{Applied=$true;MutationCount=0}};$candidates=Get-Candidates;Assert-OneCandidate $candidates;foreach($field in 'Path','View','Name','Kind','Data','Executable','ExecutableHash','ExecutableVersion','PublisherStatus','PublisherSubject','PublisherThumbprint'){if([string]$candidates[0].$field-ne[string]$state.entry.$field){throw"Captured-state drift detected: $field"}};if((Get-ProtectedSnapshot).Hash-ne[string]$state.protectedScopeHash){throw'Protected-scope drift detected.'};if($WhatIfPreference){Write-StructuredLog 'apply' 'whatif' @{mutationCount=0;target="$($state.entry.Path)::$($state.entry.Name)"};return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($state.entry.Path)::$($state.entry.Name)",'Remove Logitech Download Assistant startup registration')){Remove-ItemProperty -LiteralPath $state.entry.Path -Name $state.entry.Name};if(!(Test-Removed $state)){throw'Apply verification failed.'};Write-StructuredLog 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$state=Read-State;if(!(Test-Removed $state)){throw'Removal verification failed.'};if(!(Test-Path -LiteralPath $state.entry.Executable -PathType Leaf)){throw'Executable-preservation verification failed.'};Write-StructuredLog 'verify' 'pass' @{executablePresent=$true};$true}
'VerifyReboot'{$state=Read-State;$bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($bootTime-le[datetime]$state.capturedBootTime){throw'A later boot is required for reboot-persistence verification.'};if(!(Test-Removed $state)){throw'Reboot persistence verification failed.'};Write-StructuredLog 'verify-reboot' 'pass' @{bootTime=$bootTime.ToString('o')};$true}
'Rollback'{$state=Read-State;if(!(Test-Removed $state)){throw'Rollback refused because the value already exists.'};if($state.entry.Path-like'HKLM:*'-and!$support.Elevated){throw'Elevation is required for machine-wide rollback.'};if(!(Test-Identity $state.entry.Name $state.entry.Data $state.entry.Executable)){throw'Rollback identity validation failed.'};$publisher=Get-Publisher $state.entry.Executable;if(!$publisher-or!$publisher.Valid-or$publisher.Subject-ne[string]$state.entry.PublisherSubject-or$publisher.Thumbprint-ne[string]$state.entry.PublisherThumbprint){throw'Rollback publisher drift detected.'};if((Get-FileHash -LiteralPath $state.entry.Executable -Algorithm SHA256).Hash-ne[string]$state.entry.ExecutableHash){throw'Rollback executable hash drift detected.'};if((Get-ProtectedSnapshot).Hash-ne[string]$state.protectedScopeHash){throw'Rollback protected-scope drift detected.'};if($WhatIfPreference){Write-StructuredLog 'rollback' 'whatif' @{mutationCount=0;target="$($state.entry.Path)::$($state.entry.Name)"};return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($state.entry.Path)::$($state.entry.Name)",'Restore exact Logitech Download Assistant startup registration')){if(!(Test-Path -LiteralPath $state.entry.Path)){New-Item -Path $state.entry.Path -Force|Out-Null};(Get-Item -LiteralPath $state.entry.Path).SetValue([string]$state.entry.Name,[string]$state.entry.Data,[Microsoft.Win32.RegistryValueKind]::$($state.entry.Kind))};if(!(Test-Restored $state)){throw'Rollback verification failed.'};Write-StructuredLog 'rollback' 'pass' @{mutationCount=1};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-StructuredLog 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;statePath=$StatePath};throw}
