[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath,
 [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-055'
$provider='logitech-ghub-updater-demand-start'
$serviceName='LGHUBUpdaterService'
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|defender|securityhealth|firewall|bitlocker|credential|windows update|recovery|intune|sccm|configmgr|mdm'
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-Hash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);ServicePolicy=Test-Path "HKLM:\SOFTWARE\Policies\Lacksan\Services\$serviceName"};[pscustomobject]@{Managed=($x.DomainJoined-or$x.MdmEnrollments-gt0-or$x.PolicyManager-or$x.ConfigMgr-or$x.ServicePolicy);Signals=$x}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$id=[Security.Principal.WindowsIdentity]::GetCurrent();$admin=(New-Object Security.Principal.WindowsPrincipal($id)).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);$m=Get-ManagementState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and$admin);Elevated=$admin;OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Get-ProtectedSnapshot{$s=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale'){$x=Get-CimInstance Win32_Service -Filter "Name='$n'" -ErrorAction SilentlyContinue;if($x){[ordered]@{Name=$x.Name;State=$x.State;StartMode=$x.StartMode;PathName=$x.PathName}}};$j=[ordered]@{Services=@($s)}|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-Hash $j;Snapshot=$j}}
function Resolve-Exe([string]$PathName){$e=[Environment]::ExpandEnvironmentVariables($PathName).Trim();if($e-match$protected){return $null};if($e-match'^\s*"(?<exe>[^"]+)"'){$p=$matches.exe}elseif($e-match'^\s*(?<exe>\S+\.exe)'){$p=$matches.exe}else{return $null};try{[IO.Path]::GetFullPath($p)}catch{return $null}}
function Get-Identity{ $all=@(Get-CimInstance Win32_Service -Filter "Name='$serviceName'");if($all.Count-ne1){return @()};$s=$all[0];$exe=Resolve-Exe $s.PathName;if(!$exe-or$exe-notmatch'(?i)\\LGHUB\\.*\\lghub_updater\.exe$'){return @()};if(!(Test-Path -LiteralPath $exe -PathType Leaf)){return @()};$f=Get-Item -LiteralPath $exe;$sig=Get-AuthenticodeSignature -LiteralPath $exe;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};$deps=@($s.Dependencies);$dependents=@(Get-Service $serviceName).DependentServices|ForEach-Object{$_.Name};$delayed=(Get-ItemProperty -LiteralPath "HKLM:\SYSTEM\CurrentControlSet\Services\$serviceName" -Name DelayedAutoStart -ErrorAction SilentlyContinue).DelayedAutoStart;[pscustomobject]@{Name=$s.Name;DisplayName=$s.DisplayName;State=$s.State;StartMode=$s.StartMode;DelayedAutoStart=[int]($delayed-ne$null-and$delayed);PathName=$s.PathName;ServiceAccount=$s.StartName;Dependencies=@($deps);Dependents=@($dependents);Executable=[ordered]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $exe -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidPublisher=($sig.Status-eq'Valid'-and$pub-match'(?i)Logitech|Logi')}}}
function Assert-Eligible($Support,$Identity){if(!$Support.Supported){throw 'Elevated HP Windows 11 is required.'};if($Support.Managed){throw 'Enterprise-management ownership detected.'};if($null-eq$Identity){throw 'Exactly one LGHUBUpdaterService identity is required.'};if($Identity.DisplayName-notmatch'(?i)logitech.*g.*hub.*updat'){throw 'Service display identity mismatch.'};if(!$Identity.Executable.ValidPublisher){throw 'Valid Logitech publisher signature is required.'};if($Identity.Dependencies.Count-ne0-or$Identity.Dependents.Count-ne0){throw 'Service dependencies or dependents detected.'};if($Identity.StartMode-notin @('Auto','Automatic')){throw 'Original service start mode must be Automatic or Automatic Delayed Start.'}}
function Save-State($Support,$Identity){Assert-Eligible $Support $Identity;if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Get-ProtectedSnapshot;$s=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedScopeHash=$p.Hash;service=$Identity};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$s|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw 'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Assert-Identity($State){$i=Get-Identity;if($null-eq$i-or$i.Executable.Sha256-ne[string]$State.service.Executable.Sha256-or$i.Executable.Thumbprint-ne[string]$State.service.Executable.Thumbprint-or$i.PathName-ne[string]$State.service.PathName){throw 'Service or executable identity drift detected.'};$i}
function Set-StartMode([string]$Mode,[int]$Delayed){if($Mode-eq'Manual'){Set-Service -Name $serviceName -StartupType Manual}else{Set-Service -Name $serviceName -StartupType Automatic};$key="HKLM:\SYSTEM\CurrentControlSet\Services\$serviceName";if($Delayed-eq1){Set-ItemProperty -LiteralPath $key -Name DelayedAutoStart -Type DWord -Value 1}else{Remove-ItemProperty -LiteralPath $key -Name DelayedAutoStart -ErrorAction SilentlyContinue}}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{$i=Get-Identity;Write-Log 'service-inventory' 'pass' @{found=[bool]$i;name=if($i){$i.Name}else{$null}};[pscustomobject]@{Support=$support;Service=$i;Profile='LogitechGHubUpdaterDemandStart'}}
'Capture'{$s=Save-State $support (Get-Identity);Write-Log 'capture' 'pass' @{service=$s.service.Name;startMode=$s.service.StartMode;state=$s.service.State};$s}
'DryRun'{$i=Get-Identity;Assert-Eligible $support $i;$r=[pscustomobject]@{Profile='LogitechGHubUpdaterDemandStart';WouldChange=$true;MutationCount=1;Service=$serviceName;From=$i.StartMode;To='Manual';PreserveRunningState=$true;RebootPersistenceCheckRequired=$true;Rollback='Restore exact captured start mode, delayed-auto-start state, and running state.'};Write-Log 'dry-run' 'pass' $r;$r}
'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support (Get-Identity)};$i=Assert-Identity $s;if($i.StartMode-eq'Manual' -and $i.DelayedAutoStart-eq0){Write-Log 'apply' 'idempotent' @{mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};Assert-Eligible $support $i;if((Get-ProtectedSnapshot).Hash-ne[string]$s.protectedScopeHash){throw 'Protected-scope drift detected.'};$beforeState=$i.State;if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($serviceName,'Set startup type to Manual without stopping service')){Set-StartMode 'Manual' 0};$after=Assert-Identity $s;if($after.StartMode-ne'Manual'-or$after.State-ne$beforeState){throw 'Apply verification failed or running state changed.'};Write-Log 'apply' 'pass' @{mutationCount=1;runningStatePreserved=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$s=Read-State;$i=Assert-Identity $s;if($i.StartMode-ne'Manual'){throw 'Immediate verification failed.'};Write-Log 'verify' 'pass' @{startMode=$i.StartMode;state=$i.State};$true}
'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};$i=Assert-Identity $s;if($i.StartMode-ne'Manual'){throw 'Reboot persistence failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');startMode=$i.StartMode};$true}
'Rollback'{$s=Read-State;$i=Assert-Identity $s;if($support.Managed){throw 'Management ownership appeared.'};if((Get-ProtectedSnapshot).Hash-ne[string]$s.protectedScopeHash){throw 'Protected-scope drift detected.'};$targetMode=if([string]$s.service.StartMode-in @('Auto','Automatic')){'Automatic'}else{[string]$s.service.StartMode};$targetDelayed=[int]$s.service.DelayedAutoStart;if($i.StartMode-eq$targetMode-and$i.DelayedAutoStart-eq$targetDelayed-and$i.State-eq[string]$s.service.State){Write-Log 'rollback' 'idempotent' @{mutationCount=0};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($i.StartMode-ne'Manual'){throw 'Rollback configuration drift detected.'};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($serviceName,'Restore exact captured startup and running state')){Set-StartMode $targetMode $targetDelayed;if([string]$s.service.State-eq'Running' -and (Get-Service $serviceName).Status-ne'Running'){Start-Service $serviceName};if([string]$s.service.State-eq'Stopped' -and (Get-Service $serviceName).Status-ne'Stopped'){Stop-Service $serviceName}};$r=Assert-Identity $s;if($r.StartMode-ne$targetMode-or$r.DelayedAutoStart-ne$targetDelayed-or$r.State-ne[string]$s.service.State){throw 'Exact rollback verification failed.'};Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message};throw}
