[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-132'
$issue=299
$provider='logitech-updater-run-demand-launch'
$profile='LogitechUpdaterRunDemandLaunch'
$runPaths=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run')
$allRunPaths=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run','HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce','HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce')
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|defender|securityhealth|firewall|bitlocker|credential|windows update|wuauserv|usosvc|bits|recovery|intune|sccm|configmgr|mdm|accessibility'
$unsafe='(?i)firmware|dfu|driver|device.?install|receiver|pair|bluetooth|repair|recover|uninstall|setup|bootstrap|security|credential|accessibility|enterprise|manage'
$updaterHint='(?i)update|updater|update.?check|notification'

function Write-Log([string]$Event,[string]$Result,[object]$Data){
    if([string]::IsNullOrWhiteSpace($LogPath)){return}
    $parent=Split-Path -Parent $LogPath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null}
    [ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;issue=$issue;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8
}
function Get-TextHash([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$sha.Dispose()}}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);Intune=[bool](Get-Service IntuneManagementExtension -ErrorAction SilentlyContinue);RunPolicy=(Test-Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')};[pscustomobject]@{Managed=($x.DomainJoined-or$x.MdmEnrollments-gt0-or$x.PolicyManager-or$x.ConfigMgr-or$x.Intune-or$x.RunPolicy);Signals=$x}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard');OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=Test-Elevated;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Get-ProtectedSnapshot{$s=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale'){if($x=Get-Service $n -ErrorAction SilentlyContinue){[ordered]@{Name=$x.Name;Status=$x.Status.ToString();StartType=$x.StartType.ToString()}}};$p=@(Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.ProcessName-match'(?i)omnissa|horizon|msrdc|mstsc|tailscale|windowsapp'}|Select-Object -ExpandProperty ProcessName|Sort-Object -Unique);$j=[ordered]@{Services=@($s);Processes=$p}|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-TextHash $j;Snapshot=$j}}
function Get-DeviceSnapshot{$d=@(Get-PnpDevice -ErrorAction SilentlyContinue|Where-Object{$_.FriendlyName-match'(?i)logitech|logi'}|Sort-Object InstanceId|ForEach-Object{"$($_.InstanceId)|$($_.Status)|$($_.Class)"});$j=$d|ConvertTo-Json -Compress;[pscustomobject]@{Hash=Get-TextHash ([string]$j);Snapshot=$j}}
function Get-ServicingSnapshot{
    $services=@(Get-CimInstance Win32_Service -ErrorAction SilentlyContinue|Where-Object{($_.Name+' '+$_.DisplayName+' '+$_.PathName)-match'(?i)logitech|logi'}|Sort-Object Name|ForEach-Object{[ordered]@{Name=$_.Name;State=$_.State;StartMode=$_.StartMode;PathHash=Get-TextHash ([string]$_.PathName)}})
    $tasks=@(Get-ScheduledTask -ErrorAction SilentlyContinue|Where-Object{($_.TaskName+' '+$_.TaskPath+' '+(@($_.Actions|ForEach-Object{"$($_.Execute) $($_.Arguments)"})-join' '))-match'(?i)logitech|logi'}|Sort-Object TaskPath,TaskName|ForEach-Object{[ordered]@{TaskPath=$_.TaskPath;TaskName=$_.TaskName;Enabled=[bool]$_.Settings.Enabled;ActionHash=Get-TextHash (@($_.Actions|ForEach-Object{"$($_.Execute) $($_.Arguments)"})-join'|')}})
    $j=[ordered]@{Services=$services;Tasks=$tasks}|ConvertTo-Json -Compress -Depth 10;[pscustomobject]@{Hash=Get-TextHash $j;Snapshot=$j}
}
function Resolve-Command([string]$Command){$expanded=[Environment]::ExpandEnvironmentVariables($Command).Trim();if($expanded-match$protected-or$expanded-match$unsafe){return $null};if($expanded-match'^\s*"(?<exe>[^"]+\.exe)"\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}elseif($expanded-match'^\s*(?<exe>\S+\.exe)\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}else{return $null};try{$full=[IO.Path]::GetFullPath($exe)}catch{return $null};[pscustomobject]@{ExpandedCommand=$expanded;Executable=$full;Arguments=$args.Trim()}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$sig=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductVersion=$f.VersionInfo.ProductVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidPublisher=($sig.Status-eq'Valid'-and$pub-match'(?i)Logitech|Logi')}}
function Test-UpdaterIdentity($Resolved,$Identity,[string]$ValueName){$leaf=[IO.Path]::GetFileName([string]$Resolved.Executable);$joined="$ValueName $leaf $($Identity.ProductName) $($Identity.CompanyName) $($Resolved.Arguments) $($Resolved.Executable)";if($joined-match$unsafe-or$joined-match$protected){return $false};if($joined-notmatch'(?i)logitech|logi'){return $false};if($joined-notmatch$updaterHint){return $false};if(($Identity.CompanyName+' '+$Identity.Publisher)-notmatch'(?i)logitech|logi'){return $false};$true}
function Get-Candidates{$out=@();foreach($path in $runPaths){if(!(Test-Path -LiteralPath $path)){continue};$key=Get-Item -LiteralPath $path;$acl=Get-Acl -LiteralPath $path;foreach($name in $key.GetValueNames()){$kind=$key.GetValueKind($name).ToString();if($kind-notin @('String','ExpandString')){continue};$data=[string]$key.GetValue($name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);if("$name $data"-match$protected-or"$name $data"-match$unsafe){continue};$r=Resolve-Command $data;if(!$r){continue};$id=Get-FileIdentity $r.Executable;if(!$id-or!$id.ValidPublisher-or!(Test-UpdaterIdentity $r $id $name)){continue};$out+=[pscustomobject]@{Path=$path;Hive=if($path-like'HKLM:*'){'HKLM'}else{'HKCU'};Name=$name;Kind=$kind;Data=$data;ExpandedCommand=$r.ExpandedCommand;Arguments=$r.Arguments;Executable=$id;Product=[ordered]@{Name=$id.ProductName;Version=$id.ProductVersion;Company=$id.CompanyName};KeyOwner=$acl.Owner;KeySddl=$acl.Sddl}}};@($out)}
function Get-RelatedRunState([string]$ExcludePath,[string]$ExcludeName){$items=@();foreach($path in $allRunPaths){if(Test-Path -LiteralPath $path){$k=Get-Item -LiteralPath $path;foreach($n in $k.GetValueNames()|Sort-Object){if($path-eq$ExcludePath-and$n-eq$ExcludeName){continue};$d=[string]$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);if("$n $d"-match'(?i)logitech|logi'){$items+="$path|$n|$($k.GetValueKind($n))|$(Get-TextHash $d)"}}}};$j=@($items|Sort-Object)|ConvertTo-Json -Compress;[pscustomobject]@{Count=$items.Count;Hash=Get-TextHash ([string]$j);Items=@($items|Sort-Object)}}
function Assert-Eligible($Support,[object[]]$Candidates){if(!$Support.Supported){throw 'HP Windows 11 is required.'};if($Support.Managed){throw 'Enterprise-management ownership detected.'};if($Candidates.Count-ne1){throw "Exactly one eligible Logitech updater Run registration is required; found $($Candidates.Count)."};if($Candidates[0].Hive-eq'HKLM'-and!$Support.Elevated){throw 'Elevation is required for HKLM Run.'}}
function Save-State($Support,[object[]]$Candidates){Assert-Eligible $Support $Candidates;if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Get-ProtectedSnapshot;$d=Get-DeviceSnapshot;$sv=Get-ServicingSnapshot;$e=$Candidates[0];$related=Get-RelatedRunState $e.Path $e.Name;$s=[ordered]@{schemaVersion=1;experiment=$experiment;issue=$issue;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedScopeHash=$p.Hash;deviceStateHash=$d.Hash;servicingStateHash=$sv.Hash;servicingState=$sv.Snapshot;relatedRunHash=$related.Hash;entry=$e};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$s|ConvertTo-Json -Depth 24|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw 'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.issue-ne$issue-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Test-Removed($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $true};!((Get-Item -LiteralPath $State.entry.Path).GetValueNames()-contains[string]$State.entry.Name)}
function Test-Restored($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $false};$k=Get-Item -LiteralPath $State.entry.Path;if(!($k.GetValueNames()-contains[string]$State.entry.Name)){return $false};$d=[string]$k.GetValue([string]$State.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$d-eq[string]$State.entry.Data-and$k.GetValueKind([string]$State.entry.Name).ToString()-eq[string]$State.entry.Kind}
function Assert-DriftFree($State){$m=Get-ManagementState;if($m.Managed){throw 'Enterprise-management ownership appeared.'};if((Get-ProtectedSnapshot).Hash-ne[string]$State.protectedScopeHash){throw 'Protected-scope drift detected.'};if((Get-DeviceSnapshot).Hash-ne[string]$State.deviceStateHash){throw 'Logitech device-state drift detected.'};if((Get-ServicingSnapshot).Hash-ne[string]$State.servicingStateHash){throw 'Logitech servicing-state drift detected.'};if((Get-RelatedRunState ([string]$State.entry.Path) ([string]$State.entry.Name)).Hash-ne[string]$State.relatedRunHash){throw 'Related Logitech startup-registration drift detected.'};if(!(Test-Path -LiteralPath $State.entry.Path)){throw 'Run key missing.'};$acl=Get-Acl -LiteralPath ([string]$State.entry.Path);if($acl.Owner-ne[string]$State.entry.KeyOwner-or$acl.Sddl-ne[string]$State.entry.KeySddl){throw 'Run key ownership or ACL drift detected.'};$id=Get-FileIdentity ([string]$State.entry.Executable.Path);if(!$id-or!$id.ValidPublisher-or$id.Sha256-ne[string]$State.entry.Executable.Sha256-or$id.Thumbprint-ne[string]$State.entry.Executable.Thumbprint-or$id.FileVersion-ne[string]$State.entry.Executable.FileVersion-or$id.ProductVersion-ne[string]$State.entry.Executable.ProductVersion){throw 'Logitech updater executable identity drift detected.'};$r=[pscustomobject]@{Executable=$id.Path;Arguments=[string]$State.entry.Arguments};if(!(Test-UpdaterIdentity $r $id ([string]$State.entry.Name))){throw 'Logitech updater product-role drift detected.'}}

try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
'Check'{$c=Get-Candidates;Write-Log 'candidate-inventory' 'pass' @{count=$c.Count;names=@($c.Name);products=@($c.Product.Name)};[pscustomobject]@{Support=$support;Candidates=$c;Profile=$profile;PhysicalRoleProof='needs-evidence'}}
'Capture'{$s=Save-State $support (Get-Candidates);Write-Log 'capture' 'pass' @{before=@{present=$true;path=$s.entry.Path;name=$s.entry.Name;kind=$s.entry.Kind;dataHash=Get-TextHash ([string]$s.entry.Data)};exeSha256=$s.entry.Executable.Sha256;servicingStateHash=$s.servicingStateHash;deviceStateHash=$s.deviceStateHash};$s}
'DryRun'{$c=Get-Candidates;Assert-Eligible $support $c;$r=[pscustomobject]@{Profile=$profile;WouldChange=$true;MutationCount=1;Path=$c[0].Path;Name=$c[0].Name;FromPresent=$true;ToPresent=$false;PreserveLogitechApplication=$true;PreserveUpdaterServicesAndTasks=$true;PreserveDevicesPairingFirmwareAndDrivers=$true;PreserveSecurityUpdatesRecoveryManagement=$true;PreserveProtectedRemoteAccess=$true;RebootPersistenceCheckRequired=$true;PhysicalUpdaterRoleProofRequired=$true;Rollback='Restore exact captured hive, path, value name, type, and unexpanded data after drift checks.'};Write-Log 'dry-run' 'pass' @{before=@{present=$true};after=@{present=$false};plan=$r};$r}
'Apply'{$s=if($StatePath-and(Test-Path -LiteralPath $StatePath)){Read-State}else{Save-State $support (Get-Candidates)};Assert-DriftFree $s;if(Test-Removed $s){Write-Log 'apply' 'idempotent' @{before=@{present=$false};after=@{present=$false};mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};$k=Get-Item -LiteralPath ([string]$s.entry.Path);$d=[string]$k.GetValue([string]$s.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);if($d-ne[string]$s.entry.Data-or$k.GetValueKind([string]$s.entry.Name).ToString()-ne[string]$s.entry.Kind){throw 'Run registration drift detected.'};if($WhatIfPreference){Write-Log 'apply' 'whatif' @{before=@{present=$true};after=@{present=$true};mutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Remove exact Logitech updater sign-in Run registration')){Remove-ItemProperty -LiteralPath ([string]$s.entry.Path) -Name ([string]$s.entry.Name)};if(!(Test-Removed $s)){throw 'Apply verification failed.'};Write-Log 'apply' 'pass' @{before=@{present=$true};after=@{present=$false};mutationCount=1;physicalMeasurements='needs-evidence'};[pscustomobject]@{Applied=$true;MutationCount=1;NeedsEvidence='Physical updater-role proof, five matched baseline and treatment boots, functional checks'}}
'Verify'{$s=Read-State;if(!(Test-Removed $s)){throw 'Immediate verification failed.'};Assert-DriftFree $s;Write-Log 'verify' 'pass' @{before=@{capturedPresent=$true};after=@{present=$false}};$true}
'VerifyReboot'{$s=Read-State;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};if(!(Test-Removed $s)){throw 'Reboot persistence failed.'};Assert-DriftFree $s;Write-Log 'verify-reboot' 'pass' @{bootTime=$boot.ToString('o');present=$false};$true}
'Rollback'{$s=Read-State;Assert-DriftFree $s;if(!(Test-Removed $s)){if(Test-Restored $s){Write-Log 'rollback' 'idempotent' @{mutationCount=0;restoredExactOriginal=$true};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};throw 'Rollback overwrite refused.'};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Restore exact captured Logitech updater Run registration')){(Get-Item -LiteralPath ([string]$s.entry.Path)).SetValue([string]$s.entry.Name,[string]$s.entry.Data,[Microsoft.Win32.RegistryValueKind]::$($s.entry.Kind))};if(!(Test-Restored $s)){throw 'Exact rollback verification failed.'};Write-Log 'rollback' 'pass' @{before=@{present=$false};after=@{present=$true;kind=$s.entry.Kind;dataHash=Get-TextHash ([string]$s.entry.Data)};mutationCount=1;restoredExactOriginal=$true;postRollbackBoot='needs-evidence'};[pscustomobject]@{RolledBack=$true;MutationCount=1;RestoredExactOriginal=$true}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;refusalReason=$_.Exception.Message;failureDetail=[ordered]@{message=$_.Exception.Message;type=$_.Exception.GetType().FullName;stack=$_.ScriptStackTrace}};throw}
