[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath,
 [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-115'
$provider='logitech-ghub-startup-folder'
$profile='LogitechGHubStartupFolder'
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|defender|securityhealth|firewall|bitlocker|credential|windows update|recovery|intune|sccm|configmgr|mdm'
$unsafe='(?i)firmware|dfu|driver|device.?install|pair|receiver|repair|uninstall|security|recovery|credential|accessibility|enterprise|manage|service|critical.?update'
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-HashBytes([byte[]]$Bytes){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash($Bytes)|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)};[pscustomobject]@{Managed=($x.DomainJoined-or$x.MdmEnrollments-gt0-or$x.PolicyManager-or$x.ConfigMgr);Signals=$x}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and(Test-Elevated));Elevated=Test-Elevated;OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Get-ProtectedSnapshot{$s=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale'){if($x=Get-Service $n -ErrorAction SilentlyContinue){[ordered]@{Name=$x.Name;Status=$x.Status.ToString();StartType=$x.StartType.ToString()}}};$j=[ordered]@{Services=@($s)}|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-HashBytes ([Text.Encoding]::UTF8.GetBytes($j));Snapshot=$j}}
function Resolve-Shortcut([string]$Path){$shell=New-Object -ComObject WScript.Shell;try{$s=$shell.CreateShortcut($Path);[pscustomobject]@{TargetPath=$s.TargetPath;Arguments=[string]$s.Arguments;WorkingDirectory=[string]$s.WorkingDirectory;IconLocation=[string]$s.IconLocation;Description=[string]$s.Description;WindowStyle=$s.WindowStyle;AppUserModelId=$null}}finally{[void][Runtime.InteropServices.Marshal]::ReleaseComObject($shell)}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$sig=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidPublisher=($sig.Status-eq'Valid'-and$pub-match'(?i)Logitech|Logi')}}
function Get-StartupFolders{$folders=@([pscustomobject]@{Id='CurrentUser';Path=[Environment]::GetFolderPath([Environment+SpecialFolder]::Startup)});if(Test-Elevated){$common=[Environment]::GetFolderPath([Environment+SpecialFolder]::CommonStartup);if($common){$folders+=[pscustomobject]@{Id='AllUsers';Path=$common}}};@($folders|Where-Object{$_.Path})}
function Get-Candidates{$out=@();foreach($folder in Get-StartupFolders){if(!(Test-Path -LiteralPath $folder.Path -PathType Container)){continue};foreach($f in Get-ChildItem -LiteralPath $folder.Path -File -Filter '*.lnk' -ErrorAction SilentlyContinue){$r=Resolve-Shortcut $f.FullName;if(!$r.TargetPath){continue};$combined="$($f.Name) $($r.TargetPath) $($r.Arguments)";if($combined-match$protected-or$combined-match$unsafe){continue};$leaf=[IO.Path]::GetFileName($r.TargetPath);if($leaf-notmatch'(?i)^(lghub|lghub_agent|lghub_system_tray|lghub_updater)\.exe$'){continue};if($leaf-match'(?i)^lghub_updater\.exe$'-and$r.Arguments-match'(?i)firmware|driver|repair|install'){continue};if($r.TargetPath-notmatch'(?i)\\LGHUB\\|\\Logitech G HUB\\'){continue};$id=Get-FileIdentity $r.TargetPath;if(!$id-or!$id.ValidPublisher){continue};$bytes=[IO.File]::ReadAllBytes($f.FullName);$acl=Get-Acl -LiteralPath $f.FullName;$out+=[pscustomobject]@{KnownFolder=$folder.Id;KnownFolderPath=[IO.Path]::GetFullPath($folder.Path);Path=[IO.Path]::GetFullPath($f.FullName);Name=$f.Name;Extension=$f.Extension;BytesBase64=[Convert]::ToBase64String($bytes);Sha256=Get-HashBytes $bytes;CreationTimeUtc=$f.CreationTimeUtc.ToString('o');LastWriteTimeUtc=$f.LastWriteTimeUtc.ToString('o');Attributes=[int]$f.Attributes;Owner=$acl.Owner;Sddl=$acl.Sddl;Shortcut=$r;Target=$id;Product=[ordered]@{Name=$id.ProductName;Version=$id.FileVersion;Company=$id.CompanyName}}}};@($out)}
function Assert-Eligible($Support,[object[]]$Candidates){if(!$Support.Supported){throw 'Elevated HP Windows 11 is required.'};if($Support.Managed){throw 'Enterprise-management ownership detected.'};if($Candidates.Count-ne1){throw "Exactly one eligible Logitech G Hub Startup-folder registration is required; found $($Candidates.Count)."}}
function Save-State($Support,[object[]]$Candidates){Assert-Eligible $Support $Candidates;if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Get-ProtectedSnapshot;$s=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedScopeHash=$p.Hash;registration=$Candidates[0]};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$s|ConvertTo-Json -Depth 24|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw 'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Assert-TargetUnchanged($State){$id=Get-FileIdentity ([string]$State.registration.Target.Path);if(!$id-or!$id.ValidPublisher-or$id.Sha256-ne[string]$State.registration.Target.Sha256-or$id.FileVersion-ne[string]$State.registration.Target.FileVersion-or$id.Thumbprint-ne[string]$State.registration.Target.Thumbprint){throw 'G Hub target identity drift detected.'};$id}
function Test-Removed($State){!(Test-Path -LiteralPath ([string]$State.registration.Path))}
function Test-Restored($State){$path=[string]$State.registration.Path;if(!(Test-Path -LiteralPath $path -PathType Leaf)){return $false};$bytes=[IO.File]::ReadAllBytes($path);if((Get-HashBytes $bytes)-ne[string]$State.registration.Sha256){return $false};$r=Resolve-Shortcut $path;($r.TargetPath-eq[string]$State.registration.Shortcut.TargetPath-and$r.Arguments-eq[string]$State.registration.Shortcut.Arguments-and$r.WorkingDirectory-eq[string]$State.registration.Shortcut.WorkingDirectory-and$r.IconLocation-eq[string]$State.registration.Shortcut.IconLocation)}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
 'Check'{$c=Get-Candidates;Write-Log 'startup-folder-inventory' 'pass' @{count=$c.Count;paths=@($c.Path)};[pscustomobject]@{Support=$support;Candidates=$c;Profile=$profile}}
 'Capture'{$s=Save-State $support (Get-Candidates);Write-Log 'capture' 'pass' @{knownFolder=$s.registration.KnownFolder;sha256=$s.registration.Sha256;targetSha256=$s.registration.Target.Sha256;product=$s.registration.Product.Name;version=$s.registration.Product.Version};$s}
 'DryRun'{$c=Get-Candidates;Assert-Eligible $support $c;$r=[pscustomobject]@{Profile=$profile;WouldChange=$true;MutationCount=1;KnownFolder=$c[0].KnownFolder;Path=$c[0].Path;FromPresent=$true;ToPresent=$false;ByteExactRollback=$true;PreserveInstallation=$true;PreserveServices=$true;PreserveScheduledTasks=$true;PreserveRunRegistrations=$true;PreserveStartupTasks=$true;PreserveDevicesAndDrivers=$true;RebootPersistenceCheckRequired=$true};Write-Log 'dry-run' 'pass' $r;$r}
 'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support (Get-Candidates)};Assert-TargetUnchanged $s|Out-Null;if(Test-Removed $s){Write-Log 'apply' 'idempotent' @{mutationCount=0};return [pscustomobject]@{Applied=$true;MutationCount=0}};if($support.Managed){throw 'Management ownership appeared.'};if((Get-ProtectedSnapshot).Hash-ne[string]$s.protectedScopeHash){throw 'Protected-scope drift detected.'};$bytes=[IO.File]::ReadAllBytes([string]$s.registration.Path);if((Get-HashBytes $bytes)-ne[string]$s.registration.Sha256){throw 'Startup registration drift detected.'};if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess([string]$s.registration.Path,'Remove exact Logitech G Hub Startup-folder registration')){Remove-Item -LiteralPath ([string]$s.registration.Path) -Force};if(!(Test-Removed $s)){throw 'Apply verification failed.'};Write-Log 'apply' 'pass' @{mutationCount=1;sha256=$s.registration.Sha256};[pscustomobject]@{Applied=$true;MutationCount=1}}
 'Verify'{$s=Read-State;Assert-TargetUnchanged $s|Out-Null;if(!(Test-Removed $s)){throw 'Immediate verification failed.'};Write-Log 'verify' 'pass' @{present=$false};$true}
 'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};Assert-TargetUnchanged $s|Out-Null;if(!(Test-Removed $s)){throw 'Reboot persistence failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');present=$false};$true}
 'Rollback'{$s=Read-State;Assert-TargetUnchanged $s|Out-Null;if($support.Managed){throw 'Management ownership appeared.'};if((Get-ProtectedSnapshot).Hash-ne[string]$s.protectedScopeHash){throw 'Protected-scope drift detected.'};$folder=if([string]$s.registration.KnownFolder-eq'CurrentUser'){[Environment]::GetFolderPath([Environment+SpecialFolder]::Startup)}else{[Environment]::GetFolderPath([Environment+SpecialFolder]::CommonStartup)};if([IO.Path]::GetFullPath($folder).TrimEnd('\')-ne[IO.Path]::GetFullPath([string]$s.registration.KnownFolderPath).TrimEnd('\')){throw 'Known-folder path drift detected.'};if(Test-Path -LiteralPath ([string]$s.registration.Path)){if(Test-Restored $s){Write-Log 'rollback' 'idempotent' @{mutationCount=0;restoredExactOriginal=$true};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};throw 'Rollback destination collision detected.'};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess([string]$s.registration.Path,'Restore exact captured Logitech G Hub Startup-folder registration')){[IO.File]::WriteAllBytes([string]$s.registration.Path,[Convert]::FromBase64String([string]$s.registration.BytesBase64));$item=Get-Item -LiteralPath ([string]$s.registration.Path);$item.CreationTimeUtc=[datetime]$s.registration.CreationTimeUtc;$item.LastWriteTimeUtc=[datetime]$s.registration.LastWriteTimeUtc;$item.Attributes=[IO.FileAttributes][int]$s.registration.Attributes;try{$acl=New-Object Security.AccessControl.FileSecurity;$acl.SetSecurityDescriptorSddlForm([string]$s.registration.Sddl);Set-Acl -LiteralPath ([string]$s.registration.Path) -AclObject $acl}catch{Write-Log 'rollback-metadata' 'warning' @{message=$_.Exception.Message}}};if(!(Test-Restored $s)){throw 'Exact rollback verification failed.'};Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true;sha256=$s.registration.Sha256};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
