[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',[string]$StatePath,[string]$LogPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$serviceName='LGHUBUpdaterService'
$serviceReg="HKLM:\SYSTEM\CurrentControlSet\Services\$serviceName"
function Write-Log([string]$Event,[string]$Result,[object]$Data){if($LogPath){$r=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment='EXP-055';provider='logitech-ghub-updater-service';action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($r|ConvertTo-Json -Compress -Depth 10) -Encoding UTF8}}
function Get-Support{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);$svc=Get-CimInstance Win32_Service -Filter "Name='$serviceName'" -ErrorAction SilentlyContinue;$path=if($svc){$svc.PathName}else{$null};$identity=($svc-and$svc.DisplayName-match'Logitech|G HUB'-and$path-match'(?i)lghub_updater\.exe');[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'HP|Hewlett-Packard'-and$identity);Elevated=$admin;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;Service=$svc;IdentityMatched=$identity}}
function Get-State{$svc=Get-CimInstance Win32_Service -Filter "Name='$serviceName'" -ErrorAction Stop;$delayed=0;if(Test-Path $serviceReg){$p=Get-ItemProperty -LiteralPath $serviceReg -Name DelayedAutoStart -ErrorAction SilentlyContinue;if($p){$delayed=[int]$p.DelayedAutoStart}};[pscustomobject]@{Name=$svc.Name;DisplayName=$svc.DisplayName;PathName=$svc.PathName;StartMode=$svc.StartMode;State=$svc.State;DelayedAutoStart=$delayed}}
function Save-State($s){$o=[ordered]@{schemaVersion=1;experiment='EXP-055';provider='logitech-ghub-updater-service';machine=$env:COMPUTERNAME;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');service=$s};$o|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $StatePath -Encoding UTF8;$o}
function Read-State{if(-not(Test-Path $StatePath)){throw"State file missing: $StatePath"};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne'EXP-055'-or$s.machine-ne$env:COMPUTERNAME-or$s.service.Name-ne$serviceName){throw'State identity validation failed.'};$s}
function Assert-Safe($support,$state){if(-not$support.Elevated){throw'Elevation is required.'};if(-not$support.Supported){throw'Exact HP Windows 11 Logitech G Hub updater identity required.'};if($state.StartMode-notin@('Auto')){throw'Eligible start mode must be Automatic or Automatic Delayed Start.'}}
function Test-Applied{$s=Get-State;($s.StartMode-eq'Manual'-and$s.DelayedAutoStart-eq0)}
try{$support=Get-Support;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){'Check'{[pscustomobject]@{Support=$support;State=$(if($support.Service){Get-State}else{$null})}}'Capture'{$s=Get-State;Assert-Safe $support $s;$saved=Save-State $s;Write-Log 'capture' 'pass' $saved;$saved}'DryRun'{$s=Get-State;if((Test-Path $StatePath)-and(Test-Applied)){[void](Read-State);$r=[pscustomobject]@{WouldChange=$false;AlreadyApplied=$true}}else{Assert-Safe $support $s;$r=[pscustomobject]@{WouldChange=$true;Service=$serviceName;TargetStartMode='Manual';PreserveRunningState=$true}};Write-Log 'dry-run' 'pass' $r;$r}'Apply'{if(Test-Path $StatePath){[void](Read-State);if(Test-Applied){Write-Log 'apply' 'pass' @{changed=$false};return [pscustomobject]@{Applied=$true;MutationCount=0}}else{$s=Get-State;Assert-Safe $support $s;[void](Save-State $s)};if($PSCmdlet.ShouldProcess($serviceName,'Set startup type to Manual')){& sc.exe config $serviceName start= demand|Out-Null;New-ItemProperty -LiteralPath $serviceReg -Name DelayedAutoStart -PropertyType DWord -Value 0 -Force|Out-Null};if(-not(Test-Applied)){throw'Apply verification failed.'};Write-Log 'apply' 'pass' @{changed=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}'Verify'{$ok=Test-Applied;Write-Log 'verify' $(if($ok){'pass'}else{'fail'}) (Get-State);if(-not$ok){throw'Verification failed.'};$true}'VerifyReboot'{$ok=Test-Applied;Write-Log 'verify-reboot' $(if($ok){'pass'}else{'fail'}) @{state=Get-State;bootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime};if(-not$ok){throw'Reboot persistence verification failed.'};$true}'Rollback'{$saved=Read-State;$cur=Get-State;if(-not($cur.StartMode-eq'Manual'-and$cur.DelayedAutoStart-eq0)){throw'Rollback refused because service configuration drifted.'};$target=if($saved.service.StartMode-eq'Auto'){'auto'}else{'demand'};if($PSCmdlet.ShouldProcess($serviceName,'Restore exact startup and running state')){& sc.exe config $serviceName start= $target|Out-Null;New-ItemProperty -LiteralPath $serviceReg -Name DelayedAutoStart -PropertyType DWord -Value ([int]$saved.service.DelayedAutoStart) -Force|Out-Null;if($saved.service.State-eq'Running' -and (Get-Service $serviceName).Status-ne'Running'){Start-Service $serviceName};if($saved.service.State-ne'Running' -and (Get-Service $serviceName).Status-eq'Running'){Stop-Service $serviceName}};$after=Get-State;$ok=($after.StartMode-eq$saved.service.StartMode-and$after.DelayedAutoStart-eq[int]$saved.service.DelayedAutoStart-and$after.State-eq$saved.service.State);Write-Log 'rollback' $(if($ok){'pass'}else{'fail'}) @{restoredExactOriginal=$ok};if(-not$ok){throw'Rollback verification failed.'};[pscustomobject]@{RolledBack=$true;MutationCount=1}}}}catch{Write-Log 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
