[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-080-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-080.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-080';$Provider='logitech-download-assistant-scheduled-demand-launch'
function Log([string]$Event,[string]$Result,$Data){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 30|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Same($a,$b){($a|ConvertTo-Json -Compress -Depth 30)-eq($b|ConvertTo-Json -Compress -Depth 30)}
function HashText([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','')}finally{$sha.Dispose()}}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=$ccm}}
function FileIdentity([string]$Path){if(!$Path-or!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$s=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Name=$f.Name;Version=$f.VersionInfo.FileVersion;Product=$f.VersionInfo.ProductName;Company=$f.VersionInfo.CompanyName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;Signature=$s.Status.ToString();Publisher=$pub;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidLogitech=($s.Status-eq'Valid'-and$pub-match'(?i)Logitech|Logi')}}
function ResolvePayload($Task){$a=@($Task.Actions);if($a.Count-ne1){return $null};$exe=[Environment]::ExpandEnvironmentVariables([string]$a[0].Execute);$args=[Environment]::ExpandEnvironmentVariables([string]$a[0].Arguments);$candidate=$null;if($exe-match'(?i)rundll32\.exe$' -and$args-match'(?i)(?<dll>[A-Z]:\\[^,\"]*LogiLDA\.dll)'){$candidate=$Matches.dll}elseif($exe-match'(?i)logi(?:tech)?.*(download|assistant|lda).*\.exe$'){$candidate=$exe};if(!$candidate){return $null};$id=FileIdentity $candidate;if(!$id-or!$id.ValidLogitech){return $null};[pscustomobject]@{Execute=$exe;Arguments=$args;WorkingDirectory=[string]$a[0].WorkingDirectory;Payload=$id}}
function Protected{$services=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName;$drivers=@(Get-CimInstance Win32_SystemDriver -ErrorAction SilentlyContinue|Where-Object{$_.Name-match'(?i)logi|logitech'-or$_.PathName-match'(?i)logi|logitech'}|Sort-Object Name|Select-Object Name,State,StartMode,PathName);[pscustomobject]@{Services=@($services);LogitechDrivers=$drivers}}
function TaskState($Task){$xml=Export-ScheduledTask -TaskName $Task.TaskName -TaskPath $Task.TaskPath;$p=ResolvePayload $Task;$triggers=@($Task.Triggers|ForEach-Object{[pscustomobject]@{CimClass=$_.CimClass.CimClassName;Enabled=$_.Enabled;StartBoundary=$_.StartBoundary;UserId=$_.UserId}});[pscustomobject]@{TaskName=$Task.TaskName;TaskPath=$Task.TaskPath;State=$Task.State.ToString();Enabled=[bool]$Task.Settings.Enabled;AllowDemandStart=[bool]$Task.Settings.AllowDemandStart;Author=[string]$Task.Author;Description=[string]$Task.Description;PrincipalUserId=[string]$Task.Principal.UserId;PrincipalLogonType=[string]$Task.Principal.LogonType;PrincipalRunLevel=[string]$Task.Principal.RunLevel;Actions=@($Task.Actions|Select-Object Execute,Arguments,WorkingDirectory);Triggers=$triggers;Xml=$xml;XmlSha256=HashText $xml;Payload=$p}}
function Candidates{$out=@();foreach($t in @(Get-ScheduledTask -ErrorAction SilentlyContinue)){if("$($t.TaskPath)$($t.TaskName)$($t.Description)"-notmatch'(?i)logi(?:tech)?.*(download|assistant|lda)|logilda'){continue};$s=TaskState $t;if(!$s.Payload){continue};if(!$s.AllowDemandStart){continue};$auto=@($s.Triggers|Where-Object{$_.CimClass-match'(?i)LogonTrigger|BootTrigger'});if($auto.Count-lt1){continue};$out+=$s};@($out)}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Management;$c=@(Candidates);$r=@();if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required'};if(!(Elevated)){$r+='elevation required'};if($m.Managed){$r+='enterprise management ownership detected'};if($c.Count-ne1){$r+="exactly one eligible Logitech Download Assistant scheduled task required; found $($c.Count)"};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Management=$m;Candidates=$c;Protected=Protected;EvidenceStatus='needs-evidence'}}
function Save($s){if(!$s.Supported){throw($s.Reasons-join'; ')};if(Test-Path $StatePath){throw'State overwrite refused.'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$x=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;candidate=$s.Candidates[0];protected=$s.Protected;evidenceStatus='needs-evidence'};$x|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $StatePath -Encoding UTF8;$x}
function Load{if(!(Test-Path $StatePath)){throw'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw'State identity mismatch.'};$s}
function Current($s){$t=Get-ScheduledTask -TaskName ([string]$s.candidate.TaskName) -TaskPath ([string]$s.candidate.TaskPath) -ErrorAction Stop;TaskState $t}
function AssertIdentity($s){$c=Current $s;if(!$c.Payload-or$c.Payload.Sha256-ne[string]$s.candidate.Payload.Sha256-or$c.Payload.Thumbprint-ne[string]$s.candidate.Payload.Thumbprint){throw'Logitech payload identity drift detected.'};if($c.TaskName-ne[string]$s.candidate.TaskName-or$c.TaskPath-ne[string]$s.candidate.TaskPath){throw'Task identity drift detected.'};if(!(Same (Protected) $s.protected)){throw'Protected security update remote-access or Logitech driver state drift detected.'};$c}
function DefinitionWithoutEnabled($x){[pscustomobject]@{TaskName=$x.TaskName;TaskPath=$x.TaskPath;AllowDemandStart=$x.AllowDemandStart;Author=$x.Author;Description=$x.Description;PrincipalUserId=$x.PrincipalUserId;PrincipalLogonType=$x.PrincipalLogonType;PrincipalRunLevel=$x.PrincipalRunLevel;Actions=$x.Actions;Triggers=$x.Triggers;Payload=$x.Payload}}
try{$sup=Support;Log 'support-detection' $(if($sup.Supported){'pass'}else{'refused'}) $sup;switch($Action){
'Check'{$sup}
'Capture'{$s=Save $sup;Log 'capture' 'pass' @{taskPath=$s.candidate.TaskPath;taskName=$s.candidate.TaskName;xmlSha256=$s.candidate.XmlSha256};$s}
'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join'; ')};$c=$sup.Candidates[0];$r=[pscustomobject]@{WouldChange=[bool]$c.Enabled;MutationCount=$(if($c.Enabled){1}else{0});TaskPath=$c.TaskPath;TaskName=$c.TaskName;Treatment='disable exact Logitech Download Assistant scheduled auto-launch task';PreserveApplication=$true;PreserveDrivers=$true;PreserveProtectedScope=$true;ManualApplicationLaunchValidation='needs-evidence';RebootPersistenceRequired=$true;Rollback='restore exact captured Enabled state after task-definition, payload, and protected-state drift checks';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $r;$r}
'Apply'{$s=Load;$c=AssertIdentity $s;if(!(Same (DefinitionWithoutEnabled $c) (DefinitionWithoutEnabled $s.candidate))){throw'Task definition drift detected.'};if(!$c.Enabled){Log 'apply' 'idempotent' @{mutationCount=0};return[pscustomobject]@{Applied=$true;MutationCount=0}};if($WhatIfPreference){Log 'apply' 'whatif' @{mutationCount=0};return[pscustomobject]@{Applied=$false;MutationCount=0;WhatIf=$true}};if($PSCmdlet.ShouldProcess("$($c.TaskPath)$($c.TaskName)",'Disable exact Logitech Download Assistant scheduled startup task')){Disable-ScheduledTask -TaskName $c.TaskName -TaskPath $c.TaskPath|Out-Null}else{return};$a=Current $s;if($a.Enabled){throw'Apply verification failed.'};if(!(Same (DefinitionWithoutEnabled $a) (DefinitionWithoutEnabled $s.candidate))){throw'Task definition changed beyond Enabled state.'};AssertIdentity $s|Out-Null;Log 'apply' 'pass' @{mutationCount=1};[pscustomobject]@{Applied=$true;MutationCount=1}}
'Verify'{$s=Load;$c=AssertIdentity $s;if($c.Enabled){throw'Treatment task remains enabled.'};if(!(Same (DefinitionWithoutEnabled $c) (DefinitionWithoutEnabled $s.candidate))){throw'Task definition drift detected.'};Log 'verify' 'pass' @{enabled=$false;manualApplicationLaunch='needs-evidence'};$true}
'VerifyReboot'{$s=Load;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw'A later boot is required.'};$c=AssertIdentity $s;if($c.Enabled){throw'Treatment failed reboot persistence.'};if(!(Same (DefinitionWithoutEnabled $c) (DefinitionWithoutEnabled $s.candidate))){throw'Task definition drift detected after reboot.'};Log 'verify-reboot' 'pass' @{boot=$b.ToString('o');enabled=$false;deviceReadiness='needs-evidence';manualApplicationLaunch='needs-evidence'};$true}
'Rollback'{$s=Load;$c=AssertIdentity $s;if(!(Same (DefinitionWithoutEnabled $c) (DefinitionWithoutEnabled $s.candidate))){throw'Rollback refused on task definition drift.'};$want=[bool]$s.candidate.Enabled;if($c.Enabled-eq$want){Log 'rollback' 'idempotent' @{mutationCount=0};return[pscustomobject]@{RolledBack=$true;MutationCount=0}};if($WhatIfPreference){Log 'rollback' 'whatif' @{mutationCount=0};return[pscustomobject]@{RolledBack=$false;MutationCount=0;WhatIf=$true}};if($PSCmdlet.ShouldProcess("$($c.TaskPath)$($c.TaskName)",'Restore exact captured scheduled-task Enabled state')){if($want){Enable-ScheduledTask -TaskName $c.TaskName -TaskPath $c.TaskPath|Out-Null}else{Disable-ScheduledTask -TaskName $c.TaskName -TaskPath $c.TaskPath|Out-Null}}else{return};$a=Current $s;if($a.Enabled-ne$want-or!(Same (DefinitionWithoutEnabled $a) (DefinitionWithoutEnabled $s.candidate))){throw'Exact rollback verification failed.'};AssertIdentity $s|Out-Null;Log 'rollback' 'pass' @{mutationCount=1;restoredEnabled=$want;definitionPreserved=$true};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Log 'failure' 'failure' @{stage=$Action;message=$_.Exception.Message;evidenceStatus='needs-evidence'};throw}
