[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
    [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
    [string]$StatePath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-050'
$provider='logi-options-plus-run'
$runPath='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$protectedPattern='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|securityhealth|defender|credential|bitlocker|firewall|windows update|recovery|accessibility|driver|firmware|receiver|bluetooth|intune|sccm|configmgr|mdm'
function Write-ProviderLog([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$r=[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;data=$Data};Add-Content -LiteralPath $LogPath -Value ($r|ConvertTo-Json -Compress -Depth 12) -Encoding UTF8}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$s=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)};[pscustomobject]@{Managed=($s.DomainJoined-or$s.MdmEnrollments-gt0-or$s.PolicyManager-or$s.ConfigMgr);Signals=$s}}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$mgmt=Get-ManagementState;[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard');OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;Managed=$mgmt.Managed;ManagementSignals=$mgmt.Signals}}
function Resolve-Executable([string]$Command){$x=[Environment]::ExpandEnvironmentVariables($Command).Trim();if($x-match'^\s*"([^"]+\.exe)"'){$p=$matches[1]}elseif($x-match'^\s*([^\s]+\.exe)'){$p=$matches[1]}else{return $null};try{[IO.Path]::GetFullPath($p)}catch{$null}}
function Test-CommandIdentity([string]$Name,[string]$Command,[string]$Executable){$identity=$Name+' '+$Command+' '+$Executable;if($identity-match$protectedPattern){return $false};$nameOk=$Name-match'(?i)^(Logi Options\+|LogiOptionsPlus|Logitech Options\+|Logi Options Plus)$';$exeOk=[IO.Path]::GetFileName($Executable)-match'(?i)^(logioptionsplus_agent|logioptionsplus|logioptionsplus_appbroker)\.exe$';$pathOk=$Executable-match'(?i)\\Logi(?:tech)?\\.*Options\+|\\LogiOptionsPlus\\';$launchOk=$Command-match'(?i)(?:^|\s)(--background|--minimized|--startup|--tray|--silent|/background|/minimized|/startup|/tray|/silent)(?:\s|$)';$refused=$Command-match'(?i)updater|update\.exe|logioptionsplus_updater|uninstall|repair|firmware';$nameOk-and$exeOk-and$pathOk-and$launchOk-and!$refused}
function Get-Publisher([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$sig=Get-AuthenticodeSignature -LiteralPath $Path;$subject=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Status=$sig.Status.ToString();Subject=$subject;Valid=($sig.Status-eq'Valid'-and$subject-match'(?i)Logitech|Logi')}}
function Get-Candidates{if(!(Test-Path -LiteralPath $runPath)){return @()};$key=Get-Item -LiteralPath $runPath;$items=foreach($name in $key.GetValueNames()){$data=[string]$key.GetValue($name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$exe=Resolve-Executable $data;if($exe-and(Test-CommandIdentity $name $data $exe)){$pub=Get-Publisher $exe;if($pub-and$pub.Valid){[pscustomobject]@{Path=$runPath;Name=$name;Kind=$key.GetValueKind($name).ToString();Data=$data;Executable=$exe;ExecutableHash=(Get-FileHash -LiteralPath $exe -Algorithm SHA256).Hash;ExecutableVersion=(Get-Item -LiteralPath $exe).VersionInfo.FileVersion;PublisherStatus=$pub.Status;PublisherSubject=$pub.Subject}}}};@($items)}
function Assert-One([object[]]$Candidates){if($Candidates.Count-eq0){throw'No eligible Logi Options+ Run registration was found.'};if($Candidates.Count-gt1){throw'Multiple eligible Logi Options+ Run registrations were found.'}}
function Save-State([object[]]$Candidates){Assert-One $Candidates;if([string]::IsNullOrWhiteSpace($StatePath)){throw'StatePath is required.'};$s=[ordered]@{schemaVersion=1;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;entry=$Candidates[0]};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$s|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw"State file missing: $StatePath"};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw'State identity validation failed.'};$s}
function Test-Removed($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $true};$k=Get-Item -LiteralPath $State.entry.Path;!($k.GetValueNames()-contains[string]$State.entry.Name)}
function Test-Restored($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $false};$k=Get-Item -LiteralPath $State.entry.Path;if(!($k.GetValueNames()-contains[string]$State.entry.Name)){return $false};$d=[string]$k.GetValue($State.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$d-eq[string]$State.entry.Data-and$k.GetValueKind($State.entry.Name).ToString()-eq[string]$State.entry.Kind}
function Assert-EntryIdentity($Current,$Saved){foreach($f in 'Path','Name','Kind','Data','Executable','ExecutableHash','ExecutableVersion','PublisherSubject'){if([string]$Current.$f-ne[string]$Saved.$f){throw"Current registration differs from captured state: $f"}}}
try{$support=Get-SupportState;Write-ProviderLog 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;if(!$support.Supported){throw'Provider supports HP systems running Windows 11 only.'};if($support.Managed){throw'Enterprise-management signals are present; mutation is refused.'};switch($Action){
'Check'{$c=Get-Candidates;Write-ProviderLog 'candidate-inventory' 'pass' @{count=$c.Count;names=@($c.Name)};$c}
'Capture'{$s=Save-State (Get-Candidates);Write-ProviderLog 'capture' 'pass' @{path=$s.entry.Path;name=$s.entry.Name;hash=$s.entry.ExecutableHash};$s}
'DryRun'{$c=Get-Candidates;Assert-One $c;Write-ProviderLog 'dry-run' 'pass' @{path=$c[0].Path;name=$c[0].Name;executable=$c[0].Executable};[pscustomobject]@{Provider=$provider;WouldChange=$true;WouldRemove=$c[0];RebootPersistenceCheckRequired=$true}}
'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State (Get-Candidates)};if(Test-Removed $s){Write-ProviderLog 'apply' 'idempotent' @{path=$s.entry.Path;name=$s.entry.Name};return [pscustomobject]@{Provider=$provider;Applied=$true;MutationCount=0}};$c=Get-Candidates;Assert-One $c;Assert-EntryIdentity $c[0] $s.entry;if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Remove Logi Options+ startup registration')){Remove-ItemProperty -LiteralPath $s.entry.Path -Name $s.entry.Name};if(!(Test-Removed $s)){throw'Apply verification failed.'};Write-ProviderLog 'apply' 'pass' @{removed=1};[pscustomobject]@{Provider=$provider;Applied=$true;MutationCount=1}}
'Verify'{$s=Read-State;$ok=Test-Removed $s;Write-ProviderLog 'verify' $(if($ok){'pass'}else{'fail'}) @{};if(!$ok){throw'Removal verification failed.'};$true}
'VerifyReboot'{$s=Read-State;$ok=Test-Removed $s;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime;Write-ProviderLog 'verify-reboot' $(if($ok){'pass'}else{'fail'}) @{bootTime=$boot};if(!$ok){throw'Reboot persistence verification failed.'};$true}
'Rollback'{$s=Read-State;if(!(Test-Removed $s)){throw'Rollback refused because the registration already exists.'};if(!(Test-CommandIdentity $s.entry.Name $s.entry.Data $s.entry.Executable)){throw'Rollback command identity validation failed.'};$pub=Get-Publisher ([string]$s.entry.Executable);if(!$pub-or!$pub.Valid-or$pub.Subject-ne[string]$s.entry.PublisherSubject){throw'Rollback publisher identity validation failed.'};if((Get-FileHash -LiteralPath $s.entry.Executable -Algorithm SHA256).Hash-ne[string]$s.entry.ExecutableHash){throw'Rollback executable hash validation failed.'};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Restore exact Logi Options+ startup registration')){if(!(Test-Path -LiteralPath $s.entry.Path)){New-Item -Path $s.entry.Path -Force|Out-Null};(Get-Item -LiteralPath $s.entry.Path).SetValue([string]$s.entry.Name,[string]$s.entry.Data,[Microsoft.Win32.RegistryValueKind]::$($s.entry.Kind))};if(!(Test-Restored $s)){throw'Rollback verification failed.'};Write-ProviderLog 'rollback' 'pass' @{restored=1};[pscustomobject]@{Provider=$provider;RolledBack=$true;MutationCount=1}}
}}catch{Write-ProviderLog 'failure' 'fail' @{message=$_.Exception.Message;type=$_.Exception.GetType().FullName};throw}
