[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-085-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-085.jsonl",
 [string]$OfflineInstaller,
 [string]$InstallerArguments='/S'
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-085';$ProviderVersion='1.0.0'
$UninstallRoots=@('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*')
$ProtectedServices=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')
function Sid{[Security.Principal.WindowsIdentity]::GetCurrent().User.Value}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Log([string]$Phase,[string]$Result,$Data,[int]$MutationCount=0){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;providerVersion=$ProviderVersion;machine=$env:COMPUTERNAME;userSid=Sid;action=$Action;phase=$Phase;result=$Result;mutationCount=$MutationCount;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Products{@(foreach($r in $UninstallRoots){Get-ItemProperty $r -ErrorAction SilentlyContinue|Where-Object{$_.DisplayName -match '^(Logitech Gaming Software|Logitech Gaming Software [0-9].*)$' -and $_.Publisher -match '^(Logitech|Logi)(\s|$)' -and ($_.QuietUninstallString -or $_.UninstallString)}|ForEach-Object{[pscustomobject]@{DisplayName=$_.DisplayName;DisplayVersion=$_.DisplayVersion;Publisher=$_.Publisher;ProductCode=$_.PSChildName;InstallLocation=$_.InstallLocation;UninstallString=$_.UninstallString;QuietUninstallString=$_.QuietUninstallString;RegistryPath=$_.PSPath;Architecture=if($_.PSPath-match'WOW6432Node'){'x86'}else{'x64'}}}})}
function Signature([string]$Path){if(!$Path-or!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$s=Get-AuthenticodeSignature -LiteralPath $Path;[pscustomobject]@{Path=$f.FullName;Size=$f.Length;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductVersion=$f.VersionInfo.ProductVersion;Status=$s.Status.ToString();Publisher=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidLogitech=($s.Status-eq'Valid'-and$s.SignerCertificate-and$s.SignerCertificate.Subject-match'(?i)(Logitech|Logi)')}}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)}}
function PendingReboot{[bool]((Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'))}
function Protected{$rows=@($ProtectedServices|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName);[pscustomobject]@{Services=$rows}}
function ParseCommand([string]$Command){if([string]::IsNullOrWhiteSpace($Command)){throw 'Uninstall command missing.'};if($Command-match'(?i)(powershell|pwsh|cmd\.exe|wscript|cscript|pnputil|devcon|dism|firmware|flash|remove-pnpdevice|disable-pnpdevice|driverstore|\*|\?|&&|\|\||\||>|<)'){throw 'Unsafe uninstall command refused.'};if($Command-match'(?i)msiexec(?:\.exe)?\s+.*?({[0-9A-F-]{36}})'){return [pscustomobject]@{FilePath='msiexec.exe';Arguments="/x $($Matches[1]) /qn /norestart"}};if($Command-match'^\s*"([^"]+)"\s*(.*)$'){return [pscustomobject]@{FilePath=$Matches[1];Arguments=$Matches[2]}};$p=$Command -split '\s+',2;[pscustomobject]@{FilePath=$p[0];Arguments=if($p.Count-gt1){$p[1]}else{''}}}
function ProductSnapshot($p){$inv=ParseCommand (if($p.QuietUninstallString){$p.QuietUninstallString}else{$p.UninstallString});$procs=@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{$_.ExecutablePath -and$p.InstallLocation-and$_.ExecutablePath.StartsWith($p.InstallLocation,[StringComparison]::OrdinalIgnoreCase)}|Select-Object Name,ProcessId,ExecutablePath);$svcs=@(Get-CimInstance Win32_Service -ErrorAction SilentlyContinue|Where-Object{$_.PathName -and$p.InstallLocation-and$_.PathName -match [regex]::Escape($p.InstallLocation)}|Select-Object Name,DisplayName,State,StartMode,StartName,PathName);$runs=@(foreach($path in 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run','HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce','HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce'){if(Test-Path $path){$k=Get-Item $path;foreach($n in $k.GetValueNames()){$v=$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);if($p.InstallLocation-and[string]$v -match [regex]::Escape($p.InstallLocation)){[pscustomobject]@{Path=$path;Name=$n;Kind=$k.GetValueKind($n).ToString();Data=$v}}}}});[pscustomobject]@{Product=$p;Invocation=$inv;Processes=$procs;Services=$svcs;RunRegistrations=$runs}}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$p=Products;$m=Management;$installer=Signature $OfflineInstaller;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required'};if(!(Elevated)){$reasons+='elevation required'};if($p.Count-ne1){$reasons+='exactly one Logitech Gaming Software product required'};if($m.Managed){$reasons+='enterprise management ownership detected'};if(PendingReboot){$reasons+='pending reboot detected'};if(!$installer-or!$installer.ValidLogitech){$reasons+='signed Logitech rollback installer required'};if($p.Count-eq1-and$installer){$pv=[string]$p[0].DisplayVersion;$iv=[string]$installer.ProductVersion;if($pv-and$iv-and!($iv.StartsWith($pv)-or$pv.StartsWith($iv))){$reasons+='rollback installer version mismatch'}};if($InstallerArguments-match'(?i)(powershell|cmd\.exe|pnputil|devcon|dism|\*|&&|\|\||\||>|<)'){$reasons+='unsafe installer arguments'};[pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=Elevated;Products=$p;Management=$m;PendingReboot=PendingReboot;Installer=$installer;Protected=Protected;EvidenceStatus='needs-evidence'}}
function Save($s){if(Test-Path $StatePath){throw 'State overwrite refused.'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$snap=ProductSnapshot $s.Products[0];$x=[ordered]@{schemaVersion=1;experiment=$Experiment;providerVersion=$ProviderVersion;machine=$env:COMPUTERNAME;userSid=Sid;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');support=$s;original=$snap;installer=[ordered]@{path=$OfflineInstaller;arguments=$InstallerArguments;identity=$s.Installer};protected=$s.Protected;evidenceStatus='needs-evidence'};$x|ConvertTo-Json -Depth 24|Set-Content -LiteralPath $StatePath -Encoding UTF8;$x}
function Load{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.providerVersion-ne$ProviderVersion-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne(Sid)){throw 'State identity validation failed.'};$s}
function Removed{(Products).Count-eq0}
function Drift($s){if((Management).Managed){throw 'Management ownership drift detected.'};if(PendingReboot){throw 'Pending reboot drift detected.'};if(!((Protected|ConvertTo-Json -Compress -Depth 12)-eq($s.protected|ConvertTo-Json -Compress -Depth 12))){throw 'Protected service state drift detected.'};if(!(Test-Path -LiteralPath $s.installer.path -PathType Leaf)){throw 'Rollback installer missing.'};$i=Signature $s.installer.path;if(!$i.ValidLogitech-or$i.Sha256-ne$s.installer.identity.Sha256-or$i.Size-ne$s.installer.identity.Size){throw 'Rollback installer identity drift detected.'}}
function InvokeCaptured($inv){$p=Start-Process -FilePath $inv.FilePath -ArgumentList $inv.Arguments -Wait -PassThru;if($p.ExitCode -notin 0,1641,3010){throw "Process exited with code $($p.ExitCode)."};$p.ExitCode}
try{$support=Support;Log 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $support;switch($Action){
 'Check'{$support}
 'Capture'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$s=Save $support;Log 'capture' 'pass' @{statePath=$StatePath;product=$s.original.Product.DisplayName;version=$s.original.Product.DisplayVersion;installerSha256=$s.installer.identity.Sha256};$s}
 'DryRun'{if(!$support.Supported){throw ($support.Reasons-join'; ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Product=$support.Products[0].DisplayName;Version=$support.Products[0].DisplayVersion;UninstallMechanism='captured supported silent uninstall';RollbackInstallerSha256=$support.Installer.Sha256;PreservesDrivers=$true;RebootVerificationRequired=$true;EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $r;$r}
 'Apply'{$s=Load;Drift $s;if(Removed){Log 'apply' 'idempotent' @{removed=$true};return};$p=Products;if($p.Count-ne1-or$p[0].ProductCode-ne$s.original.Product.ProductCode-or$p[0].DisplayVersion-ne$s.original.Product.DisplayVersion){throw 'Product identity drift detected.'};if($WhatIfPreference){Log 'apply' 'whatif' @{mutationCount=0};return};if($PSCmdlet.ShouldProcess("$($p[0].DisplayName) $($p[0].DisplayVersion)",'Run captured silent uninstall')){$exit=InvokeCaptured $s.original.Invocation}else{return};if(!(Removed)){throw 'Immediate removal verification failed.'};Log 'apply' 'pass' @{exitCode=$exit;rebootRequired=($exit-in1641,3010)} 1}
 'Verify'{$s=Load;if(!(Removed)){throw 'Product remains installed.'};Log 'verify' 'pass' @{removed=$true;capturedResiduals=@{services=$s.original.Services.Count;runRegistrations=$s.original.RunRegistrations.Count};evidenceStatus='needs-evidence'};$true}
 'VerifyReboot'{$s=Load;Drift $s;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};if(!(Removed)){throw 'Removal failed reboot persistence.'};Log 'verify-reboot' 'pass' @{boot=$boot.ToString('o');removed=$true;evidenceStatus='needs-evidence'};$true}
 'Rollback'{$s=Load;Drift $s;$p=Products;if($p.Count-eq1-and$p[0].ProductCode-eq$s.original.Product.ProductCode-and$p[0].DisplayVersion-eq$s.original.Product.DisplayVersion){Log 'rollback' 'idempotent' @{mutationCount=0};return};if($p.Count-ne0){throw 'Rollback collision with another Logitech Gaming Software identity.'};if($WhatIfPreference){Log 'rollback' 'whatif' @{mutationCount=0};return};if($PSCmdlet.ShouldProcess($s.original.Product.DisplayName,'Reinstall exact captured version')){$exit=InvokeCaptured ([pscustomobject]@{FilePath=$s.installer.path;Arguments=$s.installer.arguments})}else{return};$r=Products;if($r.Count-ne1-or$r[0].ProductCode-ne$s.original.Product.ProductCode-or$r[0].DisplayVersion-ne$s.original.Product.DisplayVersion){throw 'Exact-version rollback verification failed.'};Log 'rollback' 'pass' @{exitCode=$exit;version=$r[0].DisplayVersion;rebootRequired=($exit-in1641,3010)} 1;$r[0]}
}}catch{Log 'failure' 'failure' @{refusalReason=$_.Exception.Message;failureType=$_.Exception.GetType().FullName};throw}