[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath,
 [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-125'
$issue=289
$provider='microsoft-teams-signin-task'
$profile='MicrosoftTeamsSigninTask'
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|defender|securityhealth|firewall|bitlocker|credential|windows update|recovery|intune|sccm|configmgr|mdm'
$servicing='(?i)update|updater|servic|repair|install|setup|bootstrapper|webview.*servic|edgeupdate|security|credential|accessibility|recovery|driver|firmware|officeclicktorun|windows update'
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;issue=$issue;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 28|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-TextHash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Get-TaskDefinitionHash([string]$Xml){$normalized=[regex]::Replace($Xml,'(?is)<Enabled>\s*(true|false)\s*</Enabled>','<Enabled>__EXPERIMENT_STATE__</Enabled>');Get-TextHash $normalized}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);TaskPolicy=Test-Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Task Scheduler'};[pscustomobject]@{Managed=($x.DomainJoined-or$x.MdmEnrollments-gt0-or$x.PolicyManager-or$x.ConfigMgr-or$x.TaskPolicy);Signals=$x}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard'-and(Test-Elevated));Elevated=Test-Elevated;OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Get-ProtectedSnapshot{$s=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale'){if($x=Get-Service $n -ErrorAction SilentlyContinue){[ordered]@{Name=$x.Name;Status=$x.Status.ToString();StartType=$x.StartType.ToString()}}};$p=Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.ProcessName-match'(?i)omnissa|horizon|msrdc|mstsc|tailscale'}|Sort-Object ProcessName,Id|Select-Object ProcessName,Id;$j=[ordered]@{Services=@($s);ProtectedProcesses=@($p)}|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-TextHash $j;Snapshot=$j}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$sig=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductVersion=$f.VersionInfo.ProductVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null};ValidPublisher=($sig.Status-eq'Valid'-and$pub-match'(?i)Microsoft Corporation')}}
function Get-TeamsPackages{try{@(Get-AppxPackage -Name 'MSTeams' -ErrorAction SilentlyContinue|ForEach-Object{[ordered]@{Name=$_.Name;PackageFullName=$_.PackageFullName;PackageFamilyName=$_.PackageFamilyName;Version=$_.Version.ToString();Publisher=$_.Publisher}})}catch{@()}}
function Get-Candidates{
 $packages=Get-TeamsPackages;$out=@();foreach($t in Get-ScheduledTask -ErrorAction SilentlyContinue){
  if(!$t.Settings.Enabled){continue};$xml=Export-ScheduledTask -TaskName $t.TaskName -TaskPath $t.TaskPath;if($xml-notmatch'(?i)<LogonTrigger>'){continue};$actions=@($t.Actions);if($actions.Count-ne1){continue}
  $rawExe=[string]$actions[0].Execute;$args=[string]$actions[0].Arguments;$exe=[Environment]::ExpandEnvironmentVariables($rawExe);$combined="$($t.TaskPath)$($t.TaskName) $exe $args";if($combined-match$protected-or$combined-match$servicing){continue};try{$exe=[IO.Path]::GetFullPath($exe)}catch{continue}
  $leaf=[IO.Path]::GetFileName($exe);if($leaf-notmatch'(?i)^(Teams|ms-teams|msteams)\.exe$'){continue};$id=Get-FileIdentity $exe;if(!$id-or!$id.ValidPublisher){continue};if(($id.ProductName+' '+$id.CompanyName)-notmatch'(?i)Microsoft.*Teams|Teams.*Microsoft'){continue}
  if(($args+' '+$rawExe)-match$servicing){continue};$info=Get-ScheduledTaskInfo -TaskName $t.TaskName -TaskPath $t.TaskPath
  $out+=[pscustomobject]@{TaskName=$t.TaskName;TaskPath=$t.TaskPath;Enabled=[bool]$t.Settings.Enabled;State=$t.State.ToString();Xml=$xml;XmlSha256=Get-TextHash $xml;DefinitionSha256=Get-TaskDefinitionHash $xml;TriggersXml=([regex]::Match($xml,'(?is)<Triggers>.*?</Triggers>').Value);ActionsXml=([regex]::Match($xml,'(?is)<Actions.*?</Actions>').Value);SettingsXml=([regex]::Match($xml,'(?is)<Settings>.*?</Settings>').Value);ConditionsXml=([regex]::Match($xml,'(?is)<Conditions>.*?</Conditions>').Value);RegistrationInfoXml=([regex]::Match($xml,'(?is)<RegistrationInfo>.*?</RegistrationInfo>').Value);Author=$t.Author;Principal=[ordered]@{UserId=$t.Principal.UserId;LogonType=$t.Principal.LogonType.ToString();RunLevel=$t.Principal.RunLevel.ToString()};Action=[ordered]@{Execute=$rawExe;Arguments=$actions[0].Arguments;WorkingDirectory=$actions[0].WorkingDirectory;Executable=$id};Teams=[ordered]@{ProductName=$id.ProductName;ProductVersion=$id.ProductVersion;FileVersion=$id.FileVersion;Packages=$packages};LastRunTime=$info.LastRunTime;LastTaskResult=$info.LastTaskResult;NextRunTime=$info.NextRunTime}
 };@($out)
}
function Assert-Eligible($Support,[object[]]$Candidates){if(!$Support.Supported){throw 'Elevated HP Windows 11 is required.'};if($Support.Managed){throw 'Enterprise-management ownership detected.'};if($Candidates.Count-ne1){throw "Exactly one eligible Microsoft Teams user-app sign-in task is required; found $($Candidates.Count)."}}
function Save-State($Support,[object[]]$Candidates){Assert-Eligible $Support $Candidates;if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Get-ProtectedSnapshot;$s=[ordered]@{schemaVersion=1;experiment=$experiment;issue=$issue;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedScopeHash=$p.Hash;protectedScope=$p.Snapshot;task=$Candidates[0]};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$s|ConvertTo-Json -Depth 28|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if([string]::IsNullOrWhiteSpace($StatePath)-or!(Test-Path -LiteralPath $StatePath)){throw 'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$experiment-or$s.issue-ne$issue-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Assert-DriftFree($State){$support=Get-SupportState;if($support.Managed){throw 'Management ownership appeared.'};if((Get-ProtectedSnapshot).Hash-ne[string]$State.protectedScopeHash){throw 'Protected-scope drift detected.'};$t=Get-ScheduledTask -TaskName ([string]$State.task.TaskName) -TaskPath ([string]$State.task.TaskPath) -ErrorAction SilentlyContinue;if(!$t){throw 'Captured task disappeared.'};$xml=Export-ScheduledTask -TaskName $t.TaskName -TaskPath $t.TaskPath;if((Get-TaskDefinitionHash $xml)-ne[string]$State.task.DefinitionSha256){throw 'Task-definition drift detected.'};$id=Get-FileIdentity ([string]$State.task.Action.Executable.Path);if(!$id-or!$id.ValidPublisher-or$id.Sha256-ne[string]$State.task.Action.Executable.Sha256-or$id.Thumbprint-ne[string]$State.task.Action.Executable.Thumbprint-or$id.FileVersion-ne[string]$State.task.Action.Executable.FileVersion-or$id.ProductVersion-ne[string]$State.task.Teams.ProductVersion){throw 'Microsoft Teams executable or product identity drift detected.'};$packages=Get-TeamsPackages|ConvertTo-Json -Compress -Depth 8;$captured=@($State.task.Teams.Packages)|ConvertTo-Json -Compress -Depth 8;if((Get-TextHash $packages)-ne(Get-TextHash $captured)){throw 'Microsoft Teams package identity drift detected.'};[pscustomobject]@{Task=$t;Xml=$xml;XmlSha256=Get-TextHash $xml}}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) $support;switch($Action){
 'Check'{$c=Get-Candidates;Write-Log 'task-inventory' 'pass' @{count=$c.Count;tasks=@($c|ForEach-Object{"$($_.TaskPath)$($_.TaskName)"})};[pscustomobject]@{Support=$support;Candidates=$c;Profile=$profile}}
 'Capture'{$s=Save-State $support (Get-Candidates);Write-Log 'capture' 'pass' @{task="$($s.task.TaskPath)$($s.task.TaskName)";xmlSha256=$s.task.XmlSha256;definitionSha256=$s.task.DefinitionSha256;product=$s.task.Teams.ProductName;version=$s.task.Teams.ProductVersion};$s}
 'DryRun'{$c=Get-Candidates;Assert-Eligible $support $c;$r=[pscustomobject]@{Profile=$profile;WouldChange=$true;MutationCount=1;TaskPath=$c[0].TaskPath;TaskName=$c[0].TaskName;FromEnabled=$true;ToEnabled=$false;PreserveTaskDefinition=$true;PreserveTeamsInstallation=$true;PreserveTeamsData=$true;PreserveTeamsServicing=$true;PreserveRunRegistrations=$true;PreserveStartupFolders=$true;PreserveStartupTasks=$true;PreserveServices=$true;RebootPersistenceCheckRequired=$true;Rollback='Re-enable the exact captured task after XML-definition, executable, Teams product/package, management, and protected-scope drift checks.'};Write-Log 'dry-run' 'pass' $r;$r}
 'Apply'{$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support (Get-Candidates)};$current=Assert-DriftFree $s;if(!$current.Task.Settings.Enabled){Write-Log 'apply' 'idempotent' @{mutationCount=0;before=@{enabled=$false};after=@{enabled=$false}};return [pscustomobject]@{Applied=$true;MutationCount=0}};if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0;before=@{enabled=$true};after=@{enabled=$true}};return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.task.TaskPath)$($s.task.TaskName)",'Disable exact Microsoft Teams user-app sign-in task')){Disable-ScheduledTask -TaskName ([string]$s.task.TaskName) -TaskPath ([string]$s.task.TaskPath)|Out-Null};$v=Assert-DriftFree $s;if($v.Task.Settings.Enabled){throw 'Apply verification failed.'};Write-Log 'apply' 'pass' @{mutationCount=1;before=@{enabled=$true};after=@{enabled=$false};definitionPreserved=$true};[pscustomobject]@{Applied=$true;MutationCount=1}}
 'Verify'{$s=Read-State;$current=Assert-DriftFree $s;if($current.Task.Settings.Enabled){throw 'Immediate verification failed.'};Write-Log 'verify' 'pass' @{before=@{capturedEnabled=$s.task.Enabled};after=@{enabled=$false};definitionPreserved=$true};$true}
 'VerifyReboot'{$s=Read-State;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required.'};$current=Assert-DriftFree $s;if($current.Task.Settings.Enabled){throw 'Reboot persistence failed.'};Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');before=@{capturedEnabled=$s.task.Enabled};after=@{enabled=$false};definitionPreserved=$true};$true}
 'Rollback'{$s=Read-State;$current=Assert-DriftFree $s;if($current.Task.Settings.Enabled){if($current.XmlSha256-ne[string]$s.task.XmlSha256){throw 'Rollback exact-XML verification failed.'};Write-Log 'rollback' 'idempotent' @{mutationCount=0;restoredExactOriginal=$true};return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.task.TaskPath)$($s.task.TaskName)",'Restore exact captured enabled state')){Enable-ScheduledTask -TaskName ([string]$s.task.TaskName) -TaskPath ([string]$s.task.TaskPath)|Out-Null};$v=Assert-DriftFree $s;if(!$v.Task.Settings.Enabled){throw 'Exact rollback verification failed.'};if($v.XmlSha256-ne[string]$s.task.XmlSha256){throw 'Rollback exact-XML verification failed.'};Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true;xmlVerified=$true;before=@{enabled=$false};after=@{enabled=$true}};[pscustomobject]@{RolledBack=$true;MutationCount=1}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;refusalReason=$_.Exception.Message;failureDetail=[ordered]@{message=$_.Exception.Message;type=$_.Exception.GetType().FullName;stack=$_.ScriptStackTrace}};throw}
