[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:LOCALAPPDATA\Lacksan\EXP-092-state.json",
 [string]$LogPath="$env:LOCALAPPDATA\Lacksan\EXP-092.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-092';$provider='onedrive-demand-launch'
$runPath='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$markerPath="$StatePath.applied.json"
$policyPaths=@('HKLM:\SOFTWARE\Policies\Microsoft\OneDrive','HKCU:\SOFTWARE\Policies\Microsoft\OneDrive')
$policyNames=@('KFMSilentOptIn','KFMOptInWithWizard','KFMSilentOptInWithNotification','KFMBlockOptIn','DisableFileSyncNGSC','FilesOnDemandEnabled','DisablePersonalSync','DisableLibrariesDefaultSaveToOneDrive')
function Write-Log([string]$Event,[string]$Result,[object]$Data){$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=3;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-Hash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=$en;OmadmAccounts=$om;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);RunPolicy=(Test-Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')};[pscustomobject]@{Managed=($x.DomainJoined-or$en-gt0-or$om-gt0-or$x.PolicyManager-or$x.ConfigMgr-or$x.RunPolicy);Signals=$x}}
function Get-OneDrivePolicyState{$items=@();foreach($path in $policyPaths){if(!(Test-Path -LiteralPath $path)){continue};$k=Get-Item -LiteralPath $path;foreach($n in $policyNames){if($k.GetValueNames()-contains$n){$items+=[pscustomobject]@{Path=$path;Name=$n;Kind=$k.GetValueKind($n).ToString();Value=[string]$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}}};[pscustomobject]@{Entries=@($items);PolicyOwned=($items.Count-gt0);KfmOwned=(@($items|Where-Object{$_.Name-match'^KFM'}).Count-gt0)}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$p=Get-OneDrivePolicyState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard');OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Managed=$m.Managed;ManagementSignals=$m.Signals;OneDrivePolicy=$p;EvidenceStatus='needs-evidence'}}
function Get-ProtectedSnapshot{$services=foreach($n in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$x=Get-CimInstance Win32_Service -Filter "Name='$n'" -ErrorAction SilentlyContinue;if($x){[ordered]@{Name=$x.Name;State=$x.State;StartMode=$x.StartMode;PathName=$x.PathName}}};$tasks=@(Get-ScheduledTask -ErrorAction SilentlyContinue|Where-Object{$_.TaskName-match'(?i)OneDrive'}|Sort-Object TaskPath,TaskName|ForEach-Object{[ordered]@{TaskPath=$_.TaskPath;TaskName=$_.TaskName;State=[string]$_.State;Enabled=[bool]$_.Settings.Enabled}});$j=[ordered]@{Services=@($services);OneDriveTasks=$tasks}|ConvertTo-Json -Compress -Depth 12;[pscustomobject]@{Hash=Get-Hash $j;Snapshot=$j}}
function Resolve-OneDriveCommand([string]$Command){$e=[Environment]::ExpandEnvironmentVariables($Command).Trim();$exe=$null;$args=$null;if($e-match'^\s*"(?<exe>[^"]+\\OneDrive\.exe)"\s+(?<args>.+?)\s*$'){$exe=$matches.exe;$args=$matches.args}elseif($e-match'^\s*(?<exe>[^\s]+\\OneDrive\.exe)\s+(?<args>.+?)\s*$'){$exe=$matches.exe;$args=$matches.args}else{return $null};try{$exe=[IO.Path]::GetFullPath($exe)}catch{return $null};if($exe-notmatch'(?i)\\Microsoft OneDrive\\OneDrive\.exe$' -and $exe-notmatch'(?i)\\Microsoft\\OneDrive\\OneDrive\.exe$'){return $null};if($args.Trim()-notmatch'(?i)^/background$'){return $null};[pscustomobject]@{ExpandedCommand=$e;Executable=$exe;Arguments=$args.Trim()}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$i=Get-Item -LiteralPath $Path;$s=Get-AuthenticodeSignature -LiteralPath $Path;$p=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$i.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$i.VersionInfo.FileVersion;ProductName=$i.VersionInfo.ProductName;CompanyName=$i.VersionInfo.CompanyName;SignatureStatus=$s.Status.ToString();Publisher=$p;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};ValidMicrosoftPublisher=($s.Status-eq'Valid'-and$p-match'(?i)Microsoft Corporation')}}
function Get-OneDriveAccountState{$root='HKCU:\Software\Microsoft\OneDrive\Accounts';$accounts=@();if(Test-Path -LiteralPath $root){foreach($a in @(Get-ChildItem -LiteralPath $root -ErrorAction SilentlyContinue)){$p=Get-ItemProperty -LiteralPath $a.PSPath -ErrorAction SilentlyContinue;$mount=$null;foreach($n in 'UserFolder','MountPoint'){if($p.PSObject.Properties.Name-contains$n-and$p.$n){$mount=[string]$p.$n;break}};$fod=$null;if($p.PSObject.Properties.Name-contains'FilesOnDemandEnabled'){$fod=[string]$p.FilesOnDemandEnabled};$accounts+=[pscustomobject]@{AccountKeyHash=Get-Hash $a.PSChildName;SyncRootHash=if($mount){Get-Hash $mount}else{$null};FilesOnDemandEnabled=$fod}}};$proc=@(Get-Process OneDrive -ErrorAction SilentlyContinue);[pscustomobject]@{AccountCount=$accounts.Count;Accounts=@($accounts);ProcessCount=$proc.Count;SyncHealth='needs-evidence';FilesOnDemandEvidence='needs-evidence';SensitiveIdentifiersCaptured=$false}}
function Get-Candidates{if(!(Test-Path -LiteralPath $runPath)){return @()};$k=Get-Item -LiteralPath $runPath;$out=@();foreach($n in $k.GetValueNames()){if($n-notmatch'(?i)^OneDrive$|^Microsoft OneDrive$'){continue};$d=[string]$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$r=Resolve-OneDriveCommand $d;if(!$r){continue};$id=Get-FileIdentity $r.Executable;if(!$id-or!$id.ValidMicrosoftPublisher){continue};$acl=Get-Acl -LiteralPath $runPath;$out+=[pscustomobject]@{Path=$runPath;Name=$n;Kind=$k.GetValueKind($n).ToString();Data=$d;ExpandedCommand=$r.ExpandedCommand;Executable=$id;KeyOwner=$acl.Owner;KeySddl=$acl.Sddl}};@($out)}
function Assert-Eligible($Support,[object[]]$Candidates,$AccountState){if(!$Support.Supported){throw'HP Windows 11 is required.'};if($Support.Managed){throw'Enterprise-management ownership detected.'};if($Support.OneDrivePolicy.PolicyOwned){throw'OneDrive policy ownership detected.'};if($Support.OneDrivePolicy.KfmOwned){throw'Known Folder Move policy detected.'};if($Candidates.Count-ne1){throw"Exactly one eligible OneDrive Run registration is required; found $($Candidates.Count)."};if($AccountState.AccountCount-ne1){throw"Exactly one configured OneDrive account is required for this experiment; found $($AccountState.AccountCount)."}}
function Save-State($Support,[object[]]$Candidates,$AccountState){Assert-Eligible $Support $Candidates $AccountState;if(Test-Path -LiteralPath $StatePath){throw'State overwrite refused.'};$p=Get-ProtectedSnapshot;$s=[ordered]@{schemaVersion=3;experiment=$experiment;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$Support;protectedScopeHash=$p.Hash;accountState=$AccountState;entry=$Candidates[0];evidenceStatus='needs-evidence'};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$s|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;$s}
function Read-State{if(!(Test-Path -LiteralPath $StatePath)){throw'State artifact is missing.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne3-or$s.experiment-ne$experiment-or$s.provider-ne$provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw'State identity validation failed.'};$s}
function Get-MarkerHash($State){Get-Hash ("{0}|{1}|{2}|{3}|{4}"-f$State.machine,$State.userSid,$State.entry.Path,$State.entry.Name,$State.entry.Data)}
function Write-AppliedMarker($State){[ordered]@{schemaVersion=1;experiment=$experiment;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;stateHash=Get-MarkerHash $State;appliedUtc=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json|Set-Content -LiteralPath $markerPath -Encoding UTF8}
function Test-AppliedMarker($State){if(!(Test-Path -LiteralPath $markerPath)){return $false};try{$m=Get-Content -LiteralPath $markerPath -Raw|ConvertFrom-Json;return($m.experiment-eq$experiment-and$m.machine-eq$env:COMPUTERNAME-and$m.userSid-eq[Security.Principal.WindowsIdentity]::GetCurrent().User.Value-and$m.stateHash-eq(Get-MarkerHash $State))}catch{return $false}}
function Test-Removed($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $true};!((Get-Item -LiteralPath $State.entry.Path).GetValueNames()-contains[string]$State.entry.Name)}
function Test-Restored($State){if(!(Test-Path -LiteralPath $State.entry.Path)){return $false};$k=Get-Item -LiteralPath $State.entry.Path;if(!($k.GetValueNames()-contains[string]$State.entry.Name)){return $false};$d=[string]$k.GetValue($State.entry.Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$d-eq[string]$State.entry.Data-and$k.GetValueKind($State.entry.Name).ToString()-eq[string]$State.entry.Kind}
function Assert-Executable($State){$e=Get-FileIdentity([string]$State.entry.Executable.Path);if(!$e-or!$e.ValidMicrosoftPublisher-or$e.Sha256-ne[string]$State.entry.Executable.Sha256-or$e.Thumbprint-ne[string]$State.entry.Executable.Thumbprint-or$e.FileVersion-ne[string]$State.entry.Executable.FileVersion){throw'OneDrive executable identity drift detected.'}}
function Assert-AccountState($State){$a=Get-OneDriveAccountState;if($a.AccountCount-ne[int]$State.accountState.AccountCount){throw'OneDrive account-count drift detected.'};$before=@($State.accountState.Accounts|ForEach-Object{"$($_.AccountKeyHash)|$($_.SyncRootHash)|$($_.FilesOnDemandEnabled)"}|Sort-Object);$after=@($a.Accounts|ForEach-Object{"$($_.AccountKeyHash)|$($_.SyncRootHash)|$($_.FilesOnDemandEnabled)"}|Sort-Object);if(($before-join',')-ne($after-join',')){throw'OneDrive sync-root or Files On-Demand state drift detected.'}}
function Assert-RunKey($State){if(!(Test-Path -LiteralPath $State.entry.Path)){throw'Run-key drift detected; exact rollback safety cannot be established.'};$acl=Get-Acl -LiteralPath $State.entry.Path;if($acl.Owner-ne[string]$State.entry.KeyOwner-or$acl.Sddl-ne[string]$State.entry.KeySddl){throw'Run-key ACL drift detected.'}}
function Assert-Guards($State){$support=Get-SupportState;if(!$support.Supported){throw'HP Windows 11 support drift detected.'};if($support.Managed){throw'Management ownership appeared.'};if($support.OneDrivePolicy.PolicyOwned){throw'OneDrive policy ownership appeared.'};Assert-RunKey $State;Assert-Executable $State;Assert-AccountState $State;if((Get-ProtectedSnapshot).Hash-ne[string]$State.protectedScopeHash){throw'Protected security update remote-access or OneDrive task state drift detected.'}}
function Assert-Baseline($State){Assert-Guards $State;if(!(Test-Restored $State)){throw'Captured OneDrive Run registration drift detected.'};if(Test-AppliedMarker $State){throw'Unexpected applied marker exists while baseline registration is present.'}}
try{$support=Get-SupportState;Write-Log 'support-detection' $(if($support.Supported){'pass'}else{'unsupported'}) @{OS=$support.OS;Build=$support.Build;Manufacturer=$support.Manufacturer;Model=$support.Model;Managed=$support.Managed;OneDrivePolicyOwned=$support.OneDrivePolicy.PolicyOwned;EvidenceStatus='needs-evidence'};switch($Action){
'Check'{$c=Get-Candidates;$a=Get-OneDriveAccountState;Write-Log 'candidate-inventory' 'pass' @{count=$c.Count;names=@($c.Name);accountCount=$a.AccountCount;syncHealth=$a.SyncHealth};[pscustomobject]@{Support=$support;Candidates=$c;AccountState=$a;Profile='OneDriveDemandLaunch';EvidenceStatus='needs-evidence'}}
'Capture'{$a=Get-OneDriveAccountState;$s=Save-State $support (Get-Candidates) $a;Write-Log 'capture' 'pass' @{path=$s.entry.Path;name=$s.entry.Name;kind=$s.entry.Kind;accountCount=$a.AccountCount};$s}
'DryRun'{$c=Get-Candidates;$a=Get-OneDriveAccountState;Assert-Eligible $support $c $a;$r=[pscustomobject]@{Profile='OneDriveDemandLaunch';WouldChange=$true;MutationCount=1;Path=$c[0].Path;Name=$c[0].Name;PreserveInstallation=$true;PreserveAccountConfiguration=$true;PreserveSyncRoots=$true;PreserveFilesOnDemand=$true;PreserveShellIntegration=$true;PreserveUpdaterTasks=$true;RebootPersistenceCheckRequired=$true;Rollback='Restore exact captured path, value name, registry kind, and unexpanded data after policy, ACL, executable, account, and protected-state drift checks.';EvidenceStatus='needs-evidence'};Write-Log 'dry-run' 'pass' $r;$r}
'Apply'{$a=Get-OneDriveAccountState;$s=if(Test-Path -LiteralPath $StatePath){Read-State}else{Save-State $support (Get-Candidates) $a};if(Test-Removed $s){Assert-Guards $s;if(!(Test-AppliedMarker $s)){throw'OneDrive registration disappeared outside this experiment; idempotent apply refused.'};Write-Log 'apply' 'idempotent' @{mutationCount=0};return[pscustomobject]@{Applied=$true;MutationCount=0;EvidenceStatus='needs-evidence'}};Assert-Baseline $s;if($WhatIfPreference){Write-Log 'apply' 'whatif' @{mutationCount=0};return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Remove exact OneDrive background Run registration')){Remove-ItemProperty -LiteralPath $s.entry.Path -Name $s.entry.Name}else{return};if(!(Test-Removed $s)){throw'Apply verification failed.'};Write-AppliedMarker $s;Assert-Guards $s;Write-Log 'apply' 'pass' @{mutationCount=1;syncHealth='needs-evidence'};[pscustomobject]@{Applied=$true;MutationCount=1;EvidenceStatus='needs-evidence'}}
'Verify'{$s=Read-State;if(!(Test-AppliedMarker $s)){throw'Applied marker is missing.'};if(!(Test-Removed $s)){throw'Immediate verification failed.'};Assert-Guards $s;Write-Log 'verify' 'pass' @{removed=$true;syncHealth='needs-evidence'};$true}
'VerifyReboot'{$s=Read-State;if(!(Test-AppliedMarker $s)){throw'Applied marker is missing.'};$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw'A later boot is required.'};if(!(Test-Removed $s)){throw'Reboot persistence failed.'};Assert-Guards $s;Write-Log 'verify-reboot' 'pass' @{bootTime=$b.ToString('o');syncHealth='needs-evidence';evidenceStatus='needs-evidence'};$true}
'Rollback'{$s=Read-State;if(Test-Restored $s){Assert-Guards $s;if(Test-Path -LiteralPath $markerPath){Remove-Item -LiteralPath $markerPath -Force};Write-Log 'rollback' 'idempotent' @{mutationCount=0};return[pscustomobject]@{RolledBack=$true;MutationCount=0}};if(!(Test-Removed $s)){throw'Rollback overwrite refused.'};if(!(Test-AppliedMarker $s)){throw'Rollback refused because the experiment applied marker is missing.'};Assert-Guards $s;if($WhatIfPreference){Write-Log 'rollback' 'whatif' @{mutationCount=0};return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($s.entry.Path)::$($s.entry.Name)",'Restore exact OneDrive background Run registration')){$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.entry.Kind,$true);(Get-Item -LiteralPath $s.entry.Path).SetValue([string]$s.entry.Name,[string]$s.entry.Data,$kind)}else{return};if(!(Test-Restored $s)){throw'Exact rollback verification failed.'};Assert-Guards $s;Remove-Item -LiteralPath $markerPath -Force -ErrorAction SilentlyContinue;Write-Log 'rollback' 'pass' @{mutationCount=1;restoredExactOriginal=$true;syncHealth='needs-evidence'};[pscustomobject]@{RolledBack=$true;MutationCount=1;EvidenceStatus='needs-evidence'}}
}}catch{Write-Log 'failure' 'fail' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'};throw}
