[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [Parameter(Mandatory=$true)][string]$InventoryPath,
 [Parameter(Mandatory=$true)][string]$RegistrationIdentity,
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-144-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-144.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-144';$ProviderVersion='1.0.0'
$ApprovedPaths=@(
 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run',
 'HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce',
 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run',
 'HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce',
 'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Run',
 'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\RunOnce'
)
$Protected='(?i)omnissa|horizon|windowsapp|windows app|remote desktop|mstsc|msrdc|tailscale|defender|securityhealth|security health|credential|bitlocker|firewall|windows update|wuauserv|usoclient|recovery|accessibility|narrator|magnify|driver|firmware|pnputil|intune|sccm|configmgr|mdm|enrollment'
$UnsafeLauncher='(?i)(^|\\)(cmd|powershell|pwsh|wscript|cscript|rundll32|regsvr32|msiexec)\.exe$|\.ps1$|\.cmd$|\.bat$|\.vbs$|\.js$'
function Get-Sid{[Security.Principal.WindowsIdentity]::GetCurrent().User.Value}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-HashText([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$sha.Dispose()}}
function Write-Event([string]$Phase,[string]$Result,$Data,[int]$MutationCount=0){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;providerVersion=$ProviderVersion;machine=$env:COMPUTERNAME;userSid=Get-Sid;action=$Action;phase=$Phase;result=$Result;mutationCount=$MutationCount;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$en;OmadmCount=$om;ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)}}
function Get-ProtectedState{$services=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,State,StartMode,PathName);[pscustomobject]@{Services=$services}}
function Read-Inventory{if(!(Test-Path -LiteralPath $InventoryPath -PathType Leaf)){throw 'EXP-143 inventory artifact missing.'};$raw=Get-Content -LiteralPath $InventoryPath -Raw;$x=$raw|ConvertFrom-Json;if($x.experiment-ne'EXP-143'-or$x.mode-ne'read-only'-or!$x.registrations){throw 'EXP-143 inventory identity validation failed.'};[pscustomobject]@{Document=$x;Sha256=Get-HashText $raw}}
function Get-Selection{$inv=Read-Inventory;$matches=@($inv.Document.registrations|Where-Object{$_.surface-eq'Registry'-and$_.identity-eq$RegistrationIdentity});if($matches.Count-ne1){throw 'Exactly one EXP-143 registry selection is required.'};$r=$matches[0];if($r.classification-ne'priority-target'){throw 'EXP-143 selection is outside the priority-target class.'};$i=$RegistrationIdentity.LastIndexOf('::',[StringComparison]::Ordinal);if($i-lt1){throw 'Registration identity format refused.'};$path=$RegistrationIdentity.Substring(0,$i);$name=$RegistrationIdentity.Substring($i+2);if($ApprovedPaths-notcontains$path){throw 'Registry path is outside the approved Run/RunOnce allowlist.'};if([string]::IsNullOrWhiteSpace($name)-or$name-match'^[!*]'){throw 'Unsupported or special Run/RunOnce value-name semantics refused.'};[pscustomobject]@{Inventory=$inv;Record=$r;Path=$path;Name=$name}}
function Get-RegistryValue([string]$Path,[string]$Name){if(!(Test-Path -LiteralPath $Path)){return[pscustomobject]@{Present=$false;Kind=$null;Data=$null}};$k=Get-Item -LiteralPath $Path;if($k.GetValueNames()-notcontains$Name){return[pscustomobject]@{Present=$false;Kind=$null;Data=$null}};[pscustomobject]@{Present=$true;Kind=$k.GetValueKind($Name).ToString();Data=$k.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function Resolve-Command([string]$Command){if([string]::IsNullOrWhiteSpace($Command)){throw 'Startup command missing.'};$expanded=[Environment]::ExpandEnvironmentVariables($Command).Trim();$exe=$null;$args='';if($expanded-match'^\s*"(?<exe>[^"]+\.exe)"\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}elseif($expanded-match'^\s*(?<exe>\S+\.exe)\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}else{throw 'Startup command does not resolve directly to one executable.'};try{$exe=[IO.Path]::GetFullPath($exe)}catch{throw 'Startup executable path is invalid.'};if($exe-match$UnsafeLauncher){throw 'Script, shell, installer, or indirection launcher refused.'};[pscustomobject]@{Expanded=$expanded;Executable=$exe;Arguments=$args}}
function Get-ExecutableIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){throw 'Startup executable missing.'};$f=Get-Item -LiteralPath $Path;$s=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};if($s.Status-ne'Valid'-or!$pub){throw 'Unsigned or invalid startup executable refused.'};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$s.Status.ToString();Publisher=$pub;Thumbprint=$s.SignerCertificate.Thumbprint}}
function Get-CurrentEntry($sel){$v=Get-RegistryValue $sel.Path $sel.Name;if(!$v.Present){return $null};if($v.Kind-notin@('String','ExpandString')){throw 'Only REG_SZ and REG_EXPAND_SZ startup values are supported.'};$cmd=Resolve-Command ([string]$v.Data);$exe=Get-ExecutableIdentity $cmd.Executable;$identity="$($sel.Name) $($v.Data) $($exe.Path) $($exe.ProductName) $($exe.CompanyName) $($exe.Publisher)";if($identity-match$Protected){throw 'Protected startup identity refused.'};$acl=Get-Acl -LiteralPath $sel.Path;[pscustomobject]@{Path=$sel.Path;Name=$sel.Name;Kind=$v.Kind;Data=$v.Data;ExpandedCommand=$cmd.Expanded;Arguments=$cmd.Arguments;Executable=$exe;KeyOwner=$acl.Owner;KeySddl=$acl.Sddl}}
function Get-UnrelatedSnapshot([string]$SelectedPath,[string]$SelectedName){$rows=@();foreach($p in $ApprovedPaths){if(!(Test-Path -LiteralPath $p)){continue};$k=Get-Item -LiteralPath $p;foreach($n in $k.GetValueNames()|Sort-Object){if($p-eq$SelectedPath-and$n-eq$SelectedName){continue};$d=$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$text="$n $d";if($text-match$Protected){$rows+=[pscustomobject]@{Path=$p;Name=$n;Kind=$k.GetValueKind($n).ToString();Data=$d}}}};$json=@($rows|Sort-Object Path,Name)|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-HashText $json;Rows=@($rows)}}
function Get-Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;$sel=Get-Selection;$entry=Get-CurrentEntry $sel;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required'};if($m.Managed){$reasons+='enterprise management ownership detected'};if($sel.Path-like'HKLM:*'-and!(Test-Elevated)){$reasons+='elevation required for HKLM'};if(!$entry){$reasons+='selected startup registration absent'};if($entry){$orig=$sel.Record.originalState;if($orig-and(($orig.kind-and[string]$orig.kind-ne[string]$entry.Kind)-or($null-ne$orig.data-and[string]$orig.data-ne[string]$entry.Data))){$reasons+='EXP-143 inventory and current registry state differ'}};[pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Management=$m;InventorySha256=$sel.Inventory.Sha256;Selection=$sel.Record;Entry=$entry;Protected=Get-ProtectedState;EvidenceStatus='needs-evidence'}}
function Save-State($s){if(!$s.Supported){throw($s.Reasons-join'; ')};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$u=Get-UnrelatedSnapshot $s.Entry.Path $s.Entry.Name;$entryJson=$s.Entry|ConvertTo-Json -Compress -Depth 12;$x=[ordered]@{schemaVersion=1;experiment=$Experiment;providerVersion=$ProviderVersion;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=Get-Sid;inventoryPath=$InventoryPath;inventorySha256=$s.InventorySha256;registrationIdentity=$RegistrationIdentity;entry=$s.Entry;entrySnapshotSha256=Get-HashText $entryJson;management=$s.Management;protected=$s.Protected;unrelatedProtectedRunHash=$u.Hash;evidenceStatus='needs-evidence'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$x|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;$x}
function Load-State{if(!(Test-Path -LiteralPath $StatePath)){throw 'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.providerVersion-ne$ProviderVersion-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne(Get-Sid)-or$s.registrationIdentity-ne$RegistrationIdentity){throw 'State identity validation failed.'};$inv=Read-Inventory;if($inv.Sha256-ne$s.inventorySha256){throw 'EXP-143 inventory artifact drift detected.'};$s}
function Test-Removed($s){!(Get-RegistryValue ([string]$s.entry.Path) ([string]$s.entry.Name)).Present}
function Assert-Executable($s){$e=Get-ExecutableIdentity ([string]$s.entry.Executable.Path);if($e.Sha256-ne[string]$s.entry.Executable.Sha256-or$e.Thumbprint-ne[string]$s.entry.Executable.Thumbprint-or$e.Publisher-ne[string]$s.entry.Executable.Publisher){throw 'Startup executable identity drift detected.'}}
function Assert-HeldState($s){if((Get-ManagementState).Managed){throw 'Enterprise management ownership appeared.'};$p=Get-ProtectedState|ConvertTo-Json -Compress -Depth 12;if($p-ne($s.protected|ConvertTo-Json -Compress -Depth 12)){throw 'Protected service state drift detected.'};$u=Get-UnrelatedSnapshot ([string]$s.entry.Path) ([string]$s.entry.Name);if($u.Hash-ne[string]$s.unrelatedProtectedRunHash){throw 'Protected Run/RunOnce registration drift detected.'}}
function Test-Restored($s){$v=Get-RegistryValue ([string]$s.entry.Path) ([string]$s.entry.Name);$v.Present-and$v.Kind-eq[string]$s.entry.Kind-and[string]$v.Data-eq[string]$s.entry.Data}
try{$support=Get-Support;Write-Event 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $support;switch($Action){
 'Check'{$support}
 'Capture'{$s=Save-State $support;Write-Event 'capture' 'pass' @{statePath=$StatePath;registration=$RegistrationIdentity;entrySnapshotSha256=$s.entrySnapshotSha256};$s}
 'DryRun'{if(!$support.Supported){throw($support.Reasons-join'; ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Registration=$RegistrationIdentity;Path=$support.Entry.Path;Name=$support.Entry.Name;Kind=$support.Entry.Kind;Executable=$support.Entry.Executable.Path;PreserveApplication=$true;PreserveSecurity=$true;RebootPersistenceRequired=$true;Rollback='Restore exact captured value name, type, and unexpanded raw data only when the destination remains absent.';EvidenceStatus='needs-evidence'};Write-Event 'dry-run' 'pass' $r;$r}
 'Apply'{$s=Load-State;if(Test-Removed $s){Assert-Executable $s;Assert-HeldState $s;Write-Event 'apply' 'idempotent' @{registration=$RegistrationIdentity} 0;return[pscustomobject]@{Applied=$true;MutationCount=0;EvidenceStatus='needs-evidence'}};Assert-Executable $s;Assert-HeldState $s;$v=Get-RegistryValue ([string]$s.entry.Path) ([string]$s.entry.Name);if(!$v.Present-or$v.Kind-ne[string]$s.entry.Kind-or[string]$v.Data-ne[string]$s.entry.Data){throw 'Selected startup registration drift detected.'};if($WhatIfPreference){Write-Event 'apply' 'whatif' @{registration=$RegistrationIdentity} 0;return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($RegistrationIdentity,'Delete exactly one selected Run/RunOnce startup value')){Remove-ItemProperty -LiteralPath ([string]$s.entry.Path) -Name ([string]$s.entry.Name)}else{return};if(!(Test-Removed $s)){throw 'Apply verification failed.'};Assert-HeldState $s;Write-Event 'apply' 'pass' @{registration=$RegistrationIdentity} 1;[pscustomobject]@{Applied=$true;MutationCount=1;EvidenceStatus='needs-evidence'}}
 'Verify'{$s=Load-State;if(!(Test-Removed $s)){throw 'Immediate verification failed.'};Assert-Executable $s;Assert-HeldState $s;Write-Event 'verify' 'pass' @{removed=$true};$true}
 'VerifyReboot'{$s=Load-State;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootTime){throw 'A later boot is required for reboot persistence verification.'};if(!(Test-Removed $s)){throw 'Reboot persistence failed.'};Assert-Executable $s;Assert-HeldState $s;Write-Event 'verify-reboot' 'pass' @{boot=$boot.ToString('o');removed=$true;evidenceStatus='needs-evidence'};$true}
 'Rollback'{$s=Load-State;if(!(Test-Removed $s)){if(Test-Restored $s){Assert-Executable $s;Assert-HeldState $s;Write-Event 'rollback' 'idempotent' @{registration=$RegistrationIdentity} 0;return[pscustomobject]@{RolledBack=$true;MutationCount=0}};Write-Event 'rollback' 'needs-evidence' @{reason='conflicting value reappeared';registration=$RegistrationIdentity} 0;throw 'Rollback overwrite refused because a conflicting startup value exists.'};Assert-Executable $s;Assert-HeldState $s;if(([string]$s.entry.Path)-like'HKLM:*'-and!(Test-Elevated)){throw 'Elevation required for HKLM rollback.'};if($WhatIfPreference){Write-Event 'rollback' 'whatif' @{registration=$RegistrationIdentity} 0;return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($RegistrationIdentity,'Restore exact captured Run/RunOnce startup value')){if(!(Test-Path -LiteralPath ([string]$s.entry.Path))){New-Item -Path ([string]$s.entry.Path) -Force|Out-Null};$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.entry.Kind,$true);(Get-Item -LiteralPath ([string]$s.entry.Path)).SetValue([string]$s.entry.Name,$s.entry.Data,$kind)}else{return};if(!(Test-Restored $s)){throw 'Exact rollback verification failed.'};Assert-HeldState $s;Write-Event 'rollback' 'pass' @{registration=$RegistrationIdentity;restoredExactOriginal=$true} 1;[pscustomobject]@{RolledBack=$true;MutationCount=1;EvidenceStatus='needs-evidence'}}
}}catch{try{Write-Event 'failure' 'failure' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'}}catch{};throw}
