[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [Parameter(Mandatory=$true)][string]$InventoryPath,
 [Parameter(Mandatory=$true)][string]$RegistrationIdentity,
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-144-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-144.jsonl"
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$Experiment='EXP-144';$ProviderVersion='1.0.1'
$ApprovedPaths=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce','HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\RunOnce')
$Protected='(?i)omnissa|horizon|windowsapp|windows app|remote desktop|mstsc|msrdc|tailscale|defender|securityhealth|security health|credential|bitlocker|firewall|windows update|recovery|accessibility|narrator|magnify|driver|firmware|intune|sccm|configmgr|mdm|enrollment'
$Unsafe='(?i)(^|\\)(cmd|powershell|pwsh|wscript|cscript|rundll32|regsvr32|msiexec)\.exe$|\.(ps1|cmd|bat|vbs|js)$'
function Sid{[Security.Principal.WindowsIdentity]::GetCurrent().User.Value}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Hash([string]$t){$h=[Security.Cryptography.SHA256]::Create();try{($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($t))|ForEach-Object{$_.ToString('x2')})-join''}finally{$h.Dispose()}}
function Log($phase,$result,$data,[int]$mutations=0){$d=Split-Path $LogPath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;providerVersion=$ProviderVersion;machine=$env:COMPUTERNAME;userSid=Sid;action=$Action;phase=$phase;result=$result;mutationCount=$mutations;data=$data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$e=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$o=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)-or($e-gt0-and$o-gt0));DomainJoined=[bool]$c.PartOfDomain;EnrollmentCount=$e;OmadmCount=$o;ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue)}}
function ProtectedConfig{$r=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,StartMode,PathName);[pscustomobject]@{Services=$r}}
function Inventory{if(!(Test-Path $InventoryPath -PathType Leaf)){throw 'EXP-143 inventory artifact missing.'};$raw=Get-Content $InventoryPath -Raw;$x=$raw|ConvertFrom-Json;if($x.experiment-ne'EXP-143'-or$x.mode-ne'read-only'-or!$x.registrations){throw 'EXP-143 inventory identity validation failed.'};[pscustomobject]@{Document=$x;Sha256=Hash $raw}}
function Selection{$i=Inventory;$m=@($i.Document.registrations|Where-Object{$_.surface-eq'Registry'-and$_.identity-eq$RegistrationIdentity});if($m.Count-ne1){throw 'Exactly one EXP-143 registry selection is required.'};$r=$m[0];if($r.classification-ne'priority-target'){throw 'EXP-143 selection is outside the priority-target class.'};$n=$RegistrationIdentity.LastIndexOf('::',[StringComparison]::Ordinal);if($n-lt1){throw 'Registration identity format refused.'};$p=$RegistrationIdentity.Substring(0,$n);$v=$RegistrationIdentity.Substring($n+2);if($ApprovedPaths-notcontains$p){throw 'Registry path is outside the approved Run/RunOnce allowlist.'};if([string]::IsNullOrWhiteSpace($v)-or$v-match'^[!*]'){throw 'Unsupported or special Run/RunOnce value-name semantics refused.'};[pscustomobject]@{Inventory=$i;Record=$r;Path=$p;Name=$v}}
function RegValue($p,$n){if(!(Test-Path $p)){return[pscustomobject]@{Present=$false;Kind=$null;Data=$null}};$k=Get-Item $p;if($k.GetValueNames()-notcontains$n){return[pscustomobject]@{Present=$false;Kind=$null;Data=$null}};[pscustomobject]@{Present=$true;Kind=$k.GetValueKind($n).ToString();Data=$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)}}
function ResolveCommand([string]$c){if([string]::IsNullOrWhiteSpace($c)){throw 'Startup command missing.'};$x=[Environment]::ExpandEnvironmentVariables($c).Trim();if($x-match'^\s*"(?<e>[^"]+\.exe)"\s*(?<a>.*)$'){$e=$matches.e;$a=$matches.a}elseif($x-match'^\s*(?<e>\S+\.exe)\s*(?<a>.*)$'){$e=$matches.e;$a=$matches.a}else{throw 'Startup command does not resolve directly to one executable.'};try{$e=[IO.Path]::GetFullPath($e)}catch{throw 'Startup executable path is invalid.'};if($e-match$Unsafe){throw 'Script, shell, installer, or indirection launcher refused.'};[pscustomobject]@{Expanded=$x;Executable=$e;Arguments=$a}}
function FileId($p){if(!(Test-Path $p -PathType Leaf)){throw 'Startup executable missing.'};$f=Get-Item $p;$s=Get-AuthenticodeSignature $p;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};if($s.Status-ne'Valid'-or!$pub){throw 'Unsigned or invalid startup executable refused.'};[pscustomobject]@{Path=$f.FullName;Sha256=(Get-FileHash $p -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$s.Status.ToString();Publisher=$pub;Thumbprint=$s.SignerCertificate.Thumbprint}}
function Entry($s){$v=RegValue $s.Path $s.Name;if(!$v.Present){return $null};if($v.Kind-notin@('String','ExpandString')){throw 'Only REG_SZ and REG_EXPAND_SZ startup values are supported.'};$c=ResolveCommand ([string]$v.Data);$e=FileId $c.Executable;$text="$($s.Name) $($v.Data) $($e.Path) $($e.ProductName) $($e.CompanyName) $($e.Publisher)";if($text-match$Protected){throw 'Protected startup identity refused.'};$acl=Get-Acl $s.Path;[pscustomobject]@{Path=$s.Path;Name=$s.Name;Kind=$v.Kind;Data=$v.Data;ExpandedCommand=$c.Expanded;Arguments=$c.Arguments;Executable=$e;KeyOwner=$acl.Owner;KeySddl=$acl.Sddl}}
function ProtectedRunHash($selectedPath,$selectedName){$rows=@();foreach($p in $ApprovedPaths){if(!(Test-Path $p)){continue};$k=Get-Item $p;foreach($n in $k.GetValueNames()|Sort-Object){if($p-eq$selectedPath-and$n-eq$selectedName){continue};$d=$k.GetValue($n,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);if("$n $d"-match$Protected){$rows+=[pscustomobject]@{Path=$p;Name=$n;Kind=$k.GetValueKind($n).ToString();Data=$d}}}};Hash (@($rows|Sort-Object Path,Name)|ConvertTo-Json -Compress -Depth 8)}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$m=Management;$s=Selection;$e=Entry $s;$reasons=@();if($os.Caption-notmatch'Windows 11'){$reasons+='Windows 11 required'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$reasons+='HP platform required'};if($m.Managed){$reasons+='Enterprise management ownership detected'};if(($s.Path-like'HKLM:*')-and!(Elevated)){$reasons+='elevation required for HKLM'};if(!$e){$reasons+='selected startup registration absent'};if($e){$o=$s.Record.originalState;if($o-and(($o.kind-and[string]$o.kind-ne[string]$e.Kind)-or($null-ne$o.data-and[string]$o.data-ne[string]$e.Data))){$reasons+='EXP-143 inventory and current registry state differ'}};[pscustomobject]@{Supported=($reasons.Count-eq0);Reasons=$reasons;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Management=$m;InventorySha256=$s.Inventory.Sha256;Selection=$s.Record;Entry=$e;Protected=ProtectedConfig;EvidenceStatus='needs-evidence'}}
function Save($x){if(!$x.Supported){throw($x.Reasons-join'; ')};if(Test-Path $StatePath){throw 'State overwrite refused.'};$j=$x.Entry|ConvertTo-Json -Compress -Depth 12;$s=[ordered]@{schemaVersion=1;experiment=$Experiment;providerVersion=$ProviderVersion;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=Sid;inventorySha256=$x.InventorySha256;registrationIdentity=$RegistrationIdentity;entry=$x.Entry;entrySnapshotSha256=Hash $j;management=$x.Management;protected=$x.Protected;protectedRunHash=ProtectedRunHash $x.Entry.Path $x.Entry.Name;evidenceStatus='needs-evidence'};$d=Split-Path $StatePath -Parent;if($d-and!(Test-Path $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};$s|ConvertTo-Json -Depth 20|Set-Content $StatePath -Encoding UTF8;$s}
function Load{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content $StatePath -Raw|ConvertFrom-Json;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.providerVersion-ne$ProviderVersion-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne(Sid)-or$s.registrationIdentity-ne$RegistrationIdentity){throw 'State identity validation failed.'};if((Inventory).Sha256-ne$s.inventorySha256){throw 'EXP-143 inventory artifact drift detected.'};$s}
function Removed($s){!(RegValue ([string]$s.entry.Path) ([string]$s.entry.Name)).Present}
function AssertExe($s){$e=FileId ([string]$s.entry.Executable.Path);if($e.Sha256-ne[string]$s.entry.Executable.Sha256-or$e.Thumbprint-ne[string]$s.entry.Executable.Thumbprint-or$e.Publisher-ne[string]$s.entry.Executable.Publisher){throw 'Startup executable identity drift detected.'}}
function AssertHeld($s){if((Management).Managed){throw 'Enterprise management ownership appeared.'};if((ProtectedConfig|ConvertTo-Json -Compress -Depth 12)-ne($s.protected|ConvertTo-Json -Compress -Depth 12)){throw 'Protected service configuration drift detected.'};if((ProtectedRunHash ([string]$s.entry.Path) ([string]$s.entry.Name))-ne[string]$s.protectedRunHash){throw 'Protected Run/RunOnce registration drift detected.'}}
function Restored($s){$v=RegValue ([string]$s.entry.Path) ([string]$s.entry.Name);$v.Present-and$v.Kind-eq[string]$s.entry.Kind-and[string]$v.Data-eq[string]$s.entry.Data}
try{$support=Support;Log 'support-detection' $(if($support.Supported){'pass'}else{'refused'}) $support;switch($Action){
 'Check'{$support}
 'Capture'{$s=Save $support;Log 'capture' 'pass' @{statePath=$StatePath;registration=$RegistrationIdentity;entrySnapshotSha256=$s.entrySnapshotSha256};$s}
 'DryRun'{if(!$support.Supported){throw($support.Reasons-join'; ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;Registration=$RegistrationIdentity;Path=$support.Entry.Path;Name=$support.Entry.Name;Kind=$support.Entry.Kind;Executable=$support.Entry.Executable.Path;PreserveApplication=$true;PreserveSecurity=$true;RebootPersistenceRequired=$true;Rollback='Restore exact captured value name, type, and unexpanded raw data only while the destination remains absent.';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $r;$r}
 'Apply'{$s=Load;if(Removed $s){AssertExe $s;AssertHeld $s;Log 'apply' 'idempotent' @{registration=$RegistrationIdentity};return[pscustomobject]@{Applied=$true;MutationCount=0;EvidenceStatus='needs-evidence'}};AssertExe $s;AssertHeld $s;$v=RegValue ([string]$s.entry.Path) ([string]$s.entry.Name);if(!$v.Present-or$v.Kind-ne[string]$s.entry.Kind-or[string]$v.Data-ne[string]$s.entry.Data){throw 'Selected startup registration drift detected.'};if($WhatIfPreference){Log 'apply' 'whatif' @{registration=$RegistrationIdentity};return[pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($RegistrationIdentity,'Delete exactly one selected Run/RunOnce startup value')){Remove-ItemProperty -LiteralPath ([string]$s.entry.Path) -Name ([string]$s.entry.Name)}else{return};if(!(Removed $s)){throw 'Apply verification failed.'};AssertHeld $s;Log 'apply' 'pass' @{registration=$RegistrationIdentity} 1;[pscustomobject]@{Applied=$true;MutationCount=1;EvidenceStatus='needs-evidence'}}
 'Verify'{$s=Load;if(!(Removed $s)){throw 'Immediate verification failed.'};AssertExe $s;AssertHeld $s;Log 'verify' 'pass' @{removed=$true};$true}
 'VerifyReboot'{$s=Load;$b=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($b-le[datetime]$s.capturedBootTime){throw 'A later boot is required for reboot persistence verification.'};if(!(Removed $s)){throw 'Reboot persistence failed.'};AssertExe $s;AssertHeld $s;Log 'verify-reboot' 'pass' @{boot=$b.ToString('o');removed=$true;evidenceStatus='needs-evidence'};$true}
 'Rollback'{$s=Load;if(!(Removed $s)){if(Restored $s){AssertExe $s;AssertHeld $s;Log 'rollback' 'idempotent' @{registration=$RegistrationIdentity};return[pscustomobject]@{RolledBack=$true;MutationCount=0}};Log 'rollback' 'needs-evidence' @{reason='conflicting value reappeared';registration=$RegistrationIdentity};throw 'Rollback overwrite refused because a conflicting startup value exists.'};AssertExe $s;AssertHeld $s;if((([string]$s.entry.Path)-like'HKLM:*')-and!(Elevated)){throw 'Elevation required for HKLM rollback.'};if($WhatIfPreference){Log 'rollback' 'whatif' @{registration=$RegistrationIdentity};return[pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess($RegistrationIdentity,'Restore exact captured Run/RunOnce startup value')){if(!(Test-Path ([string]$s.entry.Path))){New-Item -Path ([string]$s.entry.Path) -Force|Out-Null};$kind=[Enum]::Parse([Microsoft.Win32.RegistryValueKind],[string]$s.entry.Kind,$true);(Get-Item ([string]$s.entry.Path)).SetValue([string]$s.entry.Name,$s.entry.Data,$kind)}else{return};if(!(Restored $s)){throw 'Exact rollback verification failed.'};AssertHeld $s;Log 'rollback' 'pass' @{registration=$RegistrationIdentity;restoredExactOriginal=$true} 1;[pscustomobject]@{RolledBack=$true;MutationCount=1;EvidenceStatus='needs-evidence'}}
}}catch{try{Log 'failure' 'failure' @{stage=$Action;message=$_.Exception.Message;type=$_.Exception.GetType().FullName;evidenceStatus='needs-evidence'}}catch{};throw}
