[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [ValidateSet('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')][string]$Action='Check',
 [string]$StatePath="$env:ProgramData\Lacksan\EXP-125-teams-task-state.json",
 [string]$LogPath="$env:ProgramData\Lacksan\EXP-125-teams-task-events.jsonl"
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Experiment='EXP-125';$Provider='teams-signin-scheduled-task-disable'
$ProtectedServices=@('WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale')
function Hash([string]$Text){$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','')}finally{$h.Dispose()}}
function Same($A,$B){($A|ConvertTo-Json -Compress -Depth 30)-eq($B|ConvertTo-Json -Compress -Depth 30)}
function Log([string]$Event,[string]$Result,$Before=$null,$After=$null,[string]$Reason=$null,[string]$Failure=$null){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$Experiment;provider=$Provider;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;action=$Action;event=$Event;result=$Result;before=$Before;after=$After;refusalReason=$Reason;failureDetail=$Failure;evidenceStatus='needs-evidence'}|ConvertTo-Json -Compress -Depth 30|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Management{$c=Get-CimInstance Win32_ComputerSystem;$ccm=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);$en=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;$om=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Provisioning\OMADM\Accounts' -ErrorAction SilentlyContinue|Where-Object{$_.PSChildName-match'^[0-9A-Fa-f-]{36}$'}).Count;[pscustomobject]@{Managed=([bool]$c.PartOfDomain-or$ccm-or($en-gt0-and$om-gt0));DomainJoined=[bool]$c.PartOfDomain;ConfigMgr=$ccm;EnrollmentCount=$en;OmadmCount=$om}}
function ProtectedState{@($ProtectedServices|ForEach-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}|Where-Object{$_}|Sort-Object Name|Select-Object Name,StartMode,PathName)}
function FileIdentity([string]$Path){$expanded=[Environment]::ExpandEnvironmentVariables($Path);if(!(Test-Path -LiteralPath $expanded -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $expanded;$s=Get-AuthenticodeSignature -LiteralPath $expanded;$pub=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};[pscustomobject]@{Path=$f.FullName;Name=$f.Name;Sha256=(Get-FileHash -LiteralPath $expanded -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductVersion=$f.VersionInfo.ProductVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$s.Status.ToString();Publisher=$pub;Thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null};MicrosoftSigned=($s.Status-eq'Valid'-and$pub-match'(?i)Microsoft Corporation')}}
function TeamsProducts{$a=@(Get-AppxPackage -Name MSTeams -ErrorAction SilentlyContinue|Select-Object Name,PackageFullName,PackageFamilyName,Version,Publisher);$u=@();foreach($root in @('HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*')){$u+=@(Get-ItemProperty $root -ErrorAction SilentlyContinue|Where-Object{$_.DisplayName-match'(?i)^Microsoft Teams'}|Select-Object DisplayName,DisplayVersion,Publisher,InstallLocation,PSPath)};[pscustomobject]@{Appx=$a;Uninstall=@($u)}}
function XmlParts([string]$Xml){[xml]$x=$Xml;$ns=New-Object Xml.XmlNamespaceManager($x.NameTable);$ns.AddNamespace('t',$x.DocumentElement.NamespaceURI);$enabled=$x.SelectSingleNode('//t:Settings/t:Enabled',$ns);$enabledValue=if($enabled){$enabled.InnerText}else{'true'};if($enabled){$enabled.InnerText='__LACKSAN_ENABLED_STATE__'};$normalized=$x.OuterXml;[pscustomobject]@{Enabled=($enabledValue-ne'false');DefinitionHash=Hash $normalized;LogonTrigger=($null-ne$x.SelectSingleNode('//t:Triggers/t:LogonTrigger',$ns));TriggerXml=($x.SelectSingleNode('//t:Triggers',$ns).OuterXml);PrincipalXml=($x.SelectSingleNode('//t:Principals',$ns).OuterXml);ConditionsXml=($x.SelectSingleNode('//t:Conditions',$ns).OuterXml);SettingsXml=($x.SelectSingleNode('//t:Settings',$ns).OuterXml);RegistrationInfoXml=($x.SelectSingleNode('//t:RegistrationInfo',$ns).OuterXml);Author=if($x.SelectSingleNode('//t:RegistrationInfo/t:Author',$ns)){$x.SelectSingleNode('//t:RegistrationInfo/t:Author',$ns).InnerText}else{$null}}}
function TaskSnapshot($Task){$xml=Export-ScheduledTask -TaskName $Task.TaskName -TaskPath $Task.TaskPath;$parts=XmlParts $xml;$info=Get-ScheduledTaskInfo -TaskName $Task.TaskName -TaskPath $Task.TaskPath;$actions=@($Task.Actions|ForEach-Object{[pscustomobject]@{Execute=[string]$_.Execute;Arguments=[string]$_.Arguments;WorkingDirectory=[string]$_.WorkingDirectory}});[pscustomobject]@{TaskName=$Task.TaskName;TaskPath=$Task.TaskPath;Enabled=[bool]$Task.Settings.Enabled;Xml=$xml;XmlSha256=Hash $xml;DefinitionHash=$parts.DefinitionHash;TriggerXml=$parts.TriggerXml;LogonTrigger=$parts.LogonTrigger;Actions=$actions;PrincipalXml=$parts.PrincipalXml;ConditionsXml=$parts.ConditionsXml;SettingsXml=$parts.SettingsXml;RegistrationInfoXml=$parts.RegistrationInfoXml;Author=$parts.Author;LastRunTime=$info.LastRunTime;LastTaskResult=$info.LastTaskResult;NextRunTime=$info.NextRunTime}}
function Candidates{$rows=@();foreach($t in @(Get-ScheduledTask -ErrorAction SilentlyContinue)){$acts=@($t.Actions);if($acts.Count-ne1){continue};$exe=[string]$acts[0].Execute;if($exe-notmatch'(?i)(ms-teams|teams)\.exe'){continue};if([string]$acts[0].Arguments-match'(?i)(update|install|repair|uninstall|webview|service|bootstrapper.*update)'){continue};$id=FileIdentity $exe;if(!$id-or!$id.MicrosoftSigned-or$id.Name-notmatch'(?i)^(ms-teams|teams)\.exe$'){continue};if(($id.ProductName+$id.CompanyName+$id.Path)-notmatch'(?i)(Microsoft Teams|MSTeams)'){continue};$snap=TaskSnapshot $t;if(!$snap.LogonTrigger-or!$snap.Enabled){continue};$rows+=[pscustomobject]@{Task=$snap;Executable=$id}};@($rows)}
function Support{$os=Get-CimInstance Win32_OperatingSystem;$pc=Get-CimInstance Win32_ComputerSystem;$mg=Management;$c=@(Candidates);$products=TeamsProducts;$r=@();if($os.Caption-notmatch'Windows 11'){$r+='Windows 11 required.'};if($pc.Manufacturer-notmatch'(?i)^HP$|Hewlett-Packard'){$r+='HP platform required.'};if(!(Elevated)){$r+='Elevation required.'};if($mg.Managed){$r+='Enterprise management ownership detected.'};if($c.Count-ne1){$r+='Exactly one Microsoft-signed Teams user-logon scheduled task required.'};if($products.Appx.Count-eq0-and$products.Uninstall.Count-eq0){$r+='Microsoft Teams product identity required.'};[pscustomobject]@{Supported=($r.Count-eq0);Reasons=$r;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$pc.Manufacturer;Model=$pc.Model;Elevated=(Elevated);Management=$mg;TeamsProducts=$products;Candidate=if($c.Count-eq1){$c[0]}else{$null};EvidenceStatus='needs-evidence'}}
function Save($s){if(!$s.Supported){throw($s.Reasons-join' ')};if(Test-Path $StatePath){throw 'State overwrite refused.'};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path $p)){New-Item -ItemType Directory $p -Force|Out-Null};$o=[ordered]@{schemaVersion=1;experiment=$Experiment;provider=$Provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootUtc=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;original=$s.Candidate.Task;executable=$s.Candidate.Executable;teamsProducts=$s.TeamsProducts;management=$s.Management;protectedHash=Hash((ProtectedState|ConvertTo-Json -Compress -Depth 20));evidenceStatus='needs-evidence'};$o|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $StatePath -Encoding UTF8;[pscustomobject]$o}
function Read{if(!(Test-Path $StatePath)){throw 'Captured state required.'};$s=Get-Content -LiteralPath $StatePath -Raw|ConvertFrom-Json;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($s.schemaVersion-ne1-or$s.experiment-ne$Experiment-or$s.provider-ne$Provider-or$s.machine-ne$env:COMPUTERNAME-or$s.userSid-ne$sid){throw 'State identity validation failed.'};$s}
function Current($s){$t=Get-ScheduledTask -TaskName ([string]$s.original.TaskName) -TaskPath ([string]$s.original.TaskPath) -ErrorAction SilentlyContinue;if(!$t){throw 'Scheduled-task identity drift detected.'};TaskSnapshot $t}
function Drift($s){if((Management).Managed){throw 'Management ownership drift detected.'};$now=Current $s;if($now.DefinitionHash-ne[string]$s.original.DefinitionHash){throw 'Task-definition drift detected.'};$id=FileIdentity ([string]$s.executable.Path);if(!$id-or!$id.MicrosoftSigned-or$id.Sha256-ne[string]$s.executable.Sha256-or$id.Thumbprint-ne[string]$s.executable.Thumbprint-or$id.FileVersion-ne[string]$s.executable.FileVersion){throw 'Teams executable identity drift detected.'};$tp=TeamsProducts;if(!(Same $tp $s.teamsProducts)){throw 'Teams product identity drift detected.'};if((Hash((ProtectedState|ConvertTo-Json -Compress -Depth 20)))-ne[string]$s.protectedHash){throw 'Protected configuration drift detected.'};$now}
try{$sup=Support;Log 'support-detection' $(if($sup.Supported){'pass'}else{'refused'}) $null $sup ($(if($sup.Supported){$null}else{$sup.Reasons-join' '}));switch($Action){
 'Check'{$sup}
 'Capture'{$s=Save $sup;Log 'capture' 'pass' $null $s;$s}
 'DryRun'{if(!$sup.Supported){throw($sup.Reasons-join' ')};$r=[pscustomobject]@{WouldChange=$true;MutationCount=1;TaskPath=$sup.Candidate.Task.TaskPath;TaskName=$sup.Candidate.Task.TaskName;Change='Enabled state true to false only';PreserveTeamsInstallation=$true;RebootPersistenceRequired=$true;TeamsManualLaunch='needs-evidence';TeamsMessagingOrMeetingReadiness='needs-evidence';ServicingReadiness='needs-evidence';ProtectedApplicationReadiness='needs-evidence';Rollback='Restore captured enabled state after exact task definition, executable, product, management, and protected-scope drift checks.';EvidenceStatus='needs-evidence'};Log 'dry-run' 'pass' $sup.Candidate.Task $r;$r}
 'Apply'{$s=if(Test-Path $StatePath){Read}else{Save $sup};$before=Drift $s;if(!$before.Enabled){Log 'apply' 'idempotent' $before $before;return [pscustomobject]@{Applied=$true;MutationCount=0}};if($WhatIfPreference){Log 'apply' 'whatif' $before $before;return [pscustomobject]@{Applied=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($before.TaskPath)$($before.TaskName)",'Disable one verified Microsoft Teams sign-in scheduled task')){Disable-ScheduledTask -TaskName $before.TaskName -TaskPath $before.TaskPath|Out-Null};$after=Current $s;if($after.Enabled-or$after.DefinitionHash-ne[string]$s.original.DefinitionHash){throw 'Application verification failed.'};Log 'apply' 'pass' $before $after;$after}
 'Verify'{$s=Read;$now=Drift $s;if($now.Enabled){throw 'Treatment verification failed.'};$r=[pscustomobject]@{Verified=$true;Task=$now;TeamsManualLaunch='needs-evidence';TeamsFunction='needs-evidence';ServicingReadiness='needs-evidence';ProtectedApplicationReadiness='needs-evidence'};Log 'verify' 'pass' $now $r;$r}
 'VerifyReboot'{$s=Read;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();if($boot-le[datetime]$s.capturedBootUtc){throw 'A later boot is required.'};$now=Drift $s;if($now.Enabled){throw 'Reboot persistence failed.'};$r=[pscustomobject]@{VerifiedReboot=$true;BootUtc=$boot.ToString('o');Task=$now;TeamsManualLaunch='needs-evidence';TeamsFunction='needs-evidence';ServicingReadiness='needs-evidence';ProtectedApplicationReadiness='needs-evidence'};Log 'verify-reboot' 'pass' $now $r;$r}
 'Rollback'{$s=Read;$before=Drift $s;if($before.Enabled){Log 'rollback' 'idempotent' $before $before;return [pscustomobject]@{RolledBack=$true;MutationCount=0}};if($WhatIfPreference){Log 'rollback' 'whatif' $before $before;return [pscustomobject]@{RolledBack=$false;WhatIf=$true;MutationCount=0}};if($PSCmdlet.ShouldProcess("$($before.TaskPath)$($before.TaskName)",'Restore captured Microsoft Teams scheduled-task enabled state')){Enable-ScheduledTask -TaskName $before.TaskName -TaskPath $before.TaskPath|Out-Null};$after=Current $s;if(!$after.Enabled-or$after.DefinitionHash-ne[string]$s.original.DefinitionHash){throw 'Exact rollback verification failed.'};Log 'rollback' 'pass' $before $after;$after}
}}catch{Log 'failure' 'failure' $null $null $null $_.Exception.Message;throw}
