[CmdletBinding()]
param(
    [ValidateSet('Check','Capture','Select')][string]$Action='Check',
    [string]$StatePath,
    [string]$MeasurementPath,
    [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-134'
$issue=303
$provider='generic-run-cost-inventory'
$runPaths=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run')
$protected='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|defender|securityhealth|firewall|bitlocker|credential|windows update|wuauserv|usosvc|bits|recovery|intune|sccm|configmgr|mdm|accessibility|driver|firmware'
$servicing='(?i)update|updater|servic|repair|install|setup|bootstrap|activation|licens|uninstall|device.?install|dfu|firmware'
$specific='(?i)teams|msteams|microsoft 365|microsoft office|outlook|winword|excel|powerpnt|onenote|msaccess|logitech|logi options|logioptions|logi bolt|logibolt|g hub|lghub'

function Get-TextHash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$p=Split-Path -Parent $LogPath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;issue=$issue;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 20|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$x=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);Intune=[bool](Get-Service IntuneManagementExtension -ErrorAction SilentlyContinue);RunPolicy=(Test-Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')-or(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run')};[pscustomobject]@{Managed=($x.DomainJoined-or$x.MdmEnrollments-gt0-or$x.PolicyManager-or$x.ConfigMgr-or$x.Intune-or$x.RunPolicy);Signals=$x}}
function Get-SupportState{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;[pscustomobject]@{Supported=($o.Caption-match'Windows 11'-and$c.Manufacturer-match'(?i)^HP$|Hewlett-Packard');OS=$o.Caption;Build=$o.BuildNumber;Manufacturer=$c.Manufacturer;Model=$c.Model;Elevated=Test-Elevated;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Resolve-Command([string]$Command){$expanded=[Environment]::ExpandEnvironmentVariables($Command).Trim();if($expanded-match'^\s*"(?<exe>[^"]+\.exe)"\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}elseif($expanded-match'^\s*(?<exe>\S+\.exe)\s*(?<args>.*)$'){$exe=$matches.exe;$args=$matches.args}else{return $null};try{$full=[IO.Path]::GetFullPath($exe)}catch{return $null};[pscustomobject]@{Expanded=$expanded;Executable=$full;Arguments=$args.Trim()}}
function Get-FileIdentity([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};$f=Get-Item -LiteralPath $Path;$sig=Get-AuthenticodeSignature -LiteralPath $Path;$pub=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[pscustomobject]@{PathHash=Get-TextHash $f.FullName.ToLowerInvariant();Leaf=$f.Name;Sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductVersion=$f.VersionInfo.ProductVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$pub;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null}}}
function Get-Candidates{
    $out=@();foreach($path in $runPaths){if(!(Test-Path -LiteralPath $path)){continue};$key=Get-Item -LiteralPath $path;$acl=Get-Acl -LiteralPath $path
        foreach($name in $key.GetValueNames()|Sort-Object){$kind=$key.GetValueKind($name).ToString();if($kind-notin @('String','ExpandString')){continue};$data=[string]$key.GetValue($name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames);$joined="$name $data";if($joined-match$protected-or$joined-match$servicing-or$joined-match$specific){continue};$r=Resolve-Command $data;if(!$r){continue};$id=Get-FileIdentity $r.Executable;if(!$id-or$id.SignatureStatus-ne'Valid'){continue};$identity="$path|$name|$kind|$(Get-TextHash $data)|$($id.Sha256)";$out+=[pscustomobject]@{CandidateId=Get-TextHash $identity;Path=$path;Hive=if($path-like'HKLM:*'){'HKLM'}else{'HKCU'};Name=$name;Kind=$kind;DataHash=Get-TextHash $data;ArgumentsHash=Get-TextHash ([string]$r.Arguments);Executable=$id;KeyOwner=$acl.Owner;KeySddlHash=Get-TextHash $acl.Sddl;SpecificExperimentMatch=$false;PhysicalAttribution='needs-evidence'}}};@($out)
}
function Get-Measurements{if([string]::IsNullOrWhiteSpace($MeasurementPath)-or!(Test-Path -LiteralPath $MeasurementPath)){return @()};$raw=Get-Content -LiteralPath $MeasurementPath -Raw|ConvertFrom-Json;@($raw)}
function Get-Selection($Candidates,$Measurements){$eligible=@();foreach($c in $Candidates){$m=@($Measurements|Where-Object{$_.candidateId-eq$c.CandidateId});if($m.Count-lt5){continue};$valid=@($m|Where-Object{$null-ne$_.cpuMs-and$null-ne$_.diskBytes-and$null-ne$_.workingSetBytes-and$null-ne$_.processStarts});if($valid.Count-lt5){continue};$score=($valid|Measure-Object cpuMs -Average).Average+((($valid|Measure-Object diskBytes -Average).Average)/1MB)+((($valid|Measure-Object workingSetBytes -Average).Average)/1MB)+(($valid|Measure-Object processStarts -Average).Average*10);$eligible+=[pscustomobject]@{Candidate=$c;Trials=$valid.Count;CostScore=[math]::Round([double]$score,3)}};if($eligible.Count-eq0){return $null};$eligible|Sort-Object CostScore -Descending|Select-Object -First 1}
function Get-Inventory{$s=Get-SupportState;$c=Get-Candidates;$m=Get-Measurements;$sel=Get-Selection $c $m;[pscustomobject]@{schemaVersion=1;experiment=$experiment;issue=$issue;provider=$provider;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$s;candidates=$c;candidateCount=$c.Count;measurementCount=$m.Count;selection=$sel;mutationReady=[bool]$sel;mutationGate=if($sel){'Selected candidate requires a dedicated reversible provider and physical baseline/treatment validation.'}else{'Five valid physical attribution trials per eligible candidate are required before selection.'};evidenceState='needs-evidence'}}

try{$i=Get-Inventory;Write-Log 'inventory' 'pass' @{supported=$i.support.Supported;managed=$i.support.Managed;candidateCount=$i.candidateCount;measurementCount=$i.measurementCount;mutationReady=$i.mutationReady};switch($Action){'Check'{$i}'Capture'{if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$p=Split-Path -Parent $StatePath;if($p-and!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$i|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StatePath -Encoding UTF8;Write-Log 'capture' 'pass' @{candidateCount=$i.candidateCount;mutationReady=$i.mutationReady};$i}'Select'{if(!$i.support.Supported){throw 'HP Windows 11 is required.'};if($i.support.Managed){throw 'Enterprise-management ownership detected.'};if(!$i.selection){throw 'Physical attribution remains needs-evidence.'};Write-Log 'selection' 'pass' @{candidateId=$i.selection.Candidate.CandidateId;trials=$i.selection.Trials;costScore=$i.selection.CostScore};$i.selection}}}catch{Write-Log 'failure' 'fail' @{stage=$Action;refusalReason=$_.Exception.Message;failureDetail=[ordered]@{message=$_.Exception.Message;type=$_.Exception.GetType().FullName;stack=$_.ScriptStackTrace}};throw}
