[CmdletBinding()]
param(
 [ValidateSet('Check','Capture')][string]$Action='Check',
 [string]$StatePath,
 [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-128'
$issue=295
$provider='microsoft-365-startuptask-inventory'
$profile='Microsoft365StartupTaskInventory'
$protectedPattern='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|defender|securityhealth|firewall|bitlocker|credential|windows update|recovery|intune|sccm|configmgr|mdm'
$servicingPattern='(?i)clicktorun|officeclicktorun|update|updater|servic|repair|activation|licens|setup|install|security|credential|accessibility|recovery|driver|firmware|windows update'
function Get-TextHash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Get-PathHash([string]$Path){if([string]::IsNullOrWhiteSpace($Path)){return $null};Get-TextHash ([Environment]::ExpandEnvironmentVariables($Path).ToLowerInvariant())}
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$parent=Split-Path -Parent $LogPath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;issue=$issue;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Test-Elevated{([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$signals=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);OfficePolicies=Test-Path 'HKLM:\SOFTWARE\Policies\Microsoft\Office'};[pscustomobject]@{Managed=($signals.DomainJoined-or$signals.MdmEnrollments-gt0-or$signals.PolicyManager-or$signals.ConfigMgr);Signals=$signals}}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$mgmt=Get-ManagementState;[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard');Elevated=Test-Elevated;OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;Managed=$mgmt.Managed;ManagementSignals=$mgmt.Signals}}
function Get-ProtectedSnapshot{$services=foreach($name in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale'){if($s=Get-Service $name -ErrorAction SilentlyContinue){[ordered]@{Name=$s.Name;Status=$s.Status.ToString();StartType=$s.StartType.ToString()}}};$processes=Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.ProcessName-match'(?i)omnissa|horizon|msrdc|mstsc|tailscale'}|Sort-Object ProcessName,Id|Select-Object ProcessName,Id;$json=[ordered]@{Services=@($services);ProtectedProcesses=@($processes)}|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-TextHash $json;Snapshot=$json}}
function Get-RelatedStartupState{
 $run=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce')|ForEach-Object{if(Test-Path $_){$item=Get-ItemProperty $_;[ordered]@{Path=$_;Names=@($item.PSObject.Properties|Where-Object{$_.Name-notmatch'^PS'}|Select-Object -ExpandProperty Name|Sort-Object)}}}
 $startup=@([Environment]::GetFolderPath('Startup'),[Environment]::GetFolderPath('CommonStartup'))|ForEach-Object{if($_ -and(Test-Path -LiteralPath $_)){[ordered]@{PathHash=Get-PathHash $_;Files=@(Get-ChildItem -LiteralPath $_ -Force|Sort-Object Name|ForEach-Object{[ordered]@{Name=$_.Name;Length=$_.Length;Sha256=if(!$_.PSIsContainer){(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash}else{$null}}})}}}
 $tasks=@(Get-ScheduledTask -ErrorAction SilentlyContinue|Where-Object{($_.TaskName+' '+$_.TaskPath)-match'(?i)office|microsoft 365|outlook|word|excel|powerpoint|onenote|access'}|Sort-Object TaskPath,TaskName|ForEach-Object{[ordered]@{TaskPath=$_.TaskPath;TaskName=$_.TaskName;Enabled=[bool]$_.Settings.Enabled}})
 [ordered]@{Run=@($run);StartupFolders=@($startup);ScheduledTasks=$tasks}
}
function Get-ManifestStartupTasks($Manifest){
 $out=@();$nodes=@($Manifest.Package.Applications.Application.Extensions.Extension|Where-Object{[string]$_.Category-match'(?i)windows.startupTask'});foreach($ext in $nodes){$task=$ext.StartupTask;if(!$task){continue};$exe=[string]$ext.Executable;$entry=[string]$ext.EntryPoint;$taskId=[string]$task.TaskId;$display=[string]$task.DisplayName;$combined="$taskId $display $exe $entry";$out+=[pscustomobject]@{TaskId=$taskId;DisplayName=$display;ExecutableLeaf=if($exe){[IO.Path]::GetFileName($exe)}else{$null};ExecutablePathHash=Get-PathHash $exe;EntryPoint=$entry;ManifestEnabled=[string]$task.Enabled;ServicingIdentity=($combined-match$servicingPattern);ProtectedIdentity=($combined-match$protectedPattern)}};@($out)
}
function Get-Microsoft365Packages{
 $packages=@();foreach($pkg in Get-AppxPackage -ErrorAction SilentlyContinue){if(($pkg.Name+' '+$pkg.PackageFamilyName+' '+$pkg.Publisher)-notmatch'(?i)microsoft.*(office|365)|office.*microsoft'){continue};if($pkg.Publisher-notmatch'(?i)CN=Microsoft Corporation'){continue};try{$manifest=Get-AppxPackageManifest -Package $pkg.PackageFullName -ErrorAction Stop}catch{continue};$tasks=Get-ManifestStartupTasks $manifest;if($tasks.Count-eq0){continue};$packages+=[pscustomobject]@{Name=$pkg.Name;PackageFamilyName=$pkg.PackageFamilyName;PackageFullNameHash=Get-TextHash $pkg.PackageFullName;Version=$pkg.Version.ToString();Publisher=$pkg.Publisher;InstallLocationHash=Get-PathHash $pkg.InstallLocation;StartupTasks=$tasks}};@($packages)
}
function Get-Inventory{$support=Get-SupportState;$protected=Get-ProtectedSnapshot;$packages=Get-Microsoft365Packages;$eligible=@($packages|ForEach-Object{$p=$_;@($p.StartupTasks|Where-Object{!$_.ServicingIdentity-and!$_.ProtectedIdentity}|ForEach-Object{[ordered]@{PackageName=$p.Name;PackageFamilyName=$p.PackageFamilyName;PackageVersion=$p.Version;TaskId=$_.TaskId;DisplayName=$_.DisplayName;ExecutableLeaf=$_.ExecutableLeaf;ExecutablePathHash=$_.ExecutablePathHash;EntryPoint=$_.EntryPoint;ManifestEnabled=$_.ManifestEnabled}})});[pscustomobject]@{schemaVersion=1;experiment=$experiment;issue=$issue;provider=$provider;profile=$profile;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$support;packages=$packages;eligibleCandidates=$eligible;eligibleCandidateCount=$eligible.Count;relatedStartup=Get-RelatedStartupState;protectedScopeHash=$protected.Hash;protectedScope=$protected.Snapshot;mutationSupported=$false;mutationGate='Physical supported-API state-transition proof is required before provider implementation.'}}
try{$inventory=Get-Inventory;Write-Log 'inventory' 'pass' @{supported=$inventory.support.Supported;managed=$inventory.support.Managed;packageCount=@($inventory.packages).Count;eligibleCandidateCount=$inventory.eligibleCandidateCount;mutationSupported=$false};switch($Action){'Check'{$inventory}'Capture'{if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$inventory|ConvertTo-Json -Depth 24|Set-Content -LiteralPath $StatePath -Encoding UTF8;Write-Log 'capture' 'pass' @{statePathHash=Get-PathHash $StatePath;eligibleCandidateCount=$inventory.eligibleCandidateCount;mutationSupported=$false};$inventory}}}catch{Write-Log 'failure' 'fail' @{stage=$Action;refusalReason=$_.Exception.Message;failureDetail=[ordered]@{message=$_.Exception.Message;type=$_.Exception.GetType().FullName;stack=$_.ScriptStackTrace}};throw}
