[CmdletBinding()]
param(
 [ValidateSet('Check','Capture')][string]$Action='Check',
 [string]$StatePath,
 [string]$LogPath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$experiment='EXP-135'
$issue=305
$provider='nonallowlisted-startuptask-inventory'
$profile='NonAllowlistedStartupTaskInventory'
$protectedPattern='(?i)omnissa|vmware horizon|windows app|remote desktop|mstsc|tailscale|defender|securityhealth|firewall|bitlocker|credential|accessibility|recovery|windows update|intune|sccm|configmgr|mdm|driver|firmware|device.?install'
$servicingPattern='(?i)update|updater|servic|repair|setup|install|uninstall|bootstrap|activation|licens|security|credential|accessibility|recovery|driver|firmware|dfu'
$specificExperimentPattern='(?i)microsoft.*(office|365|teams)|office|outlook|word|excel|powerpoint|onenote|access|logitech|logi|g.?hub|options\+|bolt|tune'
function Get-TextHash([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))|ForEach-Object{$_.ToString('x2')})-join''}finally{$s.Dispose()}}
function Get-PathHash([string]$Path){if([string]::IsNullOrWhiteSpace($Path)){return $null};Get-TextHash ([Environment]::ExpandEnvironmentVariables($Path).ToLowerInvariant())}
function Write-Log([string]$Event,[string]$Result,[object]$Data){if([string]::IsNullOrWhiteSpace($LogPath)){return};$parent=Split-Path -Parent $LogPath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[ordered]@{schemaVersion=1;timestampUtc=(Get-Date).ToUniversalTime().ToString('o');experiment=$experiment;issue=$issue;provider=$provider;action=$Action;event=$Event;result=$Result;machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;data=$Data}|ConvertTo-Json -Compress -Depth 24|Add-Content -LiteralPath $LogPath -Encoding UTF8}
function Get-ManagementState{$c=Get-CimInstance Win32_ComputerSystem;$signals=[ordered]@{DomainJoined=[bool]$c.PartOfDomain;MdmEnrollments=@(Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Enrollments' -ErrorAction SilentlyContinue).Count;PolicyManager=Test-Path 'HKLM:\SOFTWARE\Microsoft\PolicyManager\current\device';ConfigMgr=[bool](Get-Service CcmExec -ErrorAction SilentlyContinue);Intune=[bool](Get-Service IntuneManagementExtension -ErrorAction SilentlyContinue)};[pscustomobject]@{Managed=($signals.DomainJoined-or$signals.MdmEnrollments-gt0-or$signals.PolicyManager-or$signals.ConfigMgr-or$signals.Intune);Signals=$signals}}
function Get-SupportState{$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$m=Get-ManagementState;[pscustomobject]@{Supported=($os.Caption-match'Windows 11'-and$cs.Manufacturer-match'(?i)^HP$|Hewlett-Packard');OS=$os.Caption;Build=$os.BuildNumber;Manufacturer=$cs.Manufacturer;Model=$cs.Model;Managed=$m.Managed;ManagementSignals=$m.Signals}}
function Get-ProtectedSnapshot{$services=foreach($name in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale'){if($s=Get-Service $name -ErrorAction SilentlyContinue){[ordered]@{Name=$s.Name;Status=$s.Status.ToString();StartType=$s.StartType.ToString()}}};$processes=@(Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.ProcessName-match'(?i)omnissa|horizon|msrdc|mstsc|tailscale|windowsapp'}|Sort-Object ProcessName,Id|Select-Object ProcessName,Id);$json=[ordered]@{Services=@($services);Processes=$processes}|ConvertTo-Json -Compress -Depth 8;[pscustomobject]@{Hash=Get-TextHash $json;Snapshot=$json}}
function Get-RelatedStartupState{$run=@('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run','HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce','HKLM:\Software\Microsoft\Windows\CurrentVersion\Run','HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce')|ForEach-Object{if(Test-Path $_){$i=Get-Item $_;[ordered]@{Path=$_;Names=@($i.GetValueNames()|Sort-Object)}}};$startup=@([Environment]::GetFolderPath('Startup'),[Environment]::GetFolderPath('CommonStartup'))|ForEach-Object{if($_-and(Test-Path -LiteralPath $_)){[ordered]@{PathHash=Get-PathHash $_;Files=@(Get-ChildItem -LiteralPath $_ -Force|Sort-Object Name|ForEach-Object{$_.Name})}}};$tasks=@(Get-ScheduledTask -ErrorAction SilentlyContinue|Sort-Object TaskPath,TaskName|ForEach-Object{[ordered]@{TaskPath=$_.TaskPath;TaskName=$_.TaskName;Enabled=[bool]$_.Settings.Enabled}});[ordered]@{Run=@($run);StartupFolders=@($startup);ScheduledTasks=$tasks}}
function Get-ExecutableIdentity([string]$InstallLocation,[string]$Executable){if([string]::IsNullOrWhiteSpace($Executable)){return $null};$path=if([IO.Path]::IsPathRooted($Executable)){$Executable}else{Join-Path $InstallLocation $Executable};if(!(Test-Path -LiteralPath $path -PathType Leaf)){return [ordered]@{Leaf=[IO.Path]::GetFileName($Executable);PathHash=Get-PathHash $path;Resolved=$false}};$f=Get-Item -LiteralPath $path;$sig=Get-AuthenticodeSignature -LiteralPath $path;$publisher=if($sig.SignerCertificate){$sig.SignerCertificate.Subject}else{$null};[ordered]@{Leaf=$f.Name;PathHash=Get-PathHash $f.FullName;Resolved=$true;Sha256=(Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash;FileVersion=$f.VersionInfo.FileVersion;ProductName=$f.VersionInfo.ProductName;CompanyName=$f.VersionInfo.CompanyName;SignatureStatus=$sig.Status.ToString();Publisher=$publisher;Thumbprint=if($sig.SignerCertificate){$sig.SignerCertificate.Thumbprint}else{$null}}}
function Get-ManifestStartupTasks($Manifest,$Package){$out=@();$nodes=@($Manifest.Package.Applications.Application.Extensions.Extension|Where-Object{[string]$_.Category-match'(?i)windows.startupTask'});foreach($ext in $nodes){$task=$ext.StartupTask;if(!$task){continue};$taskId=[string]$task.TaskId;$display=[string]$task.DisplayName;$exe=[string]$ext.Executable;$entry=[string]$ext.EntryPoint;$identity="$($Package.Name) $($Package.PackageFamilyName) $taskId $display $exe $entry";$exeIdentity=Get-ExecutableIdentity ([string]$Package.InstallLocation) $exe;$out+=[pscustomobject]@{TaskId=$taskId;DisplayName=$display;ExecutableLeaf=if($exe){[IO.Path]::GetFileName($exe)}else{$null};ExecutablePathHash=Get-PathHash $exe;EntryPoint=$entry;ManifestEnabled=[string]$task.Enabled;ExecutableIdentity=$exeIdentity;ProtectedIdentity=($identity-match$protectedPattern);ServicingIdentity=($identity-match$servicingPattern);SpecificExperimentIdentity=($identity-match$specificExperimentPattern);RuntimeState='needs-physical-probe';First120SecondAttribution='needs-evidence'}};@($out)}
function Get-Packages{$packages=@();foreach($pkg in Get-AppxPackage -ErrorAction SilentlyContinue){try{$manifest=Get-AppxPackageManifest -Package $pkg.PackageFullName -ErrorAction Stop}catch{continue};$tasks=Get-ManifestStartupTasks $manifest $pkg;if($tasks.Count-eq0){continue};$packages+=[pscustomobject]@{Name=$pkg.Name;PackageFamilyName=$pkg.PackageFamilyName;PackageFullNameHash=Get-TextHash $pkg.PackageFullName;Version=$pkg.Version.ToString();Publisher=$pkg.Publisher;InstallLocationHash=Get-PathHash $pkg.InstallLocation;StartupTasks=$tasks}};@($packages)}
function Get-Inventory{$support=Get-SupportState;$protected=Get-ProtectedSnapshot;$packages=Get-Packages;$eligible=@($packages|ForEach-Object{$p=$_;@($p.StartupTasks|Where-Object{!$_.ProtectedIdentity-and!$_.ServicingIdentity-and!$_.SpecificExperimentIdentity-and$_.ExecutableIdentity.Resolved-and$_.ExecutableIdentity.SignatureStatus-eq'Valid'}|ForEach-Object{[ordered]@{PackageName=$p.Name;PackageFamilyName=$p.PackageFamilyName;PackageVersion=$p.Version;PackagePublisher=$p.Publisher;TaskId=$_.TaskId;DisplayName=$_.DisplayName;ExecutableLeaf=$_.ExecutableLeaf;ExecutablePathHash=$_.ExecutablePathHash;EntryPoint=$_.EntryPoint;ExecutableIdentity=$_.ExecutableIdentity;RuntimeState=$_.RuntimeState;First120SecondAttribution=$_.First120SecondAttribution}})});[pscustomobject]@{schemaVersion=1;experiment=$experiment;issue=$issue;provider=$provider;profile=$profile;capturedUtc=(Get-Date).ToUniversalTime().ToString('o');capturedBootTime=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime().ToString('o');machine=$env:COMPUTERNAME;userSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;support=$support;packages=$packages;eligibleCandidates=$eligible;eligibleCandidateCount=$eligible.Count;relatedStartup=Get-RelatedStartupState;protectedScopeHash=$protected.Hash;protectedScope=$protected.Snapshot;mutationSupported=$false;selectionStatus='needs-evidence';mutationGate='Physical runtime-state, measured-cost, supported Disable(), and exact supported RequestEnableAsync() restoration proof are required before mutation engineering.'}}
try{$inventory=Get-Inventory;Write-Log 'inventory' 'pass' @{supported=$inventory.support.Supported;managed=$inventory.support.Managed;packageCount=@($inventory.packages).Count;eligibleCandidateCount=$inventory.eligibleCandidateCount;selectionStatus=$inventory.selectionStatus;mutationSupported=$false};switch($Action){'Check'{$inventory}'Capture'{if([string]::IsNullOrWhiteSpace($StatePath)){throw 'StatePath is required.'};if(Test-Path -LiteralPath $StatePath){throw 'State overwrite refused.'};$parent=Split-Path -Parent $StatePath;if($parent-and!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$inventory|ConvertTo-Json -Depth 24|Set-Content -LiteralPath $StatePath -Encoding UTF8;Write-Log 'capture' 'pass' @{statePathHash=Get-PathHash $StatePath;eligibleCandidateCount=$inventory.eligibleCandidateCount;selectionStatus='needs-evidence';mutationSupported=$false};$inventory}}}catch{Write-Log 'failure' 'fail' @{stage=$Action;refusalReason=$_.Exception.Message;failureDetail=[ordered]@{message=$_.Exception.Message;type=$_.Exception.GetType().FullName;stack=$_.ScriptStackTrace}};throw}
