Describe 'EdgeRequireHardwareAcceleration provider contract' {
 BeforeAll{$script:providerPath=Join-Path $PSScriptRoot '..\providers\EdgeRequireHardwareAcceleration.ps1';$text=Get-Content -LiteralPath $script:providerPath -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:providerPath,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'keeps Experimental identity and evidence pending'{Test-Path $script:providerPath|Should -BeTrue;$text|Should -Match 'EXP-078';$text|Should -Match 'needs-evidence';$text|Should -Not -Match 'status:stable|Stable=';$text|Should -Not -Match '(?i)\bblocked\b'}
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'targets only HardwareAccelerationModeEnabled DWORD one'{foreach($t in 'HardwareAccelerationModeEnabled','SOFTWARE\\Policies\\Microsoft\\Edge','DWord','Value=1','MutationCount=1'){$text|Should -Match $t};$text|Should -Not -Match 'Disable-ScheduledTask|Set-Service|Stop-Service|Remove-AppxPackage|Uninstall-Package|Disable-PnpDevice|pnputil'}
 It 'requires HP Windows 11 elevation signed Edge 77 and explicit GPU evidence'{foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','Microsoft Corporation','Major-ge77','GraphicsEvidencePath','edgeGpuEvidenceSha256','hardwareAccelerationEffective','gpuHealthy','rendererClassification'){$text|Should -Match ([regex]::Escape($t))}}
 It 'rejects already accelerated baseline and unhealthy display state'{foreach($t in 'already-accelerated baseline','Get-GpuState','DisplayErrors','Healthy','HardwareAccelerationEffective'){$text|Should -Match ([regex]::Escape($t))}}
 It 'captures Disable3DAPIs and held Edge state'{foreach($t in 'Disable3DAPIs','StartupBoostEnabled','BackgroundModeEnabled','SleepingTabsEnabled','EfficiencyModeEnabled','NetworkPredictionOptions','NewTabPagePrerenderEnabled','NewTabPageContentEnabled','NewTabPageLocation','RestoreOnStartup'){$text|Should -Match $t}}
 It 'captures identity management startup boot GPU and protected state'{foreach($t in 'Sha256','Thumbprint','capturedBootTime','userSid','Get-Protected','Get-Management','Get-StartupFolders','Get-GpuState','protectedConfiguration','protectedRuntime'){$text|Should -Match $t}}
 It 'has dry run WhatIf logging idempotence and terminating failure retention'{foreach($t in 'DryRun','WhatIfPreference','Write-Log','ConvertTo-Json -Compress','idempotent','catch','failure'){$text|Should -Match $t}}
 It 'requires later boot persistence and collision safe exact rollback'{foreach($t in 'A later boot is required','Reboot persistence failed','rollback overwrite refused','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match $t}}
 It 'does not equate policy presence with effective GPU acceleration'{foreach($t in 'PolicyPermitsAcceleration','EffectiveGpuAcceleration','effectiveGpuVerification','EffectiveGraphicsRestoration'){$text|Should -Match $t}}
 It 'holds security update Edge Update Remote Desktop and Tailscale configuration'{foreach($t in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','edgeupdate','edgeupdatem','TermService','Tailscale','Protected service configuration drift detected'){$text|Should -Match $t}}
}
