$provider=Join-Path $PSScriptRoot '..\providers\EdgeDisableAddressBarClipboardSuggestions.ps1'
Describe 'EdgeDisableAddressBarClipboardSuggestions provider contract' {
 BeforeAll{$text=Get-Content -LiteralPath $provider -Raw}
 It 'keeps Experimental identity and required evidence state'{Test-Path $provider|Should -BeTrue;$text|Should -Match 'EXP-151';$text|Should -Match 'needs-evidence';$text|Should -Not -Match 'status:stable|Stable=';$text|Should -Not -Match "'blocked'|\"blocked\""}
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'targets one recommended address-bar clipboard DWORD zero'{foreach($t in 'AddressBarClipboardSuggestEnabled','SOFTWARE\\Policies\\Microsoft\\Edge\\Recommended','DWord','Value=0','MutationCount=1'){$text|Should -Match $t};$text|Should -Not -Match 'Set-Service|Stop-Service|Disable-ScheduledTask|Remove-AppxPackage|Remove-Item .*User Data|Remove-Item .*Profile'}
 It 'requires HP Windows 11 elevation Microsoft-signed Edge 151 plus and a controlled non-MSA clipboard fixture'{foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','Microsoft Corporation','Major-ge151','controlledProfile','microsoftAccountSignedIn','addressBarClipboardSuggestionsEligible','benignClipboardFixtureSha256','ProfileFixturePath'){$text|Should -Match ([regex]::Escape($t))}}
 It 'refuses conflicting mandatory policy and captures held Edge state'{foreach($t in 'MandatoryCandidate','CopilotAddressBarSuggestionsEnabled','SearchSuggestEnabled','AddressBarWorkSearchResultsEnabled','StartupBoostEnabled','BackgroundModeEnabled','SleepingTabsEnabled','HardwareAccelerationModeEnabled','NetworkPredictionOptions','NewTabPageContentEnabled','DefaultClipboardSetting','ClipboardAllowedForUrls','ClipboardBlockedForUrls'){$text|Should -Match $t}}
 It 'captures Edge profile management boot and protected scope'{foreach($t in 'Sha256','Thumbprint','MarkerSha256','capturedBootTime','userSid','Get-Protected','Get-Management','Get-StartupFolders'){$text|Should -Match $t}}
 It 'has dry run WhatIf structured logging idempotence and terminating failures'{foreach($t in 'DryRun','WhatIfPreference','Write-Log','ConvertTo-Json -Compress','idempotent','catch','failure'){$text|Should -Match $t}}
 It 'requires reboot persistence and exact collision-safe rollback'{foreach($t in 'A later boot is required','Reboot persistence failed','rollback overwrite refused','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match $t}}
 It 'preserves security updates Edge Update Remote Desktop and Tailscale service configuration'{foreach($t in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','edgeupdate','edgeupdatem','TermService','Tailscale','Protected service configuration drift detected'){$text|Should -Match $t}}
}
