Describe 'EdgeDisableTextPrediction provider contract' {
 BeforeAll{$script:providerPath=Join-Path $PSScriptRoot '..\providers\EdgeDisableTextPrediction.ps1';$text=Get-Content -LiteralPath $script:providerPath -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:providerPath,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'keeps Experimental identity and evidence pending'{Test-Path $script:providerPath|Should -BeTrue;$text|Should -Match 'EXP-149';$text|Should -Match 'needs-evidence';$text|Should -Not -Match 'status:stable|Stable=';$text|Should -Not -Match '(?i)\bblocked\b'}
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'targets only mandatory TextPredictionEnabled DWORD zero'{foreach($t in 'TextPredictionEnabled','SOFTWARE\\Policies\\Microsoft\\Edge','DWord','Value=0','MutationCount=1'){$text|Should -Match $t};$text|Should -Not -Match 'Disable-ScheduledTask|Set-Service|Stop-Service|Remove-AppxPackage|Uninstall-Package|Disable-PnpDevice|pnputil'}
 It 'requires HP Windows 11 elevation Microsoft signed Edge 104 and controlled non-MSA fixture'{foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','Microsoft Corporation','Major-ge104','controlledProfile','microsoftAccountSignedIn','textPredictionEligible','fixtureSha256','ProfileFixturePath'){$text|Should -Match ([regex]::Escape($t))}}
 It 'refuses existing policy and captures held Edge state'{foreach($t in 'RecommendedCandidate','SearchSuggestEnabled','AddressBarWorkSearchResultsEnabled','CopilotAddressBarSuggestionsEnabled','AddressBarClipboardSuggestEnabled','EdgeShoppingAssistantEnabled','NewTabPageContentEnabled','NewTabPagePrerenderEnabled','NewTabPageLocation','StartupBoostEnabled','BackgroundModeEnabled','SleepingTabsEnabled','HardwareAccelerationModeEnabled','NetworkPredictionOptions','RestoreOnStartup'){$text|Should -Match $t}}
 It 'captures identity management startup boot and protected state'{foreach($t in 'Sha256','Thumbprint','MarkerSha256','capturedBootTime','userSid','Get-Protected','Get-Management','Get-StartupFolders','protectedConfiguration','protectedRuntime'){$text|Should -Match $t}}
 It 'has dry run WhatIf logging idempotence and terminating failure retention'{foreach($t in 'DryRun','WhatIfPreference','Write-Log','ConvertTo-Json -Compress','idempotent','catch','failure'){$text|Should -Match $t}}
 It 'requires later boot persistence and collision safe exact rollback'{foreach($t in 'A later boot is required','Reboot persistence failed','rollback overwrite refused','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match $t}}
 It 'holds security update Edge Update Remote Desktop and Tailscale configuration'{foreach($t in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','edgeupdate','edgeupdatem','TermService','Tailscale','Protected service configuration drift detected'){$text|Should -Match $t}}
}
