BeforeAll{$script=Join-Path $PSScriptRoot '..\providers\HPSupportAssistantQuickStartTask.ps1';$text=Get-Content $script -Raw}
Describe 'EXP-088 HP Support Assistant Quick Start task provider contract'{
 It 'uses ShouldProcess and bounded lifecycle actions'{$text|Should -Match 'SupportsShouldProcess';$text|Should -Match "ValidateSet\('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'\)";$text|Should -Match '\$WhatIfPreference'}
 It 'requires HP Windows 11 elevation and management refusal'{$text|Should -Match 'Windows 11';$text|Should -Match 'Manufacturer';$text|Should -Match 'Elevation is required';$text|Should -Match 'Enterprise-management signals'}
 It 'requires exactly one signed HP logon candidate'{$text|Should -Match 'Exactly one eligible';$text|Should -Match 'LogonTrigger';$text|Should -Match 'AuthenticodeSignature';$text|Should -Match 'HP Inc\|Hewlett-Packard'}
 It 'rejects protected task purposes and identities'{$text|Should -Match 'firmware\|bios\|driver\|security\|recovery';$text|Should -Match 'omnissa\|horizon\|windows app\|remote desktop\|tailscale'}
 It 'captures exact XML, definition, executable and runtime identity'{$text|Should -Match 'Export-ScheduledTask';$text|Should -Match 'XmlHash';$text|Should -Match 'DefinitionHash';$text|Should -Match 'ExecutableHash';$text|Should -Match 'Publisher';$text|Should -Match 'LastTaskResult'}
 It 'limits application to enabled state and uses XML only for exact rollback'{$text|Should -Match 'Disable-ScheduledTask';$text|Should -Match 'Register-ScheduledTask';$text|Should -Match 'Enable-ScheduledTask';$text|Should -Not -Match 'Unregister-ScheduledTask|Remove-Item|Stop-Service|Set-Service'}
 It 'provides structured logging idempotence persistence and failure retention'{$text|Should -Match 'ConvertTo-Json -Compress';$text|Should -Match 'idempotent';$text|Should -Match 'VerifyReboot';$text|Should -Match 'failure';$text|Should -Match 'throw'}
 It 'refuses state, executable, protected-scope, and rollback drift'{$text|Should -Match 'Task-definition drift';$text|Should -Match 'Action executable drift';$text|Should -Match 'Protected-scope drift';$text|Should -Match 'Rollback verification failed'}
 It 'binds state to experiment machine user and boot and refuses overwrite'{$text|Should -Match 'schemaVersion';$text|Should -Match 'COMPUTERNAME';$text|Should -Match 'userSid';$text|Should -Match 'capturedBootTime';$text|Should -Match 'overwrite refused';$text|Should -Match 'State identity validation failed'}
}
