$providerPath=Join-Path $PSScriptRoot '..\providers\OfficeHardwareAccelerationPolicy.ps1'
Describe 'EXP-084 Office hardware acceleration policy provider contract' {
  BeforeAll {$text=Get-Content -LiteralPath $providerPath -Raw;$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($providerPath,[ref]$tokens,[ref]$errors)}
  It 'parses as PowerShell' {$errors.Count|Should -Be 0}
  It 'supports the complete reversible lifecycle' {foreach($action in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$action'"}}
  It 'uses ShouldProcess, strict mode, and terminating failure handling' {$text|Should -Match 'SupportsShouldProcess';$text|Should -Match 'ShouldProcess';$text|Should -Match 'Set-StrictMode -Version Latest';$text|Should -Match "ErrorActionPreference='Stop'";$text|Should -Match "Write-Log 'failure'"}
  It 'captures HP, Windows, Outlook, graphics, management, machine, user, key, type, and value state' {foreach($token in 'Windows 11','Manufacturer','Build','OUTLOOK.EXE','Sha256','SignatureStatus','Graphics','DriverVersion','DomainJoined','MdmEnrollments','PolicyManager','ConfigMgr','OfficePolicyValue','machine','userSid','KeyExists','ValueExists','Kind','Data'){$text|Should -Match $token}}
  It 'limits mutation to one Office graphics preference' {$text|Should -Match "valueName='DisableHardwareAcceleration'";$text|Should -Match "policyPath='HKCU:\\Software\\Microsoft\\Office\\16.0\\Common\\Graphics'";$text|Should -Match 'New-ItemProperty';$text|Should -Match 'Remove-ItemProperty';$text|Should -Not -Match 'Set-Service|Stop-Service|Disable-ScheduledTask|Remove-AppxPackage|Uninstall-Package|pnputil|Set-MpPreference|Disable-NetAdapter|Set-NetFirewallProfile'}
  It 'requires Office process closure and refuses managed or preconfigured systems' {$text|Should -Match 'All Office applications must be closed';$text|Should -Match 'Enterprise-management or Office policy ownership';$text|Should -Match 'Existing Office graphics preference'}
  It 'includes dry run, idempotence, structured logging, reboot verification, executable drift refusal, and exact rollback' {foreach($token in 'WouldChange','idempotent','ConvertTo-Json -Compress','VerifyReboot','LastBootUpTime','Outlook executable identity drift','applied value drifted','Remove empty experiment-created key'){$text|Should -Match $token}}
}
