$root=Split-Path -Parent $PSScriptRoot
$provider=Join-Path $root 'providers/EdgeNewTabContentPolicy.ps1'
Describe 'EXP-148 Edge new-tab content provider contract' {
  BeforeAll { $text=Get-Content $provider -Raw; $tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($provider,[ref]$tokens,[ref]$errors) }
  It 'parses as PowerShell' { $errors.Count | Should -Be 0 }
  It 'uses the exact mandatory NewTabPageContentEnabled policy' { $text | Should -Match "PolicyPath='HKLM:"; $text | Should -Match 'NewTabPageContentEnabled'; $text | Should -Match '\$Treatment=0'; $text | Should -Match 'Major-lt91' }
  It 'implements the complete reversible lifecycle' { foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){ $text | Should -Match "'$a'" } }
  It 'captures Edge executable identity and registry ownership evidence' { foreach($s in 'Get-AuthenticodeSignature','Microsoft Corporation','Get-FileHash','Sha256','Thumbprint','Owner=','Sddl='){ $text | Should -Match $s } }
  It 'binds treatment to an exact eligible profile and baseline content proof' { foreach($s in 'TargetProfilePath','ProfileSignInType','BaselineContentActive','SelfManagedNtpConfirmed','MSA-signed-in profiles are ineligible','baseline Microsoft NTP content proof required'){ $text | Should -Match $s } }
  It 'refuses enterprise and Copilot NTP ownership ambiguity' { $text | Should -Match 'enterprise management ownership detected';$text | Should -Match 'self-managed NTP ownership confirmation required';$text | Should -Match 'Copilot NTP configuration requires separate applicability evidence';$text | Should -Match 'CcmExec';$text | Should -Match 'Microsoft\\Enrollments' }
  It 'holds NTP startup browser and protected state against drift' { foreach($s in 'NewTabPageLocation','NewTabPagePrerenderEnabled','NewTabPageQuickLinksEnabled','NewTabPageAllowedBackgroundTypes','CopilotNewTabPageEnabled','RestoreOnStartup','StartupBoostEnabled','BackgroundModeEnabled','SleepingTabsEnabled','NetworkPredictionOptions','WinDefend','mpssvc','wuauserv','TermService','Tailscale','edgeupdate'){ $text | Should -Match $s };$text | Should -Match 'Related Edge policy drift detected';$text | Should -Match 'Protected security update or remote-access state drift detected' }
  It 'captures prelaunch Edge resource observations without mutating them' { foreach($s in 'EdgeProcesses','WorkingSet','PrivateBytes','ReadBytes','WriteBytes','Network=','Gpu='){ $text | Should -Match $s } }
  It 'requires Edge closure around controlled mutation and exact rollback' { $text | Should -Match 'Close Edge before application';$text | Should -Match 'Close Edge before rollback';$text | Should -Match 'Rollback collision or policy drift detected';$text | Should -Match 'Exact rollback verification failed' }
  It 'requires a later boot for persistence verification' { $text | Should -Match 'A later boot is required';$text | Should -Match 'capturedBootTime' }
  It 'supports ShouldProcess WhatIf structured JSONL and idempotence' { $text | Should -Match 'SupportsShouldProcess';$text | Should -Match 'WhatIfPreference';$text | Should -Match 'ConvertTo-Json -Compress';$text | Should -Match "'idempotent'";$text | Should -Match 'MutationCount=0' }
  It 'cleans only an experiment-created empty mandatory policy key on rollback' { $text | Should -Match 'original.KeyExists';$text | Should -Match 'Remove-Item \$PolicyPath' }
  It 'retains physical observations as needs-evidence' { $text | Should -Match "EvidenceStatus='needs-evidence'";$text | Should -Match "normalNtpShellAndContentAbsence='needs-evidence'";$text | Should -Match "controlledNavigation='needs-evidence'" }
  It 'contains no protected-scope mutation commands' { $text | Should -Not -Match '(?i)Set-MpPreference|Disable-WindowsOptionalFeature|Remove-WindowsDriver|pnputil|bcdedit|manage-bde|Set-NetFirewall|Uninstall-Package|Remove-AppxPackage|Stop-Service|Set-Service|Restart-Service' }
}
