Describe 'EXP-067 HP Diagnostics HSA service provider' {
    BeforeAll {$root=Split-Path $PSScriptRoot -Parent;$provider=Join-Path $root 'providers/HPDiagnosticsHsaService.ps1';$manifest=Join-Path $root 'lacksan.manifest.json';$content=Get-Content $provider -Raw}
    It 'parses without syntax errors' {$t=$null;$e=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($provider,[ref]$t,[ref]$e);$e.Count|Should -Be 0}
    It 'exposes the complete reversible contract' {foreach($a in @('Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback')){$content|Should -Match "'$a'"};foreach($x in @('Write-StructuredLog','Save-State','Read-State','ShouldProcess','Test-Applied','Rollback refused','Apply verification failed')){$content|Should -Match [regex]::Escape($x)}}
    It 'uses the EXP-067 identity' {$content|Should -Match "experiment='EXP-067'";$content|Should -Not -Match "experiment='EXP-066'"}
    It 'targets one exact HP diagnostics service and startup mode only' {$content|Should -Match "serviceName='HPDiagsCap'";$content|Should -Match 'DiagsCap\\.exe';$content|Should -Match 'Get-AuthenticodeSignature';$content|Should -Match 'sc\.exe config';$content|Should -Match 'start= demand';$content|Should -Not -Match 'Remove-Service|Remove-AppxPackage|pnputil|devcon|Set-MpPreference|Stop-Process|Remove-Item'}
    It 'captures identity hash dependencies activity and running state' {foreach($f in @('DisplayName','PathName','ExecutablePath','ExecutableVersion','ExecutableHash','SignatureStatus','Signer','StartMode','DelayedAutoStart','State','StartName','Dependencies','DependentServices','DiagnosticActivity','windowsBuild','manufacturer','model')){$content|Should -Match $f}}
    It 'refuses management dependency and active diagnostic ambiguity' {foreach($f in @('PolicyManager','ManagementSignals','DependencySafe','DiagnosticActivity','Active HP diagnostics session','ServiceCount')){$content|Should -Match $f}}
    It 'registers the profile and protected scopes' {$m=Get-Content $manifest -Raw|ConvertFrom-Json;@($m.profiles|Where-Object id -eq 'HPDiagnosticsDemandStart').Count|Should -Be 1;$p=@($m.providers|Where-Object id -eq 'hp-diagnostics-hsa-service')[0];$p.mode|Should -Be 'Reversible';$p.script|Should -Be 'providers/HPDiagnosticsHsaService.ps1';foreach($s in @('WindowsSecurity','WindowsUpdate','Recovery','EnterpriseManagement','DeviceCriticalDrivers','Omnissa','WindowsApp','RemoteDesktop','Tailscale')){@($p.protectedScopes)|Should -Contain $s}}
}
