Describe 'EXP-068 HP Audio Analytics Manual provider contract' {
 BeforeAll{$script:path=Join-Path $PSScriptRoot '..\providers\HPAudioAnalyticsManual.ps1';$script:text=Get-Content -LiteralPath $script:path -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:path,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'retains Experimental identity and pending evidence'{$script:text|Should -Match 'EXP-068';$script:text|Should -Match 'needs-evidence';$script:text|Should -Not -Match 'status:stable|Stable='}
 It 'implements the reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$script:text|Should -Match "'$a'"}}
 It 'requires HP Windows 11 elevation clean reboot and self-managed ownership'{foreach($x in 'Windows 11 required','HP platform required','Elevation required','Pending reboot detected','Enterprise management ownership detected','CcmExec','Microsoft\\Enrollments','Provisioning\\OMADM\\Accounts'){$script:text|Should -Match $x}}
 It 'requires exact audio analytics service and HP-signed executable'{foreach($x in 'HPAudioAnalytics','HP Audio Analytics Service','HPAudioAnalytics\.exe','Valid HP-signed HPAudioAnalytics.exe required','HPSigned','Sha256','Thumbprint','FileVersion'){$script:text|Should -Match $x}}
 It 'captures startup dependency recovery trigger and audio boundary state'{foreach($x in 'StartName','Dependencies','Dependents','qfailure','qtriggerinfo','DelayedAutoStart','RegistryOwner','Get-PnpDevice','HPHotkeyAudioProducts'){$script:text|Should -Match $x}}
 It 'changes only startup configuration to Manual while preserving running state'{$script:text|Should -Match 'start= demand';$script:text|Should -Match 'PreserveCurrentRunningState';$script:text|Should -Match 'AudioMutationCount=0';$apply=[regex]::Match($script:text,"'Apply'\s*\{(?<b>[\s\S]*?)\};'Verify'").Groups['b'].Value;$apply|Should -Not -Match 'Stop-Service'}
 It 'provides dry run WhatIf JSONL idempotence and failure retention'{foreach($x in 'DryRun','WhatIfPreference','ShouldProcess','ConvertTo-Json -Compress','Add-Content','idempotent','failureDetail','ErrorActionPreference','catch'){$script:text|Should -Match $x}}
 It 'requires a later boot and refuses identity management audio and protected drift'{foreach($x in 'A later boot is required','Reboot persistence failed','Service configuration drift detected','Executable identity drift detected','Audio or hotkey boundary drift detected','Management ownership drift detected','Protected configuration drift detected','Rollback collision detected'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'restores exact startup delayed-start and running state'{foreach($x in 'Restore','original.StartMode','original.DelayedAutoStart','original.State','Exact rollback verification failed','Audio or hotkey state changed during rollback'){$script:text|Should -Match $x}}
 It 'preserves Windows audio security update and protected remote access services'{foreach($x in 'AudioSrv','AudioEndpointBuilder','WinDefend','mpssvc','BFE','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$script:text|Should -Match $x}}
 It 'contains no device driver package security or servicing mutation primitives'{$script:text|Should -Not -Match 'Disable-PnpDevice|Enable-PnpDevice|Remove-PnpDevice|pnputil|Remove-AppxPackage|Uninstall-Package|Set-MpPreference|Set-NetFirewall|Remove-Service|sc\.exe\s+delete'}
}