Describe 'EXP-120 HP Hotkey UWP delayed-start contract' {
 BeforeAll {$provider=Join-Path $PSScriptRoot '..\providers\HpHotkeyUwpDelayedStart.ps1';$text=Get-Content -LiteralPath $provider -Raw}
 It 'parses as PowerShell' {$t=$null;$e=$null;[System.Management.Automation.Language.Parser]::ParseFile($provider,[ref]$t,[ref]$e)|Out-Null;@($e).Count|Should -Be 0}
 It 'implements the reversible lifecycle' {foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'requires exact HP Hotkey service executable and publisher identity' {foreach($x in 'HotKeyServiceUWP','HP Hotkey UWP Service','HotKeyServiceUWP.exe','Get-AuthenticodeSignature','Get-FileHash','HP Hotkey Support'){$text|Should -Match ([regex]::Escape($x))}}
 It 'requires model-bound bulletin security evidence and version comparison' {foreach($x in 'HPSBHF04102 Rev. 2','SecurityFloorPath','minimumVersion','sourceUrl','model-bound HPSBHF04102 security floor evidence required','version below model security floor'){$text|Should -Match ([regex]::Escape($x))}}
 It 'captures support management BIOS service package trigger recovery device and protected state' {foreach($x in 'Management','Win32_BIOS','RegistryStart','DelayedAutoStart','RecoveryText','TriggerText','HotkeyDevices','Protected','capturedBootTime','userSid'){$text|Should -Match ([regex]::Escape($x))}}
 It 'changes only startup timing and preserves current running state' {$text|Should -Match 'Set-Service';$text|Should -Match 'DelayedAutoStart';$text|Should -Match 'PreserveRunningState';$text|Should -Not -Match 'Remove-Service|sc\.exe\s+delete|Remove-AppxPackage|Disable-PnpDevice|Remove-PnpDevice|pnputil|Unregister-ScheduledTask|Disable-ScheduledTask|Set-MpPreference|Set-NetFirewallRule|Remove-Item\s+.+DriverStore'}
 It 'supports dry run WhatIf structured logs idempotence reboot verification and terminating failure retention' {foreach($x in 'WouldChange','WhatIfPreference','schemaVersion=2','idempotent','Later boot required','failure','needs-evidence'){$text|Should -Match ([regex]::Escape($x))}}
 It 'refuses identity management dependency security-floor and protected-state drift' {foreach($x in 'identity drift detected','Management drift detected','dependency trigger or recovery drift detected','Protected security update remote-access or device state drift detected','Security-floor evidence drift detected'){$text|Should -Match ([regex]::Escape($x))}}
 It 'performs exact rollback including delayed-start existence type raw value and running state' {foreach($x in 'RegistryValueKind','Remove-ItemProperty','Start-Service','Stop-Service','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match ([regex]::Escape($x))}}
 It 'never assigns Stable' {$text|Should -Not -Match 'status:stable|Stable='}
}
