Describe 'EXP-066 HP Network HSA Manual provider contract' {
 BeforeAll{$script:path=Join-Path $PSScriptRoot '..\providers\HPNetworkCapManual.ps1';$script:text=Get-Content -LiteralPath $script:path -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:path,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'retains Experimental identity and pending evidence'{$script:text|Should -Match 'EXP-066';$script:text|Should -Match 'needs-evidence';$script:text|Should -Not -Match 'status:stable|Stable='}
 It 'implements the reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$script:text|Should -Match "'$a'"}}
 It 'requires HP Windows 11 elevation clean reboot and self-managed ownership'{foreach($x in 'Windows 11 required','HP platform required','Elevation required','Pending reboot detected','Enterprise management ownership detected','CcmExec','Microsoft\\Enrollments','Provisioning\\OMADM\\Accounts'){$script:text|Should -Match $x}}
 It 'requires exact HPNetworkCap service and signed executable identity'{foreach($x in 'HPNetworkCap','HP Network HSA Service','Valid HP-signed NetworkCap executable required','HPSigned','Sha256','Thumbprint','FileVersion'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'captures startup account dependency recovery trigger and package state'{foreach($x in 'StartName','Dependencies','Dependents','qfailure','qtriggerinfo','DelayedAutoStart','RegistryOwner','Packages','HPApplications'){$script:text|Should -Match $x}}
 It 'captures normalized network boundary state'{foreach($x in 'Get-NetAdapter','Get-NetAdapterBinding','Get-NetIPAddress','Get-NetRoute','Get-DnsClientServerAddress','Get-NetConnectionProfile','netsh winhttp show proxy','InterfaceGuid','ComponentID','ServerAddresses'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'refuses protected dependency driver and OMEN ambiguity'{foreach($x in 'Protected dependency edge detected','Kernel or driver-backed service identity refused','OMEN or HP network application presence requires physical demand-start qualification'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'changes only startup configuration to Manual during treatment'{$script:text|Should -Match 'start= demand';$script:text|Should -Match 'PreserveCurrentRunningState';$script:text|Should -Match 'NetworkMutationCount=0';$apply=[regex]::Match($script:text,"'Apply'\s*\{(?<b>[\s\S]*?)\};'Verify'").Groups['b'].Value;$apply|Should -Not -Match 'Stop-Service'}
 It 'provides DryRun WhatIf JSONL idempotence and failure retention'{foreach($x in 'DryRun','WhatIfPreference','ShouldProcess','ConvertTo-Json -Compress','Add-Content','idempotent','failureDetail','ErrorActionPreference','catch'){$script:text|Should -Match $x}}
 It 'requires later boot and refuses service network management and protected drift'{foreach($x in 'A later boot is required','Reboot persistence failed','Service configuration drift detected','Executable identity drift detected','Network stack drift detected','Management ownership drift detected','Protected configuration drift detected','Rollback collision detected'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'restores exact startup delayed-start and running state' {foreach($x in 'Restore','original.StartMode','original.DelayedAutoStart','original.State','Exact rollback verification failed','Network stack changed during rollback'){$script:text|Should -Match $x}}
 It 'preserves security update firewall and remote access configuration'{foreach($x in 'WinDefend','mpssvc','BFE','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$script:text|Should -Match $x}}
 It 'contains no network driver package device security or servicing mutation primitives'{$script:text|Should -Not -Match 'Set-Net|New-Net|Remove-Net|Disable-Net|Enable-Net|Remove-AppxPackage|Uninstall-Package|Disable-PnpDevice|Remove-PnpDevice|pnputil|Set-MpPreference|Set-NetFirewall|Remove-Service|sc\.exe\s+delete'}
}
