Describe 'EXP-087 HP Support Solutions Framework Manual provider contract' {
 BeforeAll{$script:providerPath=Join-Path $PSScriptRoot '..\providers\HPSupportSolutionsFrameworkManual.ps1';$script:text=Get-Content -LiteralPath $script:providerPath -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:providerPath,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'retains Experimental identity and pending physical evidence'{$script:text|Should -Match 'EXP-087';$script:text|Should -Match 'needs-evidence';$script:text|Should -Not -Match 'status:stable|Stable='}
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$script:text|Should -Match "'$a'"}}
 It 'qualifies HP Windows 11 elevation and unmanaged ownership'{foreach($x in 'Windows 11 required','HP platform required','Elevation required','Enterprise management ownership detected','CcmExec','Microsoft\\Enrollments','Provisioning\\OMADM\\Accounts'){$script:text|Should -Match $x}}
 It 'requires one product one signed product-owned service and exact executable identity'{foreach($x in 'Exactly one HP Support Solutions Framework product required','Exactly one signed product-owned Windows service required','HPSigned','Sha256','Thumbprint','FileVersion','InstallLocation'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'captures service account dependencies dependents recovery triggers listeners tasks and ACL owner'{foreach($x in 'StartName','Dependencies','Dependents','qfailure','qtriggerinfo','Get-Listeners','Get-Tasks','RegistryOwner','ServiceSddl'){$script:text|Should -Match $x}}
 It 'refuses disabled and dependency-sensitive candidates'{foreach($x in 'Already-disabled service refused','Dependent services make this candidate dependency-sensitive'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'changes startup configuration to Manual without stopping a running service during Apply'{$script:text|Should -Match 'start= demand';$script:text|Should -Match 'PreserveCurrentRunningState';$apply=[regex]::Match($script:text,"'Apply'\s*\{(?<b>[\s\S]*?)\n 'Verify'").Groups['b'].Value;$apply|Should -Not -Match 'Stop-Service'}
 It 'captures exact delayed auto start and running state for rollback'{foreach($x in 'DelayedAutoStart','Restore-Startup','original.State','Exact rollback verification failed'){$script:text|Should -Match $x}}
 It 'provides dry run WhatIf JSONL idempotence and terminating failure retention'{foreach($x in 'DryRun','WhatIfPreference','ConvertTo-Json -Compress','Add-Content','idempotent','failureDetail','ErrorActionPreference','catch'){$script:text|Should -Match $x}}
 It 'requires later boot persistence and refuses drift and rollback collisions'{foreach($x in 'A later boot is required','Reboot persistence failed','Executable identity drift detected','Service configuration drift detected','Management ownership drift detected','Protected configuration drift detected','Rollback collision detected'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'preserves security updates and protected remote access service configuration'{foreach($x in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$script:text|Should -Match $x}}
 It 'contains no uninstall driver package device firmware or security mutation primitives'{$script:text|Should -Not -Match 'Remove-AppxPackage|Uninstall-Package|Disable-PnpDevice|Remove-PnpDevice|pnputil|Set-MpPreference|Set-NetFirewall|Remove-Service|sc\.exe\s+delete'}
}
