$provider=Join-Path $PSScriptRoot '..\providers\HPSysInfoDemandStart.ps1'
Describe 'EXP-065 HPSysInfoDemandStart provider contract' {
    BeforeAll {$text=Get-Content -LiteralPath $provider -Raw;$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($provider,[ref]$tokens,[ref]$errors)}
    It 'parses as valid PowerShell' {$errors.Count|Should -Be 0}
    It 'implements the complete reversible lifecycle' {foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
    It 'uses ShouldProcess WhatIf structured logs idempotence and terminating failures' {foreach($t in 'SupportsShouldProcess','WhatIfPreference','ShouldProcess','ConvertTo-Json -Compress',"'idempotent'","'failure' 'fail'",'ErrorActionPreference'){$text|Should -Match [regex]::Escape($t)}}
    It 'requires elevated HP Windows 11 and refuses management ownership' {foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','DomainJoined','MdmEnrollments','PolicyManager','ConfigMgr','Intune','Enterprise-management ownership detected'){$text|Should -Match [regex]::Escape($t)}}
    It 'requires one exact signed HP System Info service identity' {foreach($t in 'HPSysInfoCap','HP System Info HSA Service','SysInfoCap.exe','Get-AuthenticodeSignature','ValidPublisher','Exactly one verified HPSysInfoCap identity is required'){$text|Should -Match [regex]::Escape($t)}}
    It 'captures exact startup executable package dependency and device evidence' {foreach($t in 'StartMode','DelayedAutoStart','State','PathName','ServiceAccount','Dependencies','Dependents','RelatedServices','Packages','PnpEvidence','Sha256','FileVersion','Publisher','Thumbprint','capturedBootTime','dependencyHash','packageHash'){$text|Should -Match $t}}
    It 'refuses driver PnP dependent package ambiguous and protected scope' {foreach($t in 'DriverStore','System32\\drivers','Dependent service evidence','Protected dependency detected','Exactly one associated HP System Info package identity is required','PnP or driver association detected','Protected-scope drift detected'){$text|Should -Match $t}}
    It 'limits treatment to one service startup mode without stopping it' {$text|Should -Match 'Set-Service -Name \$serviceName -StartupType Manual';$text|Should -Match 'PreserveRunningState';$text|Should -Not -Match 'Remove-Service|sc\.exe\s+delete|pnputil|Remove-PnpDevice|Remove-AppxPackage|Uninstall-Package|Stop-Service \$serviceName.*Apply'}
    It 'normalizes WMI Auto and Set-Service Automatic for exact rollback checks' {$text|Should -Match 'function Normalize-StartMode';$text|Should -Match "'Auto','Automatic'";$text|Should -Match 'Normalize-StartMode \$restored.StartMode'}
    It 'preserves exact delayed state and original running state during rollback' {foreach($t in 'Restore-Delayed','Test-DelayedEqual','Start-Service','Stop-Service','Rollback configuration drift detected','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match [regex]::Escape($t)}}
    It 'requires an observed later boot and retains missing physical evidence' {$text|Should -Match 'A later boot is required';$text|Should -Match 'Reboot persistence failed';$text|Should -Match 'needs-evidence'}
    It 'preserves Windows security updates recovery management and remote access scope' {foreach($t in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale','omnissa','horizon','msrdc','mstsc','bitlocker','credential','recovery','mdm'){$text|Should -Match $t}}
    It 'contains no release promotion assignment' {$text|Should -Not -Match 'status:stable|stage:stable|Stable='}
}