Describe 'EXP-153 inventory-bound Run/RunOnce provider contract' {
 BeforeAll{$script:provider=Join-Path $PSScriptRoot '..\providers\InventoryBoundRunRegistrationRemoval.ps1';$script:text=Get-Content -LiteralPath $script:provider -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($provider,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'binds only one EXP-143 priority Run or RunOnce selection'{foreach($t in 'EXP-143','priority-target','RegistryRun','RunOnce','inventoryHash','valueName','originalState'){$text|Should -Match ([regex]::Escape($t))}}
 It 'allows only approved HKCU HKLM Run and RunOnce keys with explicit 32 or 64 bit view'{foreach($t in 'HKCU','HKLM','Registry32','Registry64','Software\\Microsoft\\Windows\\CurrentVersion\\Run','Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce'){$text|Should -Match $t}}
 It 'supports REG_SZ and REG_EXPAND_SZ exact raw data'{foreach($t in 'String','ExpandString','DoNotExpandEnvironmentNames','RegistryValueKind','SetValue'){$text|Should -Match $t}}
 It 'requires HP Windows 11 elevation and self-managed ownership'{foreach($t in 'Windows 11 required','HP platform required','elevation required','enterprise management ownership detected','DomainJoined','EnrollmentCount','OmadmCount','ConfigMgr'){$text|Should -Match ([regex]::Escape($t))}}
 It 'requires a valid signed executable-backed user application identity'{foreach($t in 'Get-AuthenticodeSignature','Get-FileHash','ValidSignature','Sha256','FileVersion','ProductName','CompanyName','Publisher','Thumbprint'){$text|Should -Match $t}}
 It 'refuses protected servicing updater driver firmware and pairing identities'{foreach($t in 'Protected startup identity refused','Servicing, updater, installer, repair, firmware, driver, or pairing startup identity refused','omnissa','windows app','remote desktop','tailscale','defender','credential','bitlocker','windows update','recovery','accessib','driver','firmware','pair'){$text|Should -Match ([regex]::Escape($t))}}
 It 'captures exact value ACL executable machine user boot and hashes'{foreach($t in 'KeySddl','KeyOwner','originalValueHash','otherRunHash','protectedHash','machine=','userSid','capturedBootUtc','inventoryHash'){$text|Should -Match ([regex]::Escape($t))}}
 It 'holds unrelated registrations and protected configuration against drift'{foreach($t in 'Get-OtherRunSnapshot','Unrelated Run/RunOnce registration drift detected','Get-ProtectedConfiguration','Protected configuration drift detected','WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$text|Should -Match ([regex]::Escape($t))}}
 It 'supports dry run WhatIf ShouldProcess JSONL logging idempotence and failures'{foreach($t in 'SupportsShouldProcess','WouldChange','WhatIfPreference','ShouldProcess','ConvertTo-Json -Compress',"'idempotent'",'MutationCount',"'failure' 'fail'"){$text|Should -Match ([regex]::Escape($t))}}
 It 'limits production mutation to the selected registry value'{$text|Should -Match 'DeleteValue';$text|Should -Match '\.SetValue';$text|Should -Not -Match 'Remove-ItemProperty|Remove-AppxPackage|Uninstall-Package|Set-Service|Stop-Service|Remove-Service|Disable-PnpDevice|Remove-PnpDevice|pnputil|Disable-ScheduledTask|Unregister-ScheduledTask|Set-MpPreference|Disable-WindowsOptionalFeature'}
 It 'requires later boot persistence and collision-safe exact rollback'{foreach($t in 'DateTimeOffset','A later boot is required','Reboot persistence failed','Rollback overwrite refused because a conflicting value reappeared','rollback-collision','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match ([regex]::Escape($t))}}
 It 'keeps physical selection and performance evidence pending'{$text|Should -Match 'needs-evidence';$text|Should -Not -Match 'status:stable|stage:stable|Stable='}
}
