Describe 'EXP-160 inventory-bound Startup-folder provider contract' {
 BeforeAll {$script:providerPath=Join-Path $PSScriptRoot '..\providers\InventoryBoundStartupFolderRemoval.ps1';$text=Get-Content -LiteralPath $script:providerPath -Raw}
 It 'parses as PowerShell' {$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:providerPath,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'implements the complete reversible lifecycle' {foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'uses EXP-160 consistently and carries no EXP-155 identity' {$text|Should -Match 'EXP-160';$text|Should -Not -Match 'EXP-155'}
 It 'binds one EXP-143 priority StartupFolder selection and inventory hash' {foreach($x in "experiment-ne'EXP-143'","classification-ne'priority-target'","surface-ne'StartupFolder'",'inventoryHash','SelectionPath'){$text|Should -Match ([regex]::Escape($x))}}
 It 'allows only current-user and common Startup folder surfaces' {$text|Should -Match "GetFolderPath\('Startup'\)";$text|Should -Match "GetFolderPath\('CommonStartup'\)";$text|Should -Match 'outside approved Startup folders'}
 It 'captures exact file bytes hash owner metadata ACL shortcut and startup snapshot' {foreach($x in 'bytesBase64','Sha256','CreationTimeUtc','LastWriteTimeUtc','LastAccessTimeUtc','Attributes','Owner','AclSddl','TargetPath','Arguments','WorkingDirectory','IconLocation','Description','WindowStyle','startupSnapshot'){$text|Should -Match $x}}
 It 'requires HP Windows 11 elevation unmanaged ownership and signed publisher identity' {foreach($x in 'Windows 11 required','HP platform required','elevation required','Test-Elevated','enterprise management ownership detected','Get-AuthenticodeSignature','Microsoft Corporation','Logitech'){$text|Should -Match $x}}
 It 'refuses protected and argument-bearing startup identities' {foreach($x in 'Protected startup identity refused','Shortcut arguments require separate qualification','omnissa','windows app','remote desktop','tailscale','defender','credential','recovery','driver','firmware'){$text|Should -Match $x}}
 It 'limits application to deletion of the selected Startup registration' {$text|Should -Match 'Remove-Item -LiteralPath \$live.Path -Force';$text|Should -Not -Match 'Remove-AppxPackage|Uninstall-Package|Set-Service|Stop-Service|Remove-Service|Disable-PnpDevice|Remove-PnpDevice|pnputil|Disable-ScheduledTask|Unregister-ScheduledTask|Set-MpPreference|Set-NetFirewall'}
 It 'preserves protected configuration and unrelated startup state' {foreach($x in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','Test-RemainingMatches','Protected security update or remote-access configuration drift detected'){$text|Should -Match $x}}
 It 'supports dry run WhatIf structured logging idempotence and terminating failure evidence' {foreach($x in 'dry-run','WhatIfPreference','ConvertTo-Json -Compress','idempotent',"'failure' 'failure'",'ErrorActionPreference','needs-evidence'){$text|Should -Match ([regex]::Escape($x))}}
 It 'requires a later boot for persistence verification' {$text|Should -Match 'Later boot required';$text|Should -Match 'Treatment failed reboot persistence'}
 It 'refuses conflicting rollback and restores exact captured content ownership and ACL' {foreach($x in 'Rollback conflicting-path overwrite refused','WriteAllBytes','SetSecurityDescriptorSddlForm','Set-Acl','Owner-ne','AclSddl-ne','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match $x}}
 It 'retains Experimental evidence state without Stable assignment' {$text|Should -Match 'needs-evidence';$text|Should -Not -Match 'status:stable|Stable='}
}
