Describe 'EXP-156 inventory-bound sign-in task provider contract' {
 BeforeAll{$script:providerPath=Join-Path $PSScriptRoot '..\providers\InventoryBoundSigninTaskRemoval.ps1';$text=Get-Content -LiteralPath $script:providerPath -Raw}
 It 'parses as valid PowerShell'{[scriptblock]::Create($text)|Should -Not -BeNullOrEmpty}
 It 'binds only EXP-156 Experimental evidence'{ $text|Should -Match 'EXP-156';$text|Should -Match 'needs-evidence';$text|Should -Not -Match 'status:stable|stage:stable|Stable=' }
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'requires an exact EXP-143 priority ScheduledTask selection'{foreach($t in 'EXP-143','priority-target','ScheduledTask','inventoryHash','identity','originalState.xml','Selected task drifted from EXP-143 captured XML'){$text|Should -Match ([regex]::Escape($t))}}
 It 'requires HP Windows 11 elevation and self-managed ownership'{foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','DomainJoined','EnrollmentCount','OmadmCount','ConfigMgr','enterprise management ownership detected'){$text|Should -Match ([regex]::Escape($t))}}
 It 'qualifies one enabled logon task with one signed user application action'{foreach($t in 'LogonTrigger','Exactly one selected scheduled task','Exactly one executable task action','ValidPublisher','Microsoft Corporation','Logitech','Selected baseline task must be enabled'){$text|Should -Match ([regex]::Escape($t))}}
 It 'refuses protected and servicing task purposes'{foreach($t in 'Protected scheduled-task identity refused','Servicing, updater, installer, repair, firmware, driver, or pairing task refused','clicktorun','edgeupdate','firmware','driver','pairing'){$text|Should -Match ([regex]::Escape($t))}}
 It 'captures exact XML task action executable and boot evidence'{foreach($t in 'Xml','XmlSha256','DefinitionSha256','TriggersXml','SettingsXml','RegistrationInfoXml','TaskPath','TaskName','Author','Principal','Arguments','WorkingDirectory','Sha256','FileVersion','ProductName','CompanyName','Publisher','Thumbprint','LastRunTime','LastTaskResult','NextRunTime','capturedBootTime'){$text|Should -Match $t}}
 It 'holds unrelated sign-in tasks and protected scope against drift'{foreach($t in 'Get-UnrelatedSnapshot','Unrelated sign-in task drift detected','Get-ProtectedSnapshot','Protected-scope drift detected','WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$text|Should -Match ([regex]::Escape($t))}}
 It 'supports dry run WhatIf ShouldProcess JSONL logging and idempotence'{foreach($t in 'SupportsShouldProcess','WouldChange','WhatIfPreference','ShouldProcess','ConvertTo-Json -Compress',"'idempotent'",'MutationCount'){$text|Should -Match $t}}
 It 'limits production mutation to one task enabled state'{ $text|Should -Match 'Disable-ScheduledTask';$text|Should -Match 'Enable-ScheduledTask';$text|Should -Not -Match 'Unregister-ScheduledTask|Register-ScheduledTask|Set-Service|Stop-Service|Remove-Service|Remove-AppxPackage|Uninstall-Package|pnputil|Remove-Item' }
 It 'declares preserved application service package servicing firmware driver and protected scope'{foreach($t in 'PreserveApplication','PreserveServices','PreservePackages','PreserveServicing','PreserveFirmware','PreserveDrivers','PreserveProtectedScope'){$text|Should -Match $t}}
 It 'requires a later boot and exact rollback verification'{foreach($t in 'A later boot is required','Reboot persistence failed','Task-definition drift detected','Executable or product identity drift detected','Rollback exact-XML verification failed','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match ([regex]::Escape($t))}}
 It 'preserves protected remote access security recovery accessibility and management identities'{foreach($t in 'omnissa','windows app','remote desktop','tailscale','defender','credential','bitlocker','firewall','windows update','recovery','accessib','intune','sccm','mdm'){$text|Should -Match $t}}
 It 'retains terminating failure evidence'{ $text|Should -Match "'failure' 'fail'";$text|Should -Match '\$ErrorActionPreference=''Stop''';$text|Should -Match 'throw' }
}
