Describe 'EXP-050 LogiOptionsPlusDemandLaunch contract' {
 BeforeAll {
  $script:providerPath = Join-Path $PSScriptRoot '..\providers\LogiOptionsPlusDemandLaunch.ps1'
  $script:text = Get-Content -LiteralPath $script:providerPath -Raw
 }
 It 'parses as PowerShell' { [scriptblock]::Create($script:text) | Should -Not -BeNullOrEmpty }
 It 'retains Experimental identity and evidence state' { $script:text | Should -Match 'EXP-050'; $script:text | Should -Match 'needs-evidence'; $script:text | Should -Not -Match 'status:stable|stage:stable|Stable=' }
 It 'exposes the full reversible lifecycle' { foreach($action in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){ $script:text | Should -Match "'$action'" } }
 It 'requires HP Windows 11 elevation and self-managed ownership' { foreach($token in 'Windows 11','Hewlett-Packard','Test-Elevated','Elevated','Managed','ManagementSignals','Enterprise-management ownership detected','Management ownership appeared'){ $script:text | Should -Match ([regex]::Escape($token)) } }
 It 'uses ShouldProcess and supports WhatIf' { $script:text | Should -Match 'SupportsShouldProcess'; $script:text | Should -Match 'ShouldProcess'; $script:text | Should -Match 'WhatIfPreference' }
 It 'captures exact registry ACL executable and signer identity' { foreach($token in 'DoNotExpandEnvironmentNames','GetValueKind','Get-Acl','KeyOwner','KeySddl','Get-AuthenticodeSignature','Get-FileHash','Thumbprint','FileVersion','ProductName','CompanyName'){ $script:text | Should -Match $token } }
 It 'requires bounded Logi Options+ executable and startup intent and rejects servicing paths' { foreach($token in 'logioptionsplus_agent','logioptionsplus_appbroker','background','minimi','startup','tray','silent','IsNullOrWhiteSpace'){ $script:text | Should -Match $token }; $script:text | Should -Match 'updat\|uninstall\|repair\|firmware\|dfu\|driver\|pairing' }
 It 'uses a bounded value-name matcher and single-candidate enforcement' { $script:text | Should -Match '\^logi\(\?:tech\)\?'; $script:text | Should -Match 'Exactly one eligible Logi Options\+' }
 It 'captures bounded management ownership signals' { foreach($token in 'DomainJoined','MdmEnrollments','OmadmAccounts','PolicyManager','ConfigMgr','RunPolicy'){ $script:text | Should -Match $token } }
 It 'holds protected services Logitech drivers and Logitech devices against drift' { foreach($token in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','LogitechDrivers','LogitechDevices','Get-PnpDevice','Assert-Protected'){ $script:text | Should -Match $token } }
 It 'refuses Run-key ACL drift and unsafe key recreation' { foreach($token in 'Assert-RunKey','Run-key drift detected','Run-key ACL drift detected','PreserveRunKeyAcl'){ $script:text | Should -Match ([regex]::Escape($token)) }; $script:text | Should -Not -Match "New-Item -Path \$s\.entry\.Path" }
 It 'records Experimental evidence and requires a later boot for persistence' { $script:text | Should -Match 'needs-evidence'; $script:text | Should -Match 'capturedBootTime'; $script:text | Should -Match 'A later boot is required'; $script:text | Should -Match 'Reboot persistence failed' }
 It 'limits production mutation to the selected Run value' { $script:text | Should -Match 'Remove-ItemProperty'; $script:text | Should -Match '\.SetValue\('; $script:text | Should -Not -Match 'Remove-AppxPackage|Uninstall-Package|Remove-Package|Set-Service|Stop-Service|Remove-Service|Disable-PnpDevice|Remove-PnpDevice|pnputil|Disable-ScheduledTask|Unregister-ScheduledTask|Set-MpPreference|Disable-WindowsOptionalFeature' }
 It 'retains failures idempotence and collision-safe exact rollback' { $script:text | Should -Match "'failure' 'fail'"; $script:text | Should -Match "'idempotent'"; $script:text | Should -Match 'Rollback overwrite refused'; $script:text | Should -Match 'Enum]::Parse'; $script:text | Should -Match 'Exact rollback verification failed'; $script:text | Should -Match 'restoredExactOriginal' }
}
