$provider=Join-Path $PSScriptRoot '..\providers\LogitechUpdaterRunDemandLaunch.ps1'
Describe 'EXP-132 issue 299 LogitechUpdaterRunDemandLaunch provider contract' {
    BeforeAll {$text=Get-Content -LiteralPath $provider -Raw;$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($provider,[ref]$tokens,[ref]$errors)}
    It 'parses as valid PowerShell' {$errors.Count|Should -Be 0}
    It 'declares Experimental identity and complete reversible lifecycle' {$text|Should -Match 'EXP-132';$text|Should -Match 'issue=299';foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"};$text|Should -Not -Match 'status:stable|stage:stable'}
    It 'requires HP Windows 11 and refuses management ownership' {foreach($t in 'Windows 11','Hewlett-Packard','DomainJoined','MdmEnrollments','PolicyManager','ConfigMgr','Intune','Enterprise-management ownership detected'){$text|Should -Match [regex]::Escape($t)}}
    It 'limits mutation discovery to approved persistent Run locations' {$text|Should -Match "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run";$text|Should -Match "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run";$text|Should -Match 'Elevation is required for HKLM Run'}
    It 'requires Logitech publisher and updater role while refusing unsafe identities' {foreach($t in 'Get-AuthenticodeSignature','Logitech|Logi','update|updater|update.?check|notification','firmware','dfu','driver','receiver','pair','repair','security','credential'){$text|Should -Match $t}}
    It 'captures exact registry executable product servicing device ownership and boot state' {foreach($t in 'DoNotExpandEnvironmentNames','GetValueKind','Sha256','FileVersion','ProductVersion','ProductName','Publisher','Thumbprint','KeyOwner','KeySddl','servicingStateHash','deviceStateHash','relatedRunHash','capturedBootTime','machine','userSid'){$text|Should -Match $t}}
    It 'supports dry run WhatIf ShouldProcess structured logging and idempotence' {foreach($t in 'SupportsShouldProcess','WhatIfPreference','ShouldProcess','WouldChange','ConvertTo-Json -Compress',"'idempotent'",'before=','after='){$text|Should -Match [regex]::Escape($t)}}
    It 'limits mutation to one registry value and exact restoration' {$text|Should -Match 'Remove-ItemProperty -LiteralPath';$text|Should -Match '\.SetValue\(';$text|Should -Not -Match 'Set-Service|Stop-Service|Disable-ScheduledTask|Enable-ScheduledTask|Remove-AppxPackage|pnputil|Disable-PnpDevice|Remove-PnpDevice'}
    It 'refuses servicing device protected ownership executable and related-startup drift' {foreach($t in 'Logitech servicing-state drift detected','Logitech device-state drift detected','Protected-scope drift detected','Run key ownership or ACL drift detected','Logitech updater executable identity drift detected','Logitech updater product-role drift detected','Related Logitech startup-registration drift detected'){$text|Should -Match [regex]::Escape($t)}}
    It 'requires reboot persistence and collision-safe rollback' {foreach($t in 'A later boot is required','Reboot persistence failed','Rollback overwrite refused','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match [regex]::Escape($t)}}
    It 'preserves application servicing devices drivers security updates recovery management and protected remote access' {foreach($t in 'PreserveLogitechApplication','PreserveUpdaterServicesAndTasks','PreserveDevicesPairingFirmwareAndDrivers','PreserveSecurityUpdatesRecoveryManagement','PreserveProtectedRemoteAccess','WinDefend','mpssvc','wuauserv','Tailscale','omnissa','windows app','remote desktop'){$text|Should -Match $t}}
    It 'retains physical evidence and terminating failure requirements' {$text|Should -Match 'needs-evidence';$text|Should -Match 'PhysicalUpdaterRoleProofRequired';$text|Should -Match "'failure' 'fail'";$text|Should -Match 'refusalReason';$text|Should -Match 'failureDetail'}
}
