Describe 'EXP-080 Logitech Download Assistant Run demand-launch contract' {
 BeforeAll {
  $script:provider=Join-Path $PSScriptRoot '..\providers\LogitechDownloadAssistantDemandLaunch.ps1'
  $script:text=Get-Content -LiteralPath $script:provider -Raw
 }
 It 'parses as PowerShell' {$tokens=$null;$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($script:provider,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'implements the complete reversible lifecycle' {foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$script:text|Should -Match "'$a'"}}
 It 'targets only approved HKCU and HKLM Run registrations' {$script:text|Should -Match 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';$script:text|Should -Match 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';$script:text|Should -Match 'exactly one eligible Logitech Download Assistant Run registration'}
 It 'requires HP Windows 11 elevation and self-managed ownership' {foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','elevation required','enterprise management ownership detected','Management ownership appeared'){$script:text|Should -Match ([regex]::Escape($t))}}
 It 'recognizes only bounded Logitech Download Assistant identities' {foreach($t in 'Logitech Download Assistant','LogitechDownloadAssistant','LogiLDA','LogiFetch','Rundll32LogiLDA','DirectExe'){$script:text|Should -Match ([regex]::Escape($t))};$script:text|Should -Match '\^\(Logitech Download Assistant\|LogitechDownloadAssistant\|LogiLDA\)\$'}
 It 'binds the payload to Logitech signature hash version and signer identity' {foreach($t in 'Get-AuthenticodeSignature','Get-FileHash','ValidLogitech','Sha256','Thumbprint','Version','Publisher'){$script:text|Should -Match $t}}
 It 'captures exact registry ACL value machine user and boot identity' {foreach($t in 'DoNotExpandEnvironmentNames','GetValueKind','KeyOwner','KeySddl','capturedBootUtc','userSid','machine=','Kind=','Data='){$script:text|Should -Match $t}}
 It 'separates protected configuration from reboot-varying runtime evidence' {$script:text|Should -Match 'protectedConfigurationHash';$script:text|Should -Match 'protectedRuntime';$script:text|Should -Match 'Configuration=\$configuration';$script:text|Should -Match 'Runtime=\$runtime';$script:text|Should -Not -Match 'Select-Object ProcessName,Id'}
 It 'preserves security updates remote access Logitech drivers and devices' {foreach($t in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','Win32_SystemDriver','Get-PnpDevice','LogitechDrivers','LogitechDevices','PreserveDriverPackages','PreservePnPDevices','PreserveFirmware','PreservePairing'){$script:text|Should -Match $t}}
 It 'supports WhatIf structured JSONL logging idempotence and failure retention' {foreach($t in 'SupportsShouldProcess','WhatIfPreference','ConvertTo-Json -Compress','idempotent',"'failure' 'failed'",'needs-evidence'){$script:text|Should -Match ([regex]::Escape($t))}}
 It 'uses timezone-safe later-boot persistence verification' {$script:text|Should -Match 'DateTimeOffset';$script:text|Should -Match 'ConvertTo-UtcDateTime';$script:text|Should -Match 'A later boot is required';$script:text|Should -Match 'Treatment failed reboot persistence'}
 It 'refuses ACL payload management protected-state and rollback collisions' {foreach($t in 'Run-key ACL drift detected','payload identity drift detected','Management ownership appeared','configuration drift detected','Rollback overwrite refused'){$script:text|Should -Match ([regex]::Escape($t))}}
 It 'implements collision-safe exact value restoration without key recreation' {$script:text|Should -Match 'RegistryValueKind';$script:text|Should -Match '\.SetValue\('; $script:text|Should -Match 'Exact rollback verification failed';$script:text|Should -Match 'restoredExactOriginal';$script:text|Should -Not -Match 'New-Item -Path \(\[string\]\$s\.entry\.Path\)|Register-ScheduledTask|Unregister-ScheduledTask'}
 It 'limits production mutation to one Run value' {$script:text|Should -Match 'Remove-ItemProperty';$script:text|Should -Not -Match 'Disable-ScheduledTask|Enable-ScheduledTask|Remove-AppxPackage|Uninstall-Package|Set-Service|Stop-Service|Remove-Service|Disable-PnpDevice|Remove-PnpDevice|pnputil|Set-MpPreference|Disable-WindowsOptionalFeature'}
 It 'retains Experimental evidence state' {$script:text|Should -Match 'EXP-080';$script:text|Should -Match 'needs-evidence';$script:text|Should -Not -Match 'status:stable|stage:stable|Stable='}
}
