Describe 'EXP-052 Logi Tune demand-launch provider contract' {
 BeforeAll {
  $script:provider=Join-Path $PSScriptRoot '..\providers\LogiTuneDemandLaunch.ps1'
  $script:text=Get-Content -LiteralPath $script:provider -Raw
 }
 It 'parses as PowerShell' {$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:provider,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'implements the full reversible lifecycle' {foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$script:text|Should -Match "'$a'"}}
 It 'targets one exact current-user Logi Tune Run registration' {$script:text|Should -Match 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';foreach($t in 'logitune','logi_tune','Logi Tune','Exactly one eligible Logi Tune'){$script:text|Should -Match $t}}
 It 'requires explicit background startup intent and refuses updater pairing driver and firmware commands' {$script:text|Should -Match 'IsNullOrWhiteSpace\(\$args\)';foreach($t in 'background','minimi','startup','tray','silent','autostart','updat\|uninstall\|repair\|firmware\|dfu\|driver\|pairing','Arguments=\$c\[0\]\.Arguments'){$script:text|Should -Match $t}}
 It 'requires HP Windows 11 elevation signed Logitech identity and unmanaged ownership' {foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','Elevated','Get-AuthenticodeSignature','Get-FileHash','ValidLogitechPublisher','DomainJoined','MdmEnrollments','OmadmAccounts','ConfigMgr','Enterprise-management ownership detected','Management ownership appeared'){$script:text|Should -Match ([regex]::Escape($t))}}
 It 'captures exact registry executable ACL machine user and boot state' {foreach($t in 'DoNotExpandEnvironmentNames','GetValueKind','Get-Acl','Kind=','Data=','Sha256','FileVersion','ProductName','CompanyName','Thumbprint','KeyOwner','KeySddl','capturedBootTime','userSid'){$script:text|Should -Match $t}}
 It 'preserves security updates remote access and Logitech device-critical state' {foreach($t in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale','Win32_SystemDriver','Get-PnpDevice','LogitechDrivers','LogitechDevices','PreserveUpdaterServices','PreserveScheduledTasks','PreserveStartupTasks','PreserveDrivers','PreserveDevices','PreserveAudioVideoDevices','PreservePairing'){$script:text|Should -Match $t}}
 It 'refuses Run-key ACL drift and unsafe key recreation' {foreach($t in 'Assert-RunKey','Run-key drift detected','Run-key ACL drift detected','PreserveRunKeyAcl'){$script:text|Should -Match ([regex]::Escape($t))};$script:text|Should -Not -Match "New-Item -Path \$s\.entry\.Path"}
 It 'supports structured logging WhatIf idempotence and terminating failure retention' {foreach($t in 'SupportsShouldProcess','WhatIfPreference','ConvertTo-Json -Compress','idempotent',"'failure' 'fail'",'ErrorActionPreference','needs-evidence'){$script:text|Should -Match ([regex]::Escape($t))}}
 It 'requires later-boot persistence verification' {$script:text|Should -Match 'A later boot is required';$script:text|Should -Match 'Reboot persistence failed'}
 It 'detects executable version hash signer management ACL and protected-state drift' {foreach($t in 'FileVersion','Sha256','Thumbprint','Assert-Guards','Assert-Executable','Assert-Protected','Assert-RunKey'){$script:text|Should -Match ([regex]::Escape($t))}}
 It 'implements collision-safe exact rollback' {foreach($t in 'Rollback overwrite refused','Enum]::Parse','RegistryValueKind','SetValue','Exact rollback verification failed','restoredExactOriginal'){$script:text|Should -Match ([regex]::Escape($t))}}
 It 'limits production mutation to the selected Run value' {$script:text|Should -Match 'Remove-ItemProperty';$script:text|Should -Match '\.SetValue\('; $script:text|Should -Not -Match 'Remove-AppxPackage|Uninstall-Package|Remove-Package|Set-Service|Stop-Service|Remove-Service|Disable-PnpDevice|Remove-PnpDevice|pnputil|Disable-ScheduledTask|Unregister-ScheduledTask|Set-MpPreference|Disable-WindowsOptionalFeature'}
 It 'keeps Experimental evidence pending' {$script:text|Should -Match 'needs-evidence';$script:text|Should -Not -Match 'status:stable|stage:stable|Stable='}
}
