$provider=Join-Path $PSScriptRoot '..\providers\MicrosoftTeamsSigninTask.ps1'
Describe 'EXP-125 issue 289 MicrosoftTeamsSigninTask provider contract' {
 BeforeAll{$text=Get-Content -LiteralPath $provider -Raw}
 It 'parses as valid PowerShell'{[scriptblock]::Create($text)|Should -Not -BeNullOrEmpty}
 It 'declares Experimental scope only'{ $text|Should -Match 'EXP-125';$text|Should -Match 'issue=289';$text|Should -Match 'MicrosoftTeamsSigninTask';$text|Should -Not -Match 'status:stable|stage:stable|Stable=' }
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'requires HP Windows 11 elevation and management refusal'{foreach($t in 'Windows 11','Hewlett-Packard','Test-Elevated','DomainJoined','MdmEnrollments','PolicyManager','ConfigMgr','Enterprise-management ownership detected'){$text|Should -Match [regex]::Escape($t)}}
 It 'limits eligibility to Microsoft signed Teams user applications and excludes servicing'{foreach($t in 'Teams|ms-teams|msteams','Microsoft Corporation','bootstrapper','webview.*servic','repair','install','update','firmware','driver'){$text|Should -Match $t}}
 It 'requires a logon trigger and one exact task action'{ $text|Should -Match '<LogonTrigger>';$text|Should -Match 'actions.Count-ne1';$text|Should -Match 'Exactly one eligible Microsoft Teams user-app sign-in task is required' }
 It 'captures exact task executable Teams package and runtime evidence'{foreach($t in 'XmlSha256','DefinitionSha256','TriggersXml','ActionsXml','SettingsXml','ConditionsXml','RegistrationInfoXml','TaskName','TaskPath','Author','Principal','Arguments','WorkingDirectory','Sha256','FileVersion','ProductVersion','ProductName','Publisher','Thumbprint','Packages','LastRunTime','LastTaskResult','NextRunTime','capturedBootTime'){$text|Should -Match $t}}
 It 'normalizes only enabled state for definition drift checks and retains raw XML'{ $text|Should -Match '<Enabled>__EXPERIMENT_STATE__</Enabled>';$text|Should -Match 'Task-definition drift detected';$text|Should -Match 'Rollback exact-XML verification failed' }
 It 'supports dry run WhatIf ShouldProcess structured logs and idempotence'{foreach($t in 'SupportsShouldProcess','WhatIfPreference','ShouldProcess','WouldChange','ConvertTo-Json -Compress',"'idempotent'",'refusalReason','failureDetail','before','after'){$text|Should -Match $t}}
 It 'limits mutation to task enabled state'{ $text|Should -Match 'Disable-ScheduledTask';$text|Should -Match 'Enable-ScheduledTask';$text|Should -Not -Match 'Unregister-ScheduledTask|Register-ScheduledTask|Remove-AppxPackage|Uninstall-Package|pnputil|Set-Service|Stop-Service|Remove-Service|Remove-ItemProperty|Set-ItemProperty' }
 It 'preserves Teams installation data servicing and all other startup mechanisms'{foreach($t in 'PreserveTeamsInstallation','PreserveTeamsData','PreserveTeamsServicing','PreserveRunRegistrations','PreserveStartupFolders','PreserveStartupTasks','PreserveServices'){$text|Should -Match $t}}
 It 'requires observed reboot persistence and drift-aware rollback'{foreach($t in 'A later boot is required','Microsoft Teams executable or product identity drift detected','Microsoft Teams package identity drift detected','Protected-scope drift detected','Exact rollback verification failed','restoredExactOriginal'){$text|Should -Match [regex]::Escape($t)}}
 It 'preserves protected Windows remote access and management scope'{foreach($t in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','Tailscale','omnissa','windows app','remote desktop','bitlocker','credential','recovery','intune','sccm','mdm'){$text|Should -Match $t}}
 It 'retains terminating failure evidence'{ $text|Should -Match "'failure' 'fail'";$text|Should -Match '\$ErrorActionPreference=''Stop''';$text|Should -Match 'throw' }
}
