Describe 'EXP-124 Microsoft 365 Run quick-launch provider contract' {
 BeforeAll{$script:providerPath=Join-Path $PSScriptRoot '..\providers\Microsoft365RunQuickLaunchRemoval.ps1';$text=Get-Content -LiteralPath $script:providerPath -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:providerPath,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'retains Experimental identity and pending physical evidence'{Test-Path $script:providerPath|Should -BeTrue;$text|Should -Match 'EXP-124';$text|Should -Match 'needs-evidence';$text|Should -Not -Match 'status:stable|Stable='}
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"}}
 It 'limits mutation to one persistent Run registry value'{foreach($x in 'CurrentVersion\\Run','DeleteValue','MutationCount=1','Restore-Exact','SetValue'){$text|Should -Match $x};$text|Should -Not -Match 'Disable-ScheduledTask|Unregister-ScheduledTask|Set-Service|Stop-Service|Remove-Service|Remove-AppxPackage|Uninstall-Package|Disable-PnpDevice|Remove-PnpDevice|pnputil|Remove-Item\s+-Recurse'}
 It 'requires one exact Microsoft signed Office desktop candidate'{foreach($x in 'Exactly one eligible Microsoft 365 persistent Run candidate required','MicrosoftSigned','WINWORD.EXE','EXCEL.EXE','POWERPNT.EXE','OUTLOOK.EXE','ONENOTE.EXE','MSACCESS.EXE'){$text|Should -Match ([regex]::Escape($x))}}
 It 'refuses servicing management protected and ambiguous identities'{foreach($x in 'clicktorun','office.*update','activation','licens','credential','recovery','intune','configmgr','mdm','driver','firmware','windows update','omnissa','windows app','remote desktop','tailscale','Enterprise management ownership detected'){$text.ToLowerInvariant()|Should -Match $x.ToLowerInvariant()}}
 It 'captures exact raw registry and ownership state'{foreach($x in 'DoNotExpandEnvironmentNames','KeyOwner','KeySddl','Kind','Data','RegistryView','ValueName','capturedBootUtc','userSid'){$text|Should -Match $x}}
 It 'captures executable product management and related startup state'{foreach($x in 'Sha256','Thumbprint','FileVersion','ProductVersion','VersionToReport','ProductReleaseIds','Get-ManagementState','Get-RegistryStartupInventory','otherStartupHash','protectedHash'){$text|Should -Match $x}}
 It 'provides dry run WhatIf structured JSONL idempotence and failure evidence'{foreach($x in 'DryRun','WhatIfPreference','Write-Event','ConvertTo-Json -Compress','idempotent','failureDetail','ErrorActionPreference','catch'){$text|Should -Match $x}}
 It 'requires reboot persistence and collision safe exact rollback'{foreach($x in 'A later boot is required','Treatment failed reboot persistence','Rollback collision detected; overwrite refused','Exact rollback verification failed','RestoredExactOriginal','PostRollbackRebootCheck'){$text|Should -Match ([regex]::Escape($x))}}
 It 'preserves security updates Office servicing and protected remote access configuration'{foreach($x in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','ClickToRunSvc','TermService','Tailscale','Protected security, update, Office servicing, or remote-access configuration drift detected'){$text|Should -Match ([regex]::Escape($x))}}
 It 'keeps RunOnce and adjacent startup surfaces outside production mutation'{foreach($x in 'CurrentVersion\\RunOnce','PreserveRunOnce','Get-RegistryStartupInventory'){$text|Should -Match $x};$text|Should -Not -Match 'DeleteValue\([^\r\n]*RunOnce|StartupTask.*Disable|Disable-ScheduledTask'}
}
