$provider=Join-Path $PSScriptRoot '..\providers\MicrosoftTeamsRunOnceDemandLaunch.ps1'
Describe 'EXP-133 issue 301 MicrosoftTeamsRunOnceDemandLaunch provider contract' {
    BeforeAll {$text=Get-Content -LiteralPath $provider -Raw;$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($provider,[ref]$tokens,[ref]$errors)}
    It 'parses as valid PowerShell' {$errors.Count|Should -Be 0}
    It 'declares Experimental scope and complete reversible lifecycle' {$text|Should -Match 'EXP-133';$text|Should -Match 'issue=301';$text|Should -Match 'MicrosoftTeamsRunOnceDemandLaunch';foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$text|Should -Match "'$a'"};$text|Should -Not -Match 'status:stable|stage:stable'}
    It 'uses ShouldProcess WhatIf structured logs and terminating failure retention' {foreach($t in 'SupportsShouldProcess','WhatIfPreference','ShouldProcess','ConvertTo-Json -Compress',"'failure' 'fail'",'refusalReason','failureDetail','ErrorActionPreference'){$text|Should -Match [regex]::Escape($t)}}
    It 'requires HP Windows 11 and refuses enterprise ownership' {foreach($t in 'Windows 11','Hewlett-Packard','DomainJoined','MdmEnrollments','PolicyManager','ConfigMgr','Intune','Enterprise-management ownership detected'){$text|Should -Match [regex]::Escape($t)}}
    It 'limits discovery to approved RunOnce paths String types and ordinary value semantics' {$text|Should -Match 'CurrentVersion\\RunOnce';$text|Should -Match "StartsWith\('!'\)";$text|Should -Match "StartsWith\('\*'\)";$text|Should -Match "'String','ExpandString'";$text|Should -Match 'Elevation is required for HKLM RunOnce'}
    It 'limits eligibility to Microsoft signed Teams user applications and excludes servicing' {foreach($t in 'Teams|ms-teams|msteams','Get-AuthenticodeSignature','Microsoft Corporation','webview.*servic','edgeupdate','squirrel.*update','update\\.exe','repair','driver','firmware'){$text|Should -Match $t}}
    It 'captures exact registry executable product package ownership and related startup evidence' {foreach($t in 'DoNotExpandEnvironmentNames','GetValueKind','Data=','Sha256','FileVersion','ProductVersion','ProductName','CompanyName','Publisher','Thumbprint','KeyOwner','KeySddl','teamsPackageHash','relatedTeamsStartupHash','capturedBootTime','machine','userSid'){$text|Should -Match $t}}
    It 'captures other Teams startup mechanisms without changing them' {foreach($t in 'CurrentVersion\\Run','SpecialFolder]::Startup','SpecialFolder]::CommonStartup','Get-ScheduledTask','Get-AppxPackageManifest','windows.startupTask','relatedTeamsStartupCount'){$text|Should -Match $t}}
    It 'distinguishes Windows RunOnce consumption from experiment deletion' {foreach($t in 'treatmentAppliedByExperiment','RunOnce disappeared before experiment application','windows-or-external-needs-evidence','oneShotAttribution','OneShotConsumptionEvidenceRequired','Verification refused because experiment application is unproven','Rollback refused because the experiment did not remove the RunOnce value'){$text|Should -Match [regex]::Escape($t)}}
    It 'limits mutation to the selected registry value and exact restoration' {$text|Should -Match 'Remove-ItemProperty -LiteralPath';$text|Should -Match 'New-ItemProperty -LiteralPath';$text|Should -Match 'PropertyType';$text|Should -Match 'Test-Restored';$text|Should -Not -Match 'Remove-AppxPackage|Uninstall-Package|Disable-ScheduledTask|Enable-ScheduledTask|Register-ScheduledTask|Unregister-ScheduledTask|Set-Service|Stop-Service|pnputil|Remove-PnpDevice'}
    It 'refuses executable package ownership management protected and related-startup drift' {foreach($t in 'Microsoft Teams executable identity drift detected','Microsoft Teams package identity drift detected','RunOnce key ownership or ACL drift detected','Enterprise-management ownership appeared','Protected-scope configuration drift detected','Related Microsoft Teams startup state drift detected','RunOnce registration drift detected'){$text|Should -Match [regex]::Escape($t)}}
    It 'requires controlled reboot persistence and collision-safe exact rollback' {foreach($t in 'A later boot is required','Reboot persistence failed','Rollback overwrite refused','Exact rollback verification failed','restoredExactOriginal','oneShotPostRollbackConsumption'){$text|Should -Match [regex]::Escape($t)}}
    It 'preserves Teams servicing data other startup paths protected apps security updates recovery management and drivers' {foreach($t in 'PreserveTeamsInstallation','PreserveTeamsData','PreserveTeamsServicing','PreservePersistentRun','PreserveStartupFolders','PreserveStartupTasks','PreserveScheduledTasks','PreserveServices','WinDefend','mpssvc','wuauserv','Tailscale','omnissa','windows app','remote desktop','bitlocker','recovery','mdm','driver'){$text|Should -Match $t}}
}
