Describe 'EXP-125 Teams sign-in scheduled-task provider contract' {
 BeforeAll{$script:path=Join-Path $PSScriptRoot '..\providers\TeamsSigninScheduledTaskDisable.ps1';$script:text=Get-Content -LiteralPath $script:path -Raw}
 It 'parses as PowerShell'{$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($script:path,[ref]$tokens,[ref]$errors);@($errors).Count|Should -Be 0}
 It 'retains Experimental identity and pending physical evidence'{$script:text|Should -Match 'EXP-125';$script:text|Should -Match 'needs-evidence';$script:text|Should -Not -Match 'status:stable|Stable='}
 It 'implements the complete reversible lifecycle'{foreach($a in 'Check','Capture','DryRun','Apply','Verify','VerifyReboot','Rollback'){$script:text|Should -Match "'$a'"}}
 It 'requires HP Windows 11 elevation and self-managed ownership'{foreach($x in 'Windows 11 required','HP platform required','Elevation required','Enterprise management ownership detected','CcmExec','Microsoft\\Enrollments','Provisioning\\OMADM\\Accounts'){$script:text|Should -Match $x}}
 It 'selects a single enabled Microsoft-signed Teams logon task using executable identity'{foreach($x in 'Exactly one Microsoft-signed Teams user-logon scheduled task required','LogonTrigger','MicrosoftSigned','ms-teams','Teams product identity required','Sha256','Thumbprint'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'captures full task XML and explicit task metadata'{foreach($x in 'Export-ScheduledTask','XmlSha256','DefinitionHash','TriggerXml','Actions','PrincipalXml','ConditionsXml','SettingsXml','RegistrationInfoXml','Author','LastRunTime','LastTaskResult','NextRunTime'){$script:text|Should -Match $x}}
 It 'changes the enabled state only and avoids task re-registration during treatment'{$script:text|Should -Match 'Disable-ScheduledTask';$script:text|Should -Match 'Enable-ScheduledTask';$script:text|Should -Not -Match 'Register-ScheduledTask|Unregister-ScheduledTask|Set-ScheduledTask'}
 It 'provides DryRun WhatIf structured logging idempotence and terminating failure retention'{foreach($x in 'DryRun','WhatIfPreference','ShouldProcess','ConvertTo-Json -Compress','Add-Content','idempotent','failureDetail','ErrorActionPreference','catch'){$script:text|Should -Match $x}}
 It 'requires later boot persistence and drift-safe exact rollback'{foreach($x in 'A later boot is required','Reboot persistence failed','Task-definition drift detected','Teams executable identity drift detected','Teams product identity drift detected','Management ownership drift detected','Protected configuration drift detected','Exact rollback verification failed'){$script:text|Should -Match ([regex]::Escape($x))}}
 It 'preserves security updates and protected remote access configuration'{foreach($x in 'WinDefend','mpssvc','wuauserv','UsoSvc','BITS','TermService','Tailscale'){$script:text|Should -Match $x}}
 It 'contains no package service driver device security or update mutation primitives'{$script:text|Should -Not -Match 'Remove-AppxPackage|Uninstall-Package|Set-Service|Stop-Service|sc\.exe\s+(config|delete)|Disable-PnpDevice|Remove-PnpDevice|pnputil|Set-MpPreference|Set-NetFirewall|Remove-ItemProperty|New-ItemProperty'}
}
